"""Seed the research system: series registry, 23 desks, drivers, instruments, config.

Idempotent: UPSERTs everywhere. Run after any change to registry.py / desks.py.
    python pipeline/seed.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from lbc import db
from lbc.desks import DESKS, all_tickers
from lbc.registry import seed_rows


def main():
    n = db.upsert("mkt", "series", seed_rows(), on_conflict="key")
    print(f"mkt.series: {n}")

    desk_rows = [
        {k: d[k] for k in ("id", "name", "basket", "kind", "tickers", "benchmark", "template_ids", "sort_order")}
        for d in DESKS
    ]
    n = db.upsert("research", "desk", desk_rows, on_conflict="id")
    print(f"research.desk: {n}")

    driver_rows = []
    for d in DESKS:
        for (series_key, label, direction, weight, shared) in d["drivers"]:
            driver_rows.append({
                "desk_id": d["id"], "series_key": series_key, "label": label,
                "direction": direction, "weight": weight, "shared_factor": shared,
            })
    n = db.upsert("research", "driver", driver_rows, on_conflict="desk_id,series_key")
    print(f"research.driver: {n}")

    # Deactivate drivers no longer in desks.py. Left active they keep scoring off
    # frozen observations at full weight, which reads as a healthy dial built on
    # data that stopped moving months ago.
    wanted = {(r["desk_id"], r["series_key"]) for r in driver_rows}
    orphans = [r for r in db.select("research", "driver", "select=id,desk_id,series_key,active")
               if (r["desk_id"], r["series_key"]) not in wanted and r["active"]]
    for r in orphans:
        db.update("research", "driver", f"id=eq.{r['id']}", {"active": False})
    if orphans:
        print(f"drivers deactivated: {[(r['desk_id'], r['series_key']) for r in orphans]}")

    # Same for series: mark registry-absent series inactive rather than deleting
    # history (news.vol.* are generated by the GDELT job, not the registry).
    reg_keys = {r["key"] for r in seed_rows()}
    stale_series = [r for r in db.select("mkt", "series", "select=key,active")
                    if r["key"] not in reg_keys and not r["key"].startswith("news.vol.") and r["active"]]
    for r in stale_series:
        db.update("mkt", "series", f"key=eq.{r['key']}", {"active": False})
    if stale_series:
        print(f"series deactivated: {[r['key'] for r in stale_series]}")

    inst_rows = [
        {"ticker": t, "desk_id": desk_id, "active": True}
        for t, desk_id in sorted(all_tickers().items())
    ]
    n = db.upsert("mkt", "instrument", inst_rows, on_conflict="ticker")
    print(f"mkt.instrument: {n}")

    defaults = {
        "enabled": True,
        "telegram_push": {"chat_ids": [], "note": "empty until verified; set via terminal or bot"},
        "models": {"desk_agent": "anthropic/claude-haiku-4.5",
                   "editor": "anthropic/claude-sonnet-4.5",
                   "adversary": "anthropic/claude-sonnet-4.5",
                   "bot": "anthropic/claude-sonnet-4.5"},
        "brief_caps": {"changed": 5, "decide": 2, "blind": 1},
        "sizing_rules": {"max_single_pct": 40, "min_positions": 3, "cut_loss_pct": -20},
        "graveyard_rule": {"min_n": 20, "hit_rate_below": 0.45},
    }
    for k, v in defaults.items():
        if db.get_config(k) is None:
            db.set_config(k, v)
    print("config defaults ensured")


if __name__ == "__main__":
    main()
