"""
persist.py — publish engine output for the terminal.

  - output/engine.json         : compact index of every basket's model (the
                                 terminal-facing payload)
  - launcher/scripts/industry-engine-data.js : window.INDUSTRY_ENGINE global so
                                 the Babel-in-browser shell can read it directly

These are committed to the repo (versioned, auditable). No Supabase DDL needed.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import common as C

JS_TARGET = C.ROOT.parent / "launcher" / "scripts" / "industry-engine-data.js"


def _compact(art: dict) -> dict:
    m = art.get("model") or {}
    drivers = []
    for r in (m.get("drivers") or [])[:14]:
        drivers.append({
            "key": r["key"], "label": r.get("label"), "role": r["role"],
            "source": r.get("source"), "freq": r["test_freq"],
            "pearson": r["pearson"], "excess_pearson": r.get("excess_pearson"),
            "best_lag": r["best_lag"], "ic": r.get("ic"),
            "beta": (r.get("ols") or {}).get("beta"),
            "r2": (r.get("ols") or {}).get("r2"), "p": (r.get("ols") or {}).get("p"),
            "n": r["n"], "theory_agree": r["theory_agree"], "stable": r["stable"],
            "sign": r.get("emp_sign"), "why": r.get("why"),
            "posture": (r.get("live") or {}).get("posture"),
            "last_chg_z": r.get("last_chg_z"), "last_obs": r.get("last_obs"),
        })
    return {
        "id": art["id"], "sub_sector": art["sub_sector"], "sector": art["sector"],
        "priority": art.get("priority"), "status": art.get("status"),
        "grade": art.get("grade"), "verdict": m.get("verdict"),
        "score": m.get("score"), "confidence": m.get("confidence"),
        "net_tilt": m.get("net_tilt"), "demand_tilt": m.get("demand_tilt"),
        "supply_tilt": m.get("supply_tilt"), "cost_tilt": m.get("cost_tilt"),
        "macro_tilt": m.get("macro_tilt"),
        "multivariate": m.get("multivariate"), "narrative": m.get("narrative"),
        "n_kept": m.get("n_kept"), "n_tested": art.get("n_tested"),
        "n_used": art.get("basket", {}).get("n_used"),
        "total_mcap": art.get("basket", {}).get("total_mcap"),
        "members_used": art.get("basket", {}).get("members_used"),
        "coverage": art.get("basket", {}).get("coverage"),
        "drivers": drivers, "generated_at": art.get("generated_at"),
    }


def compile_engine() -> dict:
    arts = []
    for f in sorted(C.OUTPUT_DIR.glob("*.json")):
        if f.name in ("engine.json",):
            continue
        a = C.read_json(f)
        if a and a.get("id"):
            arts.append(a)
    arts.sort(key=lambda a: a.get("priority") or 999)
    engine = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "n_baskets": len(arts),
        "method": "Per-IDX-sub-industry demand/supply driver engine: HAC-OLS + "
                  "lead-lag + Spearman-IC + split-sample stability + multivariate "
                  "+ expanding-window OOS, theory-reconciled. Primary target = "
                  "weight-capped basket return; benchmark = IHSG.",
        "baskets": [_compact(a) for a in arts],
    }
    C.write_json(C.OUTPUT_DIR / "engine.json", engine)
    _write_js(engine)
    return engine


def _write_js(engine: dict) -> None:
    try:
        JS_TARGET.parent.mkdir(parents=True, exist_ok=True)
        body = json.dumps(engine, ensure_ascii=False, separators=(",", ":"))
        js = ("/* AUTO-GENERATED by industry-engine/engine/persist.py — do not "
              "edit by hand. */\n"
              "window.INDUSTRY_ENGINE = " + body + ";\n")
        JS_TARGET.write_text(js, encoding="utf-8")
        C.log(f"  wrote {JS_TARGET.name} ({len(engine['baskets'])} baskets)")
    except Exception as e:  # noqa: BLE001
        C.log(f"  JS write failed: {e}", level="WARN")


if __name__ == "__main__":
    eng = compile_engine()
    print(f"engine.json: {eng['n_baskets']} baskets")
