"""US Reuters Polls — Batch 05 (Labor, Durables, Agri)."""

TIER1: dict[str, dict] = {

    # ── JOLTS Job Openings ──────────────────────────────────────────────────
    "USJOLT=ECI": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "BLS monthly actual count of US job openings (JOLTS), released with ~6-week lag. Measures unfilled demand for labor across all industries.",
        "how_to_use": "Pre-COVID baseline ~7M; peaked ~12M (2022); now ~8M. Rising openings signal tight labor supply and support Fed hawkishness; compare with quits and layoffs in the same release.",
        "related_series": ["pUSJOLT=M", "pUSJOLT=E", "pUSJOLT=T", "aUSJOLTHQ"],
    },
    "pUSJOLT=M": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "Median consensus forecast for US JOLTS Job Openings from Reuters poll conducted ~1 week before BLS release.",
        "how_to_use": "Primary benchmark for surprise calculation; positive surprise (actual > median) lifts short-dated Treasuries via Fed tightening expectations. Track alongside NFP and quits rate.",
        "related_series": ["USJOLT=ECI", "pUSJOLT=E", "pUSJOLT=T", "aUSJOLTHQ"],
    },
    "pUSJOLT=F": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "SmartEconomics model-based forecast for JOLTS Job Openings, derived from macro factor inputs rather than surveyed economists.",
        "how_to_use": "Compare vs median (=M) to detect systematic model bias; large divergence may signal non-consensus regime shift in labor demand.",
        "related_series": ["USJOLT=ECI", "pUSJOLT=M", "pUSJOLT=P", "aUSJOLTHQ"],
    },
    "pUSJOLT=P": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "Predicted surprise for JOLTS Job Openings — SmartEconomics estimate of likely direction and magnitude of deviation from consensus.",
        "how_to_use": "Use pre-release to position for surprise risk; a strongly positive predicted surprise combined with tight labor market context raises rate-hike odds.",
        "related_series": ["USJOLT=ECI", "pUSJOLT=M", "pUSJOLT=F", "pUSJOLT=T"],
    },
    "pUSJOLT=E": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "Mean (average) of all surveyed economist forecasts for JOLTS Job Openings for the upcoming BLS release.",
        "how_to_use": "Use with median (=M) to detect skew in the distribution; mean > median indicates upside outlier forecasts skewing expectations.",
        "related_series": ["USJOLT=ECI", "pUSJOLT=M", "pUSJOLT=L", "pUSJOLT=H"],
    },
    "pUSJOLT=O": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "Mode (most frequently submitted) forecast for JOLTS Job Openings among Reuters poll respondents.",
        "how_to_use": "Mode near median confirms tight consensus clustering; large gap signals bi-modal forecast distribution and higher surprise risk.",
        "related_series": ["USJOLT=ECI", "pUSJOLT=M", "pUSJOLT=E", "pUSJOLT=T"],
    },
    "pUSJOLT=L": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "Minimum (most pessimistic) individual forecast for JOLTS Job Openings submitted in the Reuters poll.",
        "how_to_use": "Defines the bearish tail of analyst expectations; actual print below min signals an extreme downside surprise with potential risk-off impact.",
        "related_series": ["pUSJOLT=M", "pUSJOLT=H", "pUSJOLT=T", "USJOLT=ECI"],
    },
    "pUSJOLT=H": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "Maximum (most optimistic) individual forecast for JOLTS Job Openings submitted in the Reuters poll.",
        "how_to_use": "Defines the bullish tail; actual print above max is an extreme upside surprise, typically hawkish for rates and bullish for USD.",
        "related_series": ["pUSJOLT=M", "pUSJOLT=L", "pUSJOLT=T", "USJOLT=ECI"],
    },
    "pUSJOLT=T": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Millions of openings",
        "meaning": "Standard deviation of forecasts for JOLTS Job Openings across all Reuters poll respondents, measuring forecast dispersion.",
        "how_to_use": "High StdDev ahead of release signals elevated uncertainty; wider dispersion increases options premium on rate-sensitive instruments around JOLTS day.",
        "related_series": ["pUSJOLT=M", "pUSJOLT=L", "pUSJOLT=H", "pUSJOLT=C"],
    },
    "pUSJOLT=C": {
        "slug": "us_polls",
        "subcategory": "JOLTS Job Openings",
        "units": "Count",
        "meaning": "Number of economists who submitted a forecast for JOLTS Job Openings in the Reuters poll for the current release cycle.",
        "how_to_use": "Higher count improves reliability of median/mean; fewer than ~15 respondents makes the consensus less representative of street expectations.",
        "related_series": ["pUSJOLT=M", "pUSJOLT=E", "pUSJOLT=T", "USJOLT=ECI"],
    },

    # ── Durable Goods Orders MM ─────────────────────────────────────────────
    "USDGN=ECI": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Census Bureau monthly actual MoM percent change in US durable goods orders (items intended to last 3+ years), released ~25-26th of the following month.",
        "how_to_use": "Highly volatile due to aircraft/defense swings; use Ex-Transport (USDGXT=ECI) for trend. Upside surprises lift cyclicals and USD.",
        "related_series": ["pUSDGN=M", "USDGXT=ECI", "USNDXA=ECI", "aUSDGOAR"],
    },
    "pUSDGN=M": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Median consensus forecast for the MoM change in US durable goods orders from the Reuters pre-release poll.",
        "how_to_use": "Headline durable goods is noisy; track deviation from median alongside Ex-Transport median to distinguish underlying trend from transport volatility.",
        "related_series": ["USDGN=ECI", "pUSDGN=E", "pUSDGXT=M", "aUSDGOAR"],
    },
    "pUSDGN=F": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "SmartEconomics model-based forecast for durable goods orders MoM change.",
        "how_to_use": "Compare vs median (=M) to flag potential non-consensus signal; useful for assessing whether model factors (PMI, ISM) confirm or diverge from analyst consensus.",
        "related_series": ["USDGN=ECI", "pUSDGN=M", "pUSDGN=P", "aUSDGOAR"],
    },
    "pUSDGN=P": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Predicted surprise for durable goods orders — SmartEconomics directional estimate of deviation from consensus at release.",
        "how_to_use": "Use pre-release to gauge skew risk; combine with ISM Manufacturing New Orders as a directional cross-check.",
        "related_series": ["USDGN=ECI", "pUSDGN=M", "pUSDGN=F", "pUSDGN=T"],
    },
    "pUSDGN=E": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Mean forecast for durable goods orders MoM change across all Reuters poll respondents.",
        "how_to_use": "Compare mean vs median to detect skew from outlier forecasters; outlier large Boeing orders sometimes pull mean well above median.",
        "related_series": ["USDGN=ECI", "pUSDGN=M", "pUSDGN=L", "pUSDGN=H"],
    },
    "pUSDGN=O": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Mode (most common) forecast for durable goods orders MoM change among Reuters poll respondents.",
        "how_to_use": "Mode clustering near zero indicates consensus expects a flat month; significant deviation from median signals split views on transport orders.",
        "related_series": ["USDGN=ECI", "pUSDGN=M", "pUSDGN=E", "pUSDGN=T"],
    },
    "pUSDGN=L": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Minimum individual forecast for durable goods orders MoM change in the Reuters poll.",
        "how_to_use": "Defines the bearish bound; actual print below min indicates an extreme negative surprise, typically negative for industrial/cyclical equities.",
        "related_series": ["pUSDGN=M", "pUSDGN=H", "pUSDGN=T", "USDGN=ECI"],
    },
    "pUSDGN=H": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Maximum individual forecast for durable goods orders MoM change in the Reuters poll.",
        "how_to_use": "Defines the bullish bound; Boeing large-order months can produce prints well above max, which tend to be followed by mean-reversion next month.",
        "related_series": ["pUSDGN=M", "pUSDGN=L", "pUSDGN=T", "USDGN=ECI"],
    },
    "pUSDGN=T": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Percent MoM",
        "meaning": "Standard deviation of durable goods orders forecasts across Reuters poll respondents.",
        "how_to_use": "High StdDev reflects uncertainty about aircraft/defense swing factor; compare with Ex-Transport StdDev to isolate volatility source.",
        "related_series": ["pUSDGN=M", "pUSDGN=L", "pUSDGN=H", "pUSDGN=C"],
    },
    "pUSDGN=C": {
        "slug": "us_polls",
        "subcategory": "Durable Goods Orders MM",
        "units": "Count",
        "meaning": "Number of economists submitting a forecast for durable goods orders in the current Reuters poll cycle.",
        "how_to_use": "Validate consensus reliability; low count ahead of releases following large Boeing announcements reflects forecaster uncertainty about transport component.",
        "related_series": ["pUSDGN=M", "pUSDGN=E", "pUSDGN=T", "USDGN=ECI"],
    },

    # ── Durables Ex-Defense MM ──────────────────────────────────────────────
    "USDGND=ECI": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Actual MoM percent change in US durable goods orders excluding volatile defense spending, from Census Bureau.",
        "how_to_use": "Removes lumpy government contracts to reveal private-sector demand; compare with headline and Ex-Transport to triangulate underlying manufacturing momentum.",
        "related_series": ["pUSDGND=M", "USDGN=ECI", "USDGXT=ECI", "aUSDGOAR"],
    },
    "pUSDGND=M": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Median consensus forecast for durable goods orders MoM change excluding defense orders from the Reuters poll.",
        "how_to_use": "Use to separate private demand trends from government contract timing; persistent upside vs consensus indicates non-defense manufacturing recovery.",
        "related_series": ["USDGND=ECI", "pUSDGND=E", "pUSDGN=M", "pUSDGXT=M"],
    },
    "pUSDGND=F": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "SmartEconomics model forecast for durable goods ex-defense MoM change.",
        "how_to_use": "Compare vs median to check if macro models aligned on defense-stripped trend; useful when large DoD contracts distort headline consensus.",
        "related_series": ["USDGND=ECI", "pUSDGND=M", "pUSDGND=P", "aUSDGOAR"],
    },
    "pUSDGND=P": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Predicted surprise for durable goods ex-defense orders MoM change.",
        "how_to_use": "Signals pre-release surprise direction for private manufacturing demand; combine with ISM New Orders sub-index as a cross-check.",
        "related_series": ["USDGND=ECI", "pUSDGND=M", "pUSDGND=F", "pUSDGND=T"],
    },
    "pUSDGND=E": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Mean forecast for durable goods ex-defense MoM change across Reuters poll respondents.",
        "how_to_use": "Compare vs median to identify skew; outlier views on commercial aircraft can still distort mean even after defense exclusion.",
        "related_series": ["USDGND=ECI", "pUSDGND=M", "pUSDGND=L", "pUSDGND=H"],
    },
    "pUSDGND=O": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Mode forecast for durable goods ex-defense MoM change among Reuters poll respondents.",
        "how_to_use": "Tight clustering of mode near median signals analyst consensus on underlying ex-defense trend; gaps indicate split views.",
        "related_series": ["USDGND=ECI", "pUSDGND=M", "pUSDGND=E", "pUSDGND=T"],
    },
    "pUSDGND=L": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Minimum individual forecast for durable goods ex-defense MoM change in the Reuters poll.",
        "how_to_use": "Defines the bearish scenario for private manufacturing; useful for stress-testing capex outlooks when combined with core capex (USNDXA) range.",
        "related_series": ["pUSDGND=M", "pUSDGND=H", "pUSDGND=T", "USDGND=ECI"],
    },
    "pUSDGND=H": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Maximum individual forecast for durable goods ex-defense MoM change in the Reuters poll.",
        "how_to_use": "Defines the bullish scenario; actual print above max indicates unexpected surge in private-sector capital goods demand.",
        "related_series": ["pUSDGND=M", "pUSDGND=L", "pUSDGND=T", "USDGND=ECI"],
    },
    "pUSDGND=T": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Percent MoM",
        "meaning": "Standard deviation of durable goods ex-defense MoM forecasts across Reuters poll respondents.",
        "how_to_use": "Lower StdDev vs headline durables confirms defense exclusion reduces forecast uncertainty; persistent high StdDev may reflect aircraft order uncertainty.",
        "related_series": ["pUSDGND=M", "pUSDGND=L", "pUSDGND=H", "pUSDGND=C"],
    },
    "pUSDGND=C": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Defense MM",
        "units": "Count",
        "meaning": "Number of forecasters submitting an ex-defense durable goods estimate in the current Reuters poll.",
        "how_to_use": "Typically lower response rate than headline durables; low count increases noise in consensus measures.",
        "related_series": ["pUSDGND=M", "pUSDGND=E", "pUSDGND=T", "USDGND=ECI"],
    },

    # ── Durables Ex-Transport MM ────────────────────────────────────────────
    "USDGXT=ECI": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Actual MoM percent change in US durable goods orders excluding transportation equipment (aircraft, autos), from Census Bureau.",
        "how_to_use": "Preferred signal for underlying manufacturing demand since it strips Boeing batch effects; sustained positive trend indicates broad capex expansion.",
        "related_series": ["pUSDGXT=M", "USDGN=ECI", "USNDXA=ECI", "aUSDGOAR"],
    },
    "pUSDGXT=M": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Median consensus forecast for durable goods ex-transport MoM change from the Reuters pre-release poll.",
        "how_to_use": "Most watched durables sub-forecast by markets; positive surprise vs this median is the cleaner signal for industrial/capex sentiment compared to headline.",
        "related_series": ["USDGXT=ECI", "pUSDGXT=E", "pUSNDXA=M", "aUSDGOAR"],
    },
    "pUSDGXT=F": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "SmartEconomics model-based forecast for durable goods ex-transport MoM change.",
        "how_to_use": "Compare vs median for model vs analyst divergence on core manufacturing trend; PMI/ISM inputs typically anchor this estimate.",
        "related_series": ["USDGXT=ECI", "pUSDGXT=M", "pUSDGXT=P", "aUSDGOAR"],
    },
    "pUSDGXT=P": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Predicted surprise for durable goods ex-transport MoM change.",
        "how_to_use": "Pre-release surprise gauge for core manufacturing demand; positive predicted surprise with ISM confirmation raises industrial equity and USD outlook.",
        "related_series": ["USDGXT=ECI", "pUSDGXT=M", "pUSDGXT=F", "pUSDGXT=T"],
    },
    "pUSDGXT=E": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Mean forecast for durable goods ex-transport MoM change across all Reuters poll respondents.",
        "how_to_use": "Compare with median to check for outlier forecaster influence on the distribution of expectations for core manufacturing.",
        "related_series": ["USDGXT=ECI", "pUSDGXT=M", "pUSDGXT=L", "pUSDGXT=H"],
    },
    "pUSDGXT=O": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Mode forecast for durable goods ex-transport MoM change among Reuters poll respondents.",
        "how_to_use": "When mode matches median, consensus is tightly formed; divergence signals forecaster disagreement on auto/machinery sub-component trends.",
        "related_series": ["USDGXT=ECI", "pUSDGXT=M", "pUSDGXT=E", "pUSDGXT=T"],
    },
    "pUSDGXT=L": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Minimum individual forecast for durable goods ex-transport MoM change in the Reuters poll.",
        "how_to_use": "Bearish bound for core manufacturing; actual below min is a strong contraction signal that may weigh on industrial capex outlook.",
        "related_series": ["pUSDGXT=M", "pUSDGXT=H", "pUSDGXT=T", "USDGXT=ECI"],
    },
    "pUSDGXT=H": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Maximum individual forecast for durable goods ex-transport MoM change in the Reuters poll.",
        "how_to_use": "Bullish bound for core manufacturing; print above max signals broad-based order strength and supports upward Industrial Production revisions.",
        "related_series": ["pUSDGXT=M", "pUSDGXT=L", "pUSDGXT=T", "USDGXT=ECI"],
    },
    "pUSDGXT=T": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Percent MoM",
        "meaning": "Standard deviation of durable goods ex-transport MoM forecasts across Reuters poll respondents.",
        "how_to_use": "Benchmark uncertainty for core manufacturing; compare to headline StdDev to confirm that stripping transport reduces forecast variance.",
        "related_series": ["pUSDGXT=M", "pUSDGXT=L", "pUSDGXT=H", "pUSDGXT=C"],
    },
    "pUSDGXT=C": {
        "slug": "us_polls",
        "subcategory": "Durables Ex-Transport MM",
        "units": "Count",
        "meaning": "Number of economists submitting a durable goods ex-transport forecast in the current Reuters poll.",
        "how_to_use": "Higher participation than ex-defense given analyst focus on this strip; validate consensus quality, especially following supply-chain disruption periods.",
        "related_series": ["pUSDGXT=M", "pUSDGXT=E", "pUSDGXT=T", "USDGXT=ECI"],
    },

    # ── Nondefense Capital Goods Ex-Air (Core Capex) ─────────────────────────
    "USNDXA=ECI": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Actual MoM percent change in US nondefense capital goods orders excluding aircraft — the 'core capex' proxy — from Census Bureau.",
        "how_to_use": "Best single indicator for US business investment intentions; leads Industrial Production by 1-3 months. Sustained positive trend supports GDP upgrades and equity risk appetite.",
        "related_series": ["pUSNDXA=M", "USNDCG=ECI", "USDGXT=ECI", "aUSDGCNAR"],
    },
    "pUSNDXA=M": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Median consensus forecast for nondefense capital goods ex-aircraft (core capex) MoM change from the Reuters pre-release poll.",
        "how_to_use": "Benchmark for capex surprise; positive print vs median supports business investment narrative and leads Industrial Production revisions upward.",
        "related_series": ["USNDXA=ECI", "pUSNDXA=E", "pUSNDXA=T", "aUSDGCNAR"],
    },
    "pUSNDXA=F": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "SmartEconomics model-based forecast for core capex (nondefense cap goods ex-air) MoM change.",
        "how_to_use": "Compare vs median to detect model-driven capex signal; macro model inputs (ISM Capital Goods, PPI metals) often lead analyst surveys on this series.",
        "related_series": ["USNDXA=ECI", "pUSNDXA=M", "pUSNDXA=P", "aUSDGCNAR"],
    },
    "pUSNDXA=P": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Predicted surprise for core capex (nondefense capital goods ex-air) MoM change.",
        "how_to_use": "Key pre-release risk gauge for business investment tone; strong positive predicted surprise alongside rising ISM Capex is a GDP growth signal.",
        "related_series": ["USNDXA=ECI", "pUSNDXA=M", "pUSNDXA=F", "pUSNDXA=T"],
    },
    "pUSNDXA=E": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Mean forecast for core capex MoM change across all Reuters poll respondents.",
        "how_to_use": "Compare with median; outlier bullish capex views (M&A-driven equipment orders) can pull mean above median.",
        "related_series": ["USNDXA=ECI", "pUSNDXA=M", "pUSNDXA=L", "pUSNDXA=H"],
    },
    "pUSNDXA=O": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Mode forecast for core capex MoM change among Reuters poll respondents.",
        "how_to_use": "Tight mode-median alignment confirms consensus on business investment trend; wide gap flags analyst disagreement about capex cycle phase.",
        "related_series": ["USNDXA=ECI", "pUSNDXA=M", "pUSNDXA=E", "pUSNDXA=T"],
    },
    "pUSNDXA=L": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Minimum individual forecast for core capex MoM change in the Reuters poll.",
        "how_to_use": "Defines bearish capex scenario; print below min signals capex contraction that may prompt downward GDP tracking revisions.",
        "related_series": ["pUSNDXA=M", "pUSNDXA=H", "pUSNDXA=T", "USNDXA=ECI"],
    },
    "pUSNDXA=H": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Maximum individual forecast for core capex MoM change in the Reuters poll.",
        "how_to_use": "Defines bullish capex scenario; print above max indicates broad investment acceleration, typically supportive of industrial and tech equities.",
        "related_series": ["pUSNDXA=M", "pUSNDXA=L", "pUSNDXA=T", "USNDXA=ECI"],
    },
    "pUSNDXA=T": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Percent MoM",
        "meaning": "Standard deviation of core capex MoM forecasts across Reuters poll respondents.",
        "how_to_use": "Elevated StdDev preceding a cycle turn (recession or recovery) is typical; monitor alongside GDPNow capex tracker for consistency.",
        "related_series": ["pUSNDXA=M", "pUSNDXA=L", "pUSNDXA=H", "pUSNDXA=C"],
    },
    "pUSNDXA=C": {
        "slug": "us_polls",
        "subcategory": "Nondefense Capital Goods Ex-Air",
        "units": "Count",
        "meaning": "Number of economists submitting a core capex forecast in the current Reuters poll.",
        "how_to_use": "Core capex typically draws fewer respondents than headline durables; low count reduces statistical reliability of median and mean.",
        "related_series": ["pUSNDXA=M", "pUSNDXA=E", "pUSNDXA=T", "USNDXA=ECI"],
    },

    # ── Nondef Cap Ex-Air Revised MM (Actual only) ──────────────────────────
    "USNDCG=ECI": {
        "slug": "us_polls",
        "subcategory": "Nondef Cap Ex-Air R MM",
        "units": "Percent MoM",
        "meaning": "Revised actual MoM percent change for nondefense capital goods orders excluding aircraft, published alongside the following month's advance release.",
        "how_to_use": "Revision from the advance (USNDXA=ECI) captures order adjustments; compare advance vs revised to assess measurement noise and improve forecasting models.",
        "related_series": ["USNDXA=ECI", "pUSNDXA=M", "USDGXT=ECI", "aUSDGCNAR"],
    },

    # ── Factory Orders MM ───────────────────────────────────────────────────
    "USFORD=ECI": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Census Bureau actual MoM percent change in total US factory orders (durable + nondurable goods), released ~4 weeks after the reference month.",
        "how_to_use": "Broader than durables alone; nondurable component (chemicals, food, petroleum) adds refinery and consumer goods cycle signals. Upside confirms manufacturing recovery.",
        "related_series": ["pUSFORD=M", "USDGN=ECI", "USDGXT=ECI", "aUSFCTOAR"],
    },
    "pUSFORD=M": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Median consensus forecast for US factory orders MoM change from the Reuters pre-release poll.",
        "how_to_use": "Primary factory orders benchmark; surprise vs median typically drives industrials and materials equities. Cross-check with the durables advance release already known.",
        "related_series": ["USFORD=ECI", "pUSFORD=E", "pUSFORD=T", "aUSFCTOAR"],
    },
    "pUSFORD=F": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "SmartEconomics model-based forecast for factory orders MoM change.",
        "how_to_use": "Compare vs median; model may incorporate petroleum-price and PMI signals that analyst surveys lag, especially for nondurable component.",
        "related_series": ["USFORD=ECI", "pUSFORD=M", "pUSFORD=P", "aUSFCTOAR"],
    },
    "pUSFORD=P": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Predicted surprise for factory orders MoM change — SmartEconomics directional estimate of actual deviation from consensus.",
        "how_to_use": "Use pre-release to size surprise risk for broad manufacturing; strongly positive predicted surprise supports cyclical equity rotation.",
        "related_series": ["USFORD=ECI", "pUSFORD=M", "pUSFORD=F", "pUSFORD=T"],
    },
    "pUSFORD=E": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Mean forecast for factory orders MoM change across all Reuters poll respondents.",
        "how_to_use": "Compare mean vs median; energy-price swings can pull nondurable orders outliers, creating mean-median skew in the forecast distribution.",
        "related_series": ["USFORD=ECI", "pUSFORD=M", "pUSFORD=L", "pUSFORD=H"],
    },
    "pUSFORD=O": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Mode forecast for factory orders MoM change among Reuters poll respondents.",
        "how_to_use": "Mode near zero indicates stable consensus; significant positive mode reflects shared view on nondurable rebound (e.g., petroleum orders recovery).",
        "related_series": ["USFORD=ECI", "pUSFORD=M", "pUSFORD=E", "pUSFORD=T"],
    },
    "pUSFORD=L": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Minimum individual forecast for factory orders MoM change in the Reuters poll.",
        "how_to_use": "Defines worst-case scenario for total manufacturing demand; actual below min signals broad-based weakness across durable and nondurable goods.",
        "related_series": ["pUSFORD=M", "pUSFORD=H", "pUSFORD=T", "USFORD=ECI"],
    },
    "pUSFORD=H": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Maximum individual forecast for factory orders MoM change in the Reuters poll.",
        "how_to_use": "Defines bullish case; print above max would indicate unexpected surge across both durable and nondurable orders, rare outside energy-price spikes.",
        "related_series": ["pUSFORD=M", "pUSFORD=L", "pUSFORD=T", "USFORD=ECI"],
    },
    "pUSFORD=T": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Percent MoM",
        "meaning": "Standard deviation of factory orders MoM forecasts across Reuters poll respondents.",
        "how_to_use": "Elevated StdDev typically driven by uncertainty in petroleum/chemicals orders; compare with durable goods StdDev to identify nondurable uncertainty component.",
        "related_series": ["pUSFORD=M", "pUSFORD=L", "pUSFORD=H", "pUSFORD=C"],
    },
    "pUSFORD=C": {
        "slug": "us_polls",
        "subcategory": "Factory Orders MM",
        "units": "Count",
        "meaning": "Number of economists submitting a factory orders forecast in the current Reuters poll.",
        "how_to_use": "Factory orders draws a moderate response rate; lower count than NFP or CPI polls — validate consensus size before trading the surprise.",
        "related_series": ["pUSFORD=M", "pUSFORD=E", "pUSFORD=T", "USFORD=ECI"],
    },

    # ── Bean Oil Stocks (NOPA) ──────────────────────────────────────────────
    "USBOS=ECI": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Actual NOPA monthly soybean oil inventory stocks in millions of pounds, measuring crude soy oil held by processing members.",
        "how_to_use": "Tight stocks indicate strong biofuel or food demand; bearish if above consensus (ample supply). Compare with CBOT soybean oil futures (BO) for basis moves.",
        "related_series": ["pUSBOS=M", "USNSC=ECI", "pUSBOS=T", "pUSNSC=M"],
    },
    "pUSBOS=M": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Median consensus forecast for NOPA soybean oil stocks from the Reuters pre-release poll, typically from ~10 analysts.",
        "how_to_use": "Primary benchmark for CBOT soy oil surprise; print below median (tighter stocks) is bullish for BO futures and soybean complex broadly.",
        "related_series": ["USBOS=ECI", "pUSBOS=E", "pUSBOS=T", "pUSNSC=M"],
    },
    "pUSBOS=F": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "SmartEconomics model-based forecast for NOPA bean oil stocks.",
        "how_to_use": "Compare vs median; model may incorporate crush pace, biofuel mandate data, and export inspections to produce a supply-side estimate.",
        "related_series": ["USBOS=ECI", "pUSBOS=M", "pUSBOS=P", "USNSC=ECI"],
    },
    "pUSBOS=P": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Predicted surprise for NOPA bean oil stocks — directional estimate of deviation from consensus at release.",
        "how_to_use": "Use pre-release to set bias for CBOT soy oil and RD/RIN (renewable diesel) feedstock trades; tighter-than-expected stocks lift biofuel margins.",
        "related_series": ["USBOS=ECI", "pUSBOS=M", "pUSBOS=F", "pUSBOS=T"],
    },
    "pUSBOS=E": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Mean forecast for NOPA bean oil stocks across all Reuters poll respondents.",
        "how_to_use": "Compare vs median; mean-median divergence in small-sample agri polls is common — weight median more heavily for market impact assessment.",
        "related_series": ["USBOS=ECI", "pUSBOS=M", "pUSBOS=L", "pUSBOS=H"],
    },
    "pUSBOS=O": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Mode forecast for NOPA bean oil stocks among Reuters poll respondents.",
        "how_to_use": "With a small analyst panel, mode can equal median; large gap signals diverse views on seasonal drawdown pace or biofuel demand.",
        "related_series": ["USBOS=ECI", "pUSBOS=M", "pUSBOS=E", "pUSBOS=T"],
    },
    "pUSBOS=L": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Minimum individual forecast for NOPA bean oil stocks in the Reuters poll.",
        "how_to_use": "Defines most bullish (tightest supply) scenario; actual below min is a major upside surprise for CBOT BO futures and soy crush margins.",
        "related_series": ["pUSBOS=M", "pUSBOS=H", "pUSBOS=T", "USBOS=ECI"],
    },
    "pUSBOS=H": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Maximum individual forecast for NOPA bean oil stocks in the Reuters poll.",
        "how_to_use": "Defines most bearish (loosest supply) scenario; actual above max pressures BO futures and signals weaker biofuel or export demand than expected.",
        "related_series": ["pUSBOS=M", "pUSBOS=L", "pUSBOS=T", "USBOS=ECI"],
    },
    "pUSBOS=T": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Million pounds",
        "meaning": "Standard deviation of NOPA bean oil stocks forecasts across Reuters poll respondents.",
        "how_to_use": "Small analyst panel means StdDev can be large relative to median; high uncertainty reflects variable biofuel blending mandate pace.",
        "related_series": ["pUSBOS=M", "pUSBOS=L", "pUSBOS=H", "pUSBOS=C"],
    },
    "pUSBOS=C": {
        "slug": "us_polls",
        "subcategory": "Bean Oil Stocks",
        "units": "Count",
        "meaning": "Number of analysts submitting a bean oil stocks forecast in the current Reuters poll.",
        "how_to_use": "NOPA polls draw a small specialist panel (~8-15 respondents); interpret consensus with caution when count is below 10.",
        "related_series": ["pUSBOS=M", "pUSBOS=E", "pUSBOS=T", "USBOS=ECI"],
    },

    # ── NOPA-Soy Crush ──────────────────────────────────────────────────────
    "USNSC=ECI": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Actual monthly volume of soybeans crushed by NOPA member processors, reported in million bushels (56 lb/bu), typically released mid-month.",
        "how_to_use": "Strong crush pace draws down soybean stocks and supports CBOT soybean prices (ZS); cross-check with USDA crush estimates for seasonal demand trend.",
        "related_series": ["pUSNSC=M", "USBOS=ECI", "USSSQ=ECI", "pUSNSC=T"],
    },
    "pUSNSC=M": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Median consensus forecast for NOPA monthly soy crush volume from the Reuters pre-release poll.",
        "how_to_use": "Primary crush benchmark; actual above median (stronger crush) is bullish for CBOT soybeans (ZS) and signals strong meal/oil demand from livestock and biofuel sectors.",
        "related_series": ["USNSC=ECI", "pUSNSC=E", "pUSNSC=T", "pUSBOS=M"],
    },
    "pUSNSC=F": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "SmartEconomics model-based forecast for NOPA monthly soy crush volume.",
        "how_to_use": "Compare vs median; model likely incorporates crush margins, soybean meal export inspections, and biofuel demand signals.",
        "related_series": ["USNSC=ECI", "pUSNSC=M", "pUSNSC=P", "USBOS=ECI"],
    },
    "pUSNSC=P": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Predicted surprise for NOPA soy crush — directional estimate of actual deviation from consensus at release.",
        "how_to_use": "Use pre-release for CBOT soy positioning; positive predicted surprise combined with tight soybean stocks is a strong bullish signal for ZS futures.",
        "related_series": ["USNSC=ECI", "pUSNSC=M", "pUSNSC=F", "pUSNSC=T"],
    },
    "pUSNSC=E": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Mean forecast for NOPA soy crush volume across all Reuters poll respondents.",
        "how_to_use": "Small specialist panel; compare mean vs median to assess whether outlier crush estimates skew the distribution, common during seasonal processing peaks.",
        "related_series": ["USNSC=ECI", "pUSNSC=M", "pUSNSC=L", "pUSNSC=H"],
    },
    "pUSNSC=O": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Mode forecast for NOPA soy crush volume among Reuters poll respondents.",
        "how_to_use": "Mode-median clustering indicates consensus on processing pace; wide gap signals split analyst views on crush margin incentives.",
        "related_series": ["USNSC=ECI", "pUSNSC=M", "pUSNSC=E", "pUSNSC=T"],
    },
    "pUSNSC=L": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Minimum individual forecast for NOPA soy crush volume in the Reuters poll.",
        "how_to_use": "Defines the bearish crush scenario (weak processing demand); actual below min suggests plant outages or margin compression reducing crush pace.",
        "related_series": ["pUSNSC=M", "pUSNSC=H", "pUSNSC=T", "USNSC=ECI"],
    },
    "pUSNSC=H": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Maximum individual forecast for NOPA soy crush volume in the Reuters poll.",
        "how_to_use": "Defines the bullish crush scenario; actual above max indicates exceptional processing pace, strongly bullish for soybean cash basis and ZS futures.",
        "related_series": ["pUSNSC=M", "pUSNSC=L", "pUSNSC=T", "USNSC=ECI"],
    },
    "pUSNSC=T": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Million bushels",
        "meaning": "Standard deviation of NOPA soy crush volume forecasts across Reuters poll respondents.",
        "how_to_use": "Seasonal peaks (Sep-Nov) show lower StdDev as crush pace is predictable; high StdDev outside peak season signals unusual margin or supply disruption uncertainty.",
        "related_series": ["pUSNSC=M", "pUSNSC=L", "pUSNSC=H", "pUSNSC=C"],
    },
    "pUSNSC=C": {
        "slug": "us_polls",
        "subcategory": "NOPA-Soy Crush",
        "units": "Count",
        "meaning": "Number of analysts submitting a NOPA soy crush forecast in the current Reuters poll.",
        "how_to_use": "Specialist agri panel; low count (~8-12) is typical — weigh consensus quality accordingly and cross-reference USDA weekly crush data.",
        "related_series": ["pUSNSC=M", "pUSNSC=E", "pUSNSC=T", "USNSC=ECI"],
    },

    # ── Quarterly Grain Stocks — Soybeans ───────────────────────────────────
    "USSSQ=ECI": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Actual USDA quarterly US soybean stocks (on-farm + off-farm), released four times per year in the Grain Stocks report.",
        "how_to_use": "Major price-moving report for CBOT soybeans (ZS); stocks below consensus trigger limit-up moves. December 1 stocks are especially critical for new-crop supply outlook.",
        "related_series": ["pUSSSQ=M", "USWSQ=ECI", "USNSC=ECI", "pUSSSQ=T"],
    },
    "pUSSSQ=M": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Median consensus forecast for USDA quarterly soybean stocks from the Reuters pre-release poll.",
        "how_to_use": "Primary benchmark for CBOT ZS surprise; actual below median is strongly bullish for soybeans — these quarterly reports drive multi-cent daily moves in futures.",
        "related_series": ["USSSQ=ECI", "pUSSSQ=E", "pUSSSQ=T", "pUSWSQ=M"],
    },
    "pUSSSQ=F": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "SmartEconomics model-based forecast for USDA quarterly soybean stocks.",
        "how_to_use": "Compare vs median; model incorporates crush pace, export inspections, and USDA supply/use balance adjustments to estimate residual stocks.",
        "related_series": ["USSSQ=ECI", "pUSSSQ=M", "pUSSSQ=P", "USNSC=ECI"],
    },
    "pUSSSQ=P": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Predicted surprise for USDA quarterly soybean stocks — directional estimate of actual vs consensus deviation.",
        "how_to_use": "High-value pre-release signal for CBOT soy positioning; a strongly negative predicted surprise (tighter stocks) ahead of Dec 1 or Mar 1 stocks supports aggressive long ZS trades.",
        "related_series": ["USSSQ=ECI", "pUSSSQ=M", "pUSSSQ=F", "pUSSSQ=T"],
    },
    "pUSSSQ=E": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Mean forecast for USDA quarterly soybean stocks across all Reuters poll respondents.",
        "how_to_use": "Compare with median to assess distribution skew; large crop years may generate outlier high-stocks forecasts pulling mean above median.",
        "related_series": ["USSSQ=ECI", "pUSSSQ=M", "pUSSSQ=L", "pUSSSQ=H"],
    },
    "pUSSSQ=O": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Mode forecast for USDA quarterly soybean stocks among Reuters poll respondents.",
        "how_to_use": "Mode near median confirms tight analyst consensus; mode far from median indicates split views on on-farm vs commercial storage allocation.",
        "related_series": ["USSSQ=ECI", "pUSSSQ=M", "pUSSSQ=E", "pUSSSQ=T"],
    },
    "pUSSSQ=L": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Minimum individual forecast for USDA quarterly soybean stocks in the Reuters poll.",
        "how_to_use": "Defines the most bullish (tightest supply) analyst scenario; actual below min triggers strongest soybean futures buying as all scenarios are exceeded.",
        "related_series": ["pUSSSQ=M", "pUSSSQ=H", "pUSSSQ=T", "USSSQ=ECI"],
    },
    "pUSSSQ=H": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Maximum individual forecast for USDA quarterly soybean stocks in the Reuters poll.",
        "how_to_use": "Defines the most bearish (most abundant supply) scenario; actual above max triggers downside ZS price pressure as supply exceeds all analyst estimates.",
        "related_series": ["pUSSSQ=M", "pUSSSQ=L", "pUSSSQ=T", "USSSQ=ECI"],
    },
    "pUSSSQ=T": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Billion bushels",
        "meaning": "Standard deviation of USDA quarterly soybean stocks forecasts across Reuters poll respondents.",
        "how_to_use": "High StdDev ahead of the June stocks (new-crop transition) reflects maximum uncertainty in on-farm usage estimates; low StdDev in late-season indicates predictable drawdown.",
        "related_series": ["pUSSSQ=M", "pUSSSQ=L", "pUSSSQ=H", "pUSSSQ=C"],
    },
    "pUSSSQ=C": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Soy",
        "units": "Count",
        "meaning": "Number of analysts submitting a quarterly soybean stocks forecast in the current Reuters poll.",
        "how_to_use": "Grain stocks polls attract a specialist agri panel; validate consensus reliability — low count near major USDA reports increases surprise risk.",
        "related_series": ["pUSSSQ=M", "pUSSSQ=E", "pUSSSQ=T", "USSSQ=ECI"],
    },

    # ── Quarterly Grain Stocks — Wheat ──────────────────────────────────────
    "USWSQ=ECI": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Actual USDA quarterly US wheat stocks (all positions: on-farm + off-farm) released in the Grain Stocks report four times per year.",
        "how_to_use": "Price-moving report for CBOT wheat futures (ZW); tighter-than-expected stocks drive export premium and affect global flour/bread price chain.",
        "related_series": ["pUSWSQ=M", "USSSQ=ECI", "pUSWSQ=T", "pUSWSQ=C"],
    },
    "pUSWSQ=M": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Median consensus forecast for USDA quarterly wheat stocks from the Reuters pre-release poll.",
        "how_to_use": "Primary benchmark for CBOT ZW surprise; lower-than-expected stocks relative to median is bullish for wheat, especially when global supply is already tight.",
        "related_series": ["USWSQ=ECI", "pUSWSQ=E", "pUSWSQ=T", "pUSSSQ=M"],
    },
    "pUSWSQ=F": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "SmartEconomics model-based forecast for USDA quarterly wheat stocks.",
        "how_to_use": "Compare vs median; model integrates USDA weekly export inspections, flour mill usage, and feed residual estimates to project stocks.",
        "related_series": ["USWSQ=ECI", "pUSWSQ=M", "pUSWSQ=P", "USSSQ=ECI"],
    },
    "pUSWSQ=P": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Predicted surprise for USDA quarterly wheat stocks — directional estimate of actual vs consensus deviation.",
        "how_to_use": "High-value pre-release signal for ZW futures; in low global stock environments (e.g., post-Ukraine supply shock), negative predicted surprise has outsized price impact.",
        "related_series": ["USWSQ=ECI", "pUSWSQ=M", "pUSWSQ=F", "pUSWSQ=T"],
    },
    "pUSWSQ=E": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Mean forecast for USDA quarterly wheat stocks across all Reuters poll respondents.",
        "how_to_use": "Compare mean vs median to assess distribution shape; large winter wheat crop estimates can produce outlier high-stock forecasts that pull mean above median.",
        "related_series": ["USWSQ=ECI", "pUSWSQ=M", "pUSWSQ=L", "pUSWSQ=H"],
    },
    "pUSWSQ=O": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Mode forecast for USDA quarterly wheat stocks among Reuters poll respondents.",
        "how_to_use": "Mode clustering near median confirms tight consensus on wheat supply-use balance; divergence signals uncertainty in feed-wheat usage or export pace.",
        "related_series": ["USWSQ=ECI", "pUSWSQ=M", "pUSWSQ=E", "pUSWSQ=T"],
    },
    "pUSWSQ=L": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Minimum individual forecast for USDA quarterly wheat stocks in the Reuters poll.",
        "how_to_use": "Defines the most bullish (tightest supply) analyst scenario for wheat; actual below min is a limit-up ZW signal in tight global markets.",
        "related_series": ["pUSWSQ=M", "pUSWSQ=H", "pUSWSQ=T", "USWSQ=ECI"],
    },
    "pUSWSQ=H": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Maximum individual forecast for USDA quarterly wheat stocks in the Reuters poll.",
        "how_to_use": "Defines the most bearish (most abundant supply) wheat scenario; actual above max is a negative price signal for ZW, especially in large domestic harvest years.",
        "related_series": ["pUSWSQ=M", "pUSWSQ=L", "pUSWSQ=T", "USWSQ=ECI"],
    },
    "pUSWSQ=T": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Billion bushels",
        "meaning": "Standard deviation of USDA quarterly wheat stocks forecasts across Reuters poll respondents.",
        "how_to_use": "Elevated StdDev in the June stocks report reflects maximum uncertainty about winter-wheat harvest size; cross-check with USDA crop condition ratings.",
        "related_series": ["pUSWSQ=M", "pUSWSQ=L", "pUSWSQ=H", "pUSWSQ=C"],
    },
    "pUSWSQ=C": {
        "slug": "us_polls",
        "subcategory": "Qtrly Grain Stocks-Wheat",
        "units": "Count",
        "meaning": "Number of analysts submitting a quarterly wheat stocks forecast in the current Reuters poll.",
        "how_to_use": "Agri specialist panel similar in size to soy stocks poll; low count increases noise in consensus estimates — validate with USDA export inspection data.",
        "related_series": ["pUSWSQ=M", "pUSWSQ=E", "pUSWSQ=T", "USWSQ=ECI"],
    },
}
