"""Hand-curated content for China RICs — Batch 04b (Exports part 2)."""
TIER1: dict[str, dict] = {
    "aCNCNEBQYM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Seafood",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of manufactured or preserved squid, released by China Customs ~7-10th of the following month. Reflects downstream processing capacity and demand from key buyers in Japan, South Korea, and the EU.",
        "how_to_use": "Track alongside broader seafood export trends; seasonal peaks around Chinese New Year and summer. Weakness can signal soft consumer demand abroad or tighter sanitary inspections.",
        "related_series": ["aCNCNIAEMM", "aCNCNMDXKM", "aCNCNIFWZM"],
    },
    "aCNCNIFWZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Seafood",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of manufactured or preserved squid, alternate valuation series from China Customs. Provides a cross-check on aCNCNEBQYM for reconciling reporting discrepancies.",
        "how_to_use": "Compare with the companion volume series (aCNCNIAEMM) to derive implied unit prices and detect shifts in product mix or destination markets.",
        "related_series": ["aCNCNEBQYM", "aCNCNIAEMM", "aCNCNMDXKM"],
    },
    "aCNCNIAEMM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Seafood",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of manufactured or preserved squid, released by China Customs ~7-10th of the following month. Volume data captures quantity shipped independent of price swings.",
        "how_to_use": "Pair with the value series (aCNCNEBQYM) to compute unit export prices; divergence between value and volume growth signals price changes in destination markets.",
        "related_series": ["aCNCNEBQYM", "aCNCNMDXKM", "aCNCNIFWZM"],
    },
    "aCNCNMDXKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Seafood",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of manufactured or preserved squid, alternate volume series from China Customs. Useful for verifying aCNCNIAEMM and detecting data revisions.",
        "how_to_use": "Use alongside the value counterpart to assess whether volume or pricing is driving revenue changes in China's squid export trade.",
        "related_series": ["aCNCNIAEMM", "aCNCNEBQYM", "aCNCNIFWZM"],
    },
    "aCNCNTQVM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Electronics",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of memory chips, released by China Customs ~7-10th of the following month. Reflects China's re-export and assembly role in the global semiconductor supply chain.",
        "how_to_use": "Watch for correlation with global DRAM/NAND price cycles; a surge in export value without volume growth implies price recovery. Sensitive to US export controls on advanced chips.",
        "related_series": ["aCNCNAJSFM", "aCNCNZWCEM", "aCNCEXPYB/A"],
    },
    "aCNCNZWCEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Machinery",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of metal processing machine tools, released by China Customs ~7-10th of the following month. Reflects China's growing competitiveness in industrial capital goods exports.",
        "how_to_use": "Rising machine tool exports signal China moving up the manufacturing value chain; compare with imports of high-end German/Japanese machine tools to gauge technology gap closure.",
        "related_series": ["aCNCNTQVM", "aCNCNAJSFM", "aCNCEXPYB/A"],
    },
    "aCNCNPAVJM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Mining & Minerals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of molybdenum ore and concentrates, released by China Customs ~7-10th of the following month. China is among the top global molybdenum producers; exports serve steel alloying demand in Europe and Asia.",
        "how_to_use": "Track alongside global steel output data; molybdenum demand is tied to high-strength steel for infrastructure and energy sectors. Export quotas or environmental inspections can cause sharp supply squeezes.",
        "related_series": ["aCNCNURDM", "aCNCNGLLEM", "aCNCNYVJZM"],
    },
    "aCNCNURDM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Mining & Minerals",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of molybdenum ore and concentrates, released by China Customs ~7-10th of the following month. Volume series complements the value data for deriving implied prices.",
        "how_to_use": "Compare value and volume to extract unit prices; policy-driven export restrictions common in critical minerals — volume drops ahead of formal quota announcements can be an early signal.",
        "related_series": ["aCNCNPAVJM", "aCNCNGLLEM", "aCNCNQRGNM"],
    },
    "aCNCNZJJM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Petroleum Products",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of naphtha, released by China Customs ~7-10th of the following month. Reflects surplus refinery output as China's mega-refineries run above domestic demand.",
        "how_to_use": "Naphtha exports rise when domestic petrochemical demand is weak or refinery runs are high; track alongside crude oil import volumes and domestic PMI to assess refinery utilization cycles.",
        "related_series": ["aCNCNOHCJM", "aCNCNEXOXM", "aCNCNNPYM"],
    },
    "aCNCNOHCJM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Petroleum Products",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of naphtha, released by China Customs ~7-10th of the following month. Volume data isolates physical flows from price effects.",
        "how_to_use": "Large volume spikes suggest domestic refinery oversupply; compare against Singapore naphtha crack spreads to understand export economics and destination arbitrage.",
        "related_series": ["aCNCNZJJM", "aCNCNEXOXM", "aCNCNNPYM"],
    },
    "aCNCNWFIHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals & Minerals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of natural barium sulfate (barite), released by China Customs ~7-10th of the following month. China dominates global barite supply, used in oil drilling mud and paints.",
        "how_to_use": "Monitor alongside global oil drilling activity; demand for barite spikes when offshore and onshore rig counts rise. Export controls on critical minerals can abruptly restrict supply.",
        "related_series": ["aCNCNXIKJM", "aCNCNBIJHM", "aCNCNQRGNM"],
    },
    "aCNCNQRGNM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Critical Minerals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of natural graphite, released by China Customs ~7-10th of the following month. China controls ~65% of global natural graphite supply, a critical input for EV battery anodes.",
        "how_to_use": "Highly strategic series — China imposed graphite export controls in late 2023 targeting the EV supply chain. Monitor for policy-driven disruptions affecting global battery makers.",
        "related_series": ["aCNCNPSEYM", "aCNCNWFIHM", "aCNCNPAVJM"],
    },
    "aCNCNPSEYM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Critical Minerals",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of natural graphite, released by China Customs ~7-10th of the following month. Volume series is critical given China's export licensing regime introduced in 2023.",
        "how_to_use": "Volume declines post-export-control implementation reveal the real supply impact on global EV battery producers; pair with value data to see price discovery in a controlled market.",
        "related_series": ["aCNCNQRGNM", "aCNCNWFIHM", "aCNCNPAVJM"],
    },
    "aCNCNFOQSM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of natural honey, released by China Customs ~7-10th of the following month. China is the world's largest honey producer and exporter, supplying primarily the EU, US, and Japan.",
        "how_to_use": "Watch for anti-dumping investigations and food safety incidents — the EU and US have imposed duties on Chinese honey over adulteration concerns, causing sharp export volume swings.",
        "related_series": ["aCNCNGJOEM", "aCNCNDFNKM", "aCNCNKRWDM"],
    },
    "aCNCNXIKJM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals & Minerals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of natural magnesium carbonate and magnesium oxide, released by China Customs ~7-10th of the following month. China is the dominant global supplier of magnesia, used in refractory materials and steel production.",
        "how_to_use": "Steel sector demand drives magnesia exports; weakness in global steel output cascades to lower magnesia export volumes. Track alongside China steel export data for corroboration.",
        "related_series": ["aCNCNBIJHM", "aCNCNWFIHM", "aCNCNYVJZM"],
    },
    "aCNCNBIJHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals & Minerals",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of natural magnesium carbonate and magnesium oxide, released by China Customs ~7-10th of the following month. Volume series isolates physical tonnage shipped.",
        "how_to_use": "Compare with value series (aCNCNXIKJM) to derive unit prices; China's dominance in magnesia creates pricing power — watch for energy cost pass-through in export prices.",
        "related_series": ["aCNCNXIKJM", "aCNCNWFIHM", "aCNCNGLLEM"],
    },
    "aCNCNVUOHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Paper & Printing",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of newsprint, released by China Customs ~7-10th of the following month. Newsprint exports reflect China's paper production capacity and declining domestic print media demand.",
        "how_to_use": "Secular decline expected as digital media displaces print; short-term swings driven by global paper supply-demand dynamics and pulp input costs. Niche series with limited macro signaling.",
        "related_series": ["aCNCNZUYTM", "aCNCNULEM", "aCNCEXPYB/A"],
    },
    "aCNCNEXOXM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Petroleum Products",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of other fuel oil, released by China Customs ~7-10th of the following month. Captures residual fuel oil flows from China's large independent teapot refineries targeting bunker fuel and power generation markets.",
        "how_to_use": "Track alongside China's overall oil product export quotas; the government periodically tightens quotas to manage domestic fuel supply, causing sharp export volume and price swings.",
        "related_series": ["aCNCNZJJM", "aCNCNNPYM", "aCNCNOHCJM"],
    },
    "aCNCNNPYM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Petroleum Products",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of paraffin wax, released by China Customs ~7-10th of the following month. Paraffin is a refinery by-product exported to candle, cosmetics, and packaging markets globally.",
        "how_to_use": "Watch refinery run rates and crude oil composition for supply-side signals; paraffin export volumes tend to co-move with broader petroleum product export cycles.",
        "related_series": ["aCNCNYTPKM", "aCNCNEXOXM", "aCNCNZJJM"],
    },
    "aCNCNYTPKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Petroleum Products",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of paraffin wax, released by China Customs ~7-10th of the following month. Volume series for the paraffin trade, complementing the value series.",
        "how_to_use": "Pair with aCNCNNPYM to compute implied unit export prices; paraffin is a commodity by-product so prices closely track global crude differentials and refinery economics.",
        "related_series": ["aCNCNNPYM", "aCNCNEXOXM", "aCNCNOHCJM"],
    },
    "aCNCNGJOEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of peanut oil, released by China Customs ~7-10th of the following month. China is a major peanut producer; peanut oil exports target Southeast Asia, the Middle East, and Africa.",
        "how_to_use": "Track alongside domestic peanut harvest forecasts and global edible oil prices (palm, soy); competitive dynamics with Southeast Asian palm oil often dictate China's peanut oil export volumes.",
        "related_series": ["aCNCNQDPNM", "aCNCNFOQSM", "aCNCNPQSDM"],
    },
    "aCNCNIGQUM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Pharmaceuticals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of pharmaceutical products, released by China Customs ~7-10th of the following month. China is the world's leading API (active pharmaceutical ingredient) exporter, supplying global generic drug manufacturers.",
        "how_to_use": "Monitor for supply-chain diversification trends — the COVID-19 pandemic triggered global efforts to reduce API dependence on China. Rising exports reflect demand recovery; watch for anti-dumping actions in the EU and US.",
        "related_series": ["aCNCNAJSFM", "aCNCNTQVM", "aCNCEXPYB/A"],
    },
    "aCNCNYVJZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Steel & Metals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of pig iron and mirror iron, released by China Customs ~7-10th of the following month. Pig iron exports reflect excess blast furnace output amid China's domestic property-sector weakness since 2022.",
        "how_to_use": "Elevated pig iron exports signal domestic steel demand weakness and mill overcapacity. Rising exports often trigger anti-dumping probes by the EU, India, and Southeast Asian nations.",
        "related_series": ["aCNCNJOLEM", "aCNCNGLLEM", "aCNCNXIKJM"],
    },
    "aCNCNJOLEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Steel & Metals",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of pig iron and mirror iron, released by China Customs ~7-10th of the following month. Volume data is the key metric for tracking overcapacity-driven export surges.",
        "how_to_use": "Volume spikes confirm overcapacity displacement; compare with domestic Chinese steel PMI and property starts data. Sustained high volumes increase the probability of coordinated international anti-dumping tariffs.",
        "related_series": ["aCNCNYVJZM", "aCNCNGLLEM", "aCNCNLQBM"],
    },
    "aCNCNZUYTM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Plastics",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of plastic woven bags (excluding turnover bags), released by China Customs ~7-10th of the following month. China dominates global woven bag production for agricultural, construction, and retail packaging.",
        "how_to_use": "Track alongside broader plastics and chemical export trends; demand from ASEAN, Africa, and Latin America is the primary driver. Rising global commodity trade volumes increase woven bag demand.",
        "related_series": ["aCNCNULEM", "aCNCNVUOHM", "aCNCEXPYB/A"],
    },
    "aCNCNCRCM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of pork, released by China Customs ~7-10th of the following month. China is both the world's largest pork consumer and a significant exporter of processed and canned pork products.",
        "how_to_use": "Monitor the domestic hog cycle — ASF (African swine fever) outbreaks reduce domestic supply and exports. Export volumes tend to be countercyclical to domestic pork prices.",
        "related_series": ["aCNCNFOQSM", "aCNCNDFNKM", "aCNCNKRWDM"],
    },
    "aCNCNKNFEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Fertilizers",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of potassium chloride (MOP — muriate of potash), released by China Customs ~7-10th of the following month. China is both a major importer and processor/re-exporter of potash fertilizers.",
        "how_to_use": "China's potash trade is strategically sensitive — government periodically restricts fertilizer exports to protect domestic agriculture. Watch export surges as a signal of domestic supply abundance.",
        "related_series": ["aCNCNOKKM", "aCNCNMIJFM", "aCNCNPMAIM"],
    },
    "aCNCNOKKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Fertilizers",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of potassium chloride, released by China Customs ~7-10th of the following month. Volume series for potash exports, critical for global agricultural supply chains.",
        "how_to_use": "Volume data is more policy-sensitive than value; government export bans or quotas show up immediately in volume collapses. Pair with global potash price data to assess China's market impact.",
        "related_series": ["aCNCNKNFEM", "aCNCNMIJFM", "aCNCNPMAIM"],
    },
    "aCNCNMIJFM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Fertilizers",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of potassium sulfate (SOP — sulfate of potash), released by China Customs ~7-10th of the following month. SOP is a premium fertilizer used on chloride-sensitive crops; China is a leading producer.",
        "how_to_use": "SOP exports target high-value agricultural markets (fruits, vegetables). Track alongside global SOP prices and domestic production data; Chinese export policy shapes global SOP supply and pricing.",
        "related_series": ["aCNCNPMAIM", "aCNCNKNFEM", "aCNCNOKKM"],
    },
    "aCNCNPMAIM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Fertilizers",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of potassium sulfate, released by China Customs ~7-10th of the following month. Volume series for SOP, the premium potash fertilizer segment.",
        "how_to_use": "Compare value and volume series to extract unit export prices; China's Mannheim process SOP production is cost-competitive globally — rising volumes can pressure international prices.",
        "related_series": ["aCNCNMIJFM", "aCNCNKNFEM", "aCNCNOKKM"],
    },
    "aCNCNVLCM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of potatoes and starch-containing tubers, released by China Customs ~7-10th of the following month. China exports processed potato products and fresh tubers primarily to Southeast Asia.",
        "how_to_use": "Track alongside domestic harvest conditions and ASEAN food demand; food safety incidents or phytosanitary restrictions can abruptly disrupt export flows.",
        "related_series": ["aCNCNWEOM", "aCNCNRAZM", "aCNCNCRCM"],
    },
    "aCNCNWEOM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of potatoes and starch-containing tubers, released by China Customs ~7-10th of the following month. Volume series captures physical shipments.",
        "how_to_use": "Compare value and volume to derive implied unit prices; seasonal harvest cycles drive predictable volume patterns. Useful for cross-checking aCNCNVLCM for data consistency.",
        "related_series": ["aCNCNVLCM", "aCNCNRAZM", "aCNCNEHNUM"],
    },
    "aCNCNRAZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of potatoes and starch-containing tubers at current prices, released by China Customs ~7-10th of the following month. Alternative value series for this category.",
        "how_to_use": "Use alongside aCNCNVLCM and aCNCNEHNUM to reconcile potential reporting differences across Customs databases; annual series aCNCNUMJF provides full-year benchmark.",
        "related_series": ["aCNCNVLCM", "aCNCNEHNUM", "aCNCNUMJF"],
    },
    "aCNCNEHNUM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of potatoes and starch-containing tubers at current prices, second monthly series from China Customs ~7-10th of the following month. Parallel value track for cross-validation.",
        "how_to_use": "Cross-check against aCNCNRAZM and aCNCNVLCM; persistent divergences may reflect different HS code classifications or data source revisions.",
        "related_series": ["aCNCNRAZM", "aCNCNVLCM", "aCNCNWEOM"],
    },
    "aCNCNUMJF": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Annual",
        "meaning": "Annual export value of potatoes and starch-containing tubers, released by China Customs on an annual basis. Provides the full-year benchmark for reconciling monthly cumulative figures.",
        "how_to_use": "Use to validate monthly series cumulative totals; annual data is less subject to seasonal adjustment noise and provides a clean trend-level view of China's tuber export position.",
        "related_series": ["aCNCNRAZM", "aCNCNEHNUM", "aCNCNVLCM"],
    },
    "aCNCNULEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Plastics",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of PVC in primary shapes, released by China Customs ~7-10th of the following month. China is one of the world's largest PVC producers; domestic overcapacity drives exports to ASEAN, South Asia, and Africa.",
        "how_to_use": "PVC exports rise when domestic demand is weak (property sector slowdown) and when global construction activity is robust. Anti-dumping duties from India and Southeast Asian countries are a recurring theme.",
        "related_series": ["aCNCNZUYTM", "aCNCNVUOHM", "aCNCEXPYB/A"],
    },
    "aCNCNZTWM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Electric Vehicles",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of pure electric cars and off-road vehicles, released by China Customs ~7-10th of the following month. China overtook Japan as the world's largest auto exporter in 2023, led by NEV brands (BYD, SAIC, Chery).",
        "how_to_use": "One of the highest-profile China export series; surge post-2022 reflects EV competitiveness. Watch for EU anti-subsidy tariffs (imposed 2024), US 100% tariffs, and destination market diversification to ASEAN and Middle East.",
        "related_series": ["aCNCNJNWYM", "aCNCNAECAM", "aCNCEXPYB/A"],
    },
    "aCNCNJNWYM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Electric Vehicles",
        "units": "Units, Volume",
        "meaning": "Monthly export volume (units) of pure electric cars and off-road vehicles, released by China Customs ~7-10th of the following month. Unit count is the most direct measure of China's EV export penetration.",
        "how_to_use": "Volume in units is more transparent than value for tracking market share gains; compare with aCNCNZTWM to derive average selling prices. Volume growth in Europe and Southeast Asia is politically sensitive.",
        "related_series": ["aCNCNZTWM", "aCNCNAECAM", "aCNCEXPYB/A"],
    },
    "aCNCNAJSFM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Electronics",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of radio equipment including recording devices, released by China Customs ~7-10th of the following month. Captures a broad category of consumer and professional audio/radio electronics.",
        "how_to_use": "Useful as a proxy for mid-range consumer electronics export trends; supplements smartphone and laptop export data. Sensitive to US tariffs on Chinese electronics and supply chain shifts to Vietnam.",
        "related_series": ["aCNCNTQVM", "aCNCNZWCEM", "aCNCEXPYB/A"],
    },
    "aCNCNQDPNM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of rapeseed oil and mustard oil, released by China Customs ~7-10th of the following month. China exports surplus edible oils to regional markets, though canola imports from Canada dominate domestic supply.",
        "how_to_use": "Track alongside global canola/rapeseed prices and China's domestic crush margins; export volumes are often small relative to imports, so this series is a niche vegetable oil trade indicator.",
        "related_series": ["aCNCNGJOEM", "aCNCNPQSDM", "aCNCNJHQOM"],
    },
    "aCNCNWJPMM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of raw silk, released by China Customs ~7-10th of the following month. China controls roughly 70-80% of global raw silk production; key destinations include India, Italy, and Japan.",
        "how_to_use": "Raw silk exports are a niche but strategically important luxury input; track seasonal sericulture cycles. Italian and French luxury fashion demand is the primary Western pull factor.",
        "related_series": ["aCNCNNJOTM", "aCNCNZNSEM", "aCNCNSIMM"],
    },
    "aCNCNNJOTM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of raw silk, released by China Customs ~7-10th of the following month. Volume series for China's dominant raw silk export position.",
        "how_to_use": "Pair with aCNCNWJPMM to track unit prices; raw silk prices are highly volatile. Volume declines can signal domestic silk weaving industry expansion absorbing more output before export.",
        "related_series": ["aCNCNWJPMM", "aCNCNZNSEM", "aCNCNSIMM"],
    },
    "aCNCNDFNKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of roasted peanuts, released by China Customs ~7-10th of the following month. China is a leading peanut processor and exporter; roasted peanuts target snack food markets in Europe, Middle East, and Southeast Asia.",
        "how_to_use": "Track alongside global peanut prices and domestic harvest data; food safety recalls (aflatoxin incidents) have historically caused sharp disruptions to Chinese peanut exports in the EU.",
        "related_series": ["aCNCNFOQSM", "aCNCNGJOEM", "aCNCNCRCM"],
    },
    "aCNCNGLLEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Steel & Metals",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of steel scrap, released by China Customs ~7-10th of the following month. China's scrap export market is small relative to imports, but volume surges signal shifts in domestic EAF steelmaking economics.",
        "how_to_use": "Watch for policy changes on scrap exports (restricted in many years); rising scrap exports suggest domestic recycled steel supply exceeds mill absorption capacity.",
        "related_series": ["aCNCNLQBM", "aCNCNJOLEM", "aCNCNYVJZM"],
    },
    "aCNCNLQBM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Steel & Metals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of steel scrap, released by China Customs ~7-10th of the following month. Value series for China's scrap metal trade.",
        "how_to_use": "Pair with volume series (aCNCNGLLEM) for unit price computation; scrap prices track global steel market conditions closely. China's scrap export policy is frequently adjusted for strategic reasons.",
        "related_series": ["aCNCNGLLEM", "aCNCNJOLEM", "aCNCNYVJZM"],
    },
    "aCNCNAECAM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Automobiles",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of small passenger cars including complete sets of spare parts (CKD), released by China Customs ~7-10th of the following month. Covers both ICE and EV passenger vehicles in this size class.",
        "how_to_use": "Broadest passenger car export indicator; compare with EV-specific series (aCNCNZTWM) to gauge ICE vs. EV mix. Growing CKD shipments signal OEM local assembly partnerships in emerging markets.",
        "related_series": ["aCNCNZTWM", "aCNCNJNWYM", "aCNCEXPYB/A"],
    },
    "aCNCNSSVHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of soda ash (sodium carbonate), released by China Customs ~7-10th of the following month. China is the world's largest soda ash producer; exports serve glass, detergent, and chemical industries globally.",
        "how_to_use": "Soda ash exports surge when domestic property glass demand is depressed; monitor alongside China housing starts. Anti-dumping investigations from Turkey, India, and the EU are recurring risks.",
        "related_series": ["aCNCNLBHAM", "aCNCNLARM", "aCNCNULEM"],
    },
    "aCNCNLBHAM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of soda ash at current prices, alternate series from China Customs ~7-10th of the following month. Provides a secondary data source for cross-validation.",
        "how_to_use": "Use alongside aCNCNSSVHM to verify reported values; persistent divergences between the two series may indicate classification or reporting differences. Compare with volume series aCNCNLARM.",
        "related_series": ["aCNCNSSVHM", "aCNCNLARM", "aCNCNULEM"],
    },
    "aCNCNLARM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of soda ash, released by China Customs ~7-10th of the following month. Volume is the key metric for tracking China's soda ash export displacement in global markets.",
        "how_to_use": "Volume spikes amid weak domestic construction demand confirm overcapacity export displacement; compare with aCNCNSSVHM to compute realized export unit prices vs. global soda ash benchmark prices.",
        "related_series": ["aCNCNSSVHM", "aCNCNLBHAM", "aCNCNULEM"],
    },
    "aCNCNBCVRM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of sorghum, released by China Customs ~7-10th of the following month. China exports limited volumes of sorghum; the series primarily reflects niche trade flows to neighboring countries.",
        "how_to_use": "Sorghum exports are small relative to China's massive imports; track primarily to monitor domestic supply conditions. Any significant export surge would imply an unusual domestic surplus.",
        "related_series": ["aCNCNKRWDM", "aCNCNJHJZM", "aCNCNCRCM"],
    },
    "aCNCNKRWDM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of soybeans, released by China Customs ~7-10th of the following month. China is a massive net importer of soybeans; exports are negligible and represent minor re-export or specialty flows.",
        "how_to_use": "This series should be monitored mainly for anomalies; a sudden surge in soybean exports would be highly unusual and could signal domestic storage or policy changes. The import counterpart is far more strategically important.",
        "related_series": ["aCNCNJHJZM", "aCNCNBCVRM", "aCNCNPQSDM"],
    },
    "aCNCNJHJZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of soybeans, released by China Customs ~7-10th of the following month. Volume series for the minor soybean re-export or specialty trade flows.",
        "how_to_use": "Low-volume series given China's net importer status; pair with aCNCNKRWDM for unit price verification. Any sustained volume increase would warrant investigation into supply chain shifts or policy changes.",
        "related_series": ["aCNCNKRWDM", "aCNCNPQSDM", "aCNCNMGBBM"],
    },
    "aCNCNPQSDM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of soybean oil, released by China Customs ~7-10th of the following month. China's large crush industry produces surplus soybean oil beyond domestic demand, exported to ASEAN and Africa.",
        "how_to_use": "Track alongside domestic soybean crush margins and global edible oil prices; surplus crushing capacity drives soybean oil export volumes. Competition with Malaysian palm oil is the key dynamic.",
        "related_series": ["aCNCNPLHPM", "aCNCNMGBBM", "aCNCNJHQOM"],
    },
    "aCNCNPLHPM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of soybean oil, alternate value series from China Customs ~7-10th of the following month. Second monthly data track for cross-validation.",
        "how_to_use": "Use with aCNCNPQSDM and aCNCNMGBBM to reconcile any inter-series discrepancies; the volume series aCNCNJHQOM and aCNCNTZZNM provide the physical quantity counterpart.",
        "related_series": ["aCNCNPQSDM", "aCNCNMGBBM", "aCNCNJHQOM"],
    },
    "aCNCNMGBBM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of soybean oil, third value series from China Customs ~7-10th of the following month. Parallel reporting track for soybean oil export values.",
        "how_to_use": "With three parallel value series (aCNCNPQSDM, aCNCNPLHPM, aCNCNMGBBM), triangulate for the most reliable value read; compare against volume series to derive unit pricing trends.",
        "related_series": ["aCNCNPQSDM", "aCNCNPLHPM", "aCNCNJHQOM"],
    },
    "aCNCNJHQOM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of soybean oil, released by China Customs ~7-10th of the following month. Volume series captures physical shipments of China's surplus crush output.",
        "how_to_use": "Pair with value series (aCNCNPQSDM) to compute realized export unit prices and compare with Rotterdam soybean oil benchmarks. Rising volumes indicate domestic crush surplus relative to consumption.",
        "related_series": ["aCNCNTZZNM", "aCNCNPQSDM", "aCNCNMGBBM"],
    },
    "aCNCNTZZNM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of soybean oil, alternate volume series from China Customs ~7-10th of the following month. Second volume data track for cross-validation.",
        "how_to_use": "Cross-check against aCNCNJHQOM; divergence between the two volume series may signal HS classification differences or reporting lags. Use the average of both for a best-estimate volume read.",
        "related_series": ["aCNCNJHQOM", "aCNCNPQSDM", "aCNCNPLHPM"],
    },
    "aCNCNWHHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of elemental sulfur, released by China Customs ~7-10th of the following month. Sulfur is a by-product of oil refining and coal coking; China is a large producer with exports targeting fertilizer manufacturers (sulfuric acid).",
        "how_to_use": "Sulfur exports reflect refinery and coking activity levels; track alongside China's crude run rates. Global fertilizer demand — particularly phosphate production — is the primary end-user pull.",
        "related_series": ["aCNCNXXMTM", "aCNCNGFEHM", "aCNCNSSVHM"],
    },
    "aCNCNXXMTM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of elemental sulfur, alternate value series from China Customs ~7-10th of the following month. Provides a secondary data track for cross-validation.",
        "how_to_use": "Compare with aCNCNWHHM and volume series aCNCNGFEHM; sulfur prices are tightly linked to oil refinery economics and global phosphate fertilizer demand cycles.",
        "related_series": ["aCNCNWHHM", "aCNCNGFEHM", "aCNCNSSVHM"],
    },
    "aCNCNGFEHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals",
        "units": "Tonnes, Volume",
        "meaning": "Monthly export volume of elemental sulfur, released by China Customs ~7-10th of the following month. Volume series captures physical sulfur flows from Chinese refineries and coking plants to global markets.",
        "how_to_use": "Volume is the key driver variable; pair with aCNCNWHHM for unit price calculation. Sulfur export volumes are highly seasonal and correlated with refinery maintenance schedules.",
        "related_series": ["aCNCNWHHM", "aCNCNXXMTM", "aCNCNLARM"],
    },
    "aCNCNZNSEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles & Apparel",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of textile garments at current prices, released by China Customs ~7-10th of the following month. China remains the world's largest garment exporter despite manufacturing share shifting to Vietnam, Bangladesh, and Cambodia.",
        "how_to_use": "Core China trade series; monitor for structural share loss to Southeast Asia vs. cyclical demand swings. US and EU tariff escalations and fast-fashion platform (SHEIN/Temu) volumes increasingly captured here.",
        "related_series": ["aCNCNSIMM", "aCNCNXITNM", "aCNCEXPYB/A"],
    },
    "aCNCNSIMM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles & Apparel",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of textile garments, alternate series from China Customs ~7-10th of the following month. Secondary value track for the garment export category.",
        "how_to_use": "Use alongside aCNCNZNSEM and aCNCNXITNM to triangulate total garment export value; ASEAN as a destination is growing while US/EU share has faced tariff headwinds. Cross-reference with WTO textile trade data.",
        "related_series": ["aCNCNZNSEM", "aCNCNXITNM", "aCNCNWJPMM"],
    },
    "aCNCNXITNM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles & Apparel",
        "units": "USD, Current Prices",
        "meaning": "Monthly export value of textile garments, third series from China Customs ~7-10th of the following month. Parallel reporting track providing additional verification for garment export values.",
        "how_to_use": "Triangulate with aCNCNZNSEM and aCNCNSIMM; persistent divergence suggests HS code boundary or reporting timing differences. Combined with raw silk data (aCNCNWJPMM), gives a full textile trade picture.",
        "related_series": ["aCNCNZNSEM", "aCNCNSIMM", "aCNCNWJPMM"],
    },
}
