"""Hand-curated content for China RICs — Batch 09b (Real Estate part 2)."""
TIER1: dict[str, dict] = {
    "aCNPUCPI": {
        "slug": "cn_housing_construction",
        "subcategory": "Construction Activity",
        "units": "CNY billion",
        "meaning": "Planned investment in real estate projects currently under construction — captures the pipeline of developer commitments before completion. Published monthly by NBS as part of the fixed-asset investment framework.",
        "how_to_use": "Compare with actual completed investment to gauge developer execution vs. ambition; a widening gap signals financial stress and delivery risk among developers.",
        "related_series": ["aCNBLDUCT", "aCNCONINVR", "aCNHSALESCB"],
    },
    "aCNHSALEST": {
        "slug": "cn_housing_construction",
        "subcategory": "Sales",
        "units": "CNY billion",
        "meaning": "Total sales value of all commercial buildings (residential, commercial office, and other) — the broadest monetary measure of real estate demand. Released monthly by NBS on a cumulative year-to-date basis.",
        "how_to_use": "Track YTD growth rate versus prior year to assess the overall revenue recovery for developers; divergence from floor-space sales signals price-mix shifts.",
        "related_series": ["aCNHSALESV", "aCNHSALESCB", "aCNCONINVR"],
    },
    "aCNHSALESV": {
        "slug": "cn_housing_construction",
        "subcategory": "Sales",
        "units": "CNY billion",
        "meaning": "Sales value of commercial residential buildings specifically — strips out commercial office and retail to isolate housing market revenue. NBS monthly release, cumulative YTD basis.",
        "how_to_use": "Compare against aCNHSALEST to derive the residential share of total property sales; a declining share hints at relative weakness in the housing segment versus commercial property.",
        "related_series": ["aCNHSALEST", "aCNHSALESCB", "aCNHPIAR"],
    },
    "aCNHPATOTA": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "House Price Index",
        "units": "CNY/sq m",
        "meaning": "China Index Academy (CIA) 100-city average new residential price — a high-frequency composite averaging asking/transaction prices across 100 surveyed cities, released monthly. Broader geographic coverage than the NBS 70-city index.",
        "how_to_use": "Use as a real-time national price benchmark; compare trend with NBS 70-city data for consistency checks — divergences often reflect tier-3/4 city dynamics not captured by NBS.",
        "related_series": ["aCNHPIAR", "aCNHRPSH", "aCNHRPSZ"],
    },
    "aCNHRABT": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Baotou (Inner Mongolia) — a third-tier resource-economy city whose housing market is closely tied to coal and steel sector cycles.",
        "how_to_use": "Monitor for divergence from national trends; commodity-sector weakness tends to hit Baotou transactions harder than coastal cities, signaling demand fragility in tier-3 industrial cities.",
        "related_series": ["aCNHRPBT", "aCNHRACQ", "aCNHRASY"],
    },
    "aCNHRACQ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Chongqing — China's largest municipality by population and a key tier-1 equivalent market in the southwest with distinct policy levers including a local property tax pilot.",
        "how_to_use": "Chongqing's large affordable housing stock and unique tax environment make it a policy bellwether; compare with aCNHRASH and aCNHRASZ to gauge southwest vs. coastal divergence.",
        "related_series": ["aCNHRPCQ", "aCNHRASH", "aCNHRASZ"],
    },
    "aCNHRADG": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Dongguan — a tier-2 manufacturing hub in the Pearl River Delta whose housing demand is driven by migrant workers and Hong Kong/Shenzhen spillover demand.",
        "how_to_use": "Use alongside aCNHRAGZ and aCNHRASZ to construct a Pearl River Delta cluster view; weakness here often leads Guangdong-wide softening given its migrant-worker demand base.",
        "related_series": ["aCNHRPDG", "aCNHRAGZ", "aCNHRASZ"],
    },
    "aCNHRAGZ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Guangzhou — one of China's four tier-1 cities and the capital of Guangdong, with a large secondary market and relatively faster purchase restriction relaxation since 2023.",
        "how_to_use": "Compare with aCNHRASH and aCNHRASZ to assess tier-1 cross-city trends; Guangzhou's earlier easing of hukou and purchase restrictions makes it a leading indicator for tier-1 policy diffusion.",
        "related_series": ["aCNHRPGZ", "aCNHRASH", "aCNHRASZ"],
    },
    "aCNHRANB": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Ningbo — a strong tier-2 port city in Zhejiang with high per-capita income and an active private enterprise base supporting housing demand.",
        "how_to_use": "Ningbo tracks closely with Zhejiang provincial trends; use with aCNHRASX (Shaoxing) to build a Yangtze Delta secondary-city composite distinct from Shanghai's premium market.",
        "related_series": ["aCNHRPNB", "aCNHRASX", "aCNHRASH"],
    },
    "aCNHRASH": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Shanghai — China's largest tier-1 property market and the highest-value residential market globally by total transaction value.",
        "how_to_use": "Shanghai transactions are a confidence barometer for national housing sentiment; sustained monthly recovery here typically precedes broader tier-2 city upturn by one to two quarters.",
        "related_series": ["aCNHRPSH", "aCNHRAGZ", "aCNHRASZ"],
    },
    "aCNHRAST": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Shantou — a third-tier coastal city in eastern Guangdong historically associated with the Chaoshan business community, with overseas Chinese investment influencing demand.",
        "how_to_use": "Use as a proxy for smaller coastal Guangdong city demand; compare against aCNHRADG and aCNHRAGZ to see whether Pearl River Delta dynamism is spreading to third-tier coastal cities.",
        "related_series": ["aCNHRPST", "aCNHRAPSG", "aCNHRADG"],
    },
    "aCNHRASY": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Shenyang — capital of Liaoning province and the largest city in Northeast China, a region suffering population outflow and persistent housing oversupply.",
        "how_to_use": "Northeast China cities like Shenyang are structural outliers — use to benchmark weak-end scenarios; sustained weakness here reflects demographic and fiscal headwinds beyond cyclical policy levers.",
        "related_series": ["aCNHRPSY", "aCNHRABT", "aCNHRATJ"],
    },
    "aCNHRASZ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Shenzhen — the most expensive tier-1 city by price-to-income ratio, driven by tech sector demand and proximity to Hong Kong capital flows.",
        "how_to_use": "Shenzhen leads national price cycles — a sustained transaction uptick here typically signals the leading edge of a tier-1 recovery and precedes mortgage-rate-cut transmission effects.",
        "related_series": ["aCNHRPSZ", "aCNHRASH", "aCNHRAGZ"],
    },
    "aCNHRATJ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Transactions — Area",
        "units": "10,000 sq m",
        "meaning": "CIA monthly residential transaction area for Tianjin — a large tier-1 adjacent municipality near Beijing with significant industrial employment and a housing market that mirrors but lags Beijing's cycle.",
        "how_to_use": "Tianjin historically trades at a discount to Beijing; compare with national trends to gauge whether Bohai Rim recovery is broadening beyond Beijing's core, a sign of genuine cycle turn.",
        "related_series": ["aCNHRPTJ", "aCNHRASY", "aCNHRACQ"],
    },
    "aCNHRPBT": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Baotou — a commodity-linked, third-tier city in Inner Mongolia where prices reflect coal-industry income cycles.",
        "how_to_use": "Plot against commodity price indices (coal, steel) to quantify the resource-sector price transmission into lower-tier residential markets.",
        "related_series": ["aCNHRABT", "aCNHRPSY", "aCNHRPCQ"],
    },
    "aCNHRPCQ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Chongqing — one of the most affordable large Chinese cities given its large affordable housing supply and property tax pilot that suppresses speculative premium.",
        "how_to_use": "Chongqing's affordability ratio is a natural reference for housing policy success; track against income growth to assess real purchasing power trends in inland tier-1 equivalent markets.",
        "related_series": ["aCNHRACQ", "aCNHRPXA", "aCNHRPTJ"],
    },
    "aCNHRPDG": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Dongguan — a Pearl River Delta manufacturing hub where prices reflect export-sector incomes and commuter demand from Shenzhen.",
        "how_to_use": "Compare with aCNHRPGZ and aCNHRPSZ to map the Shenzhen price spillover gradient; Dongguan's premium over Guangzhou can widen as Shenzhen buyers seek affordability.",
        "related_series": ["aCNHRADG", "aCNHRPGZ", "aCNHRPSZ"],
    },
    "aCNHRPGZ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Guangzhou — the most affordable of China's four tier-1 cities, benefiting from broader land supply and a less restrictive purchase environment post-2023.",
        "how_to_use": "Guangzhou's relative affordability makes it more sensitive to mortgage rate cuts; use as a leading signal for volume recovery ahead of more expensive tier-1 peers.",
        "related_series": ["aCNHRAGZ", "aCNHRPSH", "aCNHRPSZ"],
    },
    "aCNHRPNB": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Ningbo — a prosperous Zhejiang port city with private economy driven house prices typically tracking the Yangtze Delta premium tier.",
        "how_to_use": "Ningbo prices reflect Zhejiang entrepreneur wealth effects; compare with aCNHRPSX and aCNHRPSH to gauge how regional private-sector confidence translates into local housing demand.",
        "related_series": ["aCNHRANB", "aCNHRPSX", "aCNHRPSH"],
    },
    "aCNHRPSA": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Sanya — Hainan's premier resort city where prices are driven by holiday home demand, high-income migration, and Hainan Free Trade Port incentives.",
        "how_to_use": "Sanya is a speculative premium market; use as a sentiment indicator for wealthy household confidence — sharp corrections here signal risk-off among high-net-worth domestic buyers.",
        "related_series": ["aCNHRPSH", "aCNHRPSZ", "aCNHPATOTA"],
    },
    "aCNHRPSH": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Shanghai — the highest-value primary residential market in China, closely watched as the national price ceiling benchmark.",
        "how_to_use": "Sustained price stabilization in Shanghai (the market most correlated with global financial conditions) is a prerequisite for declaring the national price downcycle has bottomed.",
        "related_series": ["aCNHRASH", "aCNHRPGZ", "aCNHRPSZ"],
    },
    "aCNHRPST": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Shantou — an eastern Guangdong third-tier city with historically elevated prices relative to income due to overseas Chinese demand.",
        "how_to_use": "Track alongside aCNHRPSG (Shaoguan) to construct a Guangdong tier-3 average; compare with aCNHRPGZ to measure the tier-1 to tier-3 price spread within Guangdong.",
        "related_series": ["aCNHRAST", "aCNHRPSG", "aCNHRPDG"],
    },
    "aCNHRPSG": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Shaoguan — an inland Guangdong tier-3 city with lower price levels reflecting limited economic diversification and weak in-migration.",
        "how_to_use": "Use as lower-bound reference for Guangdong's price distribution; gap versus aCNHRPGZ indicates affordability headroom and rural-urban convergence pace in the province.",
        "related_series": ["aCNHRPST", "aCNHRPGZ", "aCNHPATOTA"],
    },
    "aCNHRPSX": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Shaoxing — a tier-2 Zhejiang city with strong private textile and chemical industries underpinning residential demand.",
        "how_to_use": "Compare with aCNHRPNB (Ningbo) to track intra-Zhejiang price dynamics; Shaoxing's industry-based demand is more sensitive to export-sector performance than Shanghai spillover.",
        "related_series": ["aCNHRANB", "aCNHRPNB", "aCNHRPSH"],
    },
    "aCNHRPSY": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Shenyang — the Northeast China price bellwether reflecting demographic headwinds, population outflow, and a structurally oversupplied housing stock.",
        "how_to_use": "Shenyang's persistent price weakness serves as a lower-bound scenario for cities facing demographic decline; useful for stress-testing policy effectiveness in structurally challenged markets.",
        "related_series": ["aCNHRASY", "aCNHRPBT", "aCNHRPTJ"],
    },
    "aCNHRPSZ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Shenzhen — China's most expensive housing market by price-to-income ratio, driven by tech-sector wealth, limited land supply, and cross-border Hong Kong flows.",
        "how_to_use": "Shenzhen prices are the leading indicator for tier-1 national trends; recovery here, alongside Guangzhou purchase restriction removal, signals the start of a sustainable tier-1 price floor.",
        "related_series": ["aCNHRASZ", "aCNHRPGZ", "aCNHRPSH"],
    },
    "aCNHRPTJ": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Tianjin — a tier-1 adjacent municipality whose prices track Beijing with a significant discount, reflecting heavier industrial exposure and slower job growth.",
        "how_to_use": "Track the Beijing–Tianjin price spread as a measure of Bohai Rim housing premium concentration; narrowing spread signals improving Tianjin attractiveness relative to Beijing.",
        "related_series": ["aCNHRATJ", "aCNHRPSY", "aCNHRPCQ"],
    },
    "aCNHRPXA": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "City Prices — Average",
        "units": "CNY/sq m",
        "meaning": "CIA monthly average residential transaction price for Xi'an — the largest city in Northwest China, elevated by tech manufacturing investment and university-city demand since 2017–2020 boom years.",
        "how_to_use": "Xi'an's rapid price ascent in 2017–2020 and subsequent correction make it a useful case study in policy-induced demand volatility; compare with aCNHRPCQ to assess inland tier-2 pricing dynamics.",
        "related_series": ["aCNCNZOZWM", "aCNCNTSGPM", "aCNCNUMBXM"],
    },
    "aCNCNHTCDM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Power Infrastructure Investment",
        "units": "CNY billion",
        "meaning": "Power infrastructure investment completion at current prices — National Energy Administration (NEA) monthly series tracking actual spending on completed power grid and generation projects.",
        "how_to_use": "Use as a proxy for grid-infrastructure build-out intensity; compare with real estate investment to assess whether fixed-asset investment is rotating from property into energy infrastructure as government stimulus shifts.",
        "related_series": ["aCNCNDLKPM", "aCNCNBNYRM", "aCNCONINVR"],
    },
    "aCNCNDLKPM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Power Infrastructure Investment",
        "units": "CNY billion",
        "meaning": "Power infrastructure investment completion — NEA monthly series tracking nominal completed investment in power infrastructure, complementing the current-price version with a broader definition.",
        "how_to_use": "Cross-check with aCNCNHTCDM for consistency; sustained divergence between the two series may reflect price deflator issues or scope differences in project classification.",
        "related_series": ["aCNCNHTCDM", "aCNCNBNYRM", "aCNCONINVR"],
    },
    "aCNCNBNYRM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Power Infrastructure — Capacity",
        "units": "GW",
        "meaning": "Thermal power generation equipment installed capacity — NEA monthly series measuring cumulative installed megawatts of coal, gas, and oil-fired power generation, a key energy security indicator.",
        "how_to_use": "Track growth pace against renewable capacity additions (solar, wind) to assess China's energy transition speed; slow thermal capacity growth alongside rising renewables signals structural energy-mix shift.",
        "related_series": ["aCNCNHTCDM", "aCNCNDLKPM", "aCNCONINVR"],
    },
    "aCNHPIAR": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "House Price Index",
        "units": "% YoY",
        "meaning": "NBS nationwide newly-built residential property price index — year-on-year percentage change derived from the 70-city survey covering 35 first/second-tier and 35 third-tier cities, released monthly with a roughly 3-week lag.",
        "how_to_use": "The primary official gauge of national house price momentum; a sustained negative reading (persistent since mid-2023) signals ongoing balance-sheet stress for households and developers alike — watch for policy response triggers.",
        "related_series": ["aCNHPATOTA", "aCNHRPSH", "aCNHRPSZ"],
    },
    "aCNCNARBQM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Land Market",
        "units": "10,000 sq m",
        "meaning": "Total land area purchased by real estate enterprises — NBS monthly cumulative series measuring gross land acquisition by developers, a leading indicator for future housing supply and local government land revenue.",
        "how_to_use": "Land purchases down 50%+ from peak signal the fiscal crisis for local governments who depend on land transfers; watch for stabilization as an early signal that developer confidence and credit are recovering.",
        "related_series": ["aCNCNKPOMM", "aCNCNBFMZM", "aCNCNSCYNM"],
    },
    "aCNCNKPOMM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Land Market — City",
        "units": "10,000 sq m",
        "meaning": "Land area purchased by real estate enterprises in Hefei (Anhui capital) — a tier-2 city that has outperformed peers through strong semiconductor, EV, and advanced manufacturing investment attracting population and housing demand.",
        "how_to_use": "Hefei is a rare positive outlier in the land market; compare against national aCNCNARBQM to quantify how industrial policy success translates into developer land appetite in new-economy cities.",
        "related_series": ["aCNCNARBQM", "aCNCNEYCM1", "aCNCNBFMZM"],
    },
    "aCNCNBFMZM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Land Market — Regional",
        "units": "CNY billion",
        "meaning": "Real estate investment land acquisition fee in Western China — NBS cumulative provincial breakdown capturing developer spending on land in the western region (Sichuan, Chongqing, Yunnan, etc.).",
        "how_to_use": "Weak western land fees versus eastern peers highlight that fiscal stress from land market collapse is most acute in lower-tier provincial capitals; monitor for government-initiated land supply reduction as a relief measure.",
        "related_series": ["aCNCNSCYNM", "aCNCNARBQM", "aCNCNKPOMM"],
    },
    "aCNCNSCYNM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Land Market — Provincial",
        "units": "CNY billion",
        "meaning": "Real estate investment land acquisition fee in Zhejiang Province — NBS provincial series for one of China's wealthiest provinces, where high land prices historically generated major fiscal revenue.",
        "how_to_use": "Zhejiang's land fee collapse relative to its 2021 peak highlights fiscal pressure even in affluent coastal provinces; compare with aCNCNBFMZM to assess east-west land market divergence.",
        "related_series": ["aCNCNARBQM", "aCNCNBFMZM", "aCNCNKPOMM"],
    },
    "aCNCNVHPIM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Completions — City",
        "units": "10,000 sq m",
        "meaning": "Housing completion area in Nanjing (Jiangsu capital) — NBS city-level monthly measure of floor space in residential buildings certified as complete, reflecting delivery of pre-sold units.",
        "how_to_use": "Nanjing completions track the gap between developer obligations and delivery; rising completions despite falling new starts signals the deleveraging cycle — developers finishing old stock rather than starting new.",
        "related_series": ["aCNCNWORBM", "aCNCNIVMKM", "aCNCNRBQNM"],
    },
    "aCNCNWORBM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Completions — City",
        "units": "10,000 sq m",
        "meaning": "Housing completion area in Nanning (Guangxi capital) — NBS city-level series for a tier-2 city bordering Vietnam, where completions reflect ASEAN-oriented industrial expansion and government infrastructure investment.",
        "how_to_use": "Compare against Nanjing (aCNCNVHPIM) to examine coastal versus inland completion dynamics; Nanning's completions are more tied to state-driven construction than private developer activity.",
        "related_series": ["aCNCNVHPIM", "aCNCNIVMKM", "aCNCNEFOHM"],
    },
    "aCNCNRBQNM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Completions",
        "units": "10,000 sq m",
        "meaning": "Housing completion area for non-sale purposes — NBS monthly series covering government-allocated housing, affordable units, and other non-commercial completions not subject to open market transactions.",
        "how_to_use": "Rising non-sale completions relative to total completions signals a policy shift toward social/affordable housing delivery — a key component of the government's 'whitelist' and housing stabilization toolkit.",
        "related_series": ["aCNCNIVMKM", "aCNCNVHPIM", "aCNCNWORBM"],
    },
    "aCNCNEFOHM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Completions — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing completion area in Hohhot (Inner Mongolia capital) — NBS city-level series for a third-tier northern city where completions are driven by government resettlement and resource-sector housing demand.",
        "how_to_use": "Hohhot completions benchmark weak-end scenarios for resource-dependent provincial capitals; sustained low completions here confirm structural demand deficiency beyond cyclical policy tools.",
        "related_series": ["aCNCNWORBM", "aCNCNIVMKM", "aCNCNRBQNM"],
    },
    "aCNCNIVMKM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Completions",
        "units": "CNY billion",
        "meaning": "National housing completion value — NBS monthly measure of the monetary value of all completed residential construction, combining both commercial and affordable housing segments.",
        "how_to_use": "Compare with aCNPUCPI (planned investment) to estimate the completion-to-pipeline ratio; a rising completion value while planned investment falls confirms the sector is drawing down inventory rather than creating new supply.",
        "related_series": ["aCNCNRBQNM", "aCNCNVHPIM", "aCNPUCPI"],
    },
    "aCNCNZOZWM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Construction — City",
        "units": "10,000 sq m",
        "meaning": "Total housing construction area (under construction) in Xi'an — NBS city-level series for the Northwest's largest city, reflecting both new-start and multi-year pipeline projects still in progress.",
        "how_to_use": "Xi'an's large under-construction pipeline (legacy of the 2017–2020 boom) creates ongoing completion and delivery risk; monitor alongside new starts for signs of pipeline rationalization.",
        "related_series": ["aCNCNTSGPM", "aCNCNUMBXM", "aCNHRPXA"],
    },
    "aCNCNTJMEM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts",
        "units": "10,000 sq m",
        "meaning": "National residential housing new-start construction area — NBS monthly cumulative measure of floor space where construction began during the period, the most forward-looking supply indicator.",
        "how_to_use": "New starts have collapsed 60%+ from 2021 peak — the most consequential leading indicator for future housing supply shortfalls; stabilization is required before completions can sustainably recover.",
        "related_series": ["aCNCNOOAM", "aCNCNGVSM1", "aCNCNOXKQM"],
    },
    "aCNCNOXKQM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Housing new-start construction area in Beihai (Guangxi coastal city) — NBS city-level series for a third-tier coastal city whose residential market has attracted retiree and holiday-home demand.",
        "how_to_use": "Beihai's new-start volatility reflects speculative holiday-home cycles; compare with aCNCNIONGM (residential under construction) to assess whether new supply additions are translating to completed stock.",
        "related_series": ["aCNCNTJMEM", "aCNCNIONGM", "aCNCNWORBM"],
    },
    "aCNCNOOAM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts",
        "units": "% YoY",
        "meaning": "Housing new-start construction area YoY growth rate, cumulative — NBS official rate-of-change measure providing the percentage change versus the same period prior year on a year-to-date basis.",
        "how_to_use": "This is the most cited new-starts metric in NBS press releases; a less-negative print signals a slowdown in the deterioration even before a positive turn, which markets interpret as bottoming.",
        "related_series": ["aCNCNTJMEM", "aCNCNGVSM1", "aCNHPIAR"],
    },
    "aCNCNGVSM1": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — Regional",
        "units": "10,000 sq m",
        "meaning": "Housing new-start construction area in East China — NBS regional breakdown covering Jiangsu, Zhejiang, Shandong, Fujian, Anhui, Jiangxi, and Shanghai, the most economically active zone.",
        "how_to_use": "Eastern new starts carry the highest weight for national recovery given developer concentration and household income levels; compare with western/central breakdowns to detect geographic leadership in the recovery.",
        "related_series": ["aCNCNTJMEM", "aCNCNOOAM", "aCNCNKTPRM"],
    },
    "aCNCNKTPRM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Housing new-start construction area in Suzhou — a tier-2 Yangtze Delta manufacturing and technology hub adjacent to Shanghai with one of China's highest GDP-per-capita among non-tier-1 cities.",
        "how_to_use": "Suzhou is a bellwether for Yangtze Delta housing demand beyond Shanghai; early new-start recovery here confirms that economic spillover from Shanghai is reaching adjacent manufacturing cities.",
        "related_series": ["aCNCNGVSM1", "aCNCNTJMEM", "aCNHRANB"],
    },
    "aCNCNRLOIM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Housing new-start construction area in Yinchuan (Ningxia capital) — NBS city-level series for a small, remote northwestern provincial capital where new starts reflect government-driven construction more than private demand.",
        "how_to_use": "Yinchuan is a benchmark for state-directed construction in peripheral markets; compare against aCNCNKTPRM (Suzhou) to illustrate the market-driven vs. policy-driven new-start divergence.",
        "related_series": ["aCNCNTJMEM", "aCNCNPXILM", "aCNCNRLOIM"],
    },
    "aCNCNLOLKM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — Segment",
        "units": "10,000 sq m",
        "meaning": "Housing new-start area for commercial business premises (retail, office) — NBS segment breakdown separating non-residential commercial from the headline residential new-start figure.",
        "how_to_use": "Commercial new starts typically lag residential recovery; a widening gap between residential and commercial new starts signals developers are prioritizing housing over office/retail, reflecting demand composition shifts.",
        "related_series": ["aCNCNTJMEM", "aCNCNOOAM", "aCNCNGVSM1"],
    },
    "aCNCNMTAM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing new-start area in Guiyang (Guizhou capital) — NBS city-level series for a Southwest China provincial capital that experienced a debt-driven construction boom followed by sharp fiscal retrenchment.",
        "how_to_use": "Guiyang is a high-profile case of local government fiscal overextension; collapsing new starts here track the restructuring of LGFV (local government financing vehicle) debt constraining developer activity.",
        "related_series": ["aCNCNTJMEM", "aCNCNBFMZM", "aCNCNRLOIM"],
    },
    "aCNCNRBRM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing new-start area in Shenzhen — NBS city-level series for the most land-constrained tier-1 city, where new starts reflect highly regulated land release by the municipal government.",
        "how_to_use": "Shenzhen's new starts are supply-constrained by design (limited land); compare with aCNCNKTPRM (Suzhou) to distinguish between land-constrained tier-1 and land-abundant tier-2 supply dynamics.",
        "related_series": ["aCNCNTJMEM", "aCNCNGVSM1", "aCNHRASZ"],
    },
    "aCNCNQQONM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing new-start area in Wenzhou — NBS city-level series for a Zhejiang city historically known for its private entrepreneurship and speculative real estate investment culture.",
        "how_to_use": "Wenzhou's residential new starts are a proxy for private-sector housing investment appetite in coastal Zhejiang; compare with aCNCNKTPRM (Suzhou) to track whether Zhejiang new-start recovery is broad-based.",
        "related_series": ["aCNCNGVSM1", "aCNCNKTPRM", "aCNHRANB"],
    },
    "aCNCNTSGPM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing new-start area in Xi'an — NBS city-level series for the Northwest's largest city, tracking supply initiation in a market that boomed during 2017–2020 on tech and manufacturing investment.",
        "how_to_use": "Xi'an new starts are well below peak and must be watched for recovery signals; combine with aCNCNZOZWM (under construction) and aCNHRPXA (prices) to build a full Xi'an housing cycle picture.",
        "related_series": ["aCNCNZOZWM", "aCNCNUMBXM", "aCNHRPXA"],
    },
    "aCNCNPXILM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "New Starts — City",
        "units": "10,000 sq m",
        "meaning": "Housing new-start construction area in Urumqi (Xinjiang capital) — NBS city-level series for China's westernmost major city, where construction activity reflects state infrastructure investment and resource sector activity.",
        "how_to_use": "Urumqi new starts are largely policy-driven; compare with aCNCNRLOIM (Yinchuan) to benchmark western periphery city construction intensity and assess state-directed housing supply strategy in frontier regions.",
        "related_series": ["aCNCNTJMEM", "aCNCNRLOIM", "aCNCNMTAM"],
    },
    "aCNCNIONGM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Construction — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing under-construction area in Beihai — NBS city-level total floor space being actively constructed in this Guangxi coastal city, encompassing all stages from foundation to topping-off.",
        "how_to_use": "Compare with new starts (aCNCNOXKQM) to derive the average construction duration and pipeline drawdown; a shrinking under-construction total confirms the cycle is burning off legacy inventory.",
        "related_series": ["aCNCNOXKQM", "aCNCNWORBM", "aCNCNTJMEM"],
    },
    "aCNCNEYCM1": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Construction — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing under-construction area in Hefei — NBS city-level total reflecting the active construction pipeline in one of China's fastest-growing tier-2 cities, driven by new-economy industrial investment.",
        "how_to_use": "Hefei's resilient construction pipeline distinguishes it from most tier-2 cities; use alongside aCNCNKPOMM (land purchases) to confirm Hefei as a sustained positive outlier in the housing downcycle.",
        "related_series": ["aCNCNKPOMM", "aCNCNVHPIM", "aCNCNTJMEM"],
    },
    "aCNCNTZUBM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Construction — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing under-construction area in Nanchang (Jiangxi capital) — NBS city-level series for a central China provincial capital with significant affordable housing and government-sponsored urban renewal activity.",
        "how_to_use": "Nanchang's construction area tracks central China's state-led housing activity; compare with Nanjing (aCNCNVHPIM) to gauge central-versus-coastal completion rate divergence under the housing support program.",
        "related_series": ["aCNCNVHPIM", "aCNCNWORBM", "aCNCNTJMEM"],
    },
    "aCNCNUMBXM": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "Construction — City",
        "units": "10,000 sq m",
        "meaning": "Residential housing under-construction area in Xi'an — NBS city-level total for the Northwest's largest city, capturing the accumulated pipeline from the 2017–2020 boom still working through to completion.",
        "how_to_use": "The large Xi'an under-construction stock represents a significant completion and debt-repayment overhang; compare with new starts (aCNCNTSGPM) and prices (aCNHRPXA) to track the cycle drawdown timeline.",
        "related_series": ["aCNCNZOZWM", "aCNCNTSGPM", "aCNHRPXA"],
    },
    "aCNHPRICET": {
        "slug": "cn_housing_real_estate_prices",
        "subcategory": "House Price Index",
        "units": "% YoY",
        "meaning": "NBS/LSEG composite newly-built house price YoY change index — blends the NBS 70-city survey methodology with LSEG's data processing to produce a consistent, comparable national price change series.",
        "how_to_use": "Use as the standard reference for cross-country housing price comparisons in LSEG terminals; a less-negative reading signals that the 2021–2024 correction phase may be approaching a floor, though a positive turn requires both demand recovery and developer solvency.",
        "related_series": ["aCNHPIAR", "aCNHPATOTA", "aCNHSALESCB"],
    },
}
