"""Hand-curated content for China RICs — Batch 09a (Real Estate part 1)."""
TIER1: dict[str, dict] = {
    "aCNHRASG": {
        "slug": "cn_housing_construction",
        "subcategory": "Real Estate Transaction Area — City",
        "units": "Sq m",
        "meaning": "Cumulative floor space of commercial housing transacted in Shaoguan, a smaller Guangdong city. Reflects local demand conditions in a tier-3 city context where price sensitivity and inventory build-up differ from tier-1 markets.",
        "how_to_use": "Benchmark against Guangdong province aggregate (aCNIREDGD) to assess whether demand weakness is concentrated in lower-tier cities; sustained declines signal affordability stress spreading beyond major metros.",
        "related_series": ["aCNIREDGD", "aCNHSALESRS", "aCNIREDTC"],
    },
    "aCNHRASX": {
        "slug": "cn_housing_construction",
        "subcategory": "Real Estate Transaction Area — City",
        "units": "Sq m",
        "meaning": "Cumulative floor space of commercial housing transacted in Shaoxing, a prosperous Zhejiang city near Hangzhou. Captures demand in an affluent Yangtze River Delta sub-market closely linked to Zhejiang's export economy.",
        "how_to_use": "Compare with Zhejiang province data (aCNIREDZJ) and national residential sales (aCNHSALESRS) to isolate whether Yangtze Delta cities are recovering faster than the national average after the Evergrande shock.",
        "related_series": ["aCNIREDZJ", "aCNHSALESRS", "aCNIREDTC"],
    },
    "aCNHRAXA": {
        "slug": "cn_housing_construction",
        "subcategory": "Real Estate Transaction Area — City",
        "units": "Sq m",
        "meaning": "Cumulative floor space of commercial housing transacted in Xi'an, a major tier-1.5 city in Shaanxi and the largest population center in northwest China. Xi'an saw a population inflow boom in 2017-2020 that inflated housing demand.",
        "how_to_use": "Monitor alongside Shaanxi investment data (aCNIREDSX) to gauge whether northwestern China's relative resilience post-Three Red Lines is holding; Xi'an often outperforms the interior average due to university and tech sector demand.",
        "related_series": ["aCNIREDSX", "aCNHSALESRS", "aCNIREDTC"],
    },
    "aCNHSALESRS": {
        "slug": "cn_housing_construction",
        "subcategory": "Residential Sales",
        "units": "Million sq m",
        "meaning": "Cumulative year-to-date floor space of commercial residential buildings sold nationwide — the broadest measure of housing demand published by NBS monthly. At peak (2021) sales exceeded 1.8 billion sq m annually; by 2023 they had dropped roughly 25%.",
        "how_to_use": "This is the primary demand-side indicator for the China property cycle: sustained YoY declines confirm the post-Three Red Lines contraction, while a durable recovery in sales is the prerequisite for any rebound in new starts (aCNBSTFSHR) and developer investment.",
        "related_series": ["aCNIREDTC", "aCNIREDRBY", "aCNBSTFSHR"],
    },
    "aCNIREDAN": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Anhui province, covering construction, land purchase, and equipment. Anhui is a central China province increasingly integrated into the Yangtze River Delta economic zone.",
        "how_to_use": "Compare against the national total (aCNIREDTC) and Anhui's YoY growth rate (aCNIREDANY) to identify whether central provinces are cushioning the national decline driven by coastal developer defaults.",
        "related_series": ["aCNIREDTC", "aCNIREDANY", "aCNIREDRBY"],
    },
    "aCNIREDANY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year percentage change in cumulative real estate development investment in Anhui. Provides a cleaner cycle signal than the level series by removing seasonal accumulation patterns.",
        "how_to_use": "A sustained negative print confirms that Anhui developers are cutting capex in line with the national deleveraging; a divergence from the national YoY (aCNIREDTCY) would indicate province-specific policy stimulus or SOE developer market share gains.",
        "related_series": ["aCNIREDAN", "aCNIREDTCY", "aCNIREDRBY"],
    },
    "aCNIREDBJ": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Beijing municipality. As a top-tier city with administrative demand and strict supply constraints, Beijing investment is structurally more resilient than lower-tier markets.",
        "how_to_use": "Use alongside the Beijing YoY rate (aCNIREDBJY) and national total (aCNIREDTC) to assess whether the capital's market is decoupling from the nationwide downturn; sustained Beijing weakness signals systemic rather than local stress.",
        "related_series": ["aCNIREDBJY", "aCNIREDTC", "aCNIREDSG"],
    },
    "aCNIREDBJY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Beijing. Beijing's YoY trend is closely watched as a tier-1 bellwether — policy easing (relaxing hukou restrictions, cutting down-payment ratios) typically shows up here first.",
        "how_to_use": "Compare with the national YoY (aCNIREDTCY) and Shanghai YoY (aCNIREDSGY) to construct a tier-1 composite; if tier-1 YoY diverges positively from the national, it suggests that only SOE-backed large cities are stabilizing.",
        "related_series": ["aCNIREDBJ", "aCNIREDTCY", "aCNIREDSGY"],
    },
    "aCNIREDTCY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — National YoY",
        "units": "% YoY",
        "meaning": "Year-on-year change in total national real estate development investment — one of the most widely quoted indicators of China's property cycle health, published by NBS monthly. It turned negative in mid-2022 and remains one of the key metrics watched by the PBOC and NDRC.",
        "how_to_use": "This is the headline YoY to monitor: a return to positive territory would mark a turning point for the sector, while continued double-digit declines reinforce the case for policy stimulus. Pair with residential sub-series (aCNIREDRBY) to distinguish housing from commercial real estate drag.",
        "related_series": ["aCNIREDTC", "aCNIREDRBY", "aCNIREDRGR"],
    },
    "aCNIREDCH": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Chongqing municipality, the largest municipality by area and a key inland growth engine. Chongqing has significant public housing and municipal SOE developer activity that can offset private developer weakness.",
        "how_to_use": "Assess alongside aCNIREDCHY for the trend; Chongqing's strong infrastructure mandate means its investment data is partly driven by government-backed projects, making it a partial counter-cyclical offset to private developer collapse post-Evergrande.",
        "related_series": ["aCNIREDCHY", "aCNIREDTC", "aCNIREDSC"],
    },
    "aCNIREDCHY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Chongqing. Because Chongqing has a large social housing program, this YoY can be less negative than private-market-dominated coastal provinces during downturns.",
        "how_to_use": "Compare with Sichuan (aCNIREDSCY) as an interior southwest composite; if Chongqing outperforms Sichuan on a YoY basis, it likely reflects Chongqing's policy-driven investment activity rather than genuine market recovery.",
        "related_series": ["aCNIREDCH", "aCNIREDSCY", "aCNIREDTCY"],
    },
    "aCNIREDCBB": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Commercial Buildings",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date investment in commercial business buildings (retail, shopping malls, mixed-use commercial) nationwide. This sub-category separates commercial real estate from residential and office, capturing retail property investment trends.",
        "how_to_use": "Benchmark against residential investment (aCNIREDRB) and office investment (aCNIREDOB) to identify which property sub-segment is leading the cycle; commercial retail investment tends to lag residential recovery as consumer sentiment lags income recovery.",
        "related_series": ["aCNIREDRB", "aCNIREDOB", "aCNIREDCBBY"],
    },
    "aCNIREDCBBY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Commercial Buildings YoY",
        "units": "% YoY",
        "meaning": "Year-on-year change in investment in commercial business buildings. Reflects structural shifts in retail and commercial property demand, partly driven by the rise of e-commerce and hybrid work reducing physical retail and office demand.",
        "how_to_use": "A persistent negative YoY signals structural oversupply in commercial real estate, distinct from the cyclical housing downturn; compare with office YoY (aCNIREDOBY) to determine whether the commercial real estate correction is broad-based.",
        "related_series": ["aCNIREDCBB", "aCNIREDOBY", "aCNIREDRBY"],
    },
    "aCNIREDFJ": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Fujian province, a coastal province with strong private sector and overseas Chinese investment in real estate. Fujian was disproportionately exposed to Evergrande and Country Garden as local buyers were active pre-sale purchasers.",
        "how_to_use": "Track alongside Fujian's YoY rate (aCNIREDFJY) and compare with Guangdong (aCNIREDGD) as a coastal property bellwether pair; Fujian's recovery trajectory indicates how coastal private-market demand is faring post-default cycle.",
        "related_series": ["aCNIREDFJY", "aCNIREDGD", "aCNIREDTCY"],
    },
    "aCNIREDFJY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Fujian. Given Fujian's exposure to private developers and pre-sale model buyers, this YoY is sensitive to confidence shocks from developer defaults.",
        "how_to_use": "Use with Fujian level data (aCNIREDFJ) to track the pace of recovery; compare against Guangdong YoY (aCNIREDGDY) to see if southern coastal markets are moving in sync or diverging post-保交楼 policy.",
        "related_series": ["aCNIREDFJ", "aCNIREDGDY", "aCNIREDTCY"],
    },
    "aCNIREDGD": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Guangdong, China's largest provincial economy and ground zero for the Evergrande and Country Garden defaults. Guangdong accounts for a disproportionate share of total national real estate investment.",
        "how_to_use": "Guangdong is the single most important provincial indicator for China real estate: its trajectory versus the national average (aCNIREDTC) signals whether the epicenter of the default crisis is stabilizing or worsening. Watch for signs of SOE developer (Poly, China Resources Land) market share gains.",
        "related_series": ["aCNIREDGDY", "aCNIREDTC", "aCNIREDFJ"],
    },
    "aCNIREDGDY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Guangdong. As the province most affected by Evergrande (HQ in Shenzhen) and Country Garden (HQ in Foshan), Guangdong's YoY captures the sharpest end of the private developer deleveraging cycle.",
        "how_to_use": "A sustained recovery in Guangdong's YoY toward zero is necessary (though not sufficient) to call a national property bottom; compare with tier-1 Beijing YoY (aCNIREDBJY) to see if the recovery is geographically broadening.",
        "related_series": ["aCNIREDGD", "aCNIREDBJY", "aCNIREDTCY"],
    },
    "aCNIREDGX": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Guangxi autonomous region, a lower-income coastal province bordering Vietnam. Guangxi's real estate market is heavily influenced by speculation from neighboring provinces and cross-border trade dynamics.",
        "how_to_use": "Compare with Guangdong (aCNIREDGD) to assess spillover from Guangdong's market stress; Guangxi's smaller market means its data is more volatile but reflects conditions in China's southern tier-3/4 city markets.",
        "related_series": ["aCNIREDGXY", "aCNIREDGD", "aCNIREDTCY"],
    },
    "aCNIREDGXY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Guangxi. Guangxi's YoY can be more volatile than larger provinces due to project timing in a smaller market with large infrastructure-linked real estate components.",
        "how_to_use": "Use alongside Guangxi level data (aCNIREDGX) and compare with the national YoY (aCNIREDTCY); persistent underperformance of Guangxi vs the national average signals that lower-tier southern markets continue to suffer disproportionate inventory overhang.",
        "related_series": ["aCNIREDGX", "aCNIREDTCY", "aCNIREDHNY"],
    },
    "aCNIREDHE": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Hebei province, which surrounds Beijing and benefited from Beijing Xiong'an New Area development and 2022 Winter Olympics infrastructure. Hebei's market is closely tied to Beijing spillover demand.",
        "how_to_use": "Track alongside Beijing investment (aCNIREDBJ) as a satellite-city indicator; outperformance of Hebei vs Beijing suggests that suburban demand or Xiong'an policy investment is buffering the broader residential downturn.",
        "related_series": ["aCNIREDHEY", "aCNIREDBJ", "aCNIREDTCY"],
    },
    "aCNIREDHEY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Hebei. Reflects both organic residential market trends and Beijing-policy-driven infrastructure investment in the Jing-Jin-Ji integrated region.",
        "how_to_use": "Compare against Beijing YoY (aCNIREDBJY) and the national YoY (aCNIREDTCY); sustained Hebei outperformance would indicate that Xiong'an and government-led construction projects are propping up the provincial number.",
        "related_series": ["aCNIREDHE", "aCNIREDBJY", "aCNIREDTCY"],
    },
    "aCNIREDHJ": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Heilongjiang province, a northeastern rust-belt province experiencing long-term population outflow. Heilongjiang faces structural housing oversupply as labor migration depresses demand.",
        "how_to_use": "This series is informative as a stress case for demographic headwinds on property: compare with national total (aCNIREDTC) to see how deep the structural trough is versus the cyclical national downturn.",
        "related_series": ["aCNIREDHJY", "aCNIREDLN", "aCNIREDTCY"],
    },
    "aCNIREDHJY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Heilongjiang. Expected to be chronically negative due to structural population decline, offering a contrast with cyclical-downturn provinces.",
        "how_to_use": "Use as a baseline comparison for other declining provinces; if Liaoning (aCNIREDLNY) or Henan track toward Heilongjiang's chronic negative prints, it signals those markets are tipping from cyclical to structural decline.",
        "related_series": ["aCNIREDHJ", "aCNIREDLNY", "aCNIREDTCY"],
    },
    "aCNIREDHEN": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Henan, China's most populous province and a major lower-tier city real estate market. Henan was severely hit by the 2021 developer defaults and also by the Zhengzhou flood, compounding the property downturn.",
        "how_to_use": "Compare with Hubei (aCNIREDHU) and Hunan (aCNIREDHN) as a central China troika; Henan's persistent weakness reflects the depth of developer default exposure in inland China and the slow pace of 保交楼 delivery.",
        "related_series": ["aCNIREDHENY", "aCNIREDHU", "aCNIREDTCY"],
    },
    "aCNIREDHENY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Henan. Among the most watched inland provincial YoY series given Henan's large size and acute exposure to defaulted developers' unfinished projects.",
        "how_to_use": "A turn from negative to flat in Henan's YoY would be a significant signal for central China stabilization; contrast with Guangdong (aCNIREDGDY) to compare inland vs coastal recovery trajectories.",
        "related_series": ["aCNIREDHEN", "aCNIREDGDY", "aCNIREDTCY"],
    },
    "aCNIREDHU": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Hubei province, home of Wuhan — one of China's major inland cities. Hubei's market was doubly disrupted by COVID-19 in 2020 and the subsequent property downturn.",
        "how_to_use": "Track alongside Hunan (aCNIREDHN) and Henan (aCNIREDHEN) as an indicator of central China real estate health; Hubei's larger economy and Wuhan's tier-1.5 status mean it can recover faster than smaller inland provinces.",
        "related_series": ["aCNIREDHUY", "aCNIREDHEN", "aCNIREDHN"],
    },
    "aCNIREDHUY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Hubei. Hubei's YoY reflects both the ongoing national deleveraging cycle and the lingering impacts of COVID-19 disruption on project pipelines.",
        "how_to_use": "Compare with the national YoY (aCNIREDTCY) and Hunan (aCNIREDHNY); a meaningful Hubei outperformance would point to Wuhan's urban renewal programs or SOE developer dominance relative to defaulted private developers.",
        "related_series": ["aCNIREDHU", "aCNIREDHNY", "aCNIREDTCY"],
    },
    "aCNIREDHN": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Hunan province. Changsha, Hunan's capital, has implemented some of the more aggressive local easing measures to support the property market since 2022.",
        "how_to_use": "Watch for divergence from the national trend (aCNIREDTC) — Hunan's proactive city-level policy easing could make it a recovery leader among central provinces; compare with Hubei (aCNIREDHU) to assess which central province is recovering faster.",
        "related_series": ["aCNIREDHNY", "aCNIREDHU", "aCNIREDTCY"],
    },
    "aCNIREDHNY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Hunan. Changsha's relatively affordable housing and tech-sector job growth have made Hunan one of the more resilient central province markets in the downturn.",
        "how_to_use": "Use alongside national YoY (aCNIREDTCY) and Hubei YoY (aCNIREDHUY); if Hunan consistently outperforms both, it validates the city-level demand stimulus playbook as a template for other provinces.",
        "related_series": ["aCNIREDHN", "aCNIREDHUY", "aCNIREDTCY"],
    },
    "aCNIREDRB": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Residential",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date national investment in residential buildings only, stripping out office, commercial, and industrial real estate. Residential buildings account for roughly 70% of total real estate development investment and are the core of the property cycle.",
        "how_to_use": "Pair with total investment (aCNIREDTC) to calculate the residential share — a falling share suggests commercial/industrial is relatively better; use the residential YoY (aCNIREDRBY) as the primary sub-index for housing-specific policy transmission.",
        "related_series": ["aCNIREDRBY", "aCNIREDTC", "aCNIREDCBB"],
    },
    "aCNIREDTC": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — National Total",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date total national real estate development investment — the broadest investment measure in NBS's monthly Real Estate Investment release. This is the single most-cited China property investment figure by policymakers and markets.",
        "how_to_use": "Compare the annual run-rate with the 2021 peak (~15 trillion CNY) to gauge the depth of the cycle; use alongside residential sub-index (aCNIREDRB) and the YoY growth rate (aCNIREDTCY) to assess both the level and direction of the cycle.",
        "related_series": ["aCNIREDTCY", "aCNIREDRB", "aCNIREDRGR"],
    },
    "aCNIREDJG": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Jiangsu province. Jiangsu is one of China's wealthiest provinces and the second-largest by GDP; its real estate market is anchored by Nanjing, Suzhou, and Wuxi — all tier-1.5 or tier-2 cities.",
        "how_to_use": "Compare with Zhejiang (aCNIREDZJ) as a Yangtze River Delta pair; Jiangsu's stronger exposure to manufacturing and export sectors means its real estate cycle has a distinct income driver that can diverge from purely financial-sector-driven Zhejiang.",
        "related_series": ["aCNIREDJGY", "aCNIREDZJ", "aCNIREDTC"],
    },
    "aCNIREDJGY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Jiangsu. Jiangsu's YoY is closely watched given the province's scale and the outsized role of Suzhou and Nanjing in reflecting premium-tier demand.",
        "how_to_use": "Pair with Zhejiang YoY (aCNIREDZJY) and Shanghai YoY (aCNIREDSGY) to construct a Yangtze Delta composite; if all three recover together, it signals the most economically important corridor is stabilizing.",
        "related_series": ["aCNIREDJG", "aCNIREDZJY", "aCNIREDSGY"],
    },
    "aCNIREDJX": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Jiangxi province. Jiangxi is a mid-tier interior province whose real estate market was heavily reliant on migrant-worker remittance demand and has faced significant inventory overhang.",
        "how_to_use": "Compare with neighboring Hunan (aCNIREDHN) and Fujian (aCNIREDFJ) to assess central-interior vs coastal divergence; Jiangxi's persistent weakness often reflects interior cities' difficulty in attracting sustained housing demand.",
        "related_series": ["aCNIREDJXY", "aCNIREDHN", "aCNIREDFJ"],
    },
    "aCNIREDJXY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Jiangxi. Reflects demand conditions in a mid-tier interior market susceptible to inventory build-up and constrained by slower wage growth than coastal peers.",
        "how_to_use": "Use alongside Jiangxi level data (aCNIREDJX) and compare to the national YoY (aCNIREDTCY); consistent underperformance signals Jiangxi belongs to the structurally challenged interior tier alongside Heilongjiang and Liaoning.",
        "related_series": ["aCNIREDJX", "aCNIREDTCY", "aCNIREDHNY"],
    },
    "aCNRDLAASP": {
        "slug": "cn_housing_construction",
        "subcategory": "Land Acquisition",
        "units": "10,000 sq m",
        "meaning": "Cumulative year-to-date land acquisition area by real estate developers nationwide — the earliest leading indicator in the property pipeline, preceding new starts by 6-18 months. Land purchases by developers collapsed after the Three Red Lines policy restricted developer financing.",
        "how_to_use": "This is the most forward-looking series in the NBS real estate release: a sustained positive YoY in land acquisition precedes a recovery in new starts (aCNBSTFSHR) by at least 2-3 quarters. Watch for state-owned developers taking more land while private developers remain sidelined.",
        "related_series": ["aCNIREDTC", "aCNNPRT", "aCNBSTFSHR"],
    },
    "aCNIREDLN": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Liaoning province, a major northeastern industrial province facing demographic decline. Liaoning anchors the northeast rust belt, where structural oversupply compounds the cyclical property downturn.",
        "how_to_use": "Compare with Heilongjiang (aCNIREDHJ) as a northeast China composite; Liaoning's Shenyang and Dalian are larger cities that could show earlier recovery signs than smaller Heilongjiang cities, distinguishing city-tier effects from provincial effects.",
        "related_series": ["aCNIREDLNY", "aCNIREDHJ", "aCNIREDTCY"],
    },
    "aCNIREDLNY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Liaoning. A key read on northeast China's ability to stabilize after years of combined demographic outflow and property cycle downturn.",
        "how_to_use": "Compare with Heilongjiang YoY (aCNIREDHJY) and the national YoY (aCNIREDTCY); if Liaoning converges toward the national average while Heilongjiang continues to underperform, it suggests city-size matters more than the northeast discount.",
        "related_series": ["aCNIREDLN", "aCNIREDHJY", "aCNIREDTCY"],
    },
    "aCNIREDOB": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Office Buildings",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date national investment in office buildings. Office real estate investment reflects corporate expansion plans and is sensitive to the demand from financial services, tech, and professional services sectors.",
        "how_to_use": "Compare with residential (aCNIREDRB) and commercial business (aCNIREDCBB) to track sub-sector divergence; office investment has been under structural pressure from hybrid-work trends and the post-pandemic reconfiguration of corporate real estate demand.",
        "related_series": ["aCNIREDOBY", "aCNIREDRB", "aCNIREDCBB"],
    },
    "aCNIREDOBY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Office Buildings YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of investment in office buildings. Provides a cleaner read on the office real estate cycle stripped of the seasonal accumulation effect in the level series.",
        "how_to_use": "Use alongside commercial business YoY (aCNIREDCBBY) and residential YoY (aCNIREDRBY) to identify which sub-sector is recovering fastest; a persistent office YoY decline while residential recovers would indicate a structural shift in Chinese real estate away from office.",
        "related_series": ["aCNIREDOB", "aCNIREDCBBY", "aCNIREDRBY"],
    },
    "aCNIREDRGR": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Real Growth",
        "units": "% YoY",
        "meaning": "Quarterly real (inflation-adjusted) year-on-year growth rate of total real estate development investment, published at quarterly frequency by NBS. This provides a volume-based measure of investment activity free from price effects.",
        "how_to_use": "Cross-check against the nominal YoY (aCNIREDTCY) to identify whether nominal declines are partly offset by construction cost deflation; in a downturn, real growth can be less negative than nominal if construction input prices fall faster.",
        "related_series": ["aCNIREDTCY", "aCNIREDRBY", "aCNIREDTC"],
    },
    "aCNIREDRBY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Residential YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of investment in residential buildings — the most policy-sensitive sub-index of the NBS real estate investment release. This series directly reflects developer willingness to invest in housing after Three Red Lines constrained their balance sheets.",
        "how_to_use": "This is the most important YoY sub-series for housing policy analysis: policymakers target a return to positive residential investment YoY as a sign that the 保交楼 program is transitioning to new supply investment; compare with total YoY (aCNIREDTCY) to see residential vs commercial divergence.",
        "related_series": ["aCNIREDRB", "aCNIREDTCY", "aCNHSALESRS"],
    },
    "aCNIREDSX": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Shaanxi province. Xi'an, Shaanxi's capital, has been a notable outperformer in northwest China due to its university, military, and tech sector demand base, partially insulating it from the broader downturn.",
        "how_to_use": "Compare with Sichuan (aCNIREDSC) as a western China peer; Shaanxi's better-performing cities like Xi'an may show earlier inflection points than more rural provinces, helping to distinguish urban recovery from nationwide property stabilization.",
        "related_series": ["aCNIREDSXY", "aCNIREDSC", "aCNIREDTCY"],
    },
    "aCNIREDSXY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Shaanxi. Xi'an's population inflow and government-sector demand provide a relative buffer, potentially enabling Shaanxi's YoY to diverge positively from the national average.",
        "how_to_use": "Monitor for divergence from the national YoY (aCNIREDTCY); if Shaanxi consistently outperforms, it validates the hypothesis that northwest China's administrative and education center cities are recovering on a different (faster) timeline than coastal private-developer-dominated markets.",
        "related_series": ["aCNIREDSX", "aCNIREDTCY", "aCNIREDSCY"],
    },
    "aCNIREDSD": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Shandong, China's third-largest provincial economy. Shandong has a significant state-owned developer presence and a large working-class urban population, giving its market different dynamics from Guangdong or Zhejiang.",
        "how_to_use": "Compare with Jiangsu (aCNIREDJG) as a northern coastal vs Yangtze Delta comparison; Shandong's heavier industrial economy means its property demand is more closely correlated with industrial employment than financial or tech sector income.",
        "related_series": ["aCNIREDSDY", "aCNIREDJG", "aCNIREDTCY"],
    },
    "aCNIREDSDY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Shandong. Reflects both the national property cycle and Shandong's industrial economy dynamics; SOE developer activity in Jinan and Qingdao can buffer the Shandong series relative to coastal private-market-driven provinces.",
        "how_to_use": "Track alongside Jiangsu YoY (aCNIREDJGY) and the national YoY (aCNIREDTCY); Shandong's SOE buffer effect means it may show less extreme declines but also slower recoveries than Guangdong.",
        "related_series": ["aCNIREDSD", "aCNIREDJGY", "aCNIREDTCY"],
    },
    "aCNIREDSG": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Shanghai municipality. Shanghai is China's financial center and the most internationally monitored tier-1 city; its property investment data reflects the interplay of global capital flows, luxury housing, and commercial real estate.",
        "how_to_use": "Compare with Beijing (aCNIREDBJ) to construct a tier-1 pair; Shanghai's recovery relative to Beijing often signals whether the financial center is leading the policy-driven stabilization, as Shanghai is where international developer financing and REIT structures are most active.",
        "related_series": ["aCNIREDSGY", "aCNIREDBJ", "aCNIREDJG"],
    },
    "aCNIREDSGY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Shanghai. The single most-watched city-level real estate YoY for global investors monitoring China property stabilization.",
        "how_to_use": "If Shanghai's YoY turns positive while the national YoY (aCNIREDTCY) remains negative, it signals a top-tier city decoupling; pair with Beijing YoY (aCNIREDBJY) to determine if tier-1 divergence from the national is sustained or a one-quarter anomaly.",
        "related_series": ["aCNIREDSG", "aCNIREDBJY", "aCNIREDTCY"],
    },
    "aCNIREDSC": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Sichuan province. Chengdu, Sichuan's capital, is a major interior megacity that has attracted significant tech and manufacturing investment, supporting housing demand above the western China average.",
        "how_to_use": "Compare with Chongqing (aCNIREDCH) as the Chengdu-Chongqing Economic Circle pair; Sichuan's data reflects Chengdu's growing role as an interior consumption hub, making it one of the more resilient interior province real estate markets.",
        "related_series": ["aCNIREDSCY", "aCNIREDCH", "aCNIREDTCY"],
    },
    "aCNIREDSCY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Sichuan. Chengdu's population inflow and strong tech sector job creation have made Sichuan one of the better-performing interior provinces in the post-Three Red Lines environment.",
        "how_to_use": "Track alongside Chongqing YoY (aCNIREDCHY) and the national YoY (aCNIREDTCY); sustained outperformance of the Chengdu-Chongqing corridor vs the national average validates the western growth pole narrative for China's property stabilization.",
        "related_series": ["aCNIREDSC", "aCNIREDCHY", "aCNIREDTCY"],
    },
    "aCNIREDTJ": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Tianjin municipality, a tier-1 city and major port adjacent to Beijing. Tianjin has faced significant oversupply issues since 2018 due to prior infrastructure-led property development, making it one of the more challenged tier-1 markets.",
        "how_to_use": "Compare with Beijing (aCNIREDBJ) as a Jing-Jin corridor pair; Tianjin's persistent underperformance vs Beijing reflects its earlier oversupply cycle, and any recovery here would signal the Jing-Jin region is fully clearing its inventory backlog.",
        "related_series": ["aCNIREDTJY", "aCNIREDBJ", "aCNIREDHE"],
    },
    "aCNIREDTJY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Tianjin. Tianjin's YoY has been among the weakest of major cities, reflecting both pre-existing oversupply and the additional impact of Three Red Lines on leveraged developers active in the market.",
        "how_to_use": "Use alongside Beijing YoY (aCNIREDBJY) and the national YoY (aCNIREDTCY); a convergence of Tianjin's YoY toward the national average would signal that even the most challenged tier-1 cities are stabilizing.",
        "related_series": ["aCNIREDTJ", "aCNIREDBJY", "aCNIREDTCY"],
    },
    "aCNIREDYN": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Yunnan province, a southwestern border province. Yunnan's real estate market was boosted by tourism-linked property and retiree demand from coastal cities but has since faced sharp corrections in resort and holiday home segments.",
        "how_to_use": "Compare with Sichuan (aCNIREDSC) and Guizhou as a southwest bloc; Yunnan's tourism and lifestyle property niche means its data diverges from manufacturing-driven provincial markets and is sensitive to domestic tourism policy.",
        "related_series": ["aCNIREDYNY", "aCNIREDSC", "aCNIREDTCY"],
    },
    "aCNIREDYNY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Yunnan. Tourism-linked property and holiday home segments make Yunnan's YoY somewhat correlated with domestic tourism data and less with industrial employment.",
        "how_to_use": "Monitor alongside Sichuan YoY (aCNIREDSCY) and the national YoY (aCNIREDTCY); a sharp Yunnan underperformance vs Sichuan signals the tourism-property niche is bearing more of the downturn than broader residential markets.",
        "related_series": ["aCNIREDYN", "aCNIREDSCY", "aCNIREDTCY"],
    },
    "aCNIREDZJ": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date real estate development investment in Zhejiang province. Home to Hangzhou (tech hub), Ningbo (port/manufacturing), and Wenzhou (private enterprise capital), Zhejiang is one of China's wealthiest provinces and a key real estate market watched alongside Jiangsu and Shanghai.",
        "how_to_use": "Construct a Yangtze Delta composite with Jiangsu (aCNIREDJG) and Shanghai (aCNIREDSG); Zhejiang's entrepreneurial private sector and Hangzhou's tech economy mean its housing demand is closely tied to domestic tech sector income and valuation cycles.",
        "related_series": ["aCNIREDZJY", "aCNIREDJG", "aCNIREDSG"],
    },
    "aCNIREDZJY": {
        "slug": "cn_housing_construction",
        "subcategory": "RE Development Investment — Province YoY",
        "units": "% YoY",
        "meaning": "Year-on-year growth rate of real estate development investment in Zhejiang. Given Hangzhou's tech sector and Zhejiang's high income levels, this YoY is a useful proxy for whether affluent coastal buyers are returning to the market.",
        "how_to_use": "Compare with Jiangsu YoY (aCNIREDJGY) and Shanghai YoY (aCNIREDSGY); a positive Zhejiang YoY ahead of the national average would signal that high-income coastal buyers are leading the recovery, consistent with historical property cycle dynamics.",
        "related_series": ["aCNIREDZJ", "aCNIREDJGY", "aCNIREDSGY"],
    },
    "aCNNPRT": {
        "slug": "cn_housing_construction",
        "subcategory": "New Construction Starts — Projects",
        "units": "Count",
        "meaning": "Cumulative year-to-date number of newly started real estate development projects nationwide. This count-based metric complements floor-space new starts by capturing the number of discrete project initiations, reflecting developer pipeline activity.",
        "how_to_use": "Compare with planned investment in new projects (aCNNPRPI) to calculate average project size — a decline in project count alongside rising average size signals consolidation toward larger SOE-led projects; track with land acquisition area (aCNRDLAASP) to assess pipeline sequencing.",
        "related_series": ["aCNNPRPI", "aCNRDLAASP", "aCNIREDTC"],
    },
    "aCNNPRPI": {
        "slug": "cn_housing_construction",
        "subcategory": "New Construction Starts — Planned Investment",
        "units": "100 Million CNY",
        "meaning": "Cumulative year-to-date planned investment value of newly started real estate projects. This series captures the committed capital for projects that have broken ground, providing a forward look at construction spending momentum.",
        "how_to_use": "Ratio with project count (aCNNPRT) to derive average project investment size — rising average size with fewer projects signals market consolidation; compare against total actual investment (aCNIREDTC) as a commitment-vs-actual conversion check.",
        "related_series": ["aCNNPRT", "aCNIREDTC", "aCNRDLAASP"],
    },
    "aCNPUCT": {
        "slug": "cn_housing_construction",
        "subcategory": "Under-Construction",
        "units": "Count",
        "meaning": "Total number of real estate development projects currently under construction at period end. This stock measure captures the overhang of incomplete projects, which became a critical policy concern after the 2021-2023 developer defaults left millions of pre-sold units unfinished.",
        "how_to_use": "The under-construction project count is the denominator for the 保交楼 (deliver pre-sold homes) policy: a declining count means projects are being completed faster than new ones start, the key indicator that the unfinished-housing overhang is clearing; compare with new starts (aCNNPRT) to track the pipeline flow.",
        "related_series": ["aCNNPRT", "aCNNPRPI", "aCNIREDTC"],
    },
}
