"""Hand-curated content for China RICs — Batch 08b (CPI Sub-Components, part 2)."""
TIER1: dict[str, dict] = {
    "aCNCNFSFQQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Northwest Region",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price level for China's Northwest region (Shaanxi, Gansu, Qinghai, Ningxia, Xinjiang), sourced from the China Land Price Information Service Platform. Captures urban land transaction costs that feed into housing and construction cost components of CPI.",
        "how_to_use": "Compare with east-coast equivalents (Yangtze Delta, Pearl River Delta) to gauge regional divergence; sustained weakness signals subdued local property markets and limited pass-through to rent CPI.",
        "related_series": ["aCNCNGJSIQ", "aCNCNIIMOQ", "aCNCNFCAVQ"],
    },
    "aCNCNNTAQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Pearl River Delta",
        "units": "Index, Quarterly",
        "meaning": "Land-use price level for the Pearl River Delta Economic Zone (Guangzhou, Shenzhen, Dongguan cluster), published quarterly by the China Land Price Information Service Platform. Reflects commercial and residential land demand in China's premier manufacturing export corridor.",
        "how_to_use": "Track alongside Guangdong provincial CPI for rent pass-through signals; a sustained drop in Pearl River Delta land prices typically leads residential rent softness by 2-4 quarters.",
        "related_series": ["aCNCNBQDUQ", "aCNCNFCAVQ", "aCNCNIKBPQ"],
    },
    "aCNCNBQDUQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Pearl River Delta (Current Prices)",
        "units": "CNY/sqm, Quarterly",
        "meaning": "Pearl River Delta land-use price in current (nominal) CNY per square metre, from the China Land Price Information Service Platform. Nominal series without index adjustment, useful for absolute price-level comparisons across economic zones.",
        "how_to_use": "Use alongside the index-based PRD series (aCNCNNTAQ) to decompose real vs. nominal land cost trends; divergence may indicate price deflation pressures feeding into the housing CPI sub-component.",
        "related_series": ["aCNCNNTAQ", "aCNCNNVRQ", "aCNCNDMMXQ"],
    },
    "aCNCNUBICQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Qiqihar City",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price index for Qiqihar, a heavy-industry city in Heilongjiang province, sourced from the China Land Price Information Service Platform. Reflects conditions in northeast China's rust-belt urban land market.",
        "how_to_use": "Use as a proxy for tier-3/4 city land market stress in the northeast; sustained index decline correlates with local government fiscal pressure and weak developer activity, which can dampen local services CPI.",
        "related_series": ["aCNCNNVRQ", "aCNCNYXLFQ", "aCNCNMUFYQ"],
    },
    "aCNCNNVRQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Qiqihar City (Current Prices)",
        "units": "CNY/sqm, Quarterly",
        "meaning": "Nominal current-price land transaction value for Qiqihar city (Heilongjiang), from the China Land Price Information Service Platform. Provides an undeflated measure of local land market activity and developer appetite.",
        "how_to_use": "Compare with the Qiqihar index series (aCNCNUBICQ) to isolate nominal vs. real land price trends; sharp nominal declines indicate distressed local government land auctions, a leading indicator of fiscal strain.",
        "related_series": ["aCNCNUBICQ", "aCNCNDMMXQ", "aCNCNMUFYQ"],
    },
    "aCNCNIKBPQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Shunde District",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price index for Shunde District (Foshan, Guangdong), a major appliance and furniture manufacturing hub, from the China Land Price Information Service Platform. Reflects industrial and commercial land costs in the Pearl River Delta hinterland.",
        "how_to_use": "Monitor for signals on Guangdong manufacturing-zone land cost inflation, which can lead changes in durable-goods CPI components via input costs; compare with broader PRD series to gauge sub-regional divergence.",
        "related_series": ["aCNCNNTAQ", "aCNCNBQDUQ", "aCNCNFCAVQ"],
    },
    "aCNCNGJSIQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Southwest Region",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price level for China's Southwest region (Sichuan, Chongqing, Yunnan, Guizhou, Tibet), from the China Land Price Information Service Platform. Tracks the urbanisation-driven land market in China's fastest-developing interior zone.",
        "how_to_use": "Chengdu-Chongqing corridor land momentum often leads southwest regional CPI rent components by 2-3 quarters; sustained rises signal durable domestic demand expansion in the interior.",
        "related_series": ["aCNCNFSFQQ", "aCNCNIIMOQ", "aCNCNFCAVQ"],
    },
    "aCNCNIIMOQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Western Region",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price level for China's broader Western region (includes Northwest + Southwest, i.e. 12 provinces/municipalities), published by the China Land Price Information Service Platform. Serves as the composite western interior benchmark.",
        "how_to_use": "Use as a macro-level view of interior China land market conditions; compare East-West spreads to assess policy-driven regional investment flows (e.g., Belt and Road domestic extension, westward industrial relocation).",
        "related_series": ["aCNCNFSFQQ", "aCNCNGJSIQ", "aCNCNFCAVQ"],
    },
    "aCNCNDSKXQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Xinxiang City",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price index for Xinxiang city (Henan province), a mid-size central China industrial and agricultural hub, from the China Land Price Information Service Platform.",
        "how_to_use": "Track alongside Henan provincial CPI; Xinxiang's land market reflects central China's agricultural-industrial economy — softness may precede downward pressure on local housing CPI.",
        "related_series": ["aCNCNDMMXQ", "aCNCNUBICQ", "aCNCNNVRQ"],
    },
    "aCNCNDMMXQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Xinxiang City (Current Prices)",
        "units": "CNY/sqm, Quarterly",
        "meaning": "Nominal current-price land value for Xinxiang city (Henan), from the China Land Price Information Service Platform. Provides an absolute price benchmark for central China tier-3 land market transactions.",
        "how_to_use": "Pair with the index series (aCNCNDSKXQ) to distinguish inflation from real demand; Henan land prices often track migration-driven urbanisation — divergence with index signals deflation in the local market.",
        "related_series": ["aCNCNDSKXQ", "aCNCNNVRQ", "aCNCNBQDUQ"],
    },
    "aCNCNFCAVQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Yangtze River Delta",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price level for the Yangtze River Delta Economic Zone (Shanghai, Jiangsu, Zhejiang, Anhui), from the China Land Price Information Service Platform. Tracks the most commercially intense land market outside Tier-1 cities.",
        "how_to_use": "The YRD land price index leads eastern China housing rent CPI by roughly 2-4 quarters; compare with Pearl River Delta (aCNCNNTAQ) to assess relative property cycle positioning across China's two major megacity clusters.",
        "related_series": ["aCNCNNTAQ", "aCNCNIIMOQ", "aCNCNGJSIQ"],
    },
    "aCNCNYXLFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Yichun City",
        "units": "Index, Quarterly",
        "meaning": "Quarterly land-use price index for Yichun city (Heilongjiang), a forestry-based declining industrial city in northeast China, from the China Land Price Information Service Platform.",
        "how_to_use": "Yichun is among China's most economically distressed tier-4 cities; near-zero or negative land price readings indicate severe population outflow and suppressed local demand — relevant to northeast China regional CPI divergence analysis.",
        "related_series": ["aCNCNMUFYQ", "aCNCNUBICQ", "aCNCNNVRQ"],
    },
    "aCNCNMUFYQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Price — Yichun City (Current Prices)",
        "units": "CNY/sqm, Quarterly",
        "meaning": "Nominal current-price land transaction value for Yichun city (Heilongjiang), from the China Land Price Information Service Platform. Absolute price benchmark for one of northeast China's most depressed land markets.",
        "how_to_use": "Monitor for evidence of policy-induced stabilisation (e.g., northeast revitalisation subsidies); persistent near-zero values confirm structural deflationary pressure in the local economy with no near-term CPI upside.",
        "related_series": ["aCNCNYXLFQ", "aCNCNNVRQ", "aCNCNUBICQ"],
    },
    "aCNCNZFQQM": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Oil & Chemical Prices — Coke (Secondary Metallurgical)",
        "units": "CNY/tonne, Monthly",
        "meaning": "Average domestic market price of secondary metallurgical coke, a key steelmaking input, from China's oil and chemical product price monitoring. Tracks midstream industrial commodity costs with pass-through to steel and construction prices.",
        "how_to_use": "Coke price moves lead steel CPI components by 1-2 months; sustained softness points to weak construction/infrastructure demand, feeding into PPI deflation and downstream consumer durables price declines.",
        "related_series": ["aCNCNOOUEM", "aCNCNMIGBM", "aCNCPDURAF/C"],
    },
    "aCNCNOOUEM": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Oil & Chemical Prices — EPDM Rubber (4045#)",
        "units": "CNY/tonne, Monthly",
        "meaning": "Average domestic market price of EPDM (Ethylene Propylene Diene Monomer) rubber grade 4045#, a synthetic rubber used in automotive seals, roofing, and consumer goods, from China's oil and chemical product price series.",
        "how_to_use": "EPDM tracks crude oil and ethylene feedstock cycles; rising prices signal upstream petrochemical cost push into consumer durables and auto parts, though direct CPI pass-through is diffuse and lagged.",
        "related_series": ["aCNCNZFQQM", "aCNCNMIGBM", "aCNCPDURAF/C"],
    },
    "aCNCNMIGBM": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Oil & Chemical Prices — Formaldehyde (Primary)",
        "units": "CNY/tonne, Monthly",
        "meaning": "Average domestic market price of primary-grade formaldehyde (clean water solution), a key input to resins, adhesives, and furniture manufacturing, from China's oil and chemical price monitoring.",
        "how_to_use": "Formaldehyde prices track methanol and natural gas feedstock cycles; sustained declines indicate weak real-estate-related demand (furniture, construction materials), consistent with property sector deflation in housing CPI.",
        "related_series": ["aCNCNZFQQM", "aCNCNOOUEM", "aCNCPHF"],
    },
    "aCNCNULLRQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Hotel Room Rate — Inner Mongolia",
        "units": "CNY/night, Quarterly",
        "meaning": "Average star-hotel room rate in Inner Mongolia Autonomous Region, published quarterly. Tracks travel-services inflation in a resource-rich border region with significant business and tourist flows.",
        "how_to_use": "Hotel rates are a real-time services-CPI proxy; Inner Mongolia's rates are sensitive to coal/mining business cycles and seasonal tourism — compare with national hotel price indices to assess regional divergence in services inflation.",
        "related_series": ["aCNCNWEDXQ", "aCNCNEDONQ", "aCNCPIM"],
    },
    "aCNCNWEDXQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Hotel Room Rate — Jiangsu Province",
        "units": "CNY/night, Quarterly",
        "meaning": "Average star-hotel room rate across Jiangsu province (Nanjing, Suzhou, Wuxi), published quarterly. Jiangsu is China's second-largest provincial economy; hotel rates here are a bellwether for YRD business travel and convention activity.",
        "how_to_use": "Track alongside Jiangsu services CPI; elevated Jiangsu rates vs. national average signal strong corporate travel demand and domestic consumption recovery — relevant to the recreation and travel sub-component of CPI.",
        "related_series": ["aCNCNEDONQ", "aCNCNULLRQ", "aCNCPIM"],
    },
    "aCNCNEDONQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Hotel Room Rate — Jiangxi Province",
        "units": "CNY/night, Quarterly",
        "meaning": "Average star-hotel room rate across Jiangxi province, a central China province with significant tourism (Lushan, Jingdezhen) and manufacturing activity, published quarterly.",
        "how_to_use": "Jiangxi hotel rates capture mid-tier domestic tourism and manufacturing business travel; compare with coastal provinces (aCNCNWEDXQ) to gauge inland-coastal services-price convergence or divergence.",
        "related_series": ["aCNCNMBKQQ", "aCNCNWEDXQ", "aCNCNIDRFQ"],
    },
    "aCNCNMBKQQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Hotel Room Rate — Jiangxi (One-Star)",
        "units": "CNY/night, Quarterly",
        "meaning": "Average one-star hotel room rate in Jiangxi province, published quarterly. One-star rates capture the budget end of the accommodation market, more reflective of domestic migrant-worker and low-income travel costs.",
        "how_to_use": "One-star rates are a proxy for lower-income consumer services inflation; compare with all-star average (aCNCNEDONQ) to identify polarisation — widening spreads may signal K-shaped services price recovery.",
        "related_series": ["aCNCNEDONQ", "aCNCNIDRFQ", "aCNCPIM"],
    },
    "aCNCNIDRFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Hotel Room Rate — Jilin (One-Star)",
        "units": "CNY/night, Quarterly",
        "meaning": "Average one-star hotel room rate in Jilin province (northeast China), published quarterly. Reflects budget accommodation pricing in a slow-growth northeastern province with significant out-migration.",
        "how_to_use": "Jilin's one-star hotel rates benchmark the northeast's low-end services economy; persistent deflation vs. national average confirms structural demand weakness and contracting local services CPI.",
        "related_series": ["aCNCNMBKQQ", "aCNCNULLRQ", "aCNCPIM"],
    },
    "aCNPFAPA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Apples (Fuji)",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of Fuji apples across 50 monitored cities, published monthly by the Ministry of Commerce (MOFCOM). Fuji apples are China's dominant variety and a standard fruit-price benchmark in the food CPI basket.",
        "how_to_use": "Apple prices exhibit pronounced seasonal cycles (lowest post-harvest Oct-Dec, highest May-Jul); use YoY change to control for seasonality. Sustained price declines indicate oversupply or weak consumer demand in the fresh-fruit CPI sub-component.",
        "related_series": ["aCNPFBAA", "aCNPFPBA", "aCNCPIF"],
    },
    "aCNPFBAA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Bananas (Domestic)",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of domestic bananas across 50 monitored cities, published monthly by MOFCOM. Domestic banana supply is concentrated in Yunnan, Guangdong and Guangxi; prices are sensitive to typhoon damage and import competition.",
        "how_to_use": "Banana prices are a leading indicator of tropical fruit CPI volatility; spikes following Hainan or Yunnan weather disruptions typically reverse within 1-2 months. Compare with apple prices to assess broad fresh-fruit basket direction.",
        "related_series": ["aCNPFAPA", "aCNPFTMA", "aCNCPIF"],
    },
    "aCNPFBEA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Beef (Leg)",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of beef (leg cut) across 50 monitored cities, published monthly by MOFCOM. Beef consumption has grown rapidly with rising incomes; prices reflect both domestic cattle supply and import volumes.",
        "how_to_use": "Beef prices tend to trend structurally higher as dietary upgrading continues; watch for import policy changes (Brazil/Australia quotas) as drivers of sudden deflation. Compare with pork (aCNPFPBA) to assess meat-basket substitution dynamics.",
        "related_series": ["aCNPFMUA", "aCNPFPBA", "aCNCPIF"],
    },
    "aCNPFCEA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Celery",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of celery across 50 monitored cities, published monthly by MOFCOM. Celery is a staple Chinese vegetable with high-frequency price swings driven by planting cycles, weather and transport costs.",
        "how_to_use": "Celery price volatility is a proxy for the 'vegetable shock' component of food CPI; extreme moves (common in winter months) are largely supply-driven and typically mean-revert within 4-8 weeks.",
        "related_series": ["aCNPFCHA", "aCNPFTMA", "aCNCPIF"],
    },
    "aCNPFCBA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Chicken Breast",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of chicken breast across 50 monitored cities, published monthly by MOFCOM. Chicken breast is a premium cut whose pricing reflects rising protein demand and poultry industry consolidation.",
        "how_to_use": "Chicken breast price divergence from whole-chicken prices (aCNPFCCA) signals premiumisation trends in the poultry market; track alongside feed cost proxies (corn, soybean) for margin pressure signals.",
        "related_series": ["aCNPFCCA", "aCNPFDUA", "aCNCPIF"],
    },
    "aCNPFCCA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Frozen Fresh Chicken",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of frozen/fresh whole chicken across 50 monitored cities, published monthly by MOFCOM. Serves as the benchmark poultry price in the food CPI basket and tracks the full supply chain from farm to retail.",
        "how_to_use": "Whole chicken prices are sensitive to AI (avian influenza) outbreaks and seasonal demand spikes (Chinese New Year); compare with chicken breast (aCNPFCBA) spread to identify supply-chain margins and processing-industry health.",
        "related_series": ["aCNPFCBA", "aCNPFDUA", "aCNPFEGA"],
    },
    "aCNPFCHA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Chinese Cabbage",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of Chinese cabbage (bai cai) across 50 monitored cities, published monthly by MOFCOM. Chinese cabbage is the highest-volume vegetable in Chinese diets and a key weight in the food CPI vegetable sub-basket.",
        "how_to_use": "Chinese cabbage prices have extreme seasonal and weather sensitivity; the 'cabbage effect' can swing food CPI by 0.1-0.3 ppt in a single month. Use to flag weather-driven food CPI noise vs. structural demand shifts.",
        "related_series": ["aCNPFCEA", "aCNPFTMA", "aCNCPIF"],
    },
    "aCNPFCUA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Cucumbers",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of cucumbers across 50 monitored cities, published monthly by MOFCOM. Cucumbers are a year-round greenhouse vegetable with relatively stable but seasonally varying prices.",
        "how_to_use": "Cucumber prices are useful for tracking greenhouse vegetable inflation, which responds to energy costs (heating) and planting decisions; winter spikes signal input-cost pass-through rather than demand-pull.",
        "related_series": ["aCNPFCEA", "aCNPFCHA", "aCNCPIF"],
    },
    "aCNPFDUA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Frozen Fresh Duck",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of frozen/fresh whole duck across 50 monitored cities, published monthly by MOFCOM. Duck consumption is concentrated in southern China and is culturally important in festival-driven demand spikes.",
        "how_to_use": "Duck prices peak around Mid-Autumn and Chinese New Year festivals; monitor year-round baseline to distinguish seasonal from structural inflation in the poultry CPI component.",
        "related_series": ["aCNPFCCA", "aCNPFCBA", "aCNCPIF"],
    },
    "aCNPFEGA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Eggs (Fresh, Bulk)",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of fresh bulk eggs across 50 monitored cities, published monthly by MOFCOM. Eggs are a daily staple with tight supply-demand dynamics; price is a key food CPI input and a social stability concern for policymakers.",
        "how_to_use": "Egg prices follow a distinct seasonality (high in winter, low in autumn) and are highly sensitive to feed costs (corn/soybean); sustained moves above CNY 10/kg historically prompt market interventions to stabilise food CPI.",
        "related_series": ["aCNPFCCA", "aCNPFCBA", "aCNCPIF"],
    },
    "aCNPFFWA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Standard Wheat Flour",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of standard wheat flour across 50 monitored cities, published monthly by MOFCOM. Standard flour is a staple grain product; its price reflects both domestic wheat harvest outcomes and government grain reserve policies.",
        "how_to_use": "Flour prices are policy-managed (minimum purchase prices, state reserve releases) so tend to be stable; deviations from trend signal crop failures or international wheat price pass-through. Compare with strong flour (aCNPFFFA) for product-tier divergence.",
        "related_series": ["aCNPFFFA", "aCNPFRCA", "aCNCPIF"],
    },
    "aCNPFFFA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Strong (Bread) Flour",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of strong (high-gluten, bread-type) wheat flour across 50 monitored cities, published monthly by MOFCOM. Strong flour commands a premium over standard flour and tracks demand from bakery and processed-food sectors.",
        "how_to_use": "The spread between strong and standard flour prices reflects premiumisation of processed food demand; widening spread indicates rising middle-class food consumption upgrading, relevant to food services CPI.",
        "related_series": ["aCNPFFWA", "aCNPFRCA", "aCNCPIF"],
    },
    "aCNPFHTA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Hairtail Fish",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of hairtail (beltfish) across 50 monitored cities, published monthly by MOFCOM. Hairtail is one of China's most consumed marine fish; prices reflect East China Sea catch volumes and seasonal fishing bans.",
        "how_to_use": "Prices spike during the May-September East China Sea fishing moratorium and moderate post-ban; structural trends are driven by overfishing and aquaculture investment. Use as a proxy for marine protein CPI sub-component direction.",
        "related_series": ["aCNPFLCA", "aCNPFLGA", "aCNCPIF"],
    },
    "aCNPFKBA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Kidney Beans",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of kidney beans across 50 monitored cities, published monthly by MOFCOM. Kidney beans are a dry legume staple; prices are influenced by domestic harvest (Yunnan, Heilongjiang) and import availability.",
        "how_to_use": "Kidney bean prices are less volatile than fresh vegetables but track legume supply cycles; compare with soy products (aCNPFSPA) for broader protein-vegetable CPI basket assessment.",
        "related_series": ["aCNPFSPA", "aCNPFRCA", "aCNCPIF"],
    },
    "aCNPFLCA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Live Carp",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of live carp across 50 monitored cities, published monthly by MOFCOM. Live carp is the most widely consumed freshwater fish in China and a critical component of the food CPI aquatic products sub-basket.",
        "how_to_use": "Live carp prices are sensitive to summer flood disruptions to Yangtze/Pearl River aquaculture and to Spring Festival demand surges; sustained price weakness reflects excess aquaculture supply and soft consumer demand.",
        "related_series": ["aCNPFLGA", "aCNPFHTA", "aCNCPIF"],
    },
    "aCNPFLGA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Live Grass Carp",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of live grass carp across 50 monitored cities, published monthly by MOFCOM. Grass carp is a key pond-farming species and a lower-cost complement to common carp in China's freshwater aquaculture basket.",
        "how_to_use": "Track alongside live carp (aCNPFLCA) for cross-species price dynamics; divergence may reflect species-specific disease outbreaks or feed-cost differentials. Both series are key for modelling aquatic products CPI.",
        "related_series": ["aCNPFLCA", "aCNPFHTA", "aCNCPIF"],
    },
    "aCNPFMUA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Mutton (Leg)",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of mutton leg across 50 monitored cities, published monthly by MOFCOM. Mutton is a high-value meat concentrated in northern/northwestern China (Inner Mongolia, Xinjiang); demand spikes in winter months.",
        "how_to_use": "Mutton prices trend structurally higher due to slow herd expansion cycles (3+ year); winter demand seasonality is pronounced. Compare with beef (aCNPFBEA) for red-meat basket dynamics relevant to food CPI.",
        "related_series": ["aCNPFBEA", "aCNPFPBA", "aCNCPIF"],
    },
    "aCNPFPOA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Peanut Oil (Pressing)",
        "units": "CNY/500g, Monthly",
        "meaning": "Average retail price of pressing-grade peanut oil across 50 monitored cities, published monthly by MOFCOM. Peanut oil is the premium cooking oil in southern and central China; prices track peanut crop harvests and consumer preferences.",
        "how_to_use": "Peanut oil prices have lower sensitivity to global commodity cycles than soy/rapeseed oils; sharp divergence from soybean oil (aCNPFSBA) indicates domestic harvest disruption or shifting consumer demand in the edible oils CPI sub-basket.",
        "related_series": ["aCNPFSBA", "aCNPFRSA", "aCNCPIF"],
    },
    "aCNPFPBA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Pork Belly",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of pork belly across 50 monitored cities, published monthly by MOFCOM. Pork belly is the most popular pork cut in China and a bellwether for the 'pig cycle', the dominant driver of China's food CPI volatility.",
        "how_to_use": "Monitor alongside pork rump (aCNPFPRA) for full-carcass price dynamics. The pig cycle (18-24 month herd rebuild after ASF or profit-squeeze culling) can move headline CPI by 0.5-1.0 ppt; below CNY 20/kg signals herd oversupply.",
        "related_series": ["aCNPFPRA", "aCNPFBEA", "aCNCPIF"],
    },
    "aCNPFPRA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Pork Rump",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of pork rump (lean cut) across 50 monitored cities, published monthly by MOFCOM. Pork rump prices move closely with belly prices but reflect lean-meat demand, which tracks rising health-consciousness among urban consumers.",
        "how_to_use": "Track alongside belly (aCNPFPBA) to compute the lean/fatty spread — a widening premium for lean meat signals dietary upgrading. Both series together provide a robust pig-cycle inflation signal for food CPI modelling.",
        "related_series": ["aCNPFPBA", "aCNPFBEA", "aCNCPIF"],
    },
    "aCNPFPTA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Potatoes",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of potatoes across 50 monitored cities, published monthly by MOFCOM. Potatoes are a major staple crop in northern and southwestern China; prices reflect both domestic production (Gansu, Inner Mongolia, Yunnan) and seasonal storage dynamics.",
        "how_to_use": "Potato prices follow a clear seasonal cycle (low post-autumn harvest, high in spring/early summer); use YoY data to isolate structural supply trends. Elevated prices in winter signal cold-storage shortages or crop failure.",
        "related_series": ["aCNPFCHA", "aCNPFTMA", "aCNCPIF"],
    },
    "aCNPFRSA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Rapeseed Oil (Grade 1 Bulk)",
        "units": "CNY/500g, Monthly",
        "meaning": "Average retail price of Grade 1 bulk rapeseed oil across 50 monitored cities, published monthly by MOFCOM. Rapeseed oil is the dominant cooking oil in central and southwestern China; prices link domestic canola harvests to global oilseed markets.",
        "how_to_use": "Rapeseed oil prices are more globally linked than peanut oil — track with international canola futures and Canadian crop reports. Divergence from soybean oil (aCNPFSBA) signals domestic supply disruption vs. global feedstock shifts.",
        "related_series": ["aCNPFSBA", "aCNPFPOA", "aCNCPIF"],
    },
    "aCNPFRAA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Rapeseed (Rapes)",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of rapeseed (whole seed/crushable rapes) across 50 monitored cities, published monthly by MOFCOM. Farm-gate rapeseed prices are a direct agricultural input cost feeding into cooking oil production.",
        "how_to_use": "Use rapeseed prices as a leading indicator for rapeseed oil inflation (aCNPFRSA) with a ~1-month processing lag; sustained below-minimum-purchase-price readings signal policy intervention risk or structural supply surplus.",
        "related_series": ["aCNPFRSA", "aCNPFSBA", "aCNCPIF"],
    },
    "aCNPFRCA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Japonica Rice",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of japonica (short-grain) rice across 50 monitored cities, published monthly by MOFCOM. Japonica rice is the premium rice variety consumed in northern and northeastern China; prices reflect Heilongjiang/Jilin harvests.",
        "how_to_use": "Japonica prices are sticky due to government minimum purchase prices and state reserve buffer stocks; sharp moves indicate harvest shortfalls or reserve policy changes. Compare with flour (aCNPFFWA) for grain staple inflation breadth.",
        "related_series": ["aCNPFFWA", "aCNPFFFA", "aCNCPIF"],
    },
    "aCNPFSPA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Tofu (Bean Curd)",
        "units": "CNY/500g, Monthly",
        "meaning": "Average retail price of tofu (bean curd) across 50 monitored cities, published monthly by MOFCOM. Tofu is a daily protein staple; its price tracks soybean input costs and local manufacturing competition in the soy products CPI sub-basket.",
        "how_to_use": "Tofu prices lag soybean prices by ~1-2 months via processing; compare with soybean oil (aCNPFSBA) to assess how soybean crush economics pass through to consumer soy products inflation.",
        "related_series": ["aCNPFSBA", "aCNPFKBA", "aCNCPIF"],
    },
    "aCNPFSBA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Soybean Oil (5L Barrel)",
        "units": "CNY/5L, Monthly",
        "meaning": "Average retail price of soybean oil (5-litre barrel) across 50 monitored cities, published monthly by MOFCOM. Soybean oil is the highest-volume cooking oil in China; prices are tightly linked to US/Brazilian soybean crop forecasts and crush margins.",
        "how_to_use": "Use alongside Chicago soybean futures as a global-to-domestic price transmission monitor; a narrowing spread between soybean oil and rapeseed oil prices (aCNPFRSA) signals convergence of domestic oilseed supply conditions.",
        "related_series": ["aCNPFRSA", "aCNPFPOA", "aCNCPIF"],
    },
    "aCNPFTMA": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "50-City Food Price — Tomatoes",
        "units": "CNY/kg, Monthly",
        "meaning": "Average retail price of tomatoes across 50 monitored cities, published monthly by MOFCOM. Tomatoes are a staple cooking vegetable; prices exhibit strong seasonality driven by outdoor vs. greenhouse production cycles.",
        "how_to_use": "Tomato prices are a high-frequency CPI signal for vegetable inflation: winter peaks reflect greenhouse heating costs, summer lows reflect outdoor harvest gluts. Sharp winter spikes can add 0.05-0.1 ppt to monthly food CPI.",
        "related_series": ["aCNPFCEA", "aCNPFCHA", "aCNCPIF"],
    },
    "aCNCONPRSF": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Headline Level",
        "units": "Index (100=Base Year)",
        "meaning": "China's headline Consumer Price Index level, published monthly by the National Bureau of Statistics (NBS). The broadest measure of retail consumer price changes covering the full basket of goods and services across urban and rural areas.",
        "how_to_use": "Use as the primary inflation reference for China; compare with PPI (aCNCPPIYE/A) to assess deflation transmission risk. Sub-0 YoY readings since late 2023 confirm deflationary pressure requiring PBoC easing.",
        "related_series": ["aCNCPIYY", "aCNCPIMAR", "aCNCCORYE/A"],
    },
    "aCNCPI": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Average Index",
        "units": "Index, Average",
        "meaning": "China CPI average index (period average level), published monthly by NBS. Represents the average price level across the survey period rather than a point-in-time reading, smoothing intra-period volatility.",
        "how_to_use": "Use the average index for contract deflation, wage escalation clauses, and annual inflation comparisons; the point-in-time index (aCNCONPRSF) is preferable for real-time policy and market analysis.",
        "related_series": ["aCNCONPRSF", "aCNCPIYY", "aCNCPIF"],
    },
    "aCNCPIYY": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — YoY Change (Price Index)",
        "units": "Percent, YoY",
        "meaning": "China's headline CPI year-on-year percentage change (price index form), published monthly by NBS. The primary market-moving inflation indicator tracked by PBoC, markets and international institutions.",
        "how_to_use": "Key threshold: below 0% triggers deflation-concern narrative; the PBoC's informal comfort zone is 1-3%. Sustained sub-1% prints since 2023 reflect post-COVID demand gap and property sector deflation — watch for inflection above 1% as recovery signal.",
        "related_series": ["aCNCONPRSF", "aCNCPIMAR", "aCNCCORYE/A"],
    },
    "aCNCPIAR": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — YoY Change (Average)",
        "units": "Percent, YoY",
        "meaning": "China CPI year-on-year change calculated on the average index basis, published by NBS. Provides a smoother YoY inflation reading than the point-in-time series by averaging prices across the period.",
        "how_to_use": "Use for annual budget planning and policy analysis requiring smoothed inflation estimates; for monthly market positioning or PBoC reaction-function analysis, prefer the point-in-time YoY series (aCNCPIYY).",
        "related_series": ["aCNCPIYY", "aCNCONPRSF", "aCNCPIMAR"],
    },
    "aCNCPIMAR": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — MoM Change",
        "units": "Percent, MoM",
        "meaning": "China's headline CPI month-on-month (period-on-period) percentage change, published monthly by NBS. Provides the highest-frequency read on short-term price momentum before seasonal adjustment.",
        "how_to_use": "MoM CPI has strong seasonal patterns (January/February typically +0.5-1.0% for CNY, October-November typically negative); use seasonally adjusted estimates or SAAR transformations for underlying momentum analysis. Watch for 3+ consecutive negative MoM prints as a deflation acceleration signal.",
        "related_series": ["aCNCPICPIP", "aCNCPIYY", "aCNCONPRSF"],
    },
    "aCNCPICPIP": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — MoM Change (Alt Series)",
        "units": "Percent, MoM",
        "meaning": "Alternative monthly period-on-period CPI change series for China, published by NBS. This series may cover a different sub-population, vintage, or calculation methodology vs. aCNCPIMAR — verify source documentation for exact scope.",
        "how_to_use": "Cross-check against aCNCPIMAR to validate MoM CPI readings; persistent divergence between the two series may indicate vintage revision effects or sub-index vs. headline composition differences.",
        "related_series": ["aCNCPIMAR", "aCNCPIYY", "aCNCONPRSF"],
    },
    "aCNCPIC": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Clothing",
        "units": "Index, Average",
        "meaning": "China CPI for the Clothing sub-category (average index), published monthly by NBS. Tracks retail price changes for garments, footwear and related accessories — one of the eight major CPI sub-categories.",
        "how_to_use": "Clothing CPI is structurally disinflationary in China due to domestic overcapacity and e-commerce competition; sustained deflation here is normal. Cyclical spikes typically reflect raw material (cotton, polyester) cost shocks with 2-3 month lag.",
        "related_series": ["aCNCPIH", "aCNCPIM", "aCNCPIF"],
    },
    "aCNCPDURAF/C": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Consumer Goods",
        "units": "Index",
        "meaning": "China CPI for consumer (durable) goods as a broad category, published by NBS. Aggregates price changes across tangible goods purchased by households, excluding services — an important split in China's bifurcated goods-deflation/services-inflation environment.",
        "how_to_use": "Consumer goods CPI has been in persistent deflation since 2022, driven by e-commerce price competition, weak property demand, and EV/appliance price wars; compare with services CPI to quantify the goods-services inflation split central to PBoC analysis.",
        "related_series": ["aCNCPNDURF/C", "aCNCPNOSSF/C", "aCNCCORYE/A"],
    },
    "aCNCPIF": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Food",
        "units": "Index, Average",
        "meaning": "China CPI for the Food sub-category (average index), published monthly by NBS. At ~21% of the CPI basket, food is the largest single sub-component and the primary driver of China's headline CPI volatility through pig cycle and vegetable price swings.",
        "how_to_use": "Food CPI is the most watched NBS CPI sub-component; a swing of 1% in food CPI moves headline CPI by ~0.21 ppt. Monitor pork (aCNPFPBA) and vegetable prices as the two highest-volatility food sub-inputs.",
        "related_series": ["aCNCPIFYY", "aCNPFPBA", "aCNCCORYE/A"],
    },
    "aCNCPIFYY": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Food YoY",
        "units": "Percent, YoY",
        "meaning": "China's food CPI year-on-year percentage change, published monthly by NBS. The single most important sub-component YoY series for explaining monthly headline CPI surprises — food accounts for ~21% of the basket.",
        "how_to_use": "Food CPI YoY swings of ±3% are common and are the primary source of headline CPI beats/misses vs. consensus. Decompose into pork (aCNPFPBA/aCNPFPRA), fresh vegetables (aCNPFCHA) and grains to attribute the move.",
        "related_series": ["aCNCPIF", "aCNPFPBA", "aCNCPIYY"],
    },
    "aCNCPIM": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Health Care & Medical Services",
        "units": "Index, Average",
        "meaning": "China CPI for the Health Care and Medical Services sub-category, published monthly by NBS. This component (~8% weight) tracks hospital fees, drug prices and outpatient service costs — one of China's stickiest CPI components.",
        "how_to_use": "Medical services CPI is among the most structurally elevated CPI sub-categories in China due to ageing demographics and healthcare reform; it rarely deflates even in broader deflationary environments, supporting core CPI floors.",
        "related_series": ["aCNCPNMDTF/C", "aCNCPIM", "aCNCCORYE/A"],
    },
    "aCNCPNDURF/C": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Home Appliances",
        "units": "Index",
        "meaning": "China CPI for home appliances (household durable goods such as white goods, electronics), published by NBS. Tracks retail price trends for major consumer electronics and appliances — a sub-component facing structural price war deflation.",
        "how_to_use": "Home appliance CPI is persistently deflationary in China (-1% to -3% YoY typical) due to manufacturing overcapacity, online price competition and subsidy-driven upgrade cycles; deep deflation here is a drag on headline CPI and corporate margins.",
        "related_series": ["aCNCPDURAF/C", "aCNCPIH", "aCNCPIC"],
    },
    "aCNCPIH": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Household Facilities & Services",
        "units": "Index, Average",
        "meaning": "China CPI for Household Facilities, Articles and Services (furniture, furnishings, household maintenance services), published monthly by NBS. Tracks price changes in goods and services related to home setup and maintenance.",
        "how_to_use": "This sub-component is closely linked to property sector activity; sustained deflation here since 2022 reflects the housing downturn reducing furniture and renovation demand. Recovery signals from this series often lag property transaction data by 2-3 months.",
        "related_series": ["aCNCPNOSSF/C", "aCNCPNDURF/C", "aCNCPIC"],
    },
    "aCNCPNOSSF/C": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Household Services",
        "units": "Index",
        "meaning": "China CPI for Household Services (domestic helpers, cleaning, repair, and maintenance services), published by NBS. This is a labour-intensive services sub-category, making it a useful proxy for wage-driven services inflation in China.",
        "how_to_use": "Household services CPI tends to be one of the more resilient inflation components given labour cost stickiness; compare trend with healthcare services (aCNCPIM) and education to assess whether China's services CPI can sustain a floor even amid broader deflation.",
        "related_series": ["aCNCPIH", "aCNCPNMDTF/C", "aCNCCORYE/A"],
    },
    "aCNCPNMDTF/C": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "CPI — Medical Services",
        "units": "Index",
        "meaning": "China CPI for Medical Services specifically (physician consultations, hospital procedures, nursing care), distinct from the broader healthcare sub-index (aCNCPIM). Published by NBS, this series isolates the services component of healthcare inflation.",
        "how_to_use": "Medical services CPI is structurally sticky upward due to state-directed pricing reform and ageing demographics; it serves as an anchor for core services inflation even when goods deflation deepens. Use alongside household services to assess labour-market pass-through in services pricing.",
        "related_series": ["aCNCPIM", "aCNCPNOSSF/C", "aCNCCORYE/A"],
    },
}
