param(
  [int]$MaxTodos = 8
)

$ErrorActionPreference = "Stop"

$homeDir = [Environment]::GetFolderPath("UserProfile")
$workspaceDir = Join-Path $homeDir ".openclaw\workspace"
$skillScript = Join-Path $workspaceDir "skills\legion-brain\scripts\brain-action.mjs"
$contextPath = Join-Path $workspaceDir "LEGION_CONTEXT.md"
$logDir = Join-Path $homeDir ".openclaw\logs"
$logPath = Join-Path $logDir "legion-brain-sync.log"

New-Item -ItemType Directory -Force -Path $logDir | Out-Null

function Write-SyncLog {
  param([string]$Message)
  $stamp = (Get-Date).ToString("s")
  Add-Content -LiteralPath $logPath -Value "[$stamp] $Message"
}

try {
  if (-not (Test-Path -LiteralPath $skillScript)) {
    throw "brain-action script missing at $skillScript"
  }

  $jsonArgs = "{}"
  if ($MaxTodos -ne 8) {
    Write-SyncLog "MaxTodos override ignored by PowerShell-safe sync path; using script default"
  }
  $raw = node $skillScript brain.context_sync $jsonArgs
  if ($LASTEXITCODE -ne 0) {
    throw "brain.context_sync failed with exit code $LASTEXITCODE"
  }

  $parsed = $raw | ConvertFrom-Json
  if (-not $parsed.markdown) {
    throw "brain.context_sync returned no markdown"
  }

  $content = @(
    "<!-- Auto-generated by legion-brain-sync.ps1. Do not put secrets here. -->",
    $parsed.markdown,
    "",
    "## Sync Metadata",
    "",
    "- Source: Supabase brain schema",
    "- Script: C:\Users\DELL\.openclaw\ops\legion-brain-sync.ps1",
    "- This file is startup cache only; brain remains authority."
  ) -join "`n"

  Set-Content -LiteralPath $contextPath -Value $content -Encoding UTF8
  Write-SyncLog "synced context to $contextPath"
  exit 0
} catch {
  Write-SyncLog "sync failed: $($_.Exception.Message)"
  throw
}
