"""Hand-curated content for China RICs — Batch 08a (CPI Sub-Components, part 1)."""

TIER1: dict[str, dict] = {
    "aCNCNOULM": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Commodity Prices — Chemical/Energy",
        "units": "CNY per unit, Monthly",
        "meaning": "Average domestic market price of oil and chemical products including sodium cyanide (import), compiled monthly. Tracks upstream chemical input costs that feed through to manufacturing CPI and PPI.",
        "how_to_use": "Monitor for cost-push pressure on PPI non-metal chemicals; divergence from global crude benchmarks signals domestic supply-demand imbalance or FX pass-through.",
        "related_series": ["aCNCNVRGRM", "aCNPPIAR", "aCNCCPIYE/A"],
    },
    "aCNCNZZTS": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Commodity Prices — Energy",
        "units": "USD per MMBtu (or CNY/tonne)",
        "meaning": "Average import price for liquefied natural gas (LNG) into China, reflecting spot and term contract settlement values. China is the world's largest LNG importer; import price feeds domestic gas utility tariffs and industrial energy costs.",
        "how_to_use": "Rising LNG import prices compress margins for gas-intensive industries and push up utility CPI sub-components; compare against JKM spot prices for arbitrage signals.",
        "related_series": ["aCNCNOULM", "aCNPPIAR", "aCNCCPIYE/A"],
    },
    "aCNCNUSGC": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Commodity Prices — Agricultural Imports",
        "units": "USD per tonne (CIF China)",
        "meaning": "Average import price for palm oil arriving in China, a key cooking-oil input covering roughly 20% of edible-oil consumption. Palm oil prices from Malaysia and Indonesia pass through directly to CPI food sub-component edible oils.",
        "how_to_use": "Watch for seasonal peaks (Ramadan demand, La Nina crop impact) feeding into China edible-oil retail CPI with a 1-2 month lag; also a proxy for food-import inflation pressure on trade balance.",
        "related_series": ["aCNCCPIYE/A", "aCNCNOULM", "aCNPPIAR"],
    },
    "aCNCNVRGRM": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Commodity Prices — Steel",
        "units": "CNY per tonne, Monthly",
        "meaning": "China steel price index for rebar (construction-grade reinforcement bar), the most widely traded steel contract on Shanghai Futures Exchange. Rebar prices are a leading indicator of construction activity and housing investment.",
        "how_to_use": "Rebar price trends lead NBS land price indices by 1-3 months; sharp drops signal property sector stress feeding deflationary pressure; also watch vs SHFE DCE futures spread.",
        "related_series": ["aCNCNCLPXQ", "aCNPPIAR", "aCNCCPIYE/A"],
    },
    "aCNCNCLPXQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — National",
        "units": "CNY per sq m, Quarterly",
        "meaning": "National aggregate land price level index compiled by the China Land Price Information Service Platform (CLPIS), covering residential, commercial, and industrial use parcels transacted at government auctions. Land prices are the key input cost for property developers.",
        "how_to_use": "Declining land prices signal developer funding stress and reduced local government revenue; sustained fall below 2020 levels reinforces PBoC easing thesis and dampens housing CPI.",
        "related_series": ["aCNCNDAXFQ", "aCNCNDELJQ", "aCNCCPIYE/A"],
    },
    "aCNCNDAXFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Bohai Economic Zone",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level index for the Bohai Economic Zone (Beijing-Tianjin-Hebei region plus Liaoning/Shandong coasts), a major industrial and logistics corridor. Regional land price reflects demand from manufacturing investment and tier-1 city spillover.",
        "how_to_use": "Bohai land prices move with northern China industrial cycles; use alongside national index to assess regional divergence and targeted policy easing in the BTH integration zone.",
        "related_series": ["aCNCNCLPXQ", "aCNCNDELJQ", "aCNCNDBDIQ"],
    },
    "aCNCNDBDIQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Central South",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for China's Central South region (Hunan, Hubei, Guangdong, Guangxi, Hainan), encompassing Pearl River Delta adjacents and interior provincial cities. Captures rapid urbanization-driven land demand in a high-growth belt.",
        "how_to_use": "Divergence between Central South and East/Bohai indices flags regional property policy effectiveness; Guangdong urban-rural land reform can cause step changes.",
        "related_series": ["aCNCNCLPXQ", "aCNCNSBYJQ", "aCNCNKTFDQ"],
    },
    "aCNCNGZKN/A": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — East Area",
        "units": "CNY per sq m, Annual/Quarterly",
        "meaning": "Land price level for the East area (Yangtze River Delta: Shanghai, Jiangsu, Zhejiang, Anhui, Fujian), China's most economically dense coastal region. East area land prices command the highest national premiums and are most sensitive to property policy tightening.",
        "how_to_use": "East area land price is a bellwether for national trend; YRD city-cluster policy relaxation or tightening shows up here first, with CPI housing sub-component following 2-4 quarters later.",
        "related_series": ["aCNCNCLPXQ", "aCNCNDZQFQ", "aCNCNKTFDQ"],
    },
    "aCNCNXZFYQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Fushun City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level index for Fushun city (Liaoning province, Northeast China), a former heavy-industry base undergoing economic restructuring. Reflects micro-level land-market conditions in a tier-3 rust-belt city.",
        "how_to_use": "Fushun's persistently weak land prices illustrate population-outflow deflation dynamics typical of Northeast cities; contrast against Bohai zone aggregate to gauge regional divergence.",
        "related_series": ["aCNCNQKJUQ", "aCNCNDAXFQ", "aCNCNCLPXQ"],
    },
    "aCNCNQDTQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Fushun City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Fushun city land price level at current (nominal) prices, as reported by the China Land Price Information Service Platform. The current-price series captures nominal transaction values without deflation, useful for developer cost accounting.",
        "how_to_use": "Pair with the constant-price Fushun series (aCNCNXZFYQ) to derive implicit land price deflator for the city; large gap signals elevated local inflation even as real land demand is flat.",
        "related_series": ["aCNCNXZFYQ", "aCNCNFWBRQ", "aCNCNCLPXQ"],
    },
    "aCNCNQKJUQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Fuxin City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Fuxin city (Liaoning province), another Northeast coal-dependent city with long-term structural decline. Tracks land demand from limited industrial redevelopment and government-led urban renewal.",
        "how_to_use": "Fuxin's land prices typically lag national upturns by 6-12 months; use as a lagging indicator of whether central government stimulus is reaching distressed smaller cities.",
        "related_series": ["aCNCNXZFYQ", "aCNCNFWBRQ", "aCNCNDAXFQ"],
    },
    "aCNCNFWBRQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Fuxin City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Fuxin city land prices at current nominal values from CLPIS quarterly surveys. Nominal series includes local price-level changes relevant for municipal finance and land revenue forecasting.",
        "how_to_use": "Compare nominal vs. real series to assess how much of Fuxin land revenue growth is price vs. volume; key for gauging local government fiscal stress in Northeast China.",
        "related_series": ["aCNCNQKJUQ", "aCNCNQDTQ", "aCNCNCLPXQ"],
    },
    "aCNCNWKYAQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Handan City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Handan city (Hebei province, BTH region), a major steel-producing city whose land market is closely tied to steelmaker consolidation and environmental policy. Tracks real land demand in a transition-economy tier-3 city.",
        "how_to_use": "Handan land prices react to steel-capacity cuts and BTH integration policy; rising prices alongside rebar index (aCNCNVRGRM) confirm industrial-zone land demand is re-emerging.",
        "related_series": ["aCNCNVRGRM", "aCNCNDAXFQ", "aCNCNCLPXQ"],
    },
    "aCNCNFLNKQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Handan City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Handan city land prices at current (nominal) prices, capturing actual transaction values in CNY. Allows direct comparison with developer land bank costs and local government land revenue in nominal terms.",
        "how_to_use": "Use alongside constant-price Handan series for real price deflation estimates; gap between nominal and real signals whether local CPI is elevated relative to land market fundamentals.",
        "related_series": ["aCNCNWKYAQ", "aCNCNACMUQ", "aCNCNDAXFQ"],
    },
    "aCNCNGAQLQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Hegang City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Hegang city (Heilongjiang province), which made headlines in 2021 for house prices as low as CNY 10,000-20,000 per unit — among the cheapest in China. Captures extreme deflation in a shrinking coal-mining city.",
        "how_to_use": "Hegang is a tail-risk reference for what population-outflow deflation looks like at its extreme; useful for scenario analysis of rust-belt city property risk in Northeast portfolio exposure.",
        "related_series": ["aCNCNXZFYQ", "aCNCNQKJUQ", "aCNCNDAXFQ"],
    },
    "aCNCNTOPBQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Hegang City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Hegang city land prices at current nominal values, representing minimum land-market activity in one of China's most distressed urban economies. Nominal values may remain near zero or show very small absolute changes.",
        "how_to_use": "Pair with aCNCNGAQLQ to monitor whether government-directed redevelopment programmes are translating into real or merely nominal land price recovery in Hegang.",
        "related_series": ["aCNCNGAQLQ", "aCNCNUPGIQ", "aCNCNDAXFQ"],
    },
    "aCNCNKUWMQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Hengyang City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Hengyang city (Hunan province, Central South), a mid-size inland city with growing manufacturing investment from coastal industry relocation. Land prices reflect urbanisation-driven demand from migrant workers and industrial parks.",
        "how_to_use": "Rising Hengyang land prices alongside Central South regional index signal successful inland industry relocation absorbing coastal deflation; watch for acceleration post-stimulus rounds.",
        "related_series": ["aCNCNDBDIQ", "aCNCNCLPXQ", "aCNCNZGYQ"],
    },
    "aCNCNZGYQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Hengyang City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Hengyang city land prices at current nominal prices from CLPIS, capturing developer acquisition costs and local fiscal land revenue in CNY terms. Nominal series is used in local government budget and land auction reporting.",
        "how_to_use": "Compare to constant-price series (aCNCNKUWMQ) to assess local price inflation; Hengyang nominal land prices rising faster than real suggest cost-push pressures on new housing supply.",
        "related_series": ["aCNCNKUWMQ", "aCNCNEAUTQ", "aCNCNDBDIQ"],
    },
    "aCNCNKTFDQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Huadong Region",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for the Huadong (East China) region from CLPIS — broadly covering Shanghai, Jiangsu, Zhejiang, Fujian. As China's wealthiest coastal cluster, Huadong land prices are the highest nationally and the most policy-sensitive.",
        "how_to_use": "Huadong land prices are a primary input for developer margin models; a 10% quarterly fall signals material developer distress in the Yangtze Delta cluster, directly impacting housing CPI rents.",
        "related_series": ["aCNCNGZKN/A", "aCNCNDZQFQ", "aCNCNCLPXQ"],
    },
    "aCNCNFZZHQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Huaibei City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Huaibei city (Anhui province), a coal-mining city transitioning to manufacturing and logistics. Located in the Yangtze River Delta extended hinterland, its land market is supported by YRD integration policy.",
        "how_to_use": "Track alongside Huaibei current-price series for real demand signals; YRD integration upgrades and high-speed rail connectivity announcements tend to produce step-changes in Huaibei land prices.",
        "related_series": ["aCNCNLQAZQ", "aCNCNKTFDQ", "aCNCNCLPXQ"],
    },
    "aCNCNLQAZQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Huaibei City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Huaibei city land prices at current nominal prices, reporting actual auction transaction values used for local government fiscal planning. Nominal values reflect both real demand shifts and general price-level changes in Anhui.",
        "how_to_use": "Paired with constant-price aCNCNFZZHQ, the nominal-real gap offers an implicit local land price deflator; useful for granular Anhui property market analysis.",
        "related_series": ["aCNCNFZZHQ", "aCNCNHCSUQ", "aCNCNKTFDQ"],
    },
    "aCNCNIDZRQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Huainan City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Huainan city (Anhui province), historically a major coal-production centre now diversifying into data centres and clean energy. Real land price tracks structural economic transition in a mid-Yangtze city.",
        "how_to_use": "Rising real land prices in Huainan amid coal industry decline signal successful diversification; compare with Huaibei for Anhui intra-province land market dynamics.",
        "related_series": ["aCNCNFKSCQ", "aCNCNFZZHQ", "aCNCNKTFDQ"],
    },
    "aCNCNFKSCQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Huainan City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Huainan city land prices at current (nominal) values from CLPIS quarterly survey. Captures nominal transaction-price trends relevant for local developer cost and government revenue accounting in Anhui.",
        "how_to_use": "Use alongside aCNCNIDZRQ to compute Huainan land price inflation rate; sustained nominal-real convergence confirms deflationary pressure from coal-sector demand retreat.",
        "related_series": ["aCNCNIDZRQ", "aCNCNLQAZQ", "aCNCNKTFDQ"],
    },
    "aCNCNYTAGQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Jixi City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Jixi city (Heilongjiang province, Northeast China), a coal and graphite mining hub facing long-term population outflow. Tracks land demand conditions in one of China's most economically challenged rust-belt cities.",
        "how_to_use": "Jixi land prices, like Hegang, serve as a stress-test benchmark for Northeast deflation; persistent declines confirm structural headwinds that require central transfer payments to sustain local fiscal health.",
        "related_series": ["aCNCNQAUZQ", "aCNCNGAQLQ", "aCNCNDAXFQ"],
    },
    "aCNCNQAUZQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Jixi City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Jixi city land prices at current nominal values, from CLPIS quarterly reports. Given Jixi's weak real demand, nominal series may show near-zero or declining trends reflecting both real and price deflation.",
        "how_to_use": "Cross-reference with real-price Jixi series (aCNCNYTAGQ) to isolate price inflation from volume; compare across Heilongjiang cities to assess province-wide property market stress.",
        "related_series": ["aCNCNYTAGQ", "aCNCNTOPBQ", "aCNCNDAXFQ"],
    },
    "aCNCNDELJQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — North China",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for North China (Beijing, Tianjin, Hebei, Shanxi, Inner Mongolia), a region combining the nation's political capital premium with heavy industrial cities. Captures differentiated demand across tier-1 (Beijing) and industrial cities.",
        "how_to_use": "North China land price is heavily distorted by Beijing's administrative land-supply restrictions; strip out Beijing effects to assess Hebei/Inner Mongolia industrial land dynamics relative to national cycle.",
        "related_series": ["aCNCNDAXFQ", "aCNCNCLPXQ", "aCNCNDIDQ"],
    },
    "aCNCNDIDQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Northeast Area",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Northeast China (Liaoning, Jilin, Heilongjiang), the historic rust-belt region with chronic population outflow and weak demand. Northeast aggregate land prices have trended down since 2014 in real terms.",
        "how_to_use": "Northeast land prices are a leading indicator of regional property developer distress; sustained drops signal deeper fiscal stress for Liaoning/Jilin/Heilongjiang local governments reliant on land-sale revenue.",
        "related_series": ["aCNCNDAXFQ", "aCNCNGAQLQ", "aCNCNDELJQ"],
    },
    "aCNCNQHMPQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Northwest Region",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Northwest China (Shaanxi, Gansu, Qinghai, Ningxia, Xinjiang), a resource-rich but sparsely populated region whose land market is driven by energy and Belt-and-Road infrastructure investment.",
        "how_to_use": "Northwest land prices respond to energy commodity cycles and central policy for western development (Xi Bu Da Kai Fa); lag coastal regions by 2-4 quarters in policy transmission.",
        "related_series": ["aCNCNLRKNQ", "aCNCNFVIQ", "aCNCNCLPXQ"],
    },
    "aCNCNSBYJQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Pearl River Delta Economic Zone",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for the Pearl River Delta (PRD) Economic Zone (Guangzhou, Shenzhen, Dongguan, Foshan, etc.), China's export manufacturing and tech hub. PRD land prices reflect global supply-chain dynamics and tech-sector real-estate demand.",
        "how_to_use": "PRD land prices lead South China housing CPI; Shenzhen policy experiments (property tax pilots, land reform) often precede national rollout — monitor for early signals of structural property policy change.",
        "related_series": ["aCNCNMYWKQ", "aCNCNDBDIQ", "aCNCNCLPXQ"],
    },
    "aCNCNMYWKQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Pearl River Delta (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Pearl River Delta land prices at current (nominal) prices, capturing actual developer acquisition costs and government land-sale revenues in Guangdong's core economic zone at prevailing nominal values.",
        "how_to_use": "PRD nominal land prices are directly visible in Guangdong local government fiscal data; divergence from real price series signals price inflation or deflation within the zone's property cycle.",
        "related_series": ["aCNCNSBYJQ", "aCNCNMSQPQ", "aCNCNDBDIQ"],
    },
    "aCNCNSCXIQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Qiqihar City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Qiqihar city (Heilongjiang province), a heavy-machinery and agricultural processing centre in China's grain belt. Land prices reflect both industrial demand and agricultural land-use conversion dynamics.",
        "how_to_use": "Monitor Qiqihar land prices alongside Northeast regional aggregate; agricultural policy allowing rural collective land transfer can produce step-changes in peri-urban land prices here.",
        "related_series": ["aCNCNUEXUQ", "aCNCNDAXFQ", "aCNCNDIDQ"],
    },
    "aCNCNUEXUQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Qiqihar City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Qiqihar city land prices at current nominal prices from CLPIS. Reflects actual CNY transaction values in the city's land auction market, used for local revenue and developer cost accounting.",
        "how_to_use": "Pair with aCNCNSCXIQ real-price series; if nominal prices rise faster than real, it suggests local price inflation rather than genuine demand recovery in Qiqihar.",
        "related_series": ["aCNCNSCXIQ", "aCNCNQAUZQ", "aCNCNDAXFQ"],
    },
    "aCNCNMSQPQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Shunde District",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Shunde District (Foshan city, Guangdong), one of China's wealthiest county-level economies and home to major appliance manufacturers (Midea, Galanz). Shunde land prices reflect premium demand from high-value manufacturing.",
        "how_to_use": "Shunde is a bellwether for Pearl River Delta industrial land demand; rising prices here alongside PRD aggregate confirm manufacturing investment cycle in South China, influencing CPI through import-competing goods.",
        "related_series": ["aCNCNSBYJQ", "aCNCNMYWKQ", "aCNCNDBDIQ"],
    },
    "aCNCNFVIQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Southwest Region",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Southwest China (Sichuan, Yunnan, Guizhou, Chongqing, Tibet), a region experiencing rapid urbanisation around Chengdu-Chongqing economic circle. Land prices here outperformed national average in 2020-22 on strong infrastructure spending.",
        "how_to_use": "Southwest land prices are a proxy for Chengdu-Chongqing dual-city circle success; rising prices confirm policy-directed urban expansion absorbing coastal industrial relocation.",
        "related_series": ["aCNCNLRKNQ", "aCNCNCLPXQ", "aCNCNQHMPQ"],
    },
    "aCNCNLRKNQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Western Region",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Broad Western China land price level index, encompassing both Southwest and Northwest sub-regions. Captures the aggregate effect of western development (XiBuDaKaiFa) policies and Belt-and-Road corridor investment on land values.",
        "how_to_use": "Compare Western vs Eastern land price spread to assess policy-driven convergence; narrowing gap indicates successful fiscal transfer and investment stimulus reaching interior provinces.",
        "related_series": ["aCNCNFVIQ", "aCNCNQHMPQ", "aCNCNCLPXQ"],
    },
    "aCNCNSWSFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Xinxiang City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Xinxiang city (Henan province, Central Plains), an industrial city in the Zhengzhou metropolitan area corridor. Land prices track Zhengzhou spillover demand and Central Plains manufacturing investment.",
        "how_to_use": "Rising Xinxiang land prices signal successful Zhengzhou metropolitan expansion; monitor against provincial aggregate for Central Plains development policy effectiveness.",
        "related_series": ["aCNCNEAEX/A", "aCNCNDBEQ", "aCNCNCLPXQ"],
    },
    "aCNCNEAEX/A": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Xinxiang City (Current Prices)",
        "units": "CNY per sq m, Annual/Quarterly",
        "meaning": "Xinxiang city land prices at current nominal values, reporting actual CNY transaction prices from government land auctions in this Henan city. Nominal series reflects prevailing price levels for developer budget and municipal revenue purposes.",
        "how_to_use": "Pair with aCNCNSWSFQ constant-price series; widening nominal-real gap in Xinxiang indicates local price inflation driven by construction cost increases in Central China.",
        "related_series": ["aCNCNSWSFQ", "aCNCNFLNKQ", "aCNCNDBDIQ"],
    },
    "aCNCNDZQFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Yangtze River Delta Economic Zone",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for the Yangtze River Delta (YRD) Economic Zone (Shanghai, Jiangsu, Zhejiang, Anhui), China's most integrated regional economy. YRD land prices command a structural premium over national average due to supply constraints and high productivity.",
        "how_to_use": "YRD land prices feed directly into Shanghai housing cost and consumer rents in the CPI basket; a 5%+ quarterly decline is a strong signal of developer deleveraging affecting East China housing CPI.",
        "related_series": ["aCNCNKTFDQ", "aCNCNGZKN/A", "aCNCNCLPXQ"],
    },
    "aCNCNRQZQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Yichun City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land price level for Yichun city (Heilongjiang province), a forestry and tourism city in Northeast China with severely limited industrial base. One of the lower land price markets in China reflecting population decline and limited urban demand.",
        "how_to_use": "Yichun prices provide the low-end anchor for Northeast China land market analysis; sustained near-zero values confirm that fiscal-transfer-dependent cities cannot generate organic property price recovery.",
        "related_series": ["aCNCNLRTQ", "aCNCNGAQLQ", "aCNCNDIDQ"],
    },
    "aCNCNLRTQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Prices — Yichun City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Yichun city land prices at current nominal prices from CLPIS quarterly survey. Given the city's structurally weak demand, nominal and real price series tend to move in close parallel, with little inflation wedge.",
        "how_to_use": "Track for any nominal price recovery driven by central/provincial subsidies to Yichun redevelopment; positive nominal-real gap would signal externally injected price support rather than organic demand.",
        "related_series": ["aCNCNRQZQ", "aCNCNQAUZQ", "aCNCNDIDQ"],
    },
    "aCNCNBTFFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Bohai Economic Zone",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for the Bohai Economic Zone from CLPIS — distinct from land transaction prices, this measures the cost of land-use right leases and renewals in the Beijing-Tianjin-Hebei corridor. Reflects ongoing occupancy cost for industrial and commercial users.",
        "how_to_use": "Rising land use prices in Bohai indicate tightening supply of industrial land in the BTH integration zone; feeds into manufacturing cost-push CPI pressure in North China.",
        "related_series": ["aCNCNDAXFQ", "aCNCNNIPWQ", "aCNCNCLPXQ"],
    },
    "aCNCNNIPWQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Central Region",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Central China (Henan, Hubei, Hunan, Jiangxi, Shanxi, Anhui) from CLPIS. Central region land use costs reflect the pivot of China's manufacturing base inland and demand from logistics hubs.",
        "how_to_use": "Central China land use prices rising faster than transaction prices suggests incumbent occupier demand outpacing new auction supply; positive for local government fiscal but negative for manufacturing cost inflation.",
        "related_series": ["aCNCNQRGHQ", "aCNCNBTFFQ", "aCNCNCLPXQ"],
    },
    "aCNCNQRGHQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Central South",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Central South China, covering Hunan, Hubei, Guangdong, Guangxi, Hainan from CLPIS. Reflects land occupancy costs across a diverse region ranging from PRD tech clusters to interior agricultural land.",
        "how_to_use": "PRD industrial land use price premium vs. Central South regional average signals Guangdong's supply-constrained tech cluster; use to assess cost competitiveness for manufacturing relocation decisions.",
        "related_series": ["aCNCNDBEQ", "aCNCNHTKXQ", "aCNCNNIPWQ"],
    },
    "aCNCNDBEQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — East Area",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for East China (YRD and Fujian) from CLPIS, measuring the cost of leasing or renewing land-use rights in China's highest-value coastal cluster. East area land use prices are the national benchmark for commercial and industrial occupancy costs.",
        "how_to_use": "Elevated East area land use prices relative to other regions drive manufacturing migration inland; monitor trend for evidence of Shanghai-Jiangsu cost-push transmission into services CPI.",
        "related_series": ["aCNCNHTKXQ", "aCNCNBTFFQ", "aCNCNQRGHQ"],
    },
    "aCNCNDGDQQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Fushun City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Fushun city (Liaoning) from CLPIS quarterly survey. Measures ongoing occupancy costs for industrial and commercial tenants in a Northeast transitional economy city.",
        "how_to_use": "Fushun land use prices persistently below national average confirm limited investor confidence; use alongside land transaction price for city-level real estate stress assessment.",
        "related_series": ["aCNCNOZBPQ", "aCNCNLGNIQ", "aCNCNBTFFQ"],
    },
    "aCNCNOZBPQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Fushun City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Fushun city land use right prices at current nominal values from CLPIS. Nominal series captures actual CNY lease-cost levels prevailing in Fushun's commercial and industrial property market.",
        "how_to_use": "Compare with constant-price Fushun land use series (aCNCNDGDQQ) to assess real occupancy-cost trends; persistent nominal decline confirms structural demand destruction in Fushun.",
        "related_series": ["aCNCNDGDQQ", "aCNCNQDTQ", "aCNCNBTFFQ"],
    },
    "aCNCNLGNIQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Fuxin City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Fuxin city (Liaoning) from CLPIS, reflecting industrial and commercial occupancy costs in a coal-transition city. Land use prices in Fuxin are among the lowest in Liaoning province.",
        "how_to_use": "Monitor alongside land transaction prices in Fuxin; divergence between use-right cost and transaction price signals whether demand is from new development or existing occupiers renewing leases.",
        "related_series": ["aCNCNHMJM/A", "aCNCNDGDQQ", "aCNCNBTFFQ"],
    },
    "aCNCNHMJM/A": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Fuxin City (Current Prices)",
        "units": "CNY per sq m, Annual/Quarterly",
        "meaning": "Fuxin city land use right prices at current nominal values, published by CLPIS. Captures nominal lease-cost trends in one of Liaoning's most economically challenged cities for property market stress monitoring.",
        "how_to_use": "Pair with aCNCNLGNIQ for real vs. nominal comparison; very low absolute values confirm Fuxin's land market is not self-sustaining without central fiscal support.",
        "related_series": ["aCNCNLGNIQ", "aCNCNOZBPQ", "aCNCNBTFFQ"],
    },
    "aCNCNMQQFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Handan City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Handan city (Hebei) from CLPIS, capturing occupancy costs for steel-industry and logistics tenants in this Bohai-adjacent industrial hub. Land use prices reflect post-capacity-cut industrial restructuring.",
        "how_to_use": "Rising Handan land use prices alongside rebar index recovery (aCNCNVRGRM) confirm steel-sector consolidation is supporting industrial property demand in Hebei.",
        "related_series": ["aCNCNACMUQ", "aCNCNWKYAQ", "aCNCNBTFFQ"],
    },
    "aCNCNACMUQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Handan City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Handan city land use right prices at current nominal values, reflecting actual CNY occupancy costs for industrial tenants in a post-restructuring Hebei city. Used for local government land-lease revenue accounting.",
        "how_to_use": "Nominal-real spread for Handan land use prices provides a local inflation indicator for Hebei industrial belt; use alongside BTH regional aggregate for Hebei-specific analysis.",
        "related_series": ["aCNCNMQQFQ", "aCNCNFLNKQ", "aCNCNBTFFQ"],
    },
    "aCNCNEBXQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Hegang City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Hegang city (Heilongjiang) from CLPIS. In a city where residential transaction prices collapsed to near CNY 10,000/unit, commercial land use right costs are similarly depressed, reflecting near-zero investor demand.",
        "how_to_use": "Hegang land use prices are a stress-test floor reference for Northeast China commercial real estate; sustained very-low readings confirm the city is in structural property deflation with no near-term recovery catalyst.",
        "related_series": ["aCNCNUPGIQ", "aCNCNGAQLQ", "aCNCNDIDQ"],
    },
    "aCNCNUPGIQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Hegang City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Hegang city land use right prices at current nominal values from CLPIS. Nominal and real series in Hegang tend to converge at near-zero levels, confirming both real deflation and near-zero nominal price change.",
        "how_to_use": "Use in stress-test scenario analysis for Northeast China property debt exposure; any nominal pickup above near-zero would be notable news for Heilongjiang province recovery.",
        "related_series": ["aCNCNEBXQ", "aCNCNTOPBQ", "aCNCNDIDQ"],
    },
    "aCNCNSHOIQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Hengyang City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Hengyang city (Hunan) from CLPIS, measuring commercial and industrial occupancy costs in a Central South city benefiting from coastal industry relocation. Use-right prices reflect steady mid-tier urban growth.",
        "how_to_use": "Rising Hengyang land use prices alongside Central South aggregate signal successful industry absorption in interior Hunan; compare with transaction price (aCNCNKUWMQ) to assess new vs. renewal demand balance.",
        "related_series": ["aCNCNEAUTQ", "aCNCNKUWMQ", "aCNCNQRGHQ"],
    },
    "aCNCNEAUTQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Hengyang City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Hengyang city land use right prices at current nominal values from CLPIS. Reflects actual CNY lease costs for commercial and industrial occupants in Hunan's second-largest city, used for local revenue and developer cost modelling.",
        "how_to_use": "Compare to aCNCNSHOIQ real-price series; a widening nominal-real gap confirms local service-sector inflation contributing to consumer cost pressures in Hengyang.",
        "related_series": ["aCNCNSHOIQ", "aCNCNZGYQ", "aCNCNQRGHQ"],
    },
    "aCNCNHTKXQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Huadong Region",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for the Huadong (East China) region from CLPIS, covering YRD and Fujian. The highest regional land use price in China, reflecting intense competition for commercial and industrial space in the Yangtze Delta.",
        "how_to_use": "Huadong land use prices feed directly into East China logistics, retail, and industrial cost structures, contributing to services CPI in Shanghai and surrounding cities; 5%+ quarterly moves are market-moving for commercial REITs.",
        "related_series": ["aCNCNDBEQ", "aCNCNKTFDQ", "aCNCNQRGHQ"],
    },
    "aCNCNJDURQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Huaibei City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Huaibei city (Anhui) from CLPIS, tracking commercial and industrial occupancy costs in a Yangtze Delta hinterland coal city undergoing transition. YRD integration drives external demand for Huaibei industrial parks.",
        "how_to_use": "Monitor for rising use-right prices signalling successful YRD supply-chain relocation to Huaibei's lower-cost industrial parks; compare to YRD regional use-price for cost-differential analysis.",
        "related_series": ["aCNCNHCSUQ", "aCNCNFZZHQ", "aCNCNNIPWQ"],
    },
    "aCNCNHCSUQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Huaibei City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Huaibei city land use right prices at current nominal values from CLPIS quarterly survey. Captures actual CNY lease-cost levels for Huaibei's transitioning coal and logistics industries.",
        "how_to_use": "Pair with aCNCNJDURQ real series to compute local land-use inflation in Anhui; nominal-real divergence signals whether restructuring is producing genuine real occupancy-cost improvement.",
        "related_series": ["aCNCNJDURQ", "aCNCNLQAZQ", "aCNCNNIPWQ"],
    },
    "aCNCNPZFQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Huainan City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Huainan city (Anhui) from CLPIS, measuring occupancy costs as the city transitions from coal to data centres and green energy. Structural industry change creates demand for new types of industrial land use.",
        "how_to_use": "Rising land use prices for non-coal industrial categories in Huainan signal successful diversification; compare to transaction price (aCNCNIDZRQ) to assess whether new tenants are buying or leasing.",
        "related_series": ["aCNCNUABRQ", "aCNCNIDZRQ", "aCNCNNIPWQ"],
    },
    "aCNCNUABRQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Huainan City (Current Prices)",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Huainan city land use right prices at current nominal values from CLPIS. Reflects CNY occupancy-cost trends in Anhui's largest coal-transition city, used for local government lease-revenue and corporate real-estate cost budgeting.",
        "how_to_use": "Nominal-real gap comparison with aCNCNPZFQ reveals local service-sector inflation; use alongside Huainan current-price transaction series for a complete cost picture of the city's property market.",
        "related_series": ["aCNCNPZFQ", "aCNCNFKSCQ", "aCNCNNIPWQ"],
    },
    "aCNCNZACEQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Jixi City",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for Jixi city (Heilongjiang) from CLPIS, tracking commercial and industrial occupancy costs in this graphite-mining and coal city facing population decline. Land use prices are structurally depressed.",
        "how_to_use": "Jixi land use prices reinforce the Northeast deflation narrative alongside transaction prices; graphite-industry demand (EV battery supply chain) could be a nascent recovery driver to watch.",
        "related_series": ["aCNCNYBWQ/A", "aCNCNYTAGQ", "aCNCNDIDQ"],
    },
    "aCNCNYBWQ/A": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — Jixi City (Current Prices)",
        "units": "CNY per sq m, Annual/Quarterly",
        "meaning": "Jixi city land use right prices at current nominal values from CLPIS. Given Jixi's very weak demand, both nominal and real land use prices tend toward the national floor, with any uplift likely policy-driven.",
        "how_to_use": "Use as a tracking series for EV-supply-chain investment (graphite anode demand) lifting Jixi's property market; any sustained nominal-real convergence above historic lows would be a positive development signal.",
        "related_series": ["aCNCNZACEQ", "aCNCNQAUZQ", "aCNCNDIDQ"],
    },
    "aCNCNDQSVQ": {
        "slug": "cn_consumer_prices_inflation",
        "subcategory": "Land Use Prices — North China",
        "units": "CNY per sq m, Quarterly",
        "meaning": "Land use right price level for North China (Beijing, Tianjin, Hebei, Shanxi, Inner Mongolia) from CLPIS, measuring commercial and industrial occupancy costs across the region. Beijing's premium elevates the regional average significantly above the national median.",
        "how_to_use": "Monitor for divergence between Beijing-driven premium and Hebei/Inner Mongolia industrial use-right prices; BTH integration policy narrowing this gap would signal successful regional development and industrial cost redistribution.",
        "related_series": ["aCNCNBTFFQ", "aCNCNDELJQ", "aCNCNCLPXQ"],
    },
}
