"""US Reuters Polls — Batch 03 (Housing & Real Estate)."""

TIER1: dict[str, dict] = {

    # ── Housing Starts Number (10 RICs) ─────────────────────────────────────

    "USHST=ECI": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Realised monthly Housing Starts reported by Census/HUD, measuring the annualised number of new residential construction projects begun in the period. Typically released around the 16th–19th of the following month and subject to revision.",
        "how_to_use": "Use as the benchmark to score prior poll consensus accuracy; compare USHST=ECI against pUSHST=M to track systematic forecast bias. Persistent beats/misses signal turning points in the residential construction cycle.",
        "related_series": ["pUSHST=M", "pUSHST=E", "aUSHSTART", "USBPE=ECI"],
    },

    "pUSHST=M": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Median Consensus forecast for US Housing Starts from the Reuters poll conducted roughly one week before the Census/HUD release. The median is the central tendency of all individual analyst submissions.",
        "how_to_use": "Markets compare actual vs median; a surprise >50k units often moves homebuilder stocks and mortgage-rate expectations. Pair with permits (pUSBPE=M, forward-looking) and existing home sales (pUSEHS=M, current stock) for a full housing-cycle read.",
        "related_series": ["USHST=ECI", "pUSHST=E", "pUSHST=T", "aUSHSTART"],
    },

    "pUSHST=F": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "SmartEconomics model-based point forecast for Housing Starts, generated by Reuters' quantitative forecasting engine ahead of the release. Provides a data-driven alternative to the survey median.",
        "how_to_use": "Divergence between pUSHST=F and pUSHST=M signals that the model sees information the panel has not yet priced; track pUSHST=P (Predicted Surprise) alongside this to assess directional risk.",
        "related_series": ["pUSHST=M", "pUSHST=P", "USHST=ECI", "aUSHSTART"],
    },

    "pUSHST=P": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Predicted Surprise for Housing Starts, quantifying how much the SmartEconomics forecast (pUSHST=F) deviates from the current analyst consensus (pUSHST=M). A positive value indicates the model expects an upside print.",
        "how_to_use": "Use as a pre-release directional signal; a large positive Predicted Surprise alongside a wide StdDev (pUSHST=T) points to elevated upside risk and justifies asymmetric positioning in rate-sensitive sectors.",
        "related_series": ["pUSHST=F", "pUSHST=M", "pUSHST=T", "USHST=ECI"],
    },

    "pUSHST=E": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Mean (arithmetic average) of all individual Housing Starts forecasts submitted to the Reuters poll. The mean is more sensitive to outlier estimates than the median and can reveal skew in analyst expectations.",
        "how_to_use": "Compare pUSHST=E vs pUSHST=M: if mean > median the distribution is right-skewed (bullish tail); use alongside pUSHST=L/H to gauge the full range of analyst conviction.",
        "related_series": ["pUSHST=M", "pUSHST=L", "pUSHST=H", "USHST=ECI"],
    },

    "pUSHST=O": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Mode (most frequently submitted value) of Housing Starts forecasts in the Reuters poll, representing the single point-estimate shared by the largest cluster of analysts.",
        "how_to_use": "When mode equals median the consensus is tightly clustered; a large gap between pUSHST=O and pUSHST=M reveals bimodal analyst disagreement that median alone would mask.",
        "related_series": ["pUSHST=M", "pUSHST=E", "pUSHST=T", "USHST=ECI"],
    },

    "pUSHST=L": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Minimum (most pessimistic) individual Housing Starts forecast submitted in the Reuters poll, representing the bear-case anchor of the distribution.",
        "how_to_use": "Use pUSHST=L and pUSHST=H together to set the option-implied range; if the actual release falls below pUSHST=L it constitutes a true tail shock and warrants reassessing the macro housing view.",
        "related_series": ["pUSHST=H", "pUSHST=M", "pUSHST=T", "USHST=ECI"],
    },

    "pUSHST=H": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Maximum (most optimistic) individual Housing Starts forecast submitted in the Reuters poll, representing the bull-case anchor of the distribution.",
        "how_to_use": "A print above pUSHST=H is an extreme upside shock; the L-to-H range relative to consensus indicates how much uncertainty remains in the construction pipeline heading into the release.",
        "related_series": ["pUSHST=L", "pUSHST=M", "pUSHST=T", "USHST=ECI"],
    },

    "pUSHST=T": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Million units, SAAR",
        "meaning": "Standard deviation of all individual Housing Starts forecasts in the Reuters poll, measuring the spread of analyst uncertainty around the consensus.",
        "how_to_use": "Elevated StdDev ahead of the release suggests higher headline risk; calibrate stop-loss widths or options vol positioning on homebuilder names when pUSHST=T is in the upper quartile of its historical range.",
        "related_series": ["pUSHST=M", "pUSHST=E", "pUSHST=L", "pUSHST=H"],
    },

    "pUSHST=C": {
        "slug": "us_polls",
        "subcategory": "Housing Starts Number",
        "units": "Number of forecasters",
        "meaning": "Count of individual analysts who submitted Housing Starts forecasts in the current Reuters poll round, indicating the breadth and statistical reliability of the consensus.",
        "how_to_use": "Low forecaster count (e.g., <15) reduces confidence in the median; flag months where pUSHST=C drops materially below its average, as thin participation inflates the apparent precision of pUSHST=M.",
        "related_series": ["pUSHST=M", "pUSHST=T", "pUSBPE=C", "pUSEHS=C"],
    },

    # ── Building Permits: Number (10 RICs) ───────────────────────────────────

    "USBPE=ECI": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Realised monthly Building Permits issued, released jointly with Housing Starts by Census/HUD mid-month. Permits lead starts by 1–3 months and are considered a leading indicator of residential construction activity.",
        "how_to_use": "Track USBPE=ECI vs USHST=ECI ratio to gauge the permits-to-starts pipeline; a rising permits surplus signals future starts acceleration. Use to cross-check pUSBPE=M forecast accuracy ahead of subsequent releases.",
        "related_series": ["pUSBPE=M", "pUSBPE=E", "aUSBPERMIT", "USHST=ECI"],
    },

    "pUSBPE=M": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Median Consensus forecast for US Building Permits from the Reuters pre-release poll. Permits are a leading indicator authorising future construction and reflect developer confidence in demand conditions.",
        "how_to_use": "A permits beat above pUSBPE=M implies pipeline strength 1–3 months forward; pair with pUSHST=M for the current-month read and pUSEHS=M for existing-home demand context in a unified housing dashboard.",
        "related_series": ["USBPE=ECI", "pUSBPE=E", "pUSBPE=T", "aUSBPERMIT"],
    },

    "pUSBPE=F": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "SmartEconomics model-based point forecast for Building Permits, offering a quantitative cross-check against the analyst panel median prior to the Census release.",
        "how_to_use": "When pUSBPE=F deviates meaningfully from pUSBPE=M, consult pUSBPE=P (Predicted Surprise) to determine direction; model-consensus divergence in permits can foreshadow a starts revision the following month.",
        "related_series": ["pUSBPE=M", "pUSBPE=P", "USBPE=ECI", "aUSBPERMIT"],
    },

    "pUSBPE=P": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Predicted Surprise for Building Permits, capturing the gap between the SmartEconomics model forecast (pUSBPE=F) and the analyst consensus (pUSBPE=M). Positive values signal the model expects a stronger-than-consensus print.",
        "how_to_use": "Use as an early directional signal for the permits release; combine with pUSHST=P to identify whether the entire housing report is skewed to the upside or downside relative to consensus.",
        "related_series": ["pUSBPE=F", "pUSBPE=M", "pUSBPE=T", "USBPE=ECI"],
    },

    "pUSBPE=E": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Mean forecast for Building Permits across all Reuters poll participants, which alongside the median reveals skew in the distribution of analyst expectations.",
        "how_to_use": "A mean above the median indicates bullish tail risk from optimistic outliers; use pUSBPE=E vs pUSBPE=M divergence as a skew gauge when setting risk-reward on construction-sensitive trades.",
        "related_series": ["pUSBPE=M", "pUSBPE=L", "pUSBPE=H", "USBPE=ECI"],
    },

    "pUSBPE=O": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Mode of Building Permits forecasts—the value most frequently submitted by poll participants—indicating where analyst conviction clusters most tightly.",
        "how_to_use": "If pUSBPE=O differs sharply from pUSBPE=M, the consensus is bimodal and the median may be misleading; in such cases weight pUSBPE=T (StdDev) more heavily when assessing market impact risk.",
        "related_series": ["pUSBPE=M", "pUSBPE=E", "pUSBPE=T", "USBPE=ECI"],
    },

    "pUSBPE=L": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Minimum individual Building Permits forecast in the Reuters poll, representing the lowest (most bearish) analyst estimate submitted for the upcoming release.",
        "how_to_use": "Pair with pUSBPE=H to establish the full analyst range; a realised print below pUSBPE=L constitutes a tail miss and typically triggers meaningful downward revisions to residential construction forecasts.",
        "related_series": ["pUSBPE=H", "pUSBPE=M", "pUSBPE=T", "USBPE=ECI"],
    },

    "pUSBPE=H": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Maximum individual Building Permits forecast in the Reuters poll, representing the highest (most bullish) analyst estimate submitted for the upcoming release.",
        "how_to_use": "A print above pUSBPE=H is an extreme upside outcome; the H-minus-L spread scaled by pUSBPE=M gives a normalised uncertainty ratio useful for volatility-adjusted position sizing.",
        "related_series": ["pUSBPE=L", "pUSBPE=M", "pUSBPE=T", "USBPE=ECI"],
    },

    "pUSBPE=T": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Million units, SAAR",
        "meaning": "Standard deviation of Building Permits forecasts across Reuters poll participants, measuring the degree of analyst uncertainty ahead of the Census/HUD release.",
        "how_to_use": "Rising StdDev month-over-month signals increasing uncertainty about the housing pipeline—often tied to volatile mortgage rates or weather; calibrate event-risk trades on homebuilder or MBS instruments accordingly.",
        "related_series": ["pUSBPE=M", "pUSBPE=E", "pUSBPE=L", "pUSBPE=H"],
    },

    "pUSBPE=C": {
        "slug": "us_polls",
        "subcategory": "Building Permits Number",
        "units": "Number of forecasters",
        "meaning": "Number of individual analysts who submitted Building Permits forecasts in the current Reuters poll round, reflecting the statistical depth behind the consensus figures.",
        "how_to_use": "Cross-reference with pUSHST=C; months where both permit and starts forecaster counts are low should be treated with lower confidence, particularly in volatile rate environments.",
        "related_series": ["pUSBPE=M", "pUSBPE=T", "pUSHST=C", "pUSEHS=C"],
    },

    # ── Existing Home Sales (10 RICs) ────────────────────────────────────────

    "USEHS=ECI": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Realised monthly Existing Home Sales as reported by the National Association of Realtors (NAR), released around the 20th–25th of the following month. Represents roughly 90% of total US home sales and reflects conditions in the existing housing stock.",
        "how_to_use": "Use as the benchmark to evaluate poll accuracy (vs pUSEHS=M); sustained weakness in USEHS=ECI relative to expectations signals affordability constraints from mortgage rates and can lead housing-sensitive equity sectors.",
        "related_series": ["pUSEHS=M", "pUSEHS=E", "aUSEXHSAL", "USEHSP=ECI"],
    },

    "pUSEHS=M": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Median Consensus forecast for Existing Home Sales from the Reuters pre-release poll, representing the midpoint of analyst expectations for the NAR release.",
        "how_to_use": "Surprises vs pUSEHS=M of ±100k units typically move mortgage-REIT spreads and real-estate sector ETFs; combine with the percentage-change companion (pUSEHSP=M) to contextualise the magnitude of the miss or beat.",
        "related_series": ["USEHS=ECI", "pUSEHS=E", "pUSEHS=T", "aUSEXHSAL"],
    },

    "pUSEHS=F": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "SmartEconomics model-based point forecast for Existing Home Sales, providing a systematic quantitative estimate that can differ materially from the analyst panel consensus.",
        "how_to_use": "Compare pUSEHS=F against pUSEHS=M; when the model is significantly higher (lower) than consensus, check pUSEHS=P (Predicted Surprise) to confirm directionality and use as a pre-release positioning signal.",
        "related_series": ["pUSEHS=M", "pUSEHS=P", "USEHS=ECI", "aUSEXHSAL"],
    },

    "pUSEHS=P": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Predicted Surprise for Existing Home Sales, the signed difference between the SmartEconomics model forecast (pUSEHS=F) and the analyst consensus (pUSEHS=M). Positive values mean the model expects an upside surprise.",
        "how_to_use": "High positive pUSEHS=P ahead of an NAR release, combined with tight StdDev (pUSEHS=T), is a high-conviction setup for long housing exposure; negative pUSEHS=P warns of downside risk despite sanguine consensus.",
        "related_series": ["pUSEHS=F", "pUSEHS=M", "pUSEHS=T", "USEHS=ECI"],
    },

    "pUSEHS=E": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Mean (average) of all individual Existing Home Sales forecasts from Reuters poll participants, sensitive to extreme high or low outlier submissions.",
        "how_to_use": "When pUSEHS=E exceeds pUSEHS=M, optimistic outliers are pulling the average up—monitor whether those outliers are consistently correct to decide how much weight to give the mean vs median.",
        "related_series": ["pUSEHS=M", "pUSEHS=L", "pUSEHS=H", "USEHS=ECI"],
    },

    "pUSEHS=O": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Mode of Existing Home Sales forecasts—the most commonly submitted estimate in the Reuters poll—indicating where analyst clustering is strongest.",
        "how_to_use": "A mode-median gap in Existing Home Sales is often driven by round-number anchoring (e.g., 4.0M vs 4.05M) and may slightly distort median signal; check against pUSEHS=T for full uncertainty context.",
        "related_series": ["pUSEHS=M", "pUSEHS=E", "pUSEHS=T", "USEHS=ECI"],
    },

    "pUSEHS=L": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Minimum individual Existing Home Sales forecast in the Reuters poll, anchoring the bearish end of the analyst distribution ahead of the NAR release.",
        "how_to_use": "A realised print below pUSEHS=L indicates a full tail-miss; this threshold, alongside pUSEHS=H, establishes a hard bound for scenario analysis and option-strike selection on housing-related instruments.",
        "related_series": ["pUSEHS=H", "pUSEHS=M", "pUSEHS=T", "USEHS=ECI"],
    },

    "pUSEHS=H": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Maximum individual Existing Home Sales forecast in the Reuters poll, anchoring the bullish end of the analyst distribution ahead of the NAR release.",
        "how_to_use": "A print above pUSEHS=H represents an extreme upside shock for the existing housing market; the H-L range expressed as a percentage of pUSEHS=M provides a normalised uncertainty metric for cross-indicator comparison.",
        "related_series": ["pUSEHS=L", "pUSEHS=M", "pUSEHS=T", "USEHS=ECI"],
    },

    "pUSEHS=T": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Million units, SAAR",
        "meaning": "Standard deviation of Existing Home Sales forecasts across all Reuters poll participants, measuring dispersion of analyst views ahead of the NAR release.",
        "how_to_use": "Elevated pUSEHS=T typically coincides with uncertain mortgage-rate trajectories; use to scale stop-losses on housing-sensitive positions and compare alongside pUSHST=T and pUSBPE=T for a cross-sector uncertainty heatmap.",
        "related_series": ["pUSEHS=M", "pUSEHS=E", "pUSEHS=L", "pUSEHS=H"],
    },

    "pUSEHS=C": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales",
        "units": "Number of forecasters",
        "meaning": "Number of analysts who submitted Existing Home Sales forecasts in the current Reuters poll round, providing a gauge of survey participation depth.",
        "how_to_use": "Low participation months reduce median reliability; pair with pUSHST=C and pUSBPE=C to identify quarters where the entire housing poll complex is thinly covered, warranting wider uncertainty bands across all three indicators.",
        "related_series": ["pUSEHS=M", "pUSEHS=T", "pUSHST=C", "pUSBPE=C"],
    },

    # ── Existing Home Sales % Change (10 RICs) ───────────────────────────────

    "USEHSP=ECI": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Realised month-over-month percentage change in Existing Home Sales as published by the NAR, derived directly from USEHS=ECI. Provides a rate-of-change perspective that is easier to compare across time than the level series.",
        "how_to_use": "Use USEHSP=ECI vs pUSEHSP=M to score the percentage-change forecast; a large negative surprise (e.g., -5% vs consensus +1%) is a strong housing-cycle deceleration signal that often precedes downward revisions to GDP residential investment.",
        "related_series": ["pUSEHSP=M", "pUSEHSP=E", "USEHS=ECI", "aUSEXHSAL"],
    },

    "pUSEHSP=M": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Median Consensus forecast for the month-over-month percentage change in Existing Home Sales from the Reuters poll. Summarises analyst expectations in rate-of-change terms, which many traders monitor alongside the level (pUSEHS=M).",
        "how_to_use": "When pUSEHSP=M is positive but pUSEHS=M implies a still-depressed level, contextualise the recovery as base-effect driven; use the pair together to avoid misinterpreting a bounce in % change as a true demand recovery.",
        "related_series": ["USEHSP=ECI", "pUSEHSP=E", "pUSEHSP=T", "pUSEHS=M"],
    },

    "pUSEHSP=F": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "SmartEconomics model-based forecast for the MoM percentage change in Existing Home Sales, providing a quantitative cross-check to the analyst panel consensus in percentage-change space.",
        "how_to_use": "Compare pUSEHSP=F with pUSEHSP=M alongside pUSEHS=F vs pUSEHS=M; consistent directional agreement between level and % change model forecasts raises conviction in the Predicted Surprise signal.",
        "related_series": ["pUSEHSP=M", "pUSEHSP=P", "USEHSP=ECI", "pUSEHS=F"],
    },

    "pUSEHSP=P": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Predicted Surprise for the Existing Home Sales MoM percentage change—the difference between SmartEconomics model (pUSEHSP=F) and analyst consensus (pUSEHSP=M). A positive value signals the model expects a stronger-than-consensus monthly gain.",
        "how_to_use": "Use in conjunction with pUSEHS=P; when both level and % change Predicted Surprises agree in direction the signal is more robust. Divergence between the two may indicate rounding or seasonal-adjustment artefacts in the consensus.",
        "related_series": ["pUSEHSP=F", "pUSEHSP=M", "pUSEHSP=T", "pUSEHS=P"],
    },

    "pUSEHSP=E": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Mean forecast for the MoM percentage change in Existing Home Sales across all Reuters poll submissions, more sensitive to extreme outlier estimates than the median.",
        "how_to_use": "A mean well above the median in % change space implies a cluster of analysts expects a large monthly jump; pair with pUSEHSP=H to gauge how extreme the bullish tail is and whether it reflects genuine data signals or stale revisions.",
        "related_series": ["pUSEHSP=M", "pUSEHSP=L", "pUSEHSP=H", "USEHSP=ECI"],
    },

    "pUSEHSP=O": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Mode of the Existing Home Sales MoM percentage-change forecasts—the single % change estimate submitted most frequently by Reuters poll participants.",
        "how_to_use": "When pUSEHSP=O clusters at 0.0%, analysts may be anchoring to a no-change prior; contrast with pUSEHSP=M and pUSEHSP=T to determine whether the consensus embeds genuine uncertainty or conservative round-number anchoring.",
        "related_series": ["pUSEHSP=M", "pUSEHSP=E", "pUSEHSP=T", "USEHSP=ECI"],
    },

    "pUSEHSP=L": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Minimum (most bearish) individual MoM percentage-change forecast for Existing Home Sales in the Reuters poll, anchoring the downside of the distribution.",
        "how_to_use": "A realised MoM change below pUSEHSP=L is a tail shock in rate-of-change space; alongside pUSEHSP=H it defines the analyst forecast range, useful for setting option strikes or scenario-weighting macro models.",
        "related_series": ["pUSEHSP=H", "pUSEHSP=M", "pUSEHSP=T", "USEHSP=ECI"],
    },

    "pUSEHSP=H": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Maximum (most bullish) individual MoM percentage-change forecast for Existing Home Sales in the Reuters poll, anchoring the upside of the distribution.",
        "how_to_use": "A print above pUSEHSP=H in % change terms implies the NAR release was a strong tail beat; cross-reference with USEHS=ECI level to ensure the % surprise is not purely a base-effect or prior-month revision artefact.",
        "related_series": ["pUSEHSP=L", "pUSEHSP=M", "pUSEHSP=T", "USEHSP=ECI"],
    },

    "pUSEHSP=T": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Percent, MoM",
        "meaning": "Standard deviation of the Existing Home Sales MoM percentage-change forecasts submitted to the Reuters poll, measuring dispersion in rate-of-change expectations.",
        "how_to_use": "High pUSEHSP=T alongside high pUSEHS=T signals broad uncertainty across both level and momentum dimensions; this regime calls for wider event-risk buffers on real-estate and mortgage-sensitive positions around the NAR release.",
        "related_series": ["pUSEHSP=M", "pUSEHSP=E", "pUSEHS=T", "USEHSP=ECI"],
    },

    "pUSEHSP=C": {
        "slug": "us_polls",
        "subcategory": "Existing Home Sales Percent Change",
        "units": "Number of forecasters",
        "meaning": "Number of analysts who submitted Existing Home Sales MoM percentage-change forecasts in the current Reuters poll round, indicating participation depth for this derivative series.",
        "how_to_use": "Compare pUSEHSP=C with pUSEHS=C; materially fewer submissions for % change than for the level implies some analysts only provide level estimates—the % change consensus is then thinner and should be interpreted with more caution.",
        "related_series": ["pUSEHSP=M", "pUSEHSP=T", "pUSEHS=C", "pUSHST=C"],
    },
}
