"""Hand-curated content for US Reuters Polls — Batch 01 (GDP & Productivity)."""

TIER1: dict[str, dict] = {

    # ── GDP ADVANCE (10 RICs) ──────────────────────────────────────────────────

    "USGDPA=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of the US GDP Advance Estimate (QoQ annualized) — the BEA's first estimate of quarterly GDP, published ~30 days after quarter-end. This is the market-moving print against which all poll forecasts are measured.",
        "how_to_use": "Compare to pUSGDPA=M (Median Consensus) to calculate the surprise. A beat or miss drives 5-10 bp Treasury moves intraday. Track across vintages (Advance → 2nd → Final) to measure revision bias.",
        "related_series": ["pUSGDPA=M", "pUSGDPA=E", "pUSGDPA=T", "aUSCGDPPD/A"],
    },
    "pUSGDPA=M": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the US GDP Advance Estimate, aggregated from Reuters' poll of ~70-80 Wall Street economists ~1 week before release. The median is the single most-cited 'street consensus' figure.",
        "how_to_use": "The baseline 'expected' GDP — markets trade the surprise (Actual minus Median). When median and mean (pUSGDPA=E) diverge, the forecast distribution is skewed, signalling asymmetric risk around the print.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=E", "pUSGDPA=T", "pUSGDPA=C"],
    },
    "pUSGDPA=F": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics proprietary model forecast for the GDP Advance Estimate — an algorithm-based nowcast blending high-frequency data, rather than a surveyed economist opinion.",
        "how_to_use": "Compare SmartEconomics to the human-poll median (pUSGDPA=M) to detect model-vs-consensus divergence. A persistent SmartEconomics edge vs median can signal where the surprise lands.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=M", "pUSGDPA=P", "pUSGDPA=E"],
    },
    "pUSGDPA=P": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Advance Estimate — Refinitiv's directional signal indicating whether the actual print is expected to beat or miss the median consensus and by how much.",
        "how_to_use": "Use as a pre-release directional bias overlay. A positive Predicted Surprise alongside a high StdDev (pUSGDPA=T) implies a potential upside catalyst with wide uncertainty bounds.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=M", "pUSGDPA=F", "pUSGDPA=T"],
    },
    "pUSGDPA=E": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean (arithmetic average) forecast for the GDP Advance Estimate across all surveyed economists. The mean is sensitive to outlier forecasts unlike the median.",
        "how_to_use": "Compare mean vs median (pUSGDPA=M): a mean above the median signals a positive skew (some bulls pulling the average up), below implies a negative tail. Helps traders gauge distribution shape.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=M", "pUSGDPA=T", "pUSGDPA=C"],
    },
    "pUSGDPA=O": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Advance Estimate — the single most common point estimate submitted by economists in the Reuters survey.",
        "how_to_use": "When mode equals median, economist views are tightly clustered at a round number; when they diverge, the distribution is bimodal. Useful for options traders assessing probability mass at specific growth rates.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=M", "pUSGDPA=L", "pUSGDPA=H"],
    },
    "pUSGDPA=L": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most pessimistic) individual forecast for the GDP Advance Estimate from all economists surveyed — the bear case boundary of the forecast distribution.",
        "how_to_use": "Defines the lower tail of consensus. Pair with Max (pUSGDPA=H) to set the full forecast range; an unusually wide Min-Max spread reflects heightened macro uncertainty around the quarter.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=H", "pUSGDPA=M", "pUSGDPA=T"],
    },
    "pUSGDPA=H": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most optimistic) individual forecast for the GDP Advance Estimate — the bull case boundary of the economist survey distribution.",
        "how_to_use": "Defines the upper tail; if the actual print (USGDPA=ECI) exceeds the Max, it constitutes a consensus-busting surprise. Track the Max-Min range over time as a forward-looking uncertainty gauge.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=L", "pUSGDPA=M", "pUSGDPA=T"],
    },
    "pUSGDPA=T": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of all individual forecasts for the GDP Advance Estimate — measures the degree of disagreement among surveyed Wall Street economists.",
        "how_to_use": "Higher StdDev signals greater uncertainty and typically leads to larger market moves on release. Compare across quarters — a rising StdDev warns that consensus is fragmenting ahead of a difficult-to-forecast print.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=M", "pUSGDPA=E", "pUSGDPA=C"],
    },
    "pUSGDPA=C": {
        "slug": "us_polls",
        "subcategory": "GDP Advance",
        "units": "Count",
        "meaning": "Number of economists who submitted forecasts for the GDP Advance Estimate in the Reuters poll — the sample size underpinning the consensus statistics.",
        "how_to_use": "A count below ~40 means consensus statistics are less reliable; above ~70 indicates a robust survey. Check for sudden drops in count as a sign of reduced analyst coverage ahead of an uncertain release.",
        "related_series": ["USGDPA=ECI", "pUSGDPA=M", "pUSGDPA=T", "pUSGDPA=E"],
    },

    # ── GDP 2ND ESTIMATE (10 RICs) ─────────────────────────────────────────────

    "USGDPP=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of the US GDP Second (Preliminary) Estimate — the BEA's revision published ~60 days after quarter-end, incorporating fuller source data than the Advance.",
        "how_to_use": "Market impact is typically smaller than the Advance unless the revision is large. Compare to the Advance (USGDPA=ECI) to track revision direction; persistent upward revisions signal data momentum.",
        "related_series": ["pUSGDPP=M", "pUSGDPP=E", "USGDPA=ECI", "aUSCGDPPD/A"],
    },
    "pUSGDPP=M": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the US GDP Second Estimate from the Reuters economist poll. By this vintage, most income and spending source data are available so consensus is typically tighter.",
        "how_to_use": "Since the 2nd Estimate revises the Advance, analysts compare pUSGDPP=M to the prior Advance print (USGDPA=ECI) — a rising median implies expected upward revision, which is bullish for risk assets.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=E", "pUSGDPP=T", "pUSGDPP=C"],
    },
    "pUSGDPP=F": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the GDP Second Estimate — an algorithm-driven nowcast produced independently of the surveyed economist panel.",
        "how_to_use": "Compare to pUSGDPP=M: when SmartEconomics diverges materially from the survey median at the 2nd Estimate stage (where data are richer), it may signal a pending revision surprise.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=M", "pUSGDPP=P", "pUSGDPP=E"],
    },
    "pUSGDPP=P": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Second Estimate — directional signal indicating expected beat or miss versus the consensus median, based on Refinitiv's pre-release model.",
        "how_to_use": "Since 2nd Estimate surprises are typically smaller than Advance surprises, a non-zero Predicted Surprise here is informative. Use alongside pUSGDPP=T to judge magnitude vs uncertainty.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=M", "pUSGDPP=F", "pUSGDPP=T"],
    },
    "pUSGDPP=E": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the US GDP Second Estimate, arithmetic average across all economists in the Reuters poll. Sensitive to outlier submissions compared to the median.",
        "how_to_use": "Mean-median comparison reveals skew in the 2nd Estimate consensus. At the preliminary stage, richer data availability tends to compress mean-median spreads versus the Advance poll.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=M", "pUSGDPP=T", "pUSGDPP=C"],
    },
    "pUSGDPP=O": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Second Estimate — the most frequently submitted point estimate among surveyed economists, indicating where forecasters cluster most densely.",
        "how_to_use": "A mode matching the median signals a symmetric, concentrated consensus; divergence implies bimodal views. Useful for assessing options strike density around growth scenarios.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=M", "pUSGDPP=L", "pUSGDPP=H"],
    },
    "pUSGDPP=L": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most pessimistic) single forecast for the GDP Second Estimate — the bear case boundary in the Reuters economist survey.",
        "how_to_use": "Track whether the bear case for the 2nd Estimate is more extreme than for the Advance; a widening downside tail suggests lingering uncertainty about the quarter's data quality.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=H", "pUSGDPP=M", "pUSGDPP=T"],
    },
    "pUSGDPP=H": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most optimistic) single forecast for the GDP Second Estimate — the bull case boundary in the Reuters economist survey.",
        "how_to_use": "If the actual 2nd Estimate (USGDPP=ECI) exceeds the Max, it is an outsized upside surprise. Narrowing Max-Min range from Advance to 2nd Estimate indicates consensus convergence as data availability improves.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=L", "pUSGDPP=M", "pUSGDPP=T"],
    },
    "pUSGDPP=T": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of individual forecasts for the GDP Second Estimate — measures economist disagreement at the preliminary revision stage.",
        "how_to_use": "StdDev for the 2nd Estimate is typically lower than the Advance as more data is in hand. A 2nd Estimate StdDev that remains high suggests unusual underlying data uncertainty even after the first revision.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=M", "pUSGDPP=E", "pUSGDPP=C"],
    },
    "pUSGDPP=C": {
        "slug": "us_polls",
        "subcategory": "GDP 2nd Estimate",
        "units": "Count",
        "meaning": "Number of economists submitting forecasts for the GDP Second Estimate in the Reuters poll — sample size for the 2nd Estimate consensus statistics.",
        "how_to_use": "Compare count to the Advance poll (pUSGDPA=C) — a material drop signals reduced analyst engagement with the revision release, which can inflate the apparent surprise effect.",
        "related_series": ["USGDPP=ECI", "pUSGDPP=M", "pUSGDPP=T", "pUSGDPP=E"],
    },

    # ── GDP SALES ADVANCE (10 RICs) ────────────────────────────────────────────

    "USGFSA=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of Real Final Sales of Domestic Product (GDP Sales) Advance Estimate — GDP excluding the change in private inventories. Released simultaneously with the GDP Advance, ~30 days after quarter-end.",
        "how_to_use": "GDP Sales strips out inventory swings, making it a cleaner read on underlying demand. When GDP Sales and GDP diverge, the gap is inventory accumulation or drawdown — a key signal for the next quarter's growth outlook.",
        "related_series": ["pUSGFSA=M", "pUSGFSA=E", "USGDPA=ECI", "aUSCGDPPD/A"],
    },
    "pUSGFSA=M": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the GDP Sales Advance Estimate from the Reuters economist poll. Reflects the street's expectation of demand-side GDP growth excluding inventory effects.",
        "how_to_use": "Compare pUSGFSA=M vs pUSGDPA=M: a significantly lower GDP Sales consensus implies inventories are expected to flatter the headline GDP number. The Sales surprise (Actual minus pUSGFSA=M) is a purer demand signal.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=E", "pUSGFSA=T", "pUSGDPA=M"],
    },
    "pUSGFSA=F": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the GDP Sales Advance Estimate — an algorithm-based nowcast of real final sales excluding inventory change.",
        "how_to_use": "When SmartEconomics diverges from the median on GDP Sales specifically (vs GDP), it signals disagreement on the inventory component, which is often the least predictable sub-component.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=M", "pUSGFSA=P", "pUSGDPA=F"],
    },
    "pUSGFSA=P": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Sales Advance Estimate — directional pre-release signal for whether final sales will beat or miss the consensus median.",
        "how_to_use": "A divergence between the GDP Predicted Surprise (pUSGDPA=P) and the GDP Sales Predicted Surprise here implies the surprise is expected to come from the inventory component, not underlying demand.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=M", "pUSGFSA=F", "pUSGDPA=P"],
    },
    "pUSGFSA=E": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the GDP Sales Advance Estimate, averaging across all economists in the Reuters survey. Captures the full distribution of views on final demand growth.",
        "how_to_use": "Mean-median spread indicates distribution skew for the Sales forecast. A negative skew (mean below median) suggests some economists anticipate a soft final-demand quarter regardless of headline GDP.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=M", "pUSGFSA=T", "pUSGFSA=C"],
    },
    "pUSGFSA=O": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Sales Advance Estimate — the most common single point estimate submitted by economists surveyed by Reuters.",
        "how_to_use": "Useful when analysts want to know the most 'expected' single number rather than the central tendency; for GDP Sales, the mode is often a round number reflecting inventory-adjusted growth views.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=M", "pUSGFSA=L", "pUSGFSA=H"],
    },
    "pUSGFSA=L": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most pessimistic) forecast for the GDP Sales Advance Estimate — the bear case for underlying demand in the quarter.",
        "how_to_use": "If the actual GDP Sales (USGFSA=ECI) falls below the Min, final demand came in worse than the worst-case economist estimate — a rare but powerful recession warning signal.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=H", "pUSGFSA=M", "pUSGFSA=T"],
    },
    "pUSGFSA=H": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most optimistic) forecast for the GDP Sales Advance Estimate — the bull case for final domestic demand in the Reuters poll.",
        "how_to_use": "Serves as the upper bound for a demand-driven growth scenario. A print above the Max on GDP Sales, paired with a GDP beat, confirms genuine demand strength rather than inventory-led growth.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=L", "pUSGFSA=M", "pUSGFSA=T"],
    },
    "pUSGFSA=T": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of forecasts for the GDP Sales Advance Estimate — gauge of economist disagreement about the underlying demand component of GDP.",
        "how_to_use": "A high GDP Sales StdDev even when GDP StdDev is low implies uncertainty is concentrated in the final-demand component rather than inventories. Compare vintages to see if demand uncertainty is resolving.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=M", "pUSGFSA=E", "pUSGDPA=T"],
    },
    "pUSGFSA=C": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Advance",
        "units": "Count",
        "meaning": "Number of economists providing GDP Sales Advance forecasts in the Reuters poll — the sample size for the GDP Sales Advance consensus.",
        "how_to_use": "GDP Sales is less followed than headline GDP; a significantly lower count vs the GDP Advance poll (pUSGDPA=C) means the Sales consensus is thinner and individual outliers have more weight.",
        "related_series": ["USGFSA=ECI", "pUSGFSA=M", "pUSGFSA=T", "pUSGDPA=C"],
    },

    # ── GDP SALES PRELIM (10 RICs) ─────────────────────────────────────────────

    "USGFSP=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of the Real Final Sales Preliminary Estimate — the 2nd-vintage revision of GDP excluding inventories, published ~60 days after quarter-end alongside the GDP 2nd Estimate.",
        "how_to_use": "Track the revision from Advance (USGFSA=ECI) to Prelim — persistent upward revisions to final sales confirm demand was better than initially measured, supporting a positive revision to the headline GDP outlook.",
        "related_series": ["pUSGFSP=M", "USGFSA=ECI", "USGDPP=ECI", "aUSCGDPPD/A"],
    },
    "pUSGFSP=M": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the GDP Sales Preliminary Estimate from the Reuters economist poll — the street's expected revision to final domestic demand.",
        "how_to_use": "Compare to the prior Advance actual (USGFSA=ECI): median above the Advance signals expected upward demand revision, which reduces concern that earlier growth was inventory-driven.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=E", "pUSGFSP=T", "pUSGFSA=M"],
    },
    "pUSGFSP=F": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the GDP Sales Preliminary Estimate — algorithm-based estimate of the revised final-sales figure.",
        "how_to_use": "SmartEconomics at the prelim stage has access to fuller monthly source data. A divergence from pUSGFSP=M here is more informative than at the Advance stage.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=M", "pUSGFSP=P", "pUSGFSA=F"],
    },
    "pUSGFSP=P": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Sales Preliminary Estimate — pre-release directional signal for the revision to final domestic demand.",
        "how_to_use": "When the GDP 2nd Estimate Predicted Surprise (pUSGDPP=P) and GDP Sales Predicted Surprise diverge, the expected surprise is inventory-driven. Use to assess whether a GDP beat will be demand-based or not.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=M", "pUSGFSP=F", "pUSGDPP=P"],
    },
    "pUSGFSP=E": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the GDP Sales Preliminary Estimate across all economists in the Reuters poll. Reflects the average view on final demand at the second-vintage stage.",
        "how_to_use": "Mean-median spread at the prelim stage is informative about outlier views. If the mean is pulling well above the median, some economists expect a strong upward revision to final sales.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=M", "pUSGFSP=T", "pUSGFSP=C"],
    },
    "pUSGFSP=O": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Sales Preliminary Estimate — the most commonly submitted single point estimate by economists in the Reuters survey.",
        "how_to_use": "Mode convergence with the median at the prelim stage (more data available) indicates high consensus certainty. A gap between mode and median suggests bimodal views on the revision direction.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=M", "pUSGFSP=L", "pUSGFSP=H"],
    },
    "pUSGFSP=L": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most pessimistic) forecast for the GDP Sales Preliminary Estimate — the bear case for the revised final-demand figure.",
        "how_to_use": "If the actual Prelim GDP Sales prints at or below the Min forecast, demand was significantly weaker than any surveyed economist expected — a macro warning sign worth flagging alongside retail and PCE data.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=H", "pUSGFSP=M", "pUSGFSP=T"],
    },
    "pUSGFSP=H": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most optimistic) forecast for the GDP Sales Preliminary Estimate — the upper boundary of surveyed expectations for revised final domestic demand.",
        "how_to_use": "Tracks how bullish the most optimistic economist is on demand. Narrowing Max-Min range from Advance to Prelim is normal as data quality improves; a widening range is unusual and signals model uncertainty.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=L", "pUSGFSP=M", "pUSGFSP=T"],
    },
    "pUSGFSP=T": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of forecasts for the GDP Sales Preliminary Estimate — measures the spread of economist views on revised final domestic demand.",
        "how_to_use": "Compare to the Advance StdDev (pUSGFSA=T): StdDev should narrow at the Prelim stage as more monthly data is available. If it fails to narrow, analyst uncertainty about demand remains elevated.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=M", "pUSGFSP=E", "pUSGFSA=T"],
    },
    "pUSGFSP=C": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Prelim",
        "units": "Count",
        "meaning": "Number of economists providing forecasts for the GDP Sales Preliminary Estimate in the Reuters poll.",
        "how_to_use": "A low respondent count relative to the GDP poll (pUSGDPP=C) indicates the GDP Sales Prelim is a less-followed release; thin coverage means the median consensus is less reliable.",
        "related_series": ["USGFSP=ECI", "pUSGFSP=M", "pUSGFSP=T", "pUSGDPP=C"],
    },

    # ── GDP SALES FINAL (10 RICs) ──────────────────────────────────────────────

    "USGFSF=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of Real Final Sales Final Estimate — the third and most comprehensive BEA vintage of GDP excluding inventories, published ~90 days after quarter-end.",
        "how_to_use": "The definitive read on final demand for the quarter. Large revisions from Prelim (USGFSP=ECI) to Final are uncommon; when they occur, they often reflect BEA benchmark source-data revisions.",
        "related_series": ["pUSGFSF=M", "USGFSP=ECI", "USGFSA=ECI", "aUSCGDPPD/A"],
    },
    "pUSGFSF=M": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the GDP Sales Final Estimate from the Reuters poll — the street's expected final revision to real domestic demand.",
        "how_to_use": "By the Final stage, surprises vs consensus are rare. A notable beat or miss of pUSGFSF=M on the actual is highly significant and often tied to benchmark data revisions rather than estimation errors.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=E", "pUSGFSF=T", "pUSGFSP=M"],
    },
    "pUSGFSF=F": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the GDP Sales Final Estimate — an algorithmic estimate with access to the most complete set of quarterly source data.",
        "how_to_use": "At the Final stage, the SmartEconomics model and human consensus should converge; persistent divergence from pUSGFSF=M may indicate SmartEconomics is capturing an outlier data series.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=M", "pUSGFSF=P", "pUSGFSP=F"],
    },
    "pUSGFSF=P": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Sales Final Estimate — pre-release directional signal for the definitive final-demand revision.",
        "how_to_use": "A non-zero Predicted Surprise at the Final stage is unusual and noteworthy. If pUSGFSF=P and pUSGDPF=P (GDP Final Predicted Surprise) diverge, expected surprise is inventory-side, not demand-side.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=M", "pUSGFSF=F", "pUSGFSP=P"],
    },
    "pUSGFSF=E": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the GDP Sales Final Estimate across surveyed economists — arithmetic average of all submitted final-demand forecasts.",
        "how_to_use": "By the Final stage, mean and median (pUSGFSF=M) typically converge, indicating a symmetric, narrow distribution. Residual mean-median divergence implies outlier forecasters with access to different data.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=M", "pUSGFSF=T", "pUSGFSF=C"],
    },
    "pUSGFSF=O": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Sales Final Estimate — the most frequently submitted point estimate in the Reuters economist survey for the final demand vintage.",
        "how_to_use": "Mode-median alignment at the Final stage confirms tight, converged consensus on demand. Used alongside StdDev (pUSGFSF=T) to confirm whether the forecast distribution is narrow or still bimodal.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=M", "pUSGFSF=L", "pUSGFSF=H"],
    },
    "pUSGFSF=L": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most pessimistic) forecast for the GDP Sales Final Estimate — the floor of the final-demand distribution at the definitive vintage.",
        "how_to_use": "An actual print (USGFSF=ECI) below the Min at the Final stage would be extraordinary and would likely reflect a benchmark data revision. Track to ensure the range is narrowing from Advance to Final.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=H", "pUSGFSF=M", "pUSGFSF=T"],
    },
    "pUSGFSF=H": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most optimistic) forecast for the GDP Sales Final Estimate — the ceiling of the forecast range for the definitive final-demand release.",
        "how_to_use": "Narrowing Max from Prelim to Final is expected as uncertainty resolves. If the Max remains elevated versus the Prelim, it signals ongoing data ambiguity in the quarterly accounts.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=L", "pUSGFSF=M", "pUSGFSF=T"],
    },
    "pUSGFSF=T": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of forecasts for the GDP Sales Final Estimate — the residual level of economist disagreement about final domestic demand at the definitive revision stage.",
        "how_to_use": "StdDev at the Final stage should be the lowest of the three vintages (Advance, Prelim, Final). A Final-stage StdDev similar to the Advance stage implies the data was genuinely hard to forecast throughout.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=M", "pUSGFSF=E", "pUSGFSP=T"],
    },
    "pUSGFSF=C": {
        "slug": "us_polls",
        "subcategory": "GDP Sales Final",
        "units": "Count",
        "meaning": "Number of economists submitting forecasts for the GDP Sales Final Estimate in the Reuters poll — the sample size at the definitively revised vintage.",
        "how_to_use": "Count often drops from Advance to Final as the Final release commands less market attention. A very low count means the Final consensus statistics are unreliable and should be treated as indicative only.",
        "related_series": ["USGFSF=ECI", "pUSGFSF=M", "pUSGFSF=T", "pUSGFSP=C"],
    },

    # ── GDP DEFLATOR ADVANCE (10 RICs) ─────────────────────────────────────────

    "USDGEA=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of the GDP Chain-Type Price Index (Deflator) Advance Estimate — the BEA's broadest inflation measure covering all goods and services in GDP, released ~30 days after quarter-end.",
        "how_to_use": "The GDP Deflator is broader than CPI or PCE; a surprise versus pUSDGEA=M signals unexpected inflationary or deflationary pressure across the full economy, relevant to Fed policy discussions.",
        "related_series": ["pUSDGEA=M", "pUSDGEA=E", "pUSDGEA=T", "aUSCGDPPRC"],
    },
    "pUSDGEA=M": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the GDP Deflator Advance Estimate — the street's aggregate expectation for the broadest quarterly US inflation measure.",
        "how_to_use": "Compare to the actual (USDGEA=ECI) for a broad inflation surprise. A Deflator beat alongside a GDP beat is a stagflation-lite signal; a miss with a GDP beat is goldilocks — growth without inflation.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=E", "pUSDGEA=T", "pUSDGEA=C"],
    },
    "pUSDGEA=F": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the GDP Deflator Advance Estimate — an algorithm-based projection of broad quarterly inflation.",
        "how_to_use": "When SmartEconomics diverges from the Deflator consensus median, it often reflects real-time commodity or import price data not yet fully incorporated by surveyed economists.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=M", "pUSDGEA=P", "pUSDGEA=E"],
    },
    "pUSDGEA=P": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Deflator Advance Estimate — directional signal indicating whether the broad price index will beat or miss consensus.",
        "how_to_use": "A hawkish Predicted Surprise (upside deflator beat expected) reinforces the case for Fed tightening. Compare with PCE deflator Predicted Surprises for consistency across inflation gauges.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=M", "pUSDGEA=F", "pUSDGEA=T"],
    },
    "pUSDGEA=E": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the GDP Deflator Advance Estimate across all economists in the Reuters poll — the arithmetic average of submitted inflation forecasts.",
        "how_to_use": "Mean-median divergence for the Deflator indicates skewed inflation views. If the mean exceeds the median, some economists expect an inflation overshoot — relevant for assessing TIPS breakeven fair value.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=M", "pUSDGEA=T", "pUSDGEA=C"],
    },
    "pUSDGEA=O": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Deflator Advance Estimate — the most common inflation expectation point estimate submitted by economists in the Reuters survey.",
        "how_to_use": "A mode at a round number (e.g., 2.0%) for the Deflator signals strong consensus anchoring around a particular inflation rate, which can suppress implied volatility in inflation-linked instruments.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=M", "pUSDGEA=L", "pUSDGEA=H"],
    },
    "pUSDGEA=L": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most dovish) forecast for the GDP Deflator Advance Estimate — the lowest inflation expectation in the Reuters survey.",
        "how_to_use": "The Min Deflator forecast anchors the disinflationary scenario. A print at or below Min signals an unexpected deflation pulse, which would typically rally Treasuries and compress real yields.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=H", "pUSDGEA=M", "pUSDGEA=T"],
    },
    "pUSDGEA=H": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most hawkish) forecast for the GDP Deflator Advance Estimate — the highest inflation expectation among all economists in the Reuters survey.",
        "how_to_use": "A print above the Max is a significant inflation shock, likely triggering repricing of Fed rate expectations. Max-Min spread narrows during anchored inflation regimes and widens during supply shocks.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=L", "pUSDGEA=M", "pUSDGEA=T"],
    },
    "pUSDGEA=T": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of forecasts for the GDP Deflator Advance Estimate — gauge of economist disagreement about quarterly broad inflation.",
        "how_to_use": "Rising Deflator StdDev signals analyst uncertainty about the inflation regime, typically during commodity price volatility or supply-chain disruptions. Elevated StdDev amplifies the market impact of the actual print.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=M", "pUSDGEA=E", "pUSDGEA=C"],
    },
    "pUSDGEA=C": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Advance",
        "units": "Count",
        "meaning": "Number of economists providing GDP Deflator Advance forecasts in the Reuters poll — sample size underpinning the Deflator consensus statistics.",
        "how_to_use": "The Deflator is polled alongside the GDP Advance but typically draws fewer responses; a low count reduces the statistical robustness of the median and StdDev and should be noted in research.",
        "related_series": ["USDGEA=ECI", "pUSDGEA=M", "pUSDGEA=T", "pUSDGEA=E"],
    },

    # ── GDP DEFLATOR PRELIM (10 RICs) ──────────────────────────────────────────

    "USDGEP=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of the GDP Chain-Type Price Index Preliminary Estimate — the BEA's second vintage of the broad inflation measure, released ~60 days after quarter-end.",
        "how_to_use": "Track the Advance-to-Prelim revision for the Deflator (USDGEA=ECI vs USDGEP=ECI). An upward revision at the Prelim stage is a hawkish signal, as the broadest inflation gauge is running hotter than initially estimated.",
        "related_series": ["pUSDGEP=M", "USDGEA=ECI", "USDGEF=ECI", "aUSCGDPPRC"],
    },
    "pUSDGEP=M": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the GDP Deflator Preliminary Estimate — the street's expected revision to quarterly broad inflation at the second-vintage stage.",
        "how_to_use": "Compare to the Advance actual (USDGEA=ECI): median above the prior print signals expected upward inflation revision. A hawkish revision here may reinforce Fed communication ahead of the next FOMC meeting.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=E", "pUSDGEP=T", "pUSDGEA=M"],
    },
    "pUSDGEP=F": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the GDP Deflator Preliminary Estimate — algorithmic nowcast of the revised broad inflation figure.",
        "how_to_use": "At the Prelim stage, SmartEconomics has access to full monthly price indices. A persistent divergence from pUSDGEP=M may reflect different methodological treatments of hedonic price adjustments.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=M", "pUSDGEP=P", "pUSDGEA=F"],
    },
    "pUSDGEP=P": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Deflator Preliminary Estimate — directional signal for whether the revised broad inflation print will beat or miss consensus.",
        "how_to_use": "A hawkish Predicted Surprise at the Deflator Prelim (upside beat expected) compounds Fed tightening risk if the 2nd GDP Estimate is also expected to beat, reinforcing a nominal overheating narrative.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=M", "pUSDGEP=F", "pUSDGEA=P"],
    },
    "pUSDGEP=E": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the GDP Deflator Preliminary Estimate across all economists in the Reuters poll.",
        "how_to_use": "Mean-median comparison for the Deflator Prelim reveals whether outlier hawkish or dovish inflation views are distorting the distribution. Important context for rates traders watching for inflation tail risks.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=M", "pUSDGEP=T", "pUSDGEP=C"],
    },
    "pUSDGEP=O": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Deflator Preliminary Estimate — the most common single inflation estimate submitted by economists at the second-vintage stage.",
        "how_to_use": "Mode alignment with median at the Prelim stage confirms that the central inflation view is symmetric and well-anchored. Use as part of qualitative consensus assessment.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=M", "pUSDGEP=L", "pUSDGEP=H"],
    },
    "pUSDGEP=L": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most dovish) forecast for the GDP Deflator Preliminary Estimate — the lowest inflation expectation in the Reuters survey for this vintage.",
        "how_to_use": "If the Prelim Deflator actual comes in at or below the survey minimum, it signals a significant disinflationary development that may shift market pricing toward rate cuts.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=H", "pUSDGEP=M", "pUSDGEP=T"],
    },
    "pUSDGEP=H": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most hawkish) forecast for the GDP Deflator Preliminary Estimate — the highest inflation expectation in the Reuters survey at the second-vintage stage.",
        "how_to_use": "Max narrows from Advance to Prelim as more data arrives. A widening Max at the Prelim stage is unusual and suggests a specific data source (e.g., energy prices, import prices) is introducing fresh inflation uncertainty.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=L", "pUSDGEP=M", "pUSDGEP=T"],
    },
    "pUSDGEP=T": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of forecasts for the GDP Deflator Preliminary Estimate — measures residual analyst disagreement about broad quarterly inflation.",
        "how_to_use": "Deflator Prelim StdDev should narrow versus the Advance. If it does not, energy or commodity price data since the Advance release is injecting new inflation uncertainty — a signal to monitor TIPS vol.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=M", "pUSDGEP=E", "pUSDGEA=T"],
    },
    "pUSDGEP=C": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Prelim",
        "units": "Count",
        "meaning": "Number of economists providing GDP Deflator Preliminary forecasts in the Reuters poll — the sample size for this second-vintage inflation consensus.",
        "how_to_use": "Count typically declines from the Advance to Prelim Deflator poll as fewer economists formally re-forecast. A thin count should be flagged as a caveat on any consensus-based inflation view.",
        "related_series": ["USDGEP=ECI", "pUSDGEP=M", "pUSDGEP=T", "pUSDGEA=C"],
    },

    # ── GDP DEFLATOR FINAL (10 RICs) ───────────────────────────────────────────

    "USDGEF=ECI": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of the GDP Chain-Type Price Index Final Estimate — the BEA's definitive broad inflation measure for the quarter, released ~90 days after quarter-end.",
        "how_to_use": "Use the final Deflator print to benchmark the inflation environment for the full quarter. Compare all three vintages (Advance, Prelim, Final) to assess whether BEA had a systematic bias in initial price estimates.",
        "related_series": ["pUSDGEF=M", "USDGEP=ECI", "USDGEA=ECI", "aUSCGDPPRC"],
    },
    "pUSDGEF=M": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the GDP Deflator Final Estimate — the street's expected definitive quarterly broad inflation reading.",
        "how_to_use": "By the Final stage, surprises vs median are rare. A significant surprise here typically reflects a BEA methodological revision rather than new economic data. Use as the closing benchmark for quarterly inflation analysis.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=E", "pUSDGEF=T", "pUSDGEP=M"],
    },
    "pUSDGEF=F": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the GDP Deflator Final Estimate — the definitive algorithmic inflation estimate with access to all quarterly source data.",
        "how_to_use": "At the Final stage, SmartEconomics and human consensus (pUSDGEF=M) should converge. Persistent divergence may suggest SmartEconomics uses a different chain-weighting methodology assumption.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=M", "pUSDGEF=P", "pUSDGEP=F"],
    },
    "pUSDGEF=P": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the GDP Deflator Final Estimate — a directional signal for whether the definitive broad inflation print will beat or miss the median consensus.",
        "how_to_use": "A non-zero Predicted Surprise at the Deflator Final stage is notable and should prompt investigation of whether BEA has issued any advance signals about methodology changes or data revisions.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=M", "pUSDGEF=F", "pUSDGEP=P"],
    },
    "pUSDGEF=E": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the GDP Deflator Final Estimate across all economists in the Reuters poll — arithmetic average of all submitted definitive inflation forecasts.",
        "how_to_use": "Mean-median convergence at the Final stage confirms a tight, symmetric consensus. Any residual divergence at this stage highlights outlier models with non-standard price deflator assumptions.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=M", "pUSDGEF=T", "pUSDGEF=C"],
    },
    "pUSDGEF=O": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the GDP Deflator Final Estimate — the most frequently submitted single inflation estimate at the definitive revision stage.",
        "how_to_use": "Mode alignment with median confirms consensus certainty about the final quarterly inflation number. Used in academic studies comparing forecast accuracy across the three deflator vintages.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=M", "pUSDGEF=L", "pUSDGEF=H"],
    },
    "pUSDGEF=L": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most dovish) forecast for the GDP Deflator Final Estimate — the lower bound of the inflation distribution at the definitive BEA release.",
        "how_to_use": "The Min at the Final stage should be tighter than the Advance Min. A print below the Final Min implies a methodology-driven downward revision to prices, which can temporarily flatten the yield curve.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=H", "pUSDGEF=M", "pUSDGEF=T"],
    },
    "pUSDGEF=H": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most hawkish) forecast for the GDP Deflator Final Estimate — the ceiling of inflation expectations at the definitive revision stage.",
        "how_to_use": "A print above the Final Max for the Deflator would be an exceptional upside inflation surprise at the definitive stage, warranting immediate reassessment of the real rate environment.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=L", "pUSDGEF=M", "pUSDGEF=T"],
    },
    "pUSDGEF=T": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of forecasts for the GDP Deflator Final Estimate — measures the residual economist disagreement about the definitive quarterly broad inflation rate.",
        "how_to_use": "Final-stage Deflator StdDev should be the lowest of the three vintages. Elevated Final StdDev signals structural disagreement about the price index methodology, not just the data — important for real GDP decomposition.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=M", "pUSDGEF=E", "pUSDGEP=T"],
    },
    "pUSDGEF=C": {
        "slug": "us_polls",
        "subcategory": "GDP Deflator Final",
        "units": "Count",
        "meaning": "Number of economists providing GDP Deflator Final forecasts in the Reuters poll — the sample size for the definitive inflation consensus.",
        "how_to_use": "The Final Deflator poll draws the fewest respondents of the three vintages. A very low count (below 30) makes the median and StdDev highly sensitive to individual outlier submissions.",
        "related_series": ["USDGEF=ECI", "pUSDGEF=M", "pUSDGEF=T", "pUSDGEP=C"],
    },

    # ── PRODUCTIVITY PRELIM (10 RICs) ──────────────────────────────────────────

    "USPROP=ECI": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Actual release of US Non-farm Business Sector Labor Productivity (Preliminary Estimate) — the BLS measure of output per hour worked, released ~60 days after quarter-end.",
        "how_to_use": "Productivity is the key long-run driver of non-inflationary growth. A beat versus pUSPROP=M is bullish for equities (more output per worker) and lowers unit labor cost, reducing Fed concern about wage-driven inflation.",
        "related_series": ["pUSPROP=M", "pUSPROP=E", "pUSPROP=T", "aUSPHOPBUS/A"],
    },
    "pUSPROP=M": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Median Consensus forecast for the US Non-farm Business Sector Productivity Preliminary Estimate from the Reuters economist poll.",
        "how_to_use": "The consensus median is the standard against which to measure the Productivity surprise. A productivity surprise changes the perceived non-inflationary speed limit of the economy and affects Fed forward guidance narratives.",
        "related_series": ["USPROP=ECI", "pUSPROP=E", "pUSPROP=T", "pUSPROP=C"],
    },
    "pUSPROP=F": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Refinitiv SmartEconomics model forecast for the Productivity Preliminary Estimate — an algorithmic nowcast blending output data (GDP) and hours-worked data from the BLS.",
        "how_to_use": "SmartEconomics productivity forecast reflects a mechanical calculation from GDP growth (already known at Prelim stage) and hours worked. Divergence from pUSPROP=M may signal a specific hours-worked data source difference.",
        "related_series": ["USPROP=ECI", "pUSPROP=M", "pUSPROP=P", "pUSPROP=E"],
    },
    "pUSPROP=P": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Predicted Surprise for the Productivity Preliminary Estimate — Refinitiv's directional signal indicating whether the output-per-hour print will beat or miss consensus.",
        "how_to_use": "An upside Productivity Predicted Surprise alongside a downside Unit Labor Cost expected surprise (if available) forms a powerful benign macro narrative for risk assets and duration.",
        "related_series": ["USPROP=ECI", "pUSPROP=M", "pUSPROP=F", "pUSPROP=T"],
    },
    "pUSPROP=E": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Mean forecast for the Productivity Preliminary Estimate across all economists in the Reuters poll — arithmetic average of output-per-hour forecasts.",
        "how_to_use": "Mean-median divergence for Productivity reflects outlier views on hours worked or output. A mean significantly above median suggests some economists expect a surge in output relative to labor input.",
        "related_series": ["USPROP=ECI", "pUSPROP=M", "pUSPROP=T", "pUSPROP=C"],
    },
    "pUSPROP=O": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Mode forecast for the Productivity Preliminary Estimate — the single most commonly submitted point estimate by economists in the Reuters survey.",
        "how_to_use": "For Productivity, the mode often clusters at a round number near consensus trend (historically ~2%). A mode far from the median indicates the distribution is bimodal — some economists expect a structural shift.",
        "related_series": ["USPROP=ECI", "pUSPROP=M", "pUSPROP=L", "pUSPROP=H"],
    },
    "pUSPROP=L": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Minimum (most pessimistic) forecast for the Productivity Preliminary Estimate — the bear case for labor efficiency in the quarter.",
        "how_to_use": "A print at or below the Productivity Min implies output per worker came in below all surveyed economists' expectations, which raises unit labor costs and is a potential inflationary catalyst.",
        "related_series": ["USPROP=ECI", "pUSPROP=H", "pUSPROP=M", "pUSPROP=T"],
    },
    "pUSPROP=H": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Maximum (most optimistic) forecast for the Productivity Preliminary Estimate — the bull case for labor efficiency in the Reuters economist survey.",
        "how_to_use": "A print above the Productivity Max signals an exceptional output-per-hour surge, potentially driven by technology adoption or unusual hours data. Such a print is structurally bullish for potential GDP estimates.",
        "related_series": ["USPROP=ECI", "pUSPROP=L", "pUSPROP=M", "pUSPROP=T"],
    },
    "pUSPROP=T": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Percent, QoQ annualized",
        "meaning": "Standard deviation of forecasts for the Productivity Preliminary Estimate — measures analyst disagreement about quarterly output-per-hour growth.",
        "how_to_use": "High Productivity StdDev often reflects uncertainty about hours-worked data (which feeds directly into the calculation). Rising StdDev over time may signal increased structural uncertainty about labor market efficiency trends.",
        "related_series": ["USPROP=ECI", "pUSPROP=M", "pUSPROP=E", "pUSPROP=C"],
    },
    "pUSPROP=C": {
        "slug": "us_polls",
        "subcategory": "Productivity Prelim",
        "units": "Count",
        "meaning": "Number of economists submitting Productivity Preliminary forecasts in the Reuters poll — the sample size for this consensus.",
        "how_to_use": "Productivity is a less heavily polled indicator than GDP; a count below 30 means the consensus statistics should be treated with caution. Monitor for declining participation over time as a sign of reduced institutional coverage.",
        "related_series": ["USPROP=ECI", "pUSPROP=M", "pUSPROP=T", "pUSPROP=E"],
    },
}
