"""Hand-curated content for China RICs — Batch 04a (Exports part 1)."""
TIER1: dict[str, dict] = {
    "aCNCNZJKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "USD millions",
        "meaning": "Monthly export value of coking (bituminous) coal from China Customs (~7-10th release). China is a significant coking-coal exporter but volumes have declined as domestic steel demand absorbs supply.",
        "how_to_use": "Monitor alongside Chinese steel production; rising steel output typically reduces coal available for export. Subject to export quotas and tariff adjustments.",
        "related_series": ["aCNCNZXDRM", "aCNCNDDVEM", "aCNCNUTOSM"],
    },
    "aCNCNTGTIM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Electronics",
        "units": "Volume (units)",
        "meaning": "Monthly export volume of DVD players from China Customs (~7-10th release). China dominated global DVD-player manufacturing but volumes have collapsed as streaming displaced physical media.",
        "how_to_use": "Primarily a legacy indicator; sharp secular decline since the 2010s reflects consumer-electronics product-cycle shifts. Use alongside color-TV and camera export series for full CE picture.",
        "related_series": ["aCNCNZDTWM", "aCNCNOMMUM", "aCNCNSBHRM"],
    },
    "aCNCNTGXO": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Base Metals",
        "units": "USD millions",
        "meaning": "Annual export value of aluminum products from China Customs. China accounts for roughly 55% of global aluminum production and is the world's largest aluminum exporter.",
        "how_to_use": "Use as a full-year benchmark against monthly aCNCNZPRKM. Elevated exports often trigger anti-dumping investigations from the EU and US; tariff news is a key price driver for LME aluminum.",
        "related_series": ["aCNCNZPRKM", "aCNCNKGUPM", "aCNCNBOZEM"],
    },
    "aCNCNZPRKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Base Metals",
        "units": "USD millions",
        "meaning": "Monthly export value of aluminum products from China Customs (~7-10th release). China's semi-fabricated aluminum exports are closely watched for dumping-margin calculations by trade partners.",
        "how_to_use": "Surges often precede anti-dumping duties from the EU and US; compare against LME aluminum spot to assess export profitability and likely future volumes.",
        "related_series": ["aCNCNKGUPM", "aCNCNBOZEM", "aCNCNFHOWM"],
    },
    "aCNCNKGUPM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Base Metals",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of aluminum from China Customs (~7-10th release). Volume data strips out price effects, showing true tonnage flows to global markets.",
        "how_to_use": "Compare volume trend against aCNCNZPRKM (value) to infer unit-price movements. High volumes with flat values signal price weakness; relevant for LME aluminum positioning.",
        "related_series": ["aCNCNZPRKM", "aCNCNBOZEM", "aCNCNFHOWM"],
    },
    "aCNCNBOZEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Base Metals",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of aluminum (secondary series) from China Customs (~7-10th release). May capture a different HS sub-category of aluminum products vs aCNCNKGUPM.",
        "how_to_use": "Use alongside aCNCNKGUPM to build a complete picture of China's aluminum export flows; discrepancies between the two can reflect product-mix shifts between primary and semi-finished aluminum.",
        "related_series": ["aCNCNKGUPM", "aCNCNZPRKM", "aCNCNFHOWM"],
    },
    "aCNCNRKRHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Critical Minerals",
        "units": "USD millions",
        "meaning": "Monthly export value of ammonium paratungstate (APT) from China Customs (~7-10th release). China controls ~80% of global tungsten supply; APT is the primary traded intermediate for hard-metal tooling and electronics.",
        "how_to_use": "China periodically restricts tungsten exports via quotas; any tightening spike immediately affects global cemented-carbide and semiconductor-tooling supply chains. Track alongside export-quota announcements.",
        "related_series": ["aCNCNZENM", "aCNCNEYAYM", "aCNCNPKLIM"],
    },
    "aCNCNEYAYM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Critical Minerals",
        "units": "USD millions",
        "meaning": "Monthly export value of zinc-lanthanum compounds (lide powder) from China Customs (~7-10th release). Lanthanum is a light rare-earth element used in batteries, optics, and catalysts.",
        "how_to_use": "Monitor alongside China's rare-earth export quota announcements; export restrictions imposed in 2023-25 on critical minerals amplify price swings. Relevant for EV battery and clean-tech supply chains.",
        "related_series": ["aCNCNRKRHM", "aCNCNZENM", "aCNCNPKLIM"],
    },
    "aCNCNUTOSM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "USD millions",
        "meaning": "Monthly export value of anthracite (high-grade thermal/industrial coal) from China Customs (~7-10th release). China is a significant anthracite exporter, particularly to South Korea and Eastern Europe.",
        "how_to_use": "Seasonal spikes ahead of Northern Hemisphere winter; volumes also sensitive to domestic power demand and government export policies. Compare to coking coal exports (aCNCNZJKM) for energy-sector context.",
        "related_series": ["aCNCNZJKM", "aCNCNDDVEM", "aCNCNZXDRM"],
    },
    "aCNCNVIZCM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of apple juice from China Customs (~7-10th release). China is the world's largest apple producer and a major global supplier of apple-juice concentrate.",
        "how_to_use": "Seasonal pattern peaks post-autumn harvest (Oct-Jan); monitor for concentration market dynamics globally. Competing exporter volumes from Poland and Ukraine are key benchmarks.",
        "related_series": ["aCNCNVYNMM", "aCNCNAFMZM", "aCNCNZGAM"],
    },
    "aCNCNSHFM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Goods",
        "units": "USD millions",
        "meaning": "Monthly export value of beauty cosmetics and skin-care products from China Customs (~7-10th release). China's beauty export sector has grown rapidly driven by domestic brands expanding into ASEAN and Africa.",
        "how_to_use": "Rising series reflects China's upgrade from low-cost personal-care to branded beauty; destinations include ASEAN, Middle East, and increasingly Europe. A proxy for Chinese soft-power consumer brands.",
        "related_series": ["aCNCNFCCBM", "aCNCNDSIM", "aCNCNBCAZM"],
    },
    "aCNCNDSIM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of beef from China Customs (~7-10th release). China is primarily a beef importer, so export volumes are small and mainly consist of processed/manufactured beef products.",
        "how_to_use": "Relatively minor series; use in conjunction with aCNCNBCAZM to reconcile value vs volume. Divergences may indicate product-mix shifts between fresh, frozen, and processed categories.",
        "related_series": ["aCNCNBCAZM", "aCNCNJEJGM", "aCNCNNQCKM"],
    },
    "aCNCNBCAZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of beef from China Customs (~7-10th release). Volume series complements aCNCNDSIM value data, enabling unit-price calculations for processed beef exports.",
        "how_to_use": "Compare volume vs value (aCNCNDSIM) to derive implicit export price; useful for assessing competitiveness of Chinese processed meats in ASEAN and Middle East markets.",
        "related_series": ["aCNCNDSIM", "aCNCNJEJGM", "aCNCNNOUFM"],
    },
    "aCNCNJOMRM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Steel & Metals",
        "units": "USD millions",
        "meaning": "Monthly export value of steel billets and rough forgings (current prices) from China Customs (~7-10th release). China is the world's largest steel producer (~1 billion tonnes/year) and a major semi-finished steel exporter.",
        "how_to_use": "Surge in billet exports often precedes anti-dumping measures; key markets are ASEAN, Middle East, and South Asia. Compare with aCNCNZCMUM volume series to isolate price vs volume drivers.",
        "related_series": ["aCNCNZCMUM", "aCNCNZPRKM", "aCNCNFHOWM"],
    },
    "aCNCNZCMUM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Steel & Metals",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of steel billets and rough forgings from China Customs (~7-10th release). Volume data is preferred for steel-market analysis as it strips out steel-price volatility.",
        "how_to_use": "High volumes at low prices trigger safeguard duties globally; monitor alongside steel futures (Shanghai Futures Exchange rebar/HR coil) and ASEAN import data for arbitrage signals.",
        "related_series": ["aCNCNJOMRM", "aCNCNZPRKM", "aCNCNKGUPM"],
    },
    "aCNCNZOTVM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Electronics",
        "units": "USD millions",
        "meaning": "Monthly export value of calculators from China Customs (~7-10th release). China dominates global calculator manufacturing; Casio, Texas Instruments, and others source heavily from Chinese factories.",
        "how_to_use": "Proxy for education and office-supply demand in emerging markets; seasonal pickup ahead of back-to-school periods. Use alongside aCNCNDKJM volume series to track unit pricing.",
        "related_series": ["aCNCNDKJM", "aCNCNZERM", "aCNCNSBHRM"],
    },
    "aCNCNDKJM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Electronics",
        "units": "Volume (units, thousands)",
        "meaning": "Monthly export volume of calculators from China Customs (~7-10th release). Volume series for China's calculator exports, enabling per-unit price tracking alongside aCNCNZOTVM.",
        "how_to_use": "Flat or declining volumes with rising values suggest premiumization toward scientific/graphing calculators; compare against aCNCNZERM (keyboards/mice) for overall office-electronics export trend.",
        "related_series": ["aCNCNZOTVM", "aCNCNZERM", "aCNCNTGTIM"],
    },
    "aCNCNOMMUM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Electronics",
        "units": "USD millions",
        "meaning": "Monthly export value of cameras from China Customs (~7-10th release). China manufactures cameras for global brands (Canon, Sony, Nikon) and its own labels; action cameras and security cameras are growth segments.",
        "how_to_use": "Distinguish consumer (smartphone-displacing DSLR decline) from security/surveillance camera growth; the latter is robust but faces US/EU restrictions on Chinese surveillance hardware.",
        "related_series": ["aCNCNTGTIM", "aCNCNZDTWM", "aCNCNSBHRM"],
    },
    "aCNCNJEJGM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of canned pork from China Customs (~7-10th release). China is the world's largest pork producer and exporter of processed pork products to ASEAN and Pacific markets.",
        "how_to_use": "Seasonal demand spikes around Chinese New Year and summer; global pork-price moves and African swine fever cycles affect domestic supply and thus export capacity. Track alongside live-pig exports (aCNCNNQCKM).",
        "related_series": ["aCNCNNQCKM", "aCNCNDSIM", "aCNCNNOUFM"],
    },
    "aCNCNWFNCM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles & Apparel",
        "units": "USD millions",
        "meaning": "Monthly export value of cashmere products from China Customs (~7-10th release). China and Mongolia together supply ~90% of global cashmere fiber; China dominates downstream spinning and garment manufacturing.",
        "how_to_use": "Premium luxury-textile indicator; demand closely tied to European and US high-end retail cycles. Compare with aCNCNPKADM volume to track per-kg export prices and premiumization trends.",
        "related_series": ["aCNCNPKADM", "aCNCNQNLFM", "aCNCNFCCBM"],
    },
    "aCNCNPKADM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles & Apparel",
        "units": "Volume (tonnes)",
        "meaning": "Monthly export volume of cashmere from China Customs (~7-10th release). Volume series complements aCNCNWFNCM value data to derive implicit per-kg export price.",
        "how_to_use": "Volume declines with stable values indicate pricing power and product upgrading; monitor alongside Mongolian raw-cashmere production data for supply-chain context.",
        "related_series": ["aCNCNWFNCM", "aCNCNQNLFM", "aCNCNFCCBM"],
    },
    "aCNCNJMLM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Quarterly export value of cassava products from China Customs. China re-exports cassava-based starch and ethanol products, primarily sourced from ASEAN neighbors for domestic processing.",
        "how_to_use": "Quarterly frequency limits real-time use; relevant for Southeast Asian cassava price dynamics and China's starch/ethanol refining sector margins.",
        "related_series": ["aCNCNQSNM", "aCNCNAHRGM", "aCNCNVYNMM"],
    },
    "aCNCNQSNM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of cassava products from China Customs (~7-10th release). Monthly version of the cassava export series; China's cassava exports are primarily starch and chips to regional markets.",
        "how_to_use": "ASEAN (Thailand, Vietnam) is the key origin for Chinese cassava imports that are then processed and re-exported; shifts reflect China's food-processing competitiveness.",
        "related_series": ["aCNCNJMLM", "aCNCNAHRGM", "aCNCNVYNMM"],
    },
    "aCNCNZXDRM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "USD millions",
        "meaning": "Monthly export value of coke and semi-coke from China Customs (~7-10th release). China is the world's dominant coke exporter; coke is essential for blast-furnace steel production globally.",
        "how_to_use": "Export volumes heavily influence global coking-coal spreads; key buyers are India, Japan, South Korea, and Brazil. Government export quotas are a recurring policy lever, especially during domestic steel demand surges.",
        "related_series": ["aCNCNZJKM", "aCNCNUTOSM", "aCNCNDDVEM"],
    },
    "aCNCNZDTWM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Electronics",
        "units": "USD millions",
        "meaning": "Monthly export value of color television sets (including CKD kits) from China Customs (~7-10th release). China dominates global TV manufacturing with brands TCL, Hisense, Skyworth exporting globally.",
        "how_to_use": "Seasonal peaks ahead of Western holiday shopping (Q4); ASEAN and Africa are growth destinations as Chinese brands displace Japanese/Korean rivals on price. Monitor for EU anti-dumping risk.",
        "related_series": ["aCNCNTGTIM", "aCNCNOMMUM", "aCNCNSBHRM"],
    },
    "aCNCNVYNMM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Chemicals & Agriculture",
        "units": "USD millions",
        "meaning": "Monthly export value of compound fertilizers from China Customs (~7-10th release). China is the world's largest fertilizer producer and exporter of NPK compounds, urea, and DAP.",
        "how_to_use": "Government export quotas restrict outflows during domestic planting seasons (spring/autumn); releases coincide with global fertilizer price surges. Key for global food security and EM agricultural margins.",
        "related_series": ["aCNCNAHRGM", "aCNCNQSNM", "aCNCNAFMZM"],
    },
    "aCNCNFHOWM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Base Metals",
        "units": "USD millions",
        "meaning": "Monthly export value of copper and copper products from China Customs (~7-10th release). China is both the world's largest copper consumer and a significant refined-copper and copper-product exporter.",
        "how_to_use": "Rising copper exports indicate domestic demand weakness or inventory build; acts as a leading indicator for Chinese construction/manufacturing demand. Compare with LME-SHFE copper arbitrage to explain flow direction.",
        "related_series": ["aCNCNZPRKM", "aCNCNKGUPM", "aCNCNBOZEM"],
    },
    "aCNCNAHRGM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of corn from China Customs (~7-10th release). China alternates between net corn importer and exporter depending on domestic harvest; any export surge significantly moves global corn markets.",
        "how_to_use": "Large corn-export announcements (especially to ASEAN and North Africa) pressure CBOT corn futures; monitor alongside domestic corn prices (DCE futures) for export economics.",
        "related_series": ["aCNCNVYNMM", "aCNCNQSNM", "aCNCNJMLM"],
    },
    "aCNCNQNLFM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles & Apparel",
        "units": "USD millions",
        "meaning": "Monthly export value of cotton yarn from China Customs (~7-10th release). China is the world's largest cotton spinner; cotton-yarn exports primarily go to ASEAN garment manufacturers (Bangladesh, Vietnam, Cambodia).",
        "how_to_use": "Reflects competitiveness of Chinese spinning vs regional rivals; rising values can compress downstream ASEAN garment-maker margins. Monitor alongside Chinese cotton import data for full textile supply-chain picture.",
        "related_series": ["aCNCNWFNCM", "aCNCNPKADM", "aCNCNFCCBM"],
    },
    "aCNCNSAWNM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "USD millions",
        "meaning": "Monthly export value of crude oil from China Customs (~7-10th release). China is primarily a large crude importer (~11 mb/d), so crude oil exports are minor re-exports or condensate streams.",
        "how_to_use": "Small and volatile series; compare against crude import data (aCNCNIPQCM volume) to assess refinery throughput and any arbitrage-driven re-export activity. Limited global market impact.",
        "related_series": ["aCNCNIPQCM", "aCNCNZMHBM", "aCNCNZSHSM"],
    },
    "aCNCNIPQCM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of crude oil from China Customs (~7-10th release). Volume series for China's crude-oil exports, enabling per-barrel price comparison against aCNCNSAWNM value.",
        "how_to_use": "Primarily tracks small re-export or processing-trade crude flows; combine with China's crude import volume data for a net-balance view of Chinese oil trade.",
        "related_series": ["aCNCNSAWNM", "aCNCNZMHBM", "aCNCNZSHSM"],
    },
    "aCNCNZMHBM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of crude oil (secondary series) from China Customs (~7-10th release). Likely captures a different classification category of crude or condensate exports vs aCNCNIPQCM.",
        "how_to_use": "Use alongside aCNCNIPQCM to build a complete crude-export volume picture; differences may reflect condensate vs full-range crude categorizations under China Customs HS codes.",
        "related_series": ["aCNCNIPQCM", "aCNCNSAWNM", "aCNCNZSHSM"],
    },
    "aCNCNMTFSM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Aggregate",
        "units": "USD millions",
        "meaning": "Monthly aggregate current-price export value from China Customs (~7-10th release). Headline current-price total merchandise export series, the most widely cited export indicator for China.",
        "how_to_use": "Consensus forecasts generate significant market moves on release; ~$300B/month recently. Surprise vs consensus shifts USD/CNY, EM equities, and commodity futures. Top destinations: ASEAN, US, EU.",
        "related_series": ["aCNCEXPB/A", "aCNCEXPYB/A", "aCNCIMPB/A"],
    },
    "aCNCNZFLZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of dairy products from China Customs (~7-10th release). China is primarily a dairy importer; small dairy exports are mainly infant formula and UHT milk to ASEAN and developing markets.",
        "how_to_use": "Niche series; rising exports may indicate excess domestic supply or competitiveness gains in processed dairy. Monitor alongside Chinese milk production data for domestic oversupply signals.",
        "related_series": ["aCNCNDSIM", "aCNCNBCAZM", "aCNCNNOUFM"],
    },
    "aCNCNZSHSM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "USD millions",
        "meaning": "Monthly export value of diesel fuel from China Customs (~7-10th release). China periodically exports surplus diesel when refinery runs exceed domestic demand; key buyers are ASEAN and Africa.",
        "how_to_use": "Export quotas (permits) are issued by NDRC; quota tightening reduces global diesel supply and lifts Asian refinery crack spreads. Correlates with Sinopec/PetroChina refinery run rates.",
        "related_series": ["aCNCNSAWNM", "aCNCNIPQCM", "aCNCNZCNBM"],
    },
    "aCNCNSBHRM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Electronics",
        "units": "USD millions",
        "meaning": "Monthly export value of displays (panels) from China Customs (~7-10th release). China's BOE, CSOT, and HKC have surpassed Korean and Taiwanese rivals in LCD panel production for TVs and monitors.",
        "how_to_use": "Panel export value tracks global TV and monitor demand cycles; seasonal Q3 build-ahead-of-holiday peak is typical. Relevant for BOE and downstream global TV brand margins.",
        "related_series": ["aCNCNZDTWM", "aCNCNCGZLM", "aCNCNOMMUM"],
    },
    "aCNCNWHCDM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of dried pepper from China Customs (~7-10th release). China is a major producer of chili peppers and dried spices; key export destinations include ASEAN, Middle East, and South Asia.",
        "how_to_use": "Seasonal harvest patterns (autumn peak); monitor alongside Indian spice exports for global pepper price competition. Relatively small series but useful for agricultural commodity tracking.",
        "related_series": ["aCNCNVIZCM", "aCNCNAFMZM", "aCNCNZGAM"],
    },
    "aCNCNUMTSM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Automotive",
        "units": "USD millions",
        "meaning": "Monthly export value of engined car chassis from China Customs (~7-10th release). China's auto chassis exports support CKD assembly operations in Africa, ASEAN, and Latin America for both ICE and EV platforms.",
        "how_to_use": "Rising chassis exports indicate expansion of Chinese OEM overseas assembly strategies (SAIC, Great Wall, Chery); correlates with tariff-evasion strategies in response to EU/US vehicle import duties.",
        "related_series": ["aCNCNZENM", "aCNCNSBHRM", "aCNCNMTFSM"],
    },
    "aCNCNZENM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Critical Minerals",
        "units": "USD millions",
        "meaning": "Monthly export value of fluorite (fluorspar) from China Customs (~7-10th release). China holds ~60% of global fluorite reserves and dominates exports of this key input for hydrofluoric acid, refrigerants, and aluminum smelting.",
        "how_to_use": "Subject to export quotas; restrictions tighten hydrofluoric acid and refrigerant supply globally. Watch for Chinese quota reduction announcements, which immediately impact specialty chemical and semiconductor fab costs.",
        "related_series": ["aCNCNRKRHM", "aCNCNEYAYM", "aCNCNPKLIM"],
    },
    "aCNCNROSBM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of fresh and frozen shrimp from China Customs (~7-10th release). China is a top global shrimp producer and exporter; key markets are Japan, US, and EU.",
        "how_to_use": "Seasonal demand peaks ahead of holidays; aquaculture disease outbreaks (white spot, EMS) affect supply. Compare with aCNCNOHHMM (frozen shrimp only) to decompose product-form mix.",
        "related_series": ["aCNCNOHHMM", "aCNCNMPTM", "aCNCNNOUFM"],
    },
    "aCNCNNOUFM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of frozen chicken from China Customs (~7-10th release). China is a major frozen-chicken exporter mainly to Japan, Hong Kong, and ASEAN; avian influenza outbreaks periodically disrupt flows.",
        "how_to_use": "Bird-flu surveillance data is the key risk variable; bilateral import bans after AI outbreaks cause sharp export drops. Seasonal processing peaks in Q3-Q4 align with Northern Hemisphere autumn demand.",
        "related_series": ["aCNCNJEJGM", "aCNCNDSIM", "aCNCNROSBM"],
    },
    "aCNCNMPTM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of frozen fish and frozen fish fillets from China Customs (~7-10th release). China is the world's largest fish processor; it imports raw fish (Alaska pollock, Pacific cod) and re-exports processed fillets.",
        "how_to_use": "Track alongside US/Russian pollock harvest data, as China re-exports processed fillets to EU and US; tariff escalation (Section 301 tariffs on seafood) disrupts these flows.",
        "related_series": ["aCNCNALCHM", "aCNCNROSBM", "aCNCNNOUFM"],
    },
    "aCNCNALCHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of frozen fish and frozen fish fillets from China Customs (~7-10th release). Volume series for China's frozen-fish exports; pairs with aCNCNMPTM value to derive per-kg export price.",
        "how_to_use": "Rising volumes with flat values signal oversupply or price pressure; relevant for global seafood processing margins and Alaska pollock/Pacific cod commodity pricing.",
        "related_series": ["aCNCNMPTM", "aCNCNROSBM", "aCNCNOHHMM"],
    },
    "aCNCNOHHMM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of frozen shrimp from China Customs (~7-10th release). Distinct from aCNCNROSBM which includes fresh shrimp; frozen shrimp is the dominant traded form for retail and food-service.",
        "how_to_use": "Key indicator for global farmed-shrimp markets; compare with Ecuador and India shrimp export data for competitive positioning. Buyer destinations: Japan, US, EU food processors.",
        "related_series": ["aCNCNROSBM", "aCNCNMPTM", "aCNCNALCHM"],
    },
    "aCNCNZCNBM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "USD millions",
        "meaning": "Monthly export value of gaseous (compressed/liquefied) gas from China Customs (~7-10th release). Covers compressed natural gas (CNG) and possibly LPG exports from China's growing gas infrastructure.",
        "how_to_use": "Small but growing series as China builds gas export infrastructure; relevant for regional (ASEAN, Central Asia) natural gas market development and pipeline-vs-LNG competition.",
        "related_series": ["aCNCNZSHSM", "aCNCNSAWNM", "aCNCNIPQCM"],
    },
    "aCNCNZFLM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Construction & Materials",
        "units": "USD millions",
        "meaning": "Monthly export value of glass products from China Customs (~7-10th release). China dominates global flat-glass and specialty-glass production; solar-panel glass is a high-growth export as China holds 80%+ of global solar PV manufacturing.",
        "how_to_use": "Solar glass exports face anti-dumping duties in EU and India; monitor trade-remedy filings. Solar panel installation pipeline globally drives demand for Chinese solar glass. Also relevant for construction-demand indicators.",
        "related_series": ["aCNCNSBHRM", "aCNCNZDTWM", "aCNCNJOMRM"],
    },
    "aCNCNCGZLM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Telecommunications",
        "units": "USD millions",
        "meaning": "Monthly export value of handheld radiotelephones (mobile phones) and parts from China Customs (~7-10th release). China manufactures ~70% of the world's smartphones; Apple (iPhone), Samsung, and Chinese OEMs (Xiaomi, OPPO, vivo) all ship from China.",
        "how_to_use": "One of China's largest single export categories (~$150B+/year); sensitive to US tariff escalation (Section 301) and supply-chain relocation to India/Vietnam. iPhone launch cycles create Q3-Q4 seasonal peaks.",
        "related_series": ["aCNCNSBHRM", "aCNCNZDTWM", "aCNCNZERM"],
    },
    "aCNCNAFMZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of ketchup (tomato paste/sauce) from China Customs (~7-10th release). China is the world's second-largest tomato processor; Xinjiang tomatoes dominate Chinese tomato-paste exports to Africa and ASEAN.",
        "how_to_use": "Seasonal processing peak following summer harvest; African and Middle Eastern buyers dominate. Compare with aCNCNZGAM for volume to track pricing trends in bulk tomato paste.",
        "related_series": ["aCNCNZGAM", "aCNCNFRADM", "aCNCNVIZCM"],
    },
    "aCNCNZGAM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of ketchup (tomato products) from China Customs (~7-10th release). Likely represents a different HS sub-category or aggregation level of tomato products vs aCNCNAFMZM.",
        "how_to_use": "Use alongside aCNCNAFMZM and aCNCNFRADM to build a complete picture of China's tomato-product exports; discrepancies indicate product-mix shifts between paste, sauce, and whole tomatoes.",
        "related_series": ["aCNCNAFMZM", "aCNCNFRADM", "aCNCNVIZCM"],
    },
    "aCNCNFRADM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of ketchup/tomato products from China Customs (~7-10th release). Volume series for China's tomato-product exports; use with aCNCNAFMZM value data to derive per-tonne pricing.",
        "how_to_use": "Xinjiang harvest-year quality and yield are key supply drivers; African state buyers' purchasing patterns create lumpy demand. Volume peaks in Q1-Q2 following autumn harvest processing.",
        "related_series": ["aCNCNAFMZM", "aCNCNZGAM", "aCNCNVIZCM"],
    },
    "aCNCNZERM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Consumer Electronics",
        "units": "Volume (units, thousands)",
        "meaning": "Monthly export volume of keyboards and mice from China Customs (~7-10th release). China manufactures the vast majority of global PC peripherals; Logitech, Razer, and most white-label brands source from Chinese factories.",
        "how_to_use": "Tracks global PC and gaming peripheral demand cycle; WFH demand surge (2020-21) and subsequent normalization are visible in this series. Compare against aCNCNDKJM and aCNCNCGZLM for electronics cycle picture.",
        "related_series": ["aCNCNDKJM", "aCNCNZOTVM", "aCNCNCGZLM"],
    },
    "aCNCNFCCBM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Textiles & Apparel",
        "units": "USD millions",
        "meaning": "Monthly export value of leather gloves from China Customs (~7-10th release). China dominates global glove manufacturing for work, fashion, and sport segments; key buyers are EU and North America.",
        "how_to_use": "Labor-cost sensitivity makes this a canary for Chinese apparel-export competitiveness vs Bangladesh and Vietnam. Seasonal demand peaks pre-winter (Q3-Q4 Northern Hemisphere orders).",
        "related_series": ["aCNCNWFNCM", "aCNCNPKADM", "aCNCNQNLFM"],
    },
    "aCNCNDDVEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Energy & Fuels",
        "units": "USD millions",
        "meaning": "Monthly export value of lignite (brown coal) from China Customs (~7-10th release). China's lignite exports are small as most lignite is consumed near mine-mouth for power generation; exports are mainly to regional buyers.",
        "how_to_use": "Minor coal-export series; use alongside anthracite (aCNCNUTOSM) and coking coal (aCNCNZJKM) for a complete view of China's coal-export basket by grade.",
        "related_series": ["aCNCNUTOSM", "aCNCNZJKM", "aCNCNZXDRM"],
    },
    "aCNCNNQCKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of live pigs (non-breeding) from China Customs (~7-10th release). China's live-pig exports go primarily to Hong Kong and Macao; volumes are sensitive to African swine fever (ASF) outbreaks.",
        "how_to_use": "ASF epidemic cycles (2018-19 decimated Chinese herd; partial recovery by 2022) drive sharp swings; Hong Kong pork prices closely track these flows. Use alongside canned pork (aCNCNJEJGM) for complete pork export picture.",
        "related_series": ["aCNCNJEJGM", "aCNCNDSIM", "aCNCNBCAZM"],
    },
    "aCNCNPKLIM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Critical Minerals",
        "units": "USD millions",
        "meaning": "Monthly export value of magnesium and magnesium products (including scrap) from China Customs (~7-10th release). China produces ~85% of the world's primary magnesium, primarily in Shaanxi and Shanxi provinces.",
        "how_to_use": "2021 Chinese energy crisis caused magnesium output collapse, spiking global prices and threatening European aluminum-alloy and automotive supply chains. Monitor Chinese power-shortage signals as a leading indicator.",
        "related_series": ["aCNCNZNLHM", "aCNCNZPRKM", "aCNCNFHOWM"],
    },
    "aCNCNZNLHM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Critical Minerals",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of magnesium and magnesium products from China Customs (~7-10th release). Volume series for China's magnesium exports; pairs with aCNCNPKLIM value to derive per-tonne export price.",
        "how_to_use": "Volume contraction (as in H2 2021) with price spikes signals genuine supply squeeze vs price-driven demand destruction; critical for European auto-parts and aerospace supply-chain risk models.",
        "related_series": ["aCNCNPKLIM", "aCNCNZPRKM", "aCNCNKGUPM"],
    },
    "aCNCNFNXDM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of manufactured/preserved squid (current prices) from China Customs (~7-10th release). China processes squid from domestic fisheries and imported raw squid into preserved/canned/frozen products for export.",
        "how_to_use": "South American Humboldt squid supply (Peru/Argentina IUU fishing indicators) affects Chinese raw-squid import costs and thus export competitiveness. Japan and South Korea are key markets.",
        "related_series": ["aCNCNHYCKM", "aCNCNOYVOM", "aCNCNBMXLM"],
    },
    "aCNCNHYCKM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of manufactured/preserved squid (current prices, secondary series) from China Customs (~7-10th release). Likely captures a different HS sub-category or product form of preserved squid vs aCNCNFNXDM.",
        "how_to_use": "Use alongside aCNCNFNXDM to reconcile total squid-export value; discrepancies illuminate product-mix shifts between dried, canned, and frozen-prepared squid categories.",
        "related_series": ["aCNCNFNXDM", "aCNCNOYVOM", "aCNCNNGBZM"],
    },
    "aCNCNOYVOM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of manufactured/preserved squid from China Customs (~7-10th release). One of multiple series tracking China's squid-product exports under different HS code aggregations.",
        "how_to_use": "Aggregate with related squid series (aCNCNFNXDM, aCNCNHYCKM, aCNCNBMXLM) to build total squid export picture; useful for global cephalopod market analysis.",
        "related_series": ["aCNCNFNXDM", "aCNCNBMXLM", "aCNCNNGBZM"],
    },
    "aCNCNBMXLM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of manufactured/preserved squid from China Customs (~7-10th release). Volume series for China's preserved-squid exports; use with value series to compute per-kg export price.",
        "how_to_use": "Volume vs value divergence indicates changing product mix or pricing power; Japanese and South Korean retail demand cycles create seasonal patterns. Compare with global squid catch data for supply signals.",
        "related_series": ["aCNCNOYVOM", "aCNCNFNXDM", "aCNCNIZKEM"],
    },
    "aCNCNNGBZM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "USD millions",
        "meaning": "Monthly export value of manufactured/preserved squid (additional series) from China Customs (~7-10th release). Captures a further HS sub-category of processed squid products in China's export classification.",
        "how_to_use": "Use in aggregate with other squid series for total market size; individually tracks specific product-form exports (e.g., squid rings, tubes) for foodservice vs retail destination analysis.",
        "related_series": ["aCNCNBMXLM", "aCNCNIZKEM", "aCNCNFNXDM"],
    },
    "aCNCNIZKEM": {
        "slug": "cn_imports_exports",
        "subcategory": "Exports — Agricultural & Food",
        "units": "Volume (thousand tonnes)",
        "meaning": "Monthly export volume of manufactured/preserved squid (additional volume series) from China Customs (~7-10th release). Final squid volume series in the batch; captures residual HS sub-categories of squid products.",
        "how_to_use": "Aggregate all six squid series (aCNCNFNXDM through aCNCNIZKEM) for China's total processed-squid export footprint; useful for global squid commodity pricing and fishing-quota impact analysis.",
        "related_series": ["aCNCNNGBZM", "aCNCNBMXLM", "aCNCNOYVOM"],
    },
}
