"""US Reuters Polls — Batch 04 (Trade, Capital Flows, Prices)."""
TIER1: dict[str, dict] = {
    # ── International Trade Balance ──────────────────────────────────────────
    "USTBAL=ECI": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Actual monthly US International Trade Balance (goods + services) from Census/BEA, released ~5-7th of the following month. A negative value indicates a deficit; readings typically run -$60B to -$100B.",
        "how_to_use": "Compare against the Reuters poll median (pUSTBAL=M) to gauge the surprise; a miss wider than $5B can move USD, equity futures, and GDP nowcast models that treat net exports as a direct component.",
        "related_series": ["pUSTBAL=M", "pUSTBAL=E", "pUSTBAL=T", "aUSGS/A"],
    },
    "pUSTBAL=M": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Median consensus forecast for the US International Trade Balance from the Reuters economist poll, collected ~1 week before release. The median is the most widely cited benchmark for market expectations.",
        "how_to_use": "Plot alongside USTBAL=ECI to track revision history and surprise magnitude; persistent deficit misses vs consensus signal structural import demand shifts or export softness relevant for USD and sector ETFs.",
        "related_series": ["USTBAL=ECI", "pUSTBAL=E", "pUSTBAL=T", "pUSTBAL=C"],
    },
    "pUSTBAL=F": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "SmartEconomics model-based forecast for the US Trade Balance, derived algorithmically from high-frequency data inputs rather than a human panel survey.",
        "how_to_use": "Compare to pUSTBAL=M to assess whether systematic models are more bullish or bearish on the deficit than human forecasters; divergences can signal that the model has captured recent import/export data not yet in consensus.",
        "related_series": ["USTBAL=ECI", "pUSTBAL=M", "pUSTBAL=P", "pUSTBAL=E"],
    },
    "pUSTBAL=P": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Predicted Surprise for the US Trade Balance — the systematic component of expected deviation between the actual release and the median poll forecast.",
        "how_to_use": "A positive predicted surprise implies the actual print will likely beat (narrower deficit than) consensus; use alongside pUSTBAL=T to assess risk-reward for positioning around the release.",
        "related_series": ["USTBAL=ECI", "pUSTBAL=M", "pUSTBAL=F", "pUSTBAL=T"],
    },
    "pUSTBAL=E": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Mean (arithmetic average) forecast for the US Trade Balance from the Reuters panel, which unlike the median can be skewed by outlier forecasters with extreme deficit or surplus views.",
        "how_to_use": "When pUSTBAL=E diverges materially from pUSTBAL=M, the distribution of forecasts is skewed; a mean more negative than the median implies downside tail risk to the deficit that markets may be underpricing.",
        "related_series": ["USTBAL=ECI", "pUSTBAL=M", "pUSTBAL=L", "pUSTBAL=H"],
    },
    "pUSTBAL=O": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Mode forecast for the US Trade Balance — the single most frequently cited estimate among Reuters poll respondents.",
        "how_to_use": "A mode well away from the median indicates a bimodal or multi-clustered distribution of forecaster views, often reflecting genuine uncertainty around trade policy; use alongside pUSTBAL=L/H to map the full range.",
        "related_series": ["USTBAL=ECI", "pUSTBAL=M", "pUSTBAL=L", "pUSTBAL=H"],
    },
    "pUSTBAL=L": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Minimum (most pessimistic / widest-deficit) forecast for the US Trade Balance in the Reuters poll, representing the most bearish economist estimate.",
        "how_to_use": "Use with pUSTBAL=H to define the full forecast range; if the actual print falls outside this range it is a major surprise that will drive outsized USD and equity moves.",
        "related_series": ["pUSTBAL=H", "pUSTBAL=T", "pUSTBAL=M", "USTBAL=ECI"],
    },
    "pUSTBAL=H": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Maximum (most optimistic / narrowest-deficit) forecast for the US Trade Balance in the Reuters poll, representing the most bullish economist estimate.",
        "how_to_use": "The H-L range together with pUSTBAL=T quantifies consensus uncertainty ahead of the release; use to size option structures or set stop levels around the trade data event.",
        "related_series": ["pUSTBAL=L", "pUSTBAL=T", "pUSTBAL=M", "USTBAL=ECI"],
    },
    "pUSTBAL=T": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "USD billions",
        "meaning": "Standard deviation of forecasts in the Reuters US Trade Balance poll, measuring the degree of disagreement among economists ahead of the release.",
        "how_to_use": "Elevated standard deviation (relative to recent history) warns of high event risk; combine with pUSTBAL=M to construct an implied confidence interval and calibrate position sizing for the release.",
        "related_series": ["pUSTBAL=M", "pUSTBAL=L", "pUSTBAL=H", "pUSTBAL=C"],
    },
    "pUSTBAL=C": {
        "slug": "us_polls",
        "subcategory": "International Trade $",
        "units": "Count",
        "meaning": "Number of economists submitting forecasts in the Reuters US Trade Balance poll for the current release cycle.",
        "how_to_use": "A low forecaster count (fewer than ~15) reduces reliability of the median and standard deviation; track over time to ensure sample size is sufficient before relying on consensus statistics.",
        "related_series": ["pUSTBAL=M", "pUSTBAL=T", "pUSTBAL=E", "USTBAL=ECI"],
    },
    # ── Foreign Buying T-Bonds (TIC) ─────────────────────────────────────────
    "USFBT=ECI": {
        "slug": "us_polls",
        "subcategory": "Foreign Buying, T-Bonds",
        "units": "USD billions",
        "meaning": "Actual monthly net foreign purchases of US Treasury bonds from the Treasury International Capital (TIC) report, released with a ~6-week lag. Positive values indicate net foreign buying; negative values indicate net selling.",
        "how_to_use": "Monitor for sustained shifts in foreign appetite for Treasuries — large net selling episodes (especially by official holders) can pressure long-end yields; use alongside USNCI=ECI for the full cross-border capital picture.",
        "related_series": ["USNCI=ECI", "USTBAL=ECI", "aUSCURACFT", "aUSGFD"],
    },
    # ── Net L-T Flows Ex-Swaps (TIC) ─────────────────────────────────────────
    "USNCI=ECI": {
        "slug": "us_polls",
        "subcategory": "Net L-T Flows, Ex-Swaps",
        "units": "USD billions",
        "meaning": "Actual monthly net long-term cross-border securities flows excluding swap-related transactions, from the TIC report. Captures combined foreign purchases of US stocks, bonds, and agencies minus US purchases of foreign securities.",
        "how_to_use": "A broader capital-flow gauge than T-bond buying alone; persistent positive flows underpin USD demand and finance the current-account deficit, while a sustained decline can signal portfolio rebalancing away from US assets.",
        "related_series": ["USFBT=ECI", "USTBAL=ECI", "aUSCURACFT", "aUSGFD"],
    },
    # ── Import Prices MM ──────────────────────────────────────────────────────
    "USIMP=ECI": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Actual month-over-month change in US Import Prices from the BLS, released ~mid-month. Captures price pressures entering the US economy from abroad, driven by commodity prices, FX, and global supply-chain conditions.",
        "how_to_use": "Compare to pUSIMP=M to assess the surprise; a larger-than-expected increase raises pass-through inflation risk and can lift breakeven inflation rates and front-end yields.",
        "related_series": ["pUSIMP=M", "USIPI=ECI", "USEXP=ECI", "aUSIMPP"],
    },
    "pUSIMP=M": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Median consensus forecast for US Import Prices month-over-month from the Reuters poll, collected ahead of the BLS mid-month release.",
        "how_to_use": "Use as the key benchmark for the release; an actual print above the median — especially in a tariff-sensitive environment — reinforces inflation persistence narratives and weighs on rate-cut expectations.",
        "related_series": ["USIMP=ECI", "pUSIMP=E", "pUSIMP=T", "pUSIMP=C"],
    },
    "pUSIMP=F": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "SmartEconomics algorithmic forecast for US Import Prices MoM, providing a model-derived estimate ahead of the BLS release.",
        "how_to_use": "Divergence between pUSIMP=F and pUSIMP=M highlights cases where high-frequency commodity/FX inputs disagree with human forecasters; a higher SmartEcon forecast signals commodity or USD-driven upside risk.",
        "related_series": ["USIMP=ECI", "pUSIMP=M", "pUSIMP=P", "pUSIMP=E"],
    },
    "pUSIMP=P": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Predicted Surprise for US Import Prices MoM — the systematic expected deviation of the actual from the median consensus.",
        "how_to_use": "A positive predicted surprise suggests the actual MoM print will likely exceed consensus; combine with pUSIMP=T to assess confidence in that directional call before the BLS release.",
        "related_series": ["USIMP=ECI", "pUSIMP=M", "pUSIMP=F", "pUSIMP=T"],
    },
    "pUSIMP=E": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Mean forecast for US Import Prices MoM across all Reuters poll respondents, which may diverge from the median when a minority of forecasters hold outsized views on commodity or currency moves.",
        "how_to_use": "When the mean exceeds the median, the distribution is right-skewed, implying more upside than downside risk to import inflation; relevant for USD and TIPS positioning ahead of the release.",
        "related_series": ["USIMP=ECI", "pUSIMP=M", "pUSIMP=L", "pUSIMP=H"],
    },
    "pUSIMP=O": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Mode forecast for US Import Prices MoM — the most commonly submitted estimate in the Reuters panel.",
        "how_to_use": "If the mode differs markedly from the median, forecasters are clustered around two distinct scenarios (e.g., energy-driven spike vs. soft reading); useful for scenario-weighting in macro overlays.",
        "related_series": ["USIMP=ECI", "pUSIMP=M", "pUSIMP=L", "pUSIMP=H"],
    },
    "pUSIMP=L": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Minimum (most deflationary) forecast for US Import Prices MoM in the Reuters poll, marking the floor of economist expectations.",
        "how_to_use": "Together with pUSIMP=H, defines the full forecast range; an actual reading below the floor is a rare disinflationary shock that would strengthen rate-cut expectations and weigh on commodity currencies.",
        "related_series": ["pUSIMP=H", "pUSIMP=T", "pUSIMP=M", "USIMP=ECI"],
    },
    "pUSIMP=H": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Maximum (most inflationary) forecast for US Import Prices MoM in the Reuters poll, marking the ceiling of economist expectations.",
        "how_to_use": "Use the H-L spread as a proxy for forecast uncertainty around global commodity and FX conditions; a wide spread warrants larger volatility allowances in inflation-sensitive strategies.",
        "related_series": ["pUSIMP=L", "pUSIMP=T", "pUSIMP=M", "USIMP=ECI"],
    },
    "pUSIMP=T": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Percent",
        "meaning": "Standard deviation of forecasts for US Import Prices MoM in the Reuters poll, indicating economist disagreement about near-term import inflation.",
        "how_to_use": "High standard deviation ahead of the release (relative to recent cycles) suggests increased sensitivity to oil prices or FX volatility; combine with pUSIMP=M to construct a symmetric surprise range for risk management.",
        "related_series": ["pUSIMP=M", "pUSIMP=L", "pUSIMP=H", "pUSIMP=C"],
    },
    "pUSIMP=C": {
        "slug": "us_polls",
        "subcategory": "Import Prices MM",
        "units": "Count",
        "meaning": "Number of economists submitting forecasts in the Reuters US Import Prices MoM poll for the current release.",
        "how_to_use": "Track alongside pUSIMP=T to ensure the standard deviation is based on a sufficiently large sample; a falling count may signal declining market interest in import-price risk ahead of a data release.",
        "related_series": ["pUSIMP=M", "pUSIMP=T", "pUSIMP=E", "USIMP=ECI"],
    },
    # ── Import Prices YY ──────────────────────────────────────────────────────
    "USIPI=ECI": {
        "slug": "us_polls",
        "subcategory": "Import Prices YY",
        "units": "Percent",
        "meaning": "Actual year-over-year change in US Import Prices from the BLS, the 12-month cumulative view of import inflation that smooths monthly volatility from energy price swings.",
        "how_to_use": "The YoY rate is more relevant for trend-inflation monitoring and TIPS breakeven analysis; compare with the MoM actual (USIMP=ECI) to distinguish trend from noise and assess tariff pass-through over time.",
        "related_series": ["USIMP=ECI", "pUSIMP=M", "USEXP=ECI", "aUSIMPP"],
    },
    # ── Export Prices MM ──────────────────────────────────────────────────────
    "USEXP=ECI": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Actual month-over-month change in US Export Prices from the BLS, measuring price competitiveness of US goods in global markets and the terms-of-trade dynamics.",
        "how_to_use": "Compare to pUSEXP=M for the surprise; rising export prices can improve the terms of trade and narrow the nominal trade deficit, but may also signal lost competitiveness if driven by USD strength rather than demand.",
        "related_series": ["pUSEXP=M", "USIMP=ECI", "USTBAL=ECI", "aUSEXPP"],
    },
    "pUSEXP=M": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Median consensus forecast for US Export Prices month-over-month from the Reuters poll, the central market expectation ahead of the BLS mid-month release.",
        "how_to_use": "Pair with pUSIMP=M to track expected terms-of-trade shifts; when export price expectations diverge from import price expectations, it signals a changing relative-price dynamic with FX and sector implications.",
        "related_series": ["USEXP=ECI", "pUSEXP=E", "pUSEXP=T", "pUSIMP=M"],
    },
    "pUSEXP=F": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "SmartEconomics algorithmic forecast for US Export Prices MoM, providing a model-derived estimate that draws on commodity prices and USD index data.",
        "how_to_use": "Divergence from pUSEXP=M signals where commodity and FX models diverge from human analyst consensus; relevant when agricultural or energy export prices are moving sharply.",
        "related_series": ["USEXP=ECI", "pUSEXP=M", "pUSEXP=P", "pUSIMP=F"],
    },
    "pUSEXP=P": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Predicted Surprise for US Export Prices MoM — the systematic expected deviation of the actual from the Reuters median consensus.",
        "how_to_use": "Use alongside pUSIMP=P to assess whether import and export price surprises are expected to move in the same or opposite direction, which has different implications for the trade balance and terms of trade.",
        "related_series": ["USEXP=ECI", "pUSEXP=M", "pUSEXP=F", "pUSIMP=P"],
    },
    "pUSEXP=E": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Mean forecast for US Export Prices MoM across all Reuters poll respondents, sensitive to outlier views on agricultural commodity or energy price trajectories.",
        "how_to_use": "A mean notably above the median suggests a right-skewed distribution driven by a subset of forecasters pricing in commodity-export price spikes; relevant for agri-commodity and energy-sector positioning.",
        "related_series": ["USEXP=ECI", "pUSEXP=M", "pUSEXP=L", "pUSEXP=H"],
    },
    "pUSEXP=O": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Mode forecast for US Export Prices MoM — the most frequently submitted individual estimate in the Reuters economist panel.",
        "how_to_use": "A mode equal to the median confirms a unimodal, consensus-aligned distribution; deviation implies bifurcated views on export-price drivers such as grain or LNG pricing.",
        "related_series": ["USEXP=ECI", "pUSEXP=M", "pUSEXP=L", "pUSEXP=H"],
    },
    "pUSEXP=L": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Minimum forecast for US Export Prices MoM in the Reuters poll, representing the most deflationary individual estimate in the panel.",
        "how_to_use": "Use with pUSEXP=H to bound the distribution of outcomes; an actual print below the floor signals unexpected export deflation, potentially from USD appreciation or weak global demand.",
        "related_series": ["pUSEXP=H", "pUSEXP=T", "pUSEXP=M", "USEXP=ECI"],
    },
    "pUSEXP=H": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Maximum forecast for US Export Prices MoM in the Reuters poll, representing the most inflationary individual estimate in the panel.",
        "how_to_use": "The H-L range captures the full spectrum of economist views on global price conditions; a wide range relative to pUSEXP=T indicates distribution tails may be driven by commodity-price outliers.",
        "related_series": ["pUSEXP=L", "pUSEXP=T", "pUSEXP=M", "USEXP=ECI"],
    },
    "pUSEXP=T": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Percent",
        "meaning": "Standard deviation of forecasts for US Export Prices MoM in the Reuters poll, a direct measure of uncertainty about near-term export-price dynamics.",
        "how_to_use": "Compare with pUSIMP=T: when export-price standard deviation is low but import-price standard deviation is high, terms-of-trade uncertainty is dominated by import-side risk, e.g., from tariff uncertainty.",
        "related_series": ["pUSEXP=M", "pUSEXP=L", "pUSEXP=H", "pUSIMP=T"],
    },
    "pUSEXP=C": {
        "slug": "us_polls",
        "subcategory": "Export Prices MM",
        "units": "Count",
        "meaning": "Number of economists participating in the Reuters US Export Prices MoM poll for the current release cycle.",
        "how_to_use": "A smaller panel for export prices (vs. trade balance) is common; track to ensure the median is statistically meaningful before using it as an event benchmark.",
        "related_series": ["pUSEXP=M", "pUSEXP=T", "pUSEXP=E", "USEXP=ECI"],
    },
    # ── Federal Budget ────────────────────────────────────────────────────────
    "USGDEF=ECI": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Actual monthly US Federal Budget surplus or deficit from the Treasury Monthly Statement, released ~10th of the following month. Negative values indicate a deficit; large monthly deficits typically occur in April and September.",
        "how_to_use": "Compare against the Reuters poll median (pUSGDEF=M) for the surprise; cumulative fiscal-year deficits relative to CBO projections drive Treasury supply forecasts and term-premium dynamics in the long end.",
        "related_series": ["pUSGDEF=M", "pUSGDEF=E", "aUSGDEFAA", "aUSGFD"],
    },
    "pUSGDEF=M": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Median consensus forecast for the monthly US Federal Budget balance from the Reuters poll, the central market expectation before the Treasury Monthly Statement.",
        "how_to_use": "Budget surprises are driven by tax receipt timing and outlay volatility; a materially narrower-than-expected deficit can temporarily reduce Treasury issuance expectations and compress long-end yields.",
        "related_series": ["USGDEF=ECI", "pUSGDEF=E", "pUSGDEF=T", "aUSGDEFAA"],
    },
    "pUSGDEF=F": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "SmartEconomics algorithmic forecast for the monthly US Federal Budget balance, using high-frequency Treasury cash-flow data to estimate the official monthly figure.",
        "how_to_use": "SmartEcon has an advantage on the federal budget because Treasury publishes daily cash data (Daily Treasury Statement); divergence from pUSGDEF=M often reflects the model incorporating recent DTS flows that human forecasters have not updated.",
        "related_series": ["USGDEF=ECI", "pUSGDEF=M", "pUSGDEF=P", "aUSGDEFAA"],
    },
    "pUSGDEF=P": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Predicted Surprise for the US Federal Budget — the systematic expected deviation between the actual monthly balance and the Reuters median forecast.",
        "how_to_use": "Combine with pUSGDEF=T: a large positive predicted surprise (surplus beat) alongside low standard deviation gives high-conviction signal for Treasury market positioning ahead of the release.",
        "related_series": ["USGDEF=ECI", "pUSGDEF=M", "pUSGDEF=F", "pUSGDEF=T"],
    },
    "pUSGDEF=E": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Mean forecast for the monthly US Federal Budget balance across all Reuters poll respondents, potentially skewed by outlier estimates around large tax-receipt months.",
        "how_to_use": "When the mean is materially more negative (larger deficit) than the median, a subset of forecasters is pricing in unusual outlays or lower-than-typical receipts; relevant for tail-risk assessment in duration-sensitive portfolios.",
        "related_series": ["USGDEF=ECI", "pUSGDEF=M", "pUSGDEF=L", "pUSGDEF=H"],
    },
    "pUSGDEF=O": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Mode forecast for the monthly US Federal Budget balance — the single most commonly submitted estimate among Reuters panel economists.",
        "how_to_use": "A mode clustered far from the median suggests genuinely bifurcated fiscal views, perhaps around whether a month's tax receipts will be above or below trend; cross-reference with Daily Treasury Statement data.",
        "related_series": ["USGDEF=ECI", "pUSGDEF=M", "pUSGDEF=L", "pUSGDEF=H"],
    },
    "pUSGDEF=L": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Minimum (most bearish / largest-deficit) forecast for the monthly US Federal Budget balance in the Reuters poll.",
        "how_to_use": "Use with pUSGDEF=H to frame the full range of fiscal outcomes; an actual print below this floor — implying a larger-than-expected deficit — could steepen the yield curve by raising near-term Treasury supply concerns.",
        "related_series": ["pUSGDEF=H", "pUSGDEF=T", "pUSGDEF=M", "USGDEF=ECI"],
    },
    "pUSGDEF=H": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Maximum (most bullish / smallest-deficit or largest-surplus) forecast for the monthly US Federal Budget balance in the Reuters poll.",
        "how_to_use": "The H-L range is typically wide for the federal budget given timing uncertainty of large outlays; a narrow range signals unusually high forecaster consensus and makes surprises outside the band more impactful for rates.",
        "related_series": ["pUSGDEF=L", "pUSGDEF=T", "pUSGDEF=M", "USGDEF=ECI"],
    },
    "pUSGDEF=T": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "USD billions",
        "meaning": "Standard deviation of forecasts for the monthly US Federal Budget balance in the Reuters poll, measuring economist disagreement about the fiscal position.",
        "how_to_use": "Federal budget standard deviations are typically large (often $20-40B) due to timing of corporate tax receipts; compare across months — April (tax season) and September (fiscal year-end) carry the highest forecast uncertainty.",
        "related_series": ["pUSGDEF=M", "pUSGDEF=L", "pUSGDEF=H", "pUSGDEF=C"],
    },
    "pUSGDEF=C": {
        "slug": "us_polls",
        "subcategory": "Federal Budget,$",
        "units": "Count",
        "meaning": "Number of economists participating in the Reuters US Federal Budget poll for the current release cycle.",
        "how_to_use": "Track alongside pUSGDEF=T: a low forecaster count with high standard deviation renders the consensus statistically unreliable; in such months, the SmartEcon forecast (pUSGDEF=F) based on DTS data may be more actionable.",
        "related_series": ["pUSGDEF=M", "pUSGDEF=T", "pUSGDEF=F", "USGDEF=ECI"],
    },
}
