"""Seed Tier-1 hand-curated content for China macro RICs.

Mirrors the structure of seed_id_tier1.py and seed_tier1.py (US) but applies
content to catalog/cn/*.json. Idempotent.

Run from repo root:  python scripts/seed_cn_tier1.py
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG_DIR = os.path.join(REPO_ROOT, "catalog", "cn")


# Each entry: ric -> { slug, subcategory, units, meaning, how_to_use, related_series }
TIER1: dict[str, dict] = {
    # ============== PBoC POLICY RATES (post-2019 LPR-based regime) ==============
    "aCNLPR1YRR": {
        "slug": "cn_interest_rates",
        "subcategory": "Policy Rate",
        "units": "Percent",
        "meaning": "1-Year Loan Prime Rate (LPR) — the People's Bank of China's primary policy lending benchmark since the August 2019 reform that pegged it to the medium-term lending facility (MLF) rate plus a contributing-bank-determined spread. Set monthly on the 20th by 18 quoting banks.",
        "how_to_use": "THE key China lending-rate benchmark. Used to price most corporate loans. PBoC signals through the MLF rate and lets the LPR move with it. A 5-10 bp cut typically triggers analyst headlines and CNY/equity reaction. Recent range 3.10-3.85%. Pair with the 5Y LPR (aCNLPR5YRR) which is the mortgage-pricing benchmark.",
        "related_series": ["aCNLPR5YRR", "aCNLPRORA", "aCNCRR", "aCNXRUSD"],
    },
    "aCNLPR5YRR": {
        "slug": "cn_interest_rates",
        "subcategory": "Policy Rate",
        "units": "Percent",
        "meaning": "5-Year Loan Prime Rate (LPR) — the longer-tenor LPR that serves as the benchmark for individual mortgage rates and longer-duration corporate loans. Set monthly alongside the 1Y LPR.",
        "how_to_use": "THE mortgage-rate benchmark. PBoC has used asymmetric cuts (5Y > 1Y) to support real estate without easing too aggressively for short-term lending. The 5Y has been cut harder than the 1Y in 2022-24 to support the property sector. Watch the 5Y-1Y spread for the property-policy stance.",
        "related_series": ["aCNLPR1YRR", "aCNLPRFRA", "aCNMRGRATR"],
    },
    "aCNLPRORA": {
        "slug": "cn_interest_rates",
        "subcategory": "Policy Rate",
        "units": "Percent",
        "meaning": "Loan Prime Rate, 1-Year — alternative release of the 1Y LPR. Same conceptual measure as aCNLPR1YRR with potentially different release vintage.",
        "how_to_use": "Cross-check series. Use whichever has fresher data; The People's Bank of China publishes the LPR at 09:15 CST on the 20th of each month.",
        "related_series": ["aCNLPR1YRR", "aCNLPRFRA"],
    },
    "aCNLPRFRA": {
        "slug": "cn_interest_rates",
        "subcategory": "Policy Rate",
        "units": "Percent",
        "meaning": "Loan Prime Rate, 5-Year — alternative release of the 5Y LPR. Same conceptual measure as aCNLPR5YRR.",
        "how_to_use": "Cross-check against aCNLPR5YRR. The 5Y LPR is the mortgage-rate benchmark; PBoC publishes monthly on the 20th.",
        "related_series": ["aCNLPR5YRR", "aCNLPRORA"],
    },
    "aCNCRR": {
        "slug": "cn_interest_rates",
        "subcategory": "Reserve Requirement",
        "units": "Percent",
        "meaning": "Reserve Requirement Ratio (RRR) for Big Banks — share of deposits that the largest Chinese banks must hold as reserves at the PBoC. Major monetary-policy tool: cuts release liquidity to the banking system; hikes drain it.",
        "how_to_use": "Critical PBoC tool used to manage liquidity at quarterly and seasonal flow points. A 25 bp RRR cut typically releases ~CNY 500 billion of liquidity. Recent level ~9-10% (down from peak ~21% pre-2012). Cuts often signal dovish stance; markets watch announcement timing closely (typically late afternoon).",
        "related_series": ["aCNRRR00", "aCNRESRER", "aCNRREQRR", "aCNCRBNCG"],
    },
    "aCNRREQBR": {
        "slug": "cn_interest_rates",
        "subcategory": "Reserve Requirement",
        "units": "Percent",
        "meaning": "Reserve Requirement Ratio, Big Banks — same conceptual measure as aCNCRR in alternative framing.",
        "how_to_use": "Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series": ["aCNCRR", "aCNRRR00"],
    },
    "aCNRRR00": {
        "slug": "cn_interest_rates",
        "subcategory": "Reserve Requirement",
        "units": "Percent",
        "meaning": "Reserve Requirement Ratio, Small Banks — RRR applied to smaller financial institutions. Set 50-100 bps below the big-bank RRR to support SME lending.",
        "how_to_use": "Tiered RRR is a targeted-easing tool. Differential cuts (only small-bank RRR cut) signal targeted SME-support stance. Watch the spread between big-bank and small-bank RRR for tiered-policy signals.",
        "related_series": ["aCNCRR", "aCNRESRER", "aCNRREQRR"],
    },
    "aCNRESRER": {
        "slug": "cn_money_supply",
        "subcategory": "Reserve Requirement",
        "units": "Percent",
        "meaning": "Reserve Requirement Ratio, Small Banks — same conceptual measure as aCNRRR00 in money-supply dataset.",
        "how_to_use": "Cross-check against aCNRRR00. Small-bank RRR is set 50-100bps below big-bank RRR for SME-targeted easing.",
        "related_series": ["aCNRRR00", "aCNCRR"],
    },
    "aCNDEPR1Y": {
        "slug": "cn_interest_rates",
        "subcategory": "Deposit Rate",
        "units": "Percent",
        "meaning": "PBoC 1-Year Benchmark Deposit Rate — administrative deposit rate that anchors household deposit pricing at Chinese banks. Less actively used since the LPR reform but still publicly cited.",
        "how_to_use": "Pre-2015 the headline policy rate; now overshadowed by LPR. Banks have flexibility to price above this floor. Sustained sub-1.5% reflects the post-2020 disinflation/deflation regime. Used to gauge implicit financial-repression of household savers.",
        "related_series": ["aCNDEPR1YEP", "aCNDEPR3M", "aCNLPR1YRR"],
    },
    "aCNDEPR1YEP": {
        "slug": "cn_interest_rates",
        "subcategory": "Deposit Rate",
        "units": "Percent",
        "meaning": "1-Year Deposit Rate — alternative release of the 1Y benchmark deposit rate.",
        "how_to_use": "Cross-check against aCNDEPR1Y. Banks have flexibility to price above this benchmark floor.",
        "related_series": ["aCNDEPR1Y"],
    },
    "aCNBNKR": {
        "slug": "cn_interest_rates",
        "subcategory": "Policy Rate",
        "units": "Percent",
        "meaning": "PBoC Bank Rate — the 'rediscount rate' charged on bills the central bank discounts for commercial banks. Largely ceremonial post-2013 reforms; the LPR/MLF/OMO rates dominate active policy signaling.",
        "how_to_use": "Slow-moving administrative rate. Used in some legacy financial contracts. Watch the gap to LPR for stance signals; sustained spread compression signals tighter policy regime.",
        "related_series": ["aCNLPR1YRR", "aCNBNKREOP"],
    },
    "aCNBNKREOP": {
        "slug": "cn_interest_rates",
        "subcategory": "Policy Rate",
        "units": "Percent",
        "meaning": "PBoC 20-Day Reloan Rate — the rate at which the PBoC lends to commercial banks for 20-day terms. Used in PBoC's open market operations alongside the 7-day reverse repo rate.",
        "how_to_use": "Niche; the 7-day reverse repo (separate series, sometimes published) is more market-relevant. Reloan-rate moves signal targeted liquidity provision to specific bank categories.",
        "related_series": ["aCNBNKR"],
    },
    "aCNPRATE": {
        "slug": "cn_interest_rates",
        "subcategory": "Policy Rate",
        "units": "Percent",
        "meaning": "Major Loan Rate, Financial Institutions, 1 Year & Below — average lending rate on loans up to 1 year extended by Chinese financial institutions. Aggregates LPR-pricing across the system.",
        "how_to_use": "Captures effective lending costs (vs LPR which is the benchmark). The spread vs LPR signals risk-premium dynamics — widening spreads suggest banks pricing in greater credit risk.",
        "related_series": ["aCNLPR1YRR", "aCNALRNFER"],
    },
    "aCNALRNFER": {
        "slug": "cn_interest_rates",
        "subcategory": "Lending Rate",
        "units": "Percent",
        "meaning": "Weighted Average Lending Rate (general) — the headline blended lending rate published by the PBoC quarterly. Captures the rate at which Chinese banks actually extended new loans.",
        "how_to_use": "Most analytically useful 'real economy' lending-rate gauge — includes regulatory pricing pressures and bank competitive dynamics. Sustained declines despite stable LPR signal banks competing for lending share. PBoC cites this in Monetary Policy Reports.",
        "related_series": ["aCNAVELNDR", "aCNALRBFNR", "aCNLPR1YRR"],
    },
    "aCNAVELNDR": {
        "slug": "cn_interest_rates",
        "subcategory": "Lending Rate",
        "units": "Percent",
        "meaning": "Average Lending Rate, Ordinary Loans — weighted average rate on ordinary (non-bill, non-mortgage) bank loans. Subset of the broader weighted-average lending rate.",
        "how_to_use": "Cleaner signal of corporate-loan pricing than the broad weighted average. Watch the spread vs LPR for credit-risk premium dynamics.",
        "related_series": ["aCNALRNFER", "aCNALRBFNR"],
    },
    "aCNALRBFNR": {
        "slug": "cn_interest_rates",
        "subcategory": "Lending Rate",
        "units": "Percent",
        "meaning": "Average Lending Rate, Bill Financing — rate on short-term commercial bills (banker's acceptances) financed by banks. Most rate-sensitive lending segment.",
        "how_to_use": "Bill rates are among the most-watched short-term financing indicators in China. Sharp drops indicate banks meeting lending quotas via bill discounting (low-quality 'window dressing'). PBoC and CBIRC monitor for evidence of low-quality credit creation.",
        "related_series": ["aCNAVELNDR", "aCNALRNFER"],
    },
    "aCNMRGRATR": {
        "slug": "cn_interest_rates",
        "subcategory": "Mortgage Rate",
        "units": "Percent",
        "meaning": "Average Lending Rate, Individual Mortgage Loans — weighted average new-mortgage rate. Set as LPR-5Y plus a regulator-determined spread (positive for additional homes).",
        "how_to_use": "Tracks the property-cycle credit channel. China cut individual-mortgage rates aggressively 2022-24 (from peak ~5.6% to ~3.3%) to support property demand. Watch the spread to 5Y LPR — narrowing spread signals support; wider spread signals tightening.",
        "related_series": ["aCNLPR5YRR", "aCNBLDUCRB"],
    },

    # ============== EXCHANGE RATE ==============
    "aCNXRUSD": {
        "slug": "cn_exchange_rates_and_operations",
        "subcategory": "FX",
        "units": "CNY per USD",
        "meaning": "Chinese Yuan (Renminbi) per US Dollar — the headline USD/CNY spot rate. The PBoC sets a daily mid-point fix at 09:15 CST around which the onshore CNY is allowed to trade within ±2%.",
        "how_to_use": "THE China FX rate. Recent range 6.4-7.4. The PBoC manages CNY against a basket but DXY/USD-CNY is the most-watched cross. Onshore CNY (CNY) and offshore CNH typically trade within ~50 bps; wider spreads signal capital-control stress. Pair with FX reserves (aCNCRESA) for intervention-intensity signals.",
        "related_series": ["aCNCNXROM", "aCNFXEFFECT", "aCNBISRXBR", "aCNCRESA"],
    },
    "aCNCNXROM": {
        "slug": "cn_exchange_rates_and_operations",
        "subcategory": "FX",
        "units": "USD per CNY (mid-price)",
        "meaning": "Mid-Price of USD-CNY — the daily PBoC reference fix (zhōngjiānjià). Set at 09:15 CST and used as the center of the daily ±2% trading band.",
        "how_to_use": "The PBoC's official signaling tool. Sharp moves in the fix (relative to market) signal policy intent — weaker-than-expected fix is depreciation guidance; stronger-than-expected is appreciation guidance. Markets watch the 'counter-cyclical factor' commentary in PBoC quarterly reports.",
        "related_series": ["aCNXRUSD", "aCNFXEFFECT"],
    },
    "aCNCNLANDM": {
        "slug": "cn_exchange_rates_and_operations",
        "subcategory": "FX",
        "units": "USD per CNY",
        "meaning": "Exchange rate RMB/USD — companion CNY/USD reference. Same conceptual measure as aCNXRUSD with potentially different vintage.",
        "how_to_use": "Cross-check against aCNXRUSD. Use whichever has fresher data; both track the daily CNY-USD spot rate.",
        "related_series": ["aCNXRUSD", "aCNCNXROM"],
    },
    "aCNFXEFFECT": {
        "slug": "cn_exchange_rates_and_operations",
        "subcategory": "FX",
        "units": "Index",
        "meaning": "BIS Nominal Broad Effective Exchange Rate Index for CNY — trade-weighted CNY against a basket of trading partners' currencies in nominal terms. The PBoC also publishes its own trade-weighted index (CFETS RMB Index) with similar weights.",
        "how_to_use": "Better than USD/CNY alone for CNY competitiveness — captures moves vs JPY, EUR, KRW, SGD (key trade partners). Falling NEER = CNY weakening on trade-weighted basis. The PBoC explicitly targets stability against the basket post-2015 reform.",
        "related_series": ["aCNXRUSD", "aCNBISRXBR"],
    },
    "aCNBISRXBR": {
        "slug": "cn_exchange_rates_and_operations",
        "subcategory": "FX",
        "units": "Index",
        "meaning": "BIS Real Broad Effective Exchange Rate Index for CNY — trade-weighted CNY adjusted for relative inflation against trading partners. Shows true CNY competitiveness.",
        "how_to_use": "Most analytically meaningful FX gauge. CNY's real EER appreciated through 2010s as China grew faster than peers; reversed post-2022 amid CNY weakness + China deflation. Watch real EER trends for CNY structural overvaluation/undervaluation signals.",
        "related_series": ["aCNFXEFFECT", "aCNXRUSD"],
    },
    "aCNCNCQXM": {
        "slug": "cn_exchange_rates_and_operations",
        "subcategory": "FX",
        "units": "HKD per USD",
        "meaning": "Hong Kong Dollar to USD exchange rate — included in China dataset due to HKD's tight peg (HKD pegged to USD at 7.75-7.85). HKMA defends the peg via convertibility undertakings.",
        "how_to_use": "Track for HK monetary-policy stress signals. Persistent trading at 7.85 (weak side) signals Hong Kong outflows; HKMA buys HKD/sells USD to defend. Critical for Hong Kong financial stability and offshore CNH market.",
        "related_series": ["aCNXRUSD"],
    },

    # ============== GDP ==============
    "aCNCGDPYD/A": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "Percent, YoY",
        "meaning": "Real GDP Growth, year-over-year change in constant prices — the headline China GDP print. Released quarterly by the National Bureau of Statistics (NBS) ~3 weeks after quarter-end (e.g., Q1 published ~April 18-20).",
        "how_to_use": "THE most-watched China growth number. Annual official target typically 'around 5%'. China hit ~6%+ pre-2018, slowed to 5%-ish post-2020. Sustained sub-4% prints raise hard-landing concerns; >6% would be a re-acceleration story. Markets often question NBS data accuracy — cross-check with industrial production, trade, and the Li Keqiang index (electricity + rail freight + bank loans).",
        "related_series": ["aCNCGDPPD/A", "aCNGDPY/C", "aCNCPCED/CA", "aCNCGFCD/CA"],
    },
    "aCNCGDPPD/A": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "Percent, QoQ",
        "meaning": "Real GDP Growth, quarter-over-quarter change in constant prices, seasonally adjusted — sequential momentum gauge.",
        "how_to_use": "Use for sequential momentum. China QoQ less commonly cited than YoY but useful for identifying turning points. Multiply QoQ by 4 for annualized rate (US-style). Recent QoQ ~1.0-1.5%.",
        "related_series": ["aCNCGDPYD/A", "aCNGDPGR/CA"],
    },
    "aCNGDPY/C": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "Percent, YoY",
        "meaning": "GDP Growth Rate, YoY — alternative release of GDP year-over-year growth (Refinitiv/NBS). Same conceptual measure as aCNCGDPYD/A.",
        "how_to_use": "Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series": ["aCNCGDPYD/A", "aCNGDPGRYTD/C"],
    },
    "aCNGDPGRYTD/C": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "Percent, YoY YTD",
        "meaning": "GDP Growth Rate, Year-to-Date YoY — cumulative YTD growth, the official format China publishes for monthly data.",
        "how_to_use": "China publishes most data in YTD-cumulative form (a non-Western convention). Convert to single-month/single-quarter by differencing consecutive YTD values. Used in NBS's Monthly Activity Indicators release.",
        "related_series": ["aCNCGDPYD/A", "aCNGDPY/C"],
    },
    "aCNGDPGR/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "Percent, QoQ",
        "meaning": "GDP Growth Rate, QoQ (seasonally adjusted) — sequential growth at quarterly frequency.",
        "how_to_use": "China only published QoQ-SA from 2011 onwards. Useful for identifying inflection points in real-time. Annualize by ×4 for international comparison.",
        "related_series": ["aCNCGDPPD/A", "aCNGDPAAR"],
    },
    "aCNGDP": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "CNY billions, current prices",
        "meaning": "GDP at Current Prices — nominal GDP level. China's nominal GDP ~CNY 130 trillion (~$18 trillion USD) in 2024 — second-largest economy globally after US.",
        "how_to_use": "Use for nominal-GDP arithmetic (debt/GDP, deficit/GDP). Real-vs-nominal gap = GDP deflator — Chinese deflator turned negative 2023-24 (deflation), key macro story.",
        "related_series": ["aCNGDPC/C", "aCNGDPV/C", "aCNCGDPYA"],
    },
    "aCNGDPC/C": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "CNY billions, constant prices",
        "meaning": "GDP at Constant Prices, quarterly — real GDP level.",
        "how_to_use": "Use for real-level comparisons. NBS publishes constant-price GDP using rolling base years (current 2020 base). YoY growth rate (aCNCGDPYD/A) is the meaningful signal.",
        "related_series": ["aCNGDP", "aCNGDPV/C", "aCNCGDPD/CA"],
    },
    "aCNCPCED/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "Consumption",
        "units": "CNY billions, constant prices",
        "meaning": "Consumer Spending (Household Final Consumption) — constant-price level. ~38-40% of China GDP — historically low for an economy at China's stage of development; rebalancing toward consumption-led growth is a long-running policy theme.",
        "how_to_use": "China's consumption share is ~10-15pp lower than peers — a function of high household savings rate, low wages-to-GDP, and underdeveloped social safety net. Track for 'rebalancing' signal — sustained increases would mark a structural shift away from investment-led growth.",
        "related_series": ["aCNCGDPYD/A", "aCNRSLSAR"],
    },
    "aCNCGFCD/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "Investment",
        "units": "CNY billions, constant prices",
        "meaning": "Gross Fixed Capital Formation — investment level in real terms. ~42% of GDP, the world's highest investment share for a major economy. Driven by infrastructure (state-led), property, manufacturing capex.",
        "how_to_use": "Cycle-sensitive. Property sector ~20% of GFCF historically; deleveraging since 2021 (Three Red Lines) made GFCF a major drag on growth 2022-2024. Watch fixed-asset-investment monthly release (FAI) for higher-frequency signal.",
        "related_series": ["aCNCGDPYD/A", "aCNFAII"],
    },
    "aCNCGCED/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "Government",
        "units": "CNY billions, constant prices",
        "meaning": "Government Consumption — central + local government final consumption (salaries, goods/services). ~16% of GDP.",
        "how_to_use": "Track for fiscal-stance signals. Surges signal counter-cyclical fiscal support (e.g., 2020 COVID response). Local-government weakness post-2022 (LGFV stress) is a key macro theme.",
        "related_series": ["aCNCGDPYD/A", "aCNCGEXP"],
    },
    "aCNCEXND/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "External",
        "units": "CNY billions, constant prices",
        "meaning": "Exports of Goods and Services (constant prices) — volume measure of external demand. China is the world's largest goods exporter (~$3.5 trillion annually).",
        "how_to_use": "Tracks global goods demand for Chinese manufactures. Sensitive to USD strength (negative for China exports) and US/EU growth. Major Chinese export categories: electronics, machinery, chemicals, autos (rapidly growing — EVs).",
        "related_series": ["aCNCGDPYD/A", "aCNCEXPB/A"],
    },
    "aCNCIMND/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "External",
        "units": "CNY billions, constant prices",
        "meaning": "Imports of Goods and Services (constant prices) — volume measure of import demand.",
        "how_to_use": "Pro-cyclical with industrial activity (raw materials, capital goods) and consumption. Falls during property-led slowdowns. Watch oil + iron ore + soybean imports as the largest sub-categories.",
        "related_series": ["aCNCGDPYD/A", "aCNCIMPB/A"],
    },
    "aCNCGDHD/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP per capita",
        "units": "Index, constant prices",
        "meaning": "GDP per capita, constant prices — real income per person. China crossed the World Bank 'high income' threshold in PPP terms but remains in 'upper middle income' at market exchange rates.",
        "how_to_use": "China per-capita GDP ~$13,000 (current USD, 2024) — at the threshold of the 'middle-income trap' debate. Sustained 4-5% per-capita real growth needed to reach high-income status by 2035 (CCP target).",
        "related_series": ["aCNCGDHA"],
    },

    # ============== MONEY SUPPLY (M2 is the headline) ==============
    "aCNM2": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "CNY billions",
        "meaning": "Money Supply M2 — the broadest commonly-tracked Chinese monetary aggregate. Includes M1 + household and corporate time deposits + foreign-currency deposits at banks. PBoC publishes monthly around the 10th-15th.",
        "how_to_use": "China's M2 growth is the single most-watched liquidity gauge. Pre-2018 typically 11-15% YoY; post-2018 ~8-12%; 2024 dropped to ~6.5% (lowest on record), reflecting weak credit demand. PBoC sets implicit M2 targets aligned with nominal GDP growth.",
        "related_series": ["aCNM2GRTY", "aCNCMS2YB/A", "aCNM1", "aCNM0"],
    },
    "aCNM2GRTY": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "Percent, YoY",
        "meaning": "M2 Money Supply, year-over-year change — the headline China money-growth gauge.",
        "how_to_use": "PBoC's main implicit policy target. Above 10% historically signals expansionary stance; below 8% signals tight (rare pre-2024). Markets compare to nominal GDP growth — when M2 growth falls below nominal GDP, monetary support is contracting.",
        "related_series": ["aCNM2", "aCNCMS2YB/A", "aCNMSM2AR"],
    },
    "aCNCMS2YB/A": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "Percent, YoY",
        "meaning": "Money Supply M2, YoY change (standardized) — same conceptual measure as aCNM2GRTY in OECD-comparable framing.",
        "how_to_use": "Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series": ["aCNM2GRTY", "aCNM2"],
    },
    "aCNMSM2AR": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "Percent, YoY",
        "meaning": "Money Supply M2, YoY change — alternative release. Reuters poll-anchored 'actual'.",
        "how_to_use": "Cross-check series; markets compare to consensus poll for surprise-driving headlines.",
        "related_series": ["aCNM2GRTY", "aCNM2"],
    },
    "aCNM1": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "CNY billions",
        "meaning": "Money Supply M1 — narrow money: currency in circulation + corporate demand deposits. Excludes household deposits (which are in M2 only).",
        "how_to_use": "Leading indicator for activity. M1 growth surges before economic acceleration; sustained sub-zero M1 YoY (rare, observed 2024) signals corporate-cash hoarding and weak investment. M1-M2 spread is a closely-watched cycle gauge.",
        "related_series": ["aCNM1GRTY", "aCNM2", "aCNMSUP"],
    },
    "aCNM1GRTY": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "Percent, YoY",
        "meaning": "Money Supply M1, YoY change — narrow-money growth pace. Most cyclical Chinese liquidity indicator.",
        "how_to_use": "Sub-zero readings are rare and signal economic stress; recent dip into negative territory (mid-2024) flagged the property-led demand weakness. M1-M2 spread (M1 minus M2 growth) indicates corporate vs household liquidity dynamics.",
        "related_series": ["aCNM1", "aCNM2GRTY"],
    },
    "aCNM0": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "CNY billions",
        "meaning": "Money Supply M0 — currency in circulation outside the banking system. ~CNY 12 trillion. Smallest aggregate.",
        "how_to_use": "Track digital-payment adoption proxy: Chinese consumers shifted to mobile payments (Alipay, WeChat Pay) at scale post-2015. M0 growth has slowed accordingly. Useful for tracking cash-in-circulation trends and Lunar New Year demand spikes.",
        "related_series": ["aCNM0GRTY", "aCNM1"],
    },
    "aCNM0GRTY": {
        "slug": "cn_money_supply",
        "subcategory": "Money Supply",
        "units": "Percent, YoY",
        "meaning": "Money Supply M0, YoY change — currency-in-circulation growth.",
        "how_to_use": "Slow-moving. Useful for spotting Lunar New Year cash-demand spikes (Q1) and digital-payment adoption trends (declining M0 growth).",
        "related_series": ["aCNM0", "aCNM1GRTY"],
    },

    # ============== INTERNATIONAL RESERVES ==============
    "aCNCRESA": {
        "slug": "cn_international_reserves",
        "subcategory": "Reserves",
        "units": "USD billions",
        "meaning": "Official International Reserves (Standardized) — China's total foreign reserves: FX, gold, IMF position, SDRs. The world's largest at ~$3.2 trillion. Published monthly by SAFE (State Administration of Foreign Exchange).",
        "how_to_use": "THE critical CNY-defense indicator. Reserves peaked $4 trillion in 2014; fell to $3 trillion in 2017 during capital outflows; stabilized since at $3.0-3.3 trillion. Sharp drawdowns (>$50B/month) signal heavy FX intervention. SAFE publishes ~7th of each month.",
        "related_series": ["aCNFXMAA", "aCNFXRES", "aCNGOLDRSH", "aCNXRUSD"],
    },
    "aCNRESERVA": {
        "slug": "cn_international_reserves",
        "subcategory": "Reserves",
        "units": "USD billions",
        "meaning": "Total Official Reserve Assets — alternative release of total reserves. Companion to aCNCRESA.",
        "how_to_use": "Cross-check against aCNCRESA. Total reserves include FX, gold, IMF position, SDRs.",
        "related_series": ["aCNCRESA"],
    },
    "aCNFXMAA": {
        "slug": "cn_international_reserves",
        "subcategory": "Reserves",
        "units": "USD billions",
        "meaning": "Foreign Currency Reserves — FX-only component of total reserves (excludes gold, IMF position, SDRs). ~95% of total reserves.",
        "how_to_use": "Currency composition: estimated ~60% USD, ~20% EUR, ~5% JPY, ~3% GBP, ~2% AUD, plus other (PBoC does not publish exact split). Diversification away from USD has been a slow multi-decade theme.",
        "related_series": ["aCNCRESA", "aCNFXRES"],
    },
    "aCNFXRES": {
        "slug": "cn_international_reserves",
        "subcategory": "Reserves",
        "units": "USD billions",
        "meaning": "Foreign Currency Reserves — same as aCNFXMAA in alternative release. Tracks FX-only component.",
        "how_to_use": "Cross-check against aCNFXMAA. FX reserves are the bulk of total reserves (~95%).",
        "related_series": ["aCNFXMAA", "aCNCRESA"],
    },
    "aCNGOLDRSH": {
        "slug": "cn_international_reserves",
        "subcategory": "Reserves",
        "units": "USD billions",
        "meaning": "Gold Reserves — China's gold holdings. PBoC has been a net gold buyer since 2022, increasing holdings from ~1,950 tons to ~2,250 tons (2024). Reflects strategic diversification away from USD reserves.",
        "how_to_use": "Track PBoC gold purchases for de-dollarization signal. Monthly disclosures resumed post-2018 (PBoC was opaque about gold buys 2009-2015). Gold-price moves drive dollar-value swings; track ounces if available.",
        "related_series": ["aCNCRESA"],
    },
    "aCNCNOIJM": {
        "slug": "cn_exchange_rates_and_operations",
        "subcategory": "Reserves",
        "units": "USD millions",
        "meaning": "Foreign Exchange Reserves — release-vintage version of total FX reserves. Cross-listed in exchange-rates dataset.",
        "how_to_use": "Cross-check against aCNFXMAA. SAFE publishes FX reserves monthly with a 1-week lag.",
        "related_series": ["aCNFXMAA", "aCNCRESA"],
    },

    # ============== GOVERNMENT FINANCE ==============
    "aCNGDEF": {
        "slug": "cn_gov_accounts",
        "subcategory": "Fiscal",
        "units": "CNY billions",
        "meaning": "General Government Deficit/Surplus — China's official budget balance. Released monthly by the Ministry of Finance.",
        "how_to_use": "Official deficit understates true fiscal stance — excludes local-government financing vehicles (LGFVs), special bonds, and other off-budget items. Augmented fiscal deficit (IMF measure) typically 8-12% of GDP vs official ~3%. Watch the official-vs-augmented gap.",
        "related_series": ["aCNCGOVA", "aCNCGREV", "aCNCGEXP", "aCNPDEBTA"],
    },
    "aCNCGOVA": {
        "slug": "cn_gov_accounts",
        "subcategory": "Fiscal",
        "units": "CNY billions",
        "meaning": "Central Government Deficit/Surplus (Standardized) — central-only fiscal balance (excludes local governments). The 'on-budget' deficit subject to the 3%-of-GDP cap.",
        "how_to_use": "Used in central-government budget arithmetic. Local-government deficits run ~4-6% of GDP separately, financed via LGFV bonds and special-purpose bonds. The total 'general government' framework is the meaningful sustainability measure.",
        "related_series": ["aCNGDEF", "aCNCGEXP", "aCNCGREV"],
    },
    "aCNCGREV": {
        "slug": "cn_gov_accounts",
        "subcategory": "Fiscal",
        "units": "CNY billions",
        "meaning": "General Government Revenue — central + local tax + non-tax receipts. Major sources: VAT (~40%), corporate income tax (~25%), individual income tax (~7%), customs (~3%), state-owned-enterprise dividends (~7%).",
        "how_to_use": "Tax-to-GDP ~16% — moderate. Land sales (counted separately as 'government fund revenue', ~CNY 8 trillion historical peak) are critical to local-government finances; collapsed 2022-24 with property downturn — major fiscal stress point.",
        "related_series": ["aCNCGEXP", "aCNGDEF", "aCNGGREVG"],
    },
    "aCNGGREVG": {
        "slug": "cn_gov_accounts",
        "subcategory": "Fiscal",
        "units": "Percent, YoY",
        "meaning": "General Government Revenue, YoY — pace of revenue growth.",
        "how_to_use": "Cyclical with GDP. Watch land-sales-revenue separately reported by MoF — its YoY changes far more cyclical than total revenue.",
        "related_series": ["aCNCGREV", "aCNGDEF"],
    },
    "aCNCGEXP": {
        "slug": "cn_gov_accounts",
        "subcategory": "Fiscal",
        "units": "CNY billions",
        "meaning": "General Government Expenditure (Budgetary) — central + local government spending. Major lines: education, social security, healthcare, infrastructure, defense, agriculture support, public administration.",
        "how_to_use": "Pro-cyclical fiscal stance shifted to counter-cyclical 2018+. Watch the 'special-purpose bond quota' set in March each year — this drives infrastructure spending. Front-loading bond issuance to Q1-Q2 signals counter-cyclical fiscal push.",
        "related_series": ["aCNCGREV", "aCNGDEF"],
    },
    "aCNPDEBTA": {
        "slug": "cn_government_total_debt",
        "subcategory": "Public Debt",
        "units": "CNY billions",
        "meaning": "Central Government Debt, Total — outstanding central-government debt. About CNY 40 trillion (2024). Excludes local-government debt (~CNY 90 trillion in special + general bonds plus implicit LGFV debt).",
        "how_to_use": "Central-government debt-to-GDP ~30% (low by international standards). Total public debt including local + LGFVs ~85-90% of GDP (closer to advanced-economy norms). True 'augmented' debt including SOE liabilities is a contested research topic.",
        "related_series": ["aCNGDEF", "aCNCGEXP"],
    },

    # ============== EXTERNAL DEBT ==============
    "aCNCEXTA": {
        "slug": "cn_external_debt",
        "subcategory": "External Debt",
        "units": "USD billions",
        "meaning": "Total External Debt — debt owed to non-residents (FX + RMB-denominated debt held by foreigners). ~$2.5 trillion (2024). Published quarterly by SAFE.",
        "how_to_use": "China external debt is moderate at ~14% of GDP (vs 30% for India, 50%+ for many EM peers). Composition: ~60% short-term (mostly trade credits + interbank), ~40% long-term (sovereign + corporate bonds). Foreign holdings of CGBs are ~$200 billion.",
        "related_series": ["aCNCEXTYA", "aCNCGVXA", "aCNDEBTF"],
    },
    "aCNCEXTYA": {
        "slug": "cn_external_debt",
        "subcategory": "External Debt",
        "units": "Percent, YoY",
        "meaning": "Total External Debt, YoY change — pace of external-debt accumulation.",
        "how_to_use": "Track for external-vulnerability buildup. China's external debt growth slowed sharply post-2022 with USD strength + capital-control tightening. Watch alongside FDI for net foreign claims direction.",
        "related_series": ["aCNCEXTA", "aCNCEXTPA"],
    },
    "aCNCGVXA": {
        "slug": "cn_external_debt",
        "subcategory": "External Debt",
        "units": "USD billions",
        "meaning": "Government External Debt — central + local-government foreign-currency debt + non-resident-held CGBs (Chinese Government Bonds). Largest component is foreign holdings of onshore RMB CGBs.",
        "how_to_use": "Foreign CGB holdings indicator. Bond Connect and CIBM Direct allow foreign investors to hold onshore CGBs; foreign holdings ~5% of total CGBs outstanding. Sharp inflows/outflows correlate with USD-CNY moves.",
        "related_series": ["aCNCEXTA", "aCNCGVXYA"],
    },
    "aCNDEBTF": {
        "slug": "cn_external_debt",
        "subcategory": "External Debt",
        "units": "USD billions",
        "meaning": "External Debt — alternative release of total external debt level.",
        "how_to_use": "Cross-check against aCNCEXTA. SAFE quarterly publication is the authoritative source for China external-debt statistics.",
        "related_series": ["aCNCEXTA"],
    },

    # ============== CONSUMER SURVEYS ==============
    "aCNCONCF": {
        "slug": "cn_consumer_surveys",
        "subcategory": "Consumer Confidence",
        "units": "Index",
        "meaning": "Consumer Confidence Index — official NBS monthly consumer-sentiment gauge. Combines current-conditions and future-expectations sub-indices. Released ~3 weeks after month-end.",
        "how_to_use": "Headline ~80-115 historical range. Index dropped sharply post-COVID (April 2022 lockdowns) and remained subdued amid property-sector stress. Cross-check against Westpac MNI Consumer Sentiment (aCNWMCSIR) which uses a different methodology.",
        "related_series": ["aCNCONCE", "aCNCONCS", "aCNWMCSIR"],
    },
    "aCNCONCE": {
        "slug": "cn_consumer_surveys",
        "subcategory": "Consumer Confidence",
        "units": "Index",
        "meaning": "Consumer Expectations Index — forward-looking sub-component of CCI. Captures households' 6-month outlook on income, employment, business conditions.",
        "how_to_use": "Leads consumption growth by 1-2 quarters. Sharp drops alongside falling current-conditions signal accelerating pessimism. Use spread vs Current Satisfaction (aCNCONCS) for cycle inflection.",
        "related_series": ["aCNCONCF", "aCNCONCS"],
    },
    "aCNCONCS": {
        "slug": "cn_consumer_surveys",
        "subcategory": "Consumer Confidence",
        "units": "Index",
        "meaning": "Consumer Satisfaction Index — current-conditions sub-component of CCI. Captures present economic and household conditions.",
        "how_to_use": "Coincides with retail sales activity. Use the spread vs Expectations (aCNCONCE) — when expectations fall faster than satisfaction, cycle is rolling over from peak.",
        "related_series": ["aCNCONCF", "aCNCONCE"],
    },
    "aCNWMCSIR": {
        "slug": "cn_consumer_surveys",
        "subcategory": "Consumer Confidence",
        "units": "Index",
        "meaning": "Westpac MNI Consumer Sentiment Indicator — alternative private-sector consumer-confidence gauge. Smaller sample but methodology aligned with OECD international standards.",
        "how_to_use": "Cross-check against the official CCI. Useful when official numbers face data-quality questions. Westpac MNI tends to track CCI directionally with some lead at turning points.",
        "related_series": ["aCNCONCF"],
    },
    "aCNIPSOAR": {
        "slug": "cn_consumer_surveys",
        "subcategory": "Consumer Confidence",
        "units": "Index",
        "meaning": "Reuters Poll: TR CN IPSOS Consumer Sentiment, Actual — Reuters poll-anchored release of Ipsos primary consumer sentiment index for China.",
        "how_to_use": "Tertiary cross-check vs official CCI and Westpac MNI. Smaller sample.",
        "related_series": ["aCNCCIPSOR", "aCNCONCF"],
    },
    "aCNCCIPSOR": {
        "slug": "cn_consumer_surveys",
        "subcategory": "Consumer Confidence",
        "units": "Index",
        "meaning": "LSEG/Ipsos Primary Consumer Sentiment Index (CSI) for China — global-standardized consumer-sentiment measure.",
        "how_to_use": "Use for cross-country comparisons; domestic analysts use CCI (aCNCONCF) as the primary gauge.",
        "related_series": ["aCNIPSOAR", "aCNCONCF"],
    },

    # ============== KEY GDP-RELATED VARIANTS ==============
    "aCNCGDPYA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "Percent, YoY",
        "meaning": "Nominal GDP, YoY change in current prices — captures real growth + GDP deflator inflation.",
        "how_to_use": "Use for fiscal arithmetic. Recent nominal YoY 4-5% (vs real 5%+) reflects deflator-deflation. Persistent nominal-below-real growth = deflation regime — uniquely concerning for China since 2023.",
        "related_series": ["aCNCGDPYD/A", "aCNGDP"],
    },
    "aCNCGDPA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "CNY billions, current prices",
        "meaning": "GDP at Current Prices, quarterly (Standardized) — companion to aCNGDP.",
        "how_to_use": "Cross-check against aCNGDP. Current-price (nominal) GDP is used in fiscal arithmetic.",
        "related_series": ["aCNGDP", "aCNCGDPYA"],
    },
    "aCNCGDPD/CA": {
        "slug": "cn_gdp_by_expenditure",
        "subcategory": "GDP",
        "units": "CNY billions, constant prices",
        "meaning": "GDP at Constant Prices, quarterly (Standardized) — companion to aCNGDPC/C.",
        "how_to_use": "Cross-check against aCNGDPC/C. Constant-price GDP captures real-output level.",
        "related_series": ["aCNGDPC/C", "aCNCGDPYD/A"],
    },

    # ============== ROUND 2 ==============

    # ============== CONSUMER PRICE INFLATION (KEY: deflation regime 2023-24) ==============
    "aCNCCPIYE/A": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Headline","units":"Percent, YoY",
        "meaning":"Headline Consumer Price Index, year-over-year change — the headline China inflation print. Released monthly by NBS ~10th of each month with 1-month lag.",
        "how_to_use":"THE most-watched China inflation gauge. Pre-2018 ranged 1-3%; turned negative 2023-24 (-0.5% to +0.5%) — China's first deflation in decades. PBoC's implicit comfort zone is 1-3%. Surprise vs Reuters consensus moves CNY and CGB yields. Pork prices (~3% of basket) drive much of the cyclical noise.",
        "related_series":["aCNCCPIPE/A","aCNCCORYE/A","aCNCCPIE/CA","aCNPPIAR"]},
    "aCNCCPIYF": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Headline","units":"Percent, YoY",
        "meaning":"CPI YoY — alternative release. Same conceptual measure as aCNCCPIYE/A.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNCCPIYE/A"]},
    "aCNCCPIPE/A": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Headline","units":"Percent, MoM",
        "meaning":"CPI Month-over-Month — high-frequency inflation pulse. Volatile (food + holiday seasonality dominates).",
        "how_to_use":"Smooth with 3-month average. Lunar New Year timing (January or February) drives Q1 distortions. Markets watch annualized 3-month MoM as a smoothed momentum gauge.",
        "related_series":["aCNCCPIYE/A","aCNCCPIPF"]},
    "aCNCCPIPF": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Headline","units":"Percent, MoM",
        "meaning":"CPI MoM — alternative release. Same conceptual measure as aCNCCPIPE/A.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNCCPIPE/A"]},
    "aCNCCPIE/CA": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Headline","units":"Index (1982-84=100)",
        "meaning":"CPI level — index measure of consumer prices. NBS uses chain-weighted methodology with rolling base updates.",
        "how_to_use":"Use YoY (aCNCCPIYE/A) for trend; level for analytical baseline. China deflation 2023-24 visible as negative YoY moves in this series.",
        "related_series":["aCNCCPIYE/A","aCNCCPIPE/A"]},
    "aCNCCPIF/C": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Headline","units":"Index",
        "meaning":"CPI level — alternative release.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNCCPIE/CA"]},
    "aCNCCORYE/A": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Core","units":"Percent, YoY",
        "meaning":"Core CPI, year-over-year — All items excluding food and energy. The cleanest read on underlying inflation, removing volatile pork/vegetable prices.",
        "how_to_use":"PBoC's preferred underlying-inflation gauge. Has trended at 0.5-1.0% post-2020 — well below pre-2018 norm of ~2%. Sustained sub-1% core signals weak demand and persistent disinflation. Watch services component for sticky-inflation signals.",
        "related_series":["aCNCCPIYE/A","aCNCCORE/CA","aCNCCORPE/A"]},
    "aCNCCORYF": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Core","units":"Percent, YoY",
        "meaning":"Core CPI YoY — alternative release.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNCCORYE/A"]},
    "aCNCCORE/CA": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Core","units":"Index",
        "meaning":"Core CPI level — All items excluding food and energy.",
        "how_to_use":"Use YoY (aCNCCORYE/A) for trend signal. Core CPI excludes volatile food and energy.",
        "related_series":["aCNCCORYE/A"]},
    "aCNCCORF/C": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Core","units":"Index",
        "meaning":"Core CPI level — alternative release.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNCCORE/CA"]},
    "aCNCCORPE/A": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Core","units":"Percent, MoM",
        "meaning":"Core CPI MoM — sequential core-inflation pulse.",
        "how_to_use":"Smooth with 3-month average. Cleaner sequential signal than headline (no food/energy noise).",
        "related_series":["aCNCCORYE/A"]},
    "aCNCCORPF": {"slug":"cn_consumer_prices_inflation","subcategory":"CPI Core","units":"Percent, MoM",
        "meaning":"Core CPI MoM — alternative release.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNCCORPE/A"]},

    # ============== PRODUCER PRICES (PPI — China deflation indicator) ==============
    "aCNPPIAR": {"slug":"cn_producer_prices","subcategory":"PPI Headline","units":"Percent, YoY",
        "meaning":"Producer Price Index, year-over-year — pace of factory-gate price change. Released monthly by NBS alongside CPI.",
        "how_to_use":"China PPI in deflation since late 2022 (negative YoY for 20+ consecutive months by 2024). Reflects industrial overcapacity, weak property-sector demand for steel/cement, falling commodity-input costs. PPI deflation transmits into corporate margins and global tradable-goods inflation. Watch alongside CPI — divergence (CPI positive, PPI negative) signals services-led inflation regime.",
        "related_series":["aCNPPI","aCNCCPIYE/A","aCNPPICG"]},
    "aCNPPI": {"slug":"cn_producer_prices","subcategory":"PPI Headline","units":"Index",
        "meaning":"Producer Prices — index level for industrial producer prices. Tracks ex-factory prices of industrial products.",
        "how_to_use":"Use YoY (aCNPPIAR) for trend signal. The level captures cumulative price-level changes useful for nominal-real GDP arithmetic in industry.",
        "related_series":["aCNPPIAR"]},
    "aCNPPIFD": {"slug":"cn_producer_prices","subcategory":"PPI Sub-Index","units":"Index",
        "meaning":"PPI Food — food-products factory-gate prices.",
        "how_to_use":"Tracks food-manufacturer pricing. Less cyclical than CPI food (which captures retail-level prices including agricultural fluctuations). Useful for tracking food-CPI pass-through.",
        "related_series":["aCNPPIAR","aCNPPIBM"]},
    "aCNPPICG": {"slug":"cn_producer_prices","subcategory":"PPI Sub-Index","units":"Index",
        "meaning":"PPI Consumer Goods — factory-gate prices for consumer-oriented industrial products.",
        "how_to_use":"Pre-CPI inflation indicator (1-3 month lead). Rising consumer-goods PPI signals upcoming retail price increases; sustained deflation here was a leading signal of broader China disinflation.",
        "related_series":["aCNPPIAR","aCNCCPIYE/A"]},
    "aCNPPIDG": {"slug":"cn_producer_prices","subcategory":"PPI Sub-Index","units":"Index",
        "meaning":"PPI Durable Consumer Goods — factory prices for consumer durables (autos, appliances, electronics).",
        "how_to_use":"Tracks durables-sector pricing. China durables PPI has been in deflation 2022+ as overcapacity (especially in EVs, solar) pressures prices.",
        "related_series":["aCNPPICG","aCNPPIEMEM"]},
    "aCNCGPIT": {"slug":"cn_producer_prices","subcategory":"Corporate Goods","units":"Index",
        "meaning":"Corporate Goods Price Index — total factory-gate prices including goods + services for corporate buyers. Alternative measure to PPI; published by PBoC.",
        "how_to_use":"PBoC-sourced version of PPI for monetary-policy analysis. Includes services unlike NBS PPI which is goods-only.",
        "related_series":["aCNPPI","aCNPPIAR"]},

    # ============== TRADE (KEY: China is world's largest goods exporter) ==============
    "aCNCEXPB/A": {"slug":"cn_imports_exports","subcategory":"Exports","units":"USD billions",
        "meaning":"Merchandise Exports, level — total monthly goods exports. Released by China Customs ~7-10th of each month. China is the world's largest goods exporter (~$3.5T annually).",
        "how_to_use":"THE headline China trade print. Pre-2018 ~$200B/month, peaked $340B (Dec 2021), recently ~$300B/month. Major destinations: US, ASEAN, EU. Surprise vs consensus moves global EM equities and risk sentiment immediately. Pair with PMI new export orders for forward signal.",
        "related_series":["aCNCEXPYB/A","aCNCEXPPB/A","aCNCIMPB/A"]},
    "aCNCEXPYB/A": {"slug":"cn_imports_exports","subcategory":"Exports","units":"Percent, YoY",
        "meaning":"Merchandise Exports, year-over-year change — pace of export growth.",
        "how_to_use":"Volatile due to base effects. China exports YoY swung from -20% (early COVID) to +30% (2021 boom). Sustained sub-zero readings (rare) are recession-territory signals; +5% to +10% is healthy.",
        "related_series":["aCNCEXPB/A","aCNCEXPPB/A"]},
    "aCNCEXPPB/A": {"slug":"cn_imports_exports","subcategory":"Exports","units":"Percent, MoM",
        "meaning":"Merchandise Exports, month-over-month change — high-frequency export-momentum gauge.",
        "how_to_use":"Highly volatile. Smooth with 3-month average. Lunar New Year (Jan/Feb) creates Q1 distortions.",
        "related_series":["aCNCEXPB/A","aCNCEXPYB/A"]},
    "aCNCIMPB/A": {"slug":"cn_imports_exports","subcategory":"Imports","units":"USD billions",
        "meaning":"Merchandise Imports, level — total monthly goods imports. Major categories: integrated circuits, crude oil, iron ore, soybeans, machinery, copper.",
        "how_to_use":"China is largest crude oil importer (~10mb/d), iron ore importer (~70% of seaborne global trade), soybean importer (~60% of global trade). Imports cycle with property + manufacturing investment. Crude oil + iron ore + IC chip imports together ~25% of total imports.",
        "related_series":["aCNCIMPYB/A","aCNCIMPPB/A","aCNCEXPB/A"]},
    "aCNCIMPYB/A": {"slug":"cn_imports_exports","subcategory":"Imports","units":"Percent, YoY",
        "meaning":"Merchandise Imports, year-over-year change — pace of import growth.",
        "how_to_use":"Pro-cyclical with manufacturing + property investment cycles. Falls during property downturns. China imports YoY drop -10% in major slowdowns; +15% to +20% in commodity-cycle peaks.",
        "related_series":["aCNCIMPB/A","aCNCIMPPB/A"]},
    "aCNCIMPPB/A": {"slug":"cn_imports_exports","subcategory":"Imports","units":"Percent, MoM",
        "meaning":"Merchandise Imports, month-over-month change.",
        "how_to_use":"Volatile MoM. Smooth with 3-month moving average for trend; use YoY (aCNCIMPYB/A) for cleaner trend signal.",
        "related_series":["aCNCIMPB/A"]},

    # ============== PMI (multiple sources: NBS, Caixin/RatingDog, MinXin, MNI) ==============
    "aCNPMIBAQ": {"slug":"cn_business_surveys","subcategory":"Manufacturing PMI","units":"Diffusion (50=neutral)",
        "meaning":"NBS Manufacturing Sector PMI — official Chinese government PMI from National Bureau of Statistics. Released last business day of each month at 09:00 CST. Survey of ~3,000 manufacturing companies, larger sample than Caixin/Ratingdog.",
        "how_to_use":"THE official China PMI. Sample skews toward large state-owned enterprises (SOEs). Above 50 = expansion. Currently hovering around 49-51 (no clear expansion). Sub-50 sustained signals manufacturing recession — uncommon but observed 2022-2024 in months. Markets watch the 50 line obsessively.",
        "related_series":["aCNNPMIGRQ/A","aCNNPMMLN/A","aCNNPMMSE/A"]},
    "aCNNPMIGRQ/A": {"slug":"cn_business_surveys","subcategory":"Composite PMI","units":"Diffusion (50=neutral)",
        "meaning":"NBS Whole-Economy General PMI (Composite) — combines manufacturing + non-manufacturing PMI. Releases alongside the manufacturing print at the end of each month.",
        "how_to_use":"Best aggregate cyclical gauge for the Chinese economy. Composite stays above 50 even when manufacturing PMI dips below — non-manufacturing (services + construction) typically stronger. Sustained sub-50 composite is rare; signals broad-based slowdown.",
        "related_series":["aCNCPMIAQ","aCNPMIBAQ","aCNNPMMLN/A"]},
    "aCNCPMIAQ": {"slug":"cn_business_surveys","subcategory":"Composite PMI","units":"Diffusion (50=neutral)",
        "meaning":"Composite PMI from NBS — same conceptual measure as aCNNPMIGRQ/A. Combines manufacturing + non-manufacturing.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNNPMIGRQ/A"]},
    "aCNNPMMLN/A": {"slug":"cn_business_surveys","subcategory":"Manufacturing PMI","units":"Diffusion (50=neutral)",
        "meaning":"NBS Manufacturing PMI — Large Enterprises sub-index. Captures production at large (mostly SOE) manufacturers.",
        "how_to_use":"State-sector cycle gauge. Large enterprises typically run higher than small/medium (better access to credit, government contracts). Spread between large and small (aCNNPMMSE/A) signals the SOE-vs-private divergence.",
        "related_series":["aCNNPMMME/A","aCNNPMMSE/A","aCNPMIBAQ"]},
    "aCNNPMMME/A": {"slug":"cn_business_surveys","subcategory":"Manufacturing PMI","units":"Diffusion (50=neutral)",
        "meaning":"NBS Manufacturing PMI — Medium Enterprises sub-index. Bridges large and small enterprise dynamics.",
        "how_to_use":"Track the SME pulse without smallest-firm volatility. Medium enterprises typically track headline closely but with somewhat better credit access than smallest tier.",
        "related_series":["aCNNPMMLN/A","aCNNPMMSE/A"]},
    "aCNNPMMSE/A": {"slug":"cn_business_surveys","subcategory":"Manufacturing PMI","units":"Diffusion (50=neutral)",
        "meaning":"NBS Manufacturing PMI — Small Enterprises sub-index. Captures the most credit-constrained part of Chinese manufacturing.",
        "how_to_use":"Most cyclical PMI tier — smaller firms are most sensitive to credit conditions and demand swings. Sustained sub-50 is the rule for small enterprises (chronic SME-stress narrative). Spread vs Large enterprises = SOE-vs-private divergence indicator.",
        "related_series":["aCNNPMMLN/A","aCNNPMMME/A"]},
    "aCNBUSA/A": {"slug":"cn_business_surveys","subcategory":"Services PMI","units":"Diffusion (50=neutral)",
        "meaning":"RatingDog (formerly Caixin) Services Business Activity Index, seasonally adjusted — private-sector services PMI. Smaller-sample alternative to NBS non-manufacturing PMI; skews toward SMEs and private firms.",
        "how_to_use":"More cyclical than NBS PMI due to smaller-firm sample. Caixin/RatingDog tends to lead NBS at turning points. Markets watch BOTH the NBS and Caixin/RatingDog versions because they often diverge — divergence reflects private-vs-state economy dynamics.",
        "related_series":["aCNNPMIGRQ/A"]},
    "aCNMNIBCCQ": {"slug":"cn_business_surveys","subcategory":"Business Sentiment","units":"Diffusion (50=neutral)",
        "meaning":"MNI Business Sentiment, seasonally adjusted — alternative private-sector business-confidence gauge. Smaller sample than NBS or Caixin.",
        "how_to_use":"Tertiary cross-check. Useful for triangulated business-cycle reads when NBS and Caixin diverge.",
        "related_series":["aCNMNIBCCR","aCNPMIBAQ"]},
    "aCNMNIBCCR": {"slug":"cn_business_surveys","subcategory":"Business Sentiment","units":"Diffusion (50=neutral)",
        "meaning":"MNI Business Sentiment — non-seasonally-adjusted version.",
        "how_to_use":"Cross-check against the SA version (aCNMNIBCCQ). The seasonally-adjusted version is the more market-relevant gauge.",
        "related_series":["aCNMNIBCCQ"]},

    # ============== BANKING (KEY: TSF and new loans) ==============
    "aCNNYLAA": {"slug":"cn_banking","subcategory":"Bank Credit","units":"CNY billions",
        "meaning":"New Loans (Monthly) — total new RMB-denominated loans from financial institutions. Published monthly by PBoC alongside Total Social Financing (TSF) data.",
        "how_to_use":"Most-watched China credit-creation gauge. Pre-2017 ~CNY 1-2 trillion/month average; surged to CNY 4 trillion in major Q1 prints. Sharp YoY drops signal credit-cycle slowdown. Markets parse the household-vs-corporate split closely.",
        "related_series":["aCNLOAN","aCNDEPT","aCNSFBABMA","aCNM2GRTY"]},
    "aCNLOAN": {"slug":"cn_banking","subcategory":"Bank Credit","units":"CNY billions",
        "meaning":"Total Bank Loans, outstanding (Monetary Financial Institutions) — stock of bank credit. Largest single bank balance-sheet item (~CNY 250 trillion).",
        "how_to_use":"Track YoY growth for credit-cycle signal. Loan growth has slowed structurally from ~13% YoY (2010s) to ~9% (2024) reflecting weak credit demand.",
        "related_series":["aCNNYLAA","aCNMFIUOFT","aCNDEPT"]},
    "aCNMFIUOFT": {"slug":"cn_banking","subcategory":"Bank Credit","units":"CNY billions",
        "meaning":"MFI Uses of Funds: Total Loans — alternative aggregation of total bank loans.",
        "how_to_use":"Cross-check against aCNLOAN. Total bank-loan stock is the meaningful credit-cycle gauge.",
        "related_series":["aCNLOAN"]},
    "aCNDEPT": {"slug":"cn_banking","subcategory":"Bank Deposits","units":"CNY billions",
        "meaning":"Total Bank Deposits — monetary financial institutions' deposit liabilities. The funding side of Chinese banks. Largest aggregate at ~CNY 300 trillion.",
        "how_to_use":"Track for funding stability. Deposit growth has slowed alongside M2. Household-vs-corporate composition matters: household deposit surge during property-deleveraging signals 'precautionary savings' (consumption-suppressing).",
        "related_series":["aCNLOAN","aCNM2"]},
    "aCNSFBABMA": {"slug":"cn_banking","subcategory":"Social Financing","units":"CNY billions",
        "meaning":"Total Social Financing (TSF), monthly new flows — broad credit-creation measure beyond bank loans. Includes bank loans + corporate bonds + government bonds + entrust loans + trust loans + bankers' acceptances + asset-backed securities.",
        "how_to_use":"PBoC's preferred credit gauge. Captures shadow-banking activity which bank-loan data misses. TSF stock-vs-GDP rose from ~140% (2010) to ~290% (2024) — major leverage buildup. Year-end TSF growth target is set by PBoC implicitly.",
        "related_series":["aCNNYLAA","aCNSFBABLA","aCNSFBABSA","aCNSFDELMA"]},
    "aCNSFBABLA": {"slug":"cn_banking","subcategory":"Social Financing","units":"CNY billions",
        "meaning":"Bank's Acceptance Bills (TSF component) — bills issued by Chinese banks accepting payment liability.",
        "how_to_use":"Sub-component of TSF. Acceptance bills are a low-quality credit-creation tool — surges signal banks meeting credit quotas via bills rather than productive lending.",
        "related_series":["aCNSFBABMA","aCNSFBABSA"]},
    "aCNCBCPARR": {"slug":"cn_banking","subcategory":"Capital Adequacy","units":"Percent",
        "meaning":"Commercial Banks: Capital Adequacy Ratio (CAR) — total capital / risk-weighted assets. Bank-system aggregate. Regulatory minimum is 8% (Basel III with Chinese add-ons making effective minimum higher for major banks).",
        "how_to_use":"Track for banking-system soundness. China bank CAR ~15% (well above minima). Watch alongside NPL ratio. Major banks (ICBC, CCB, ABC, BoC, BoCom + PSBC) have higher requirements (G-SIBs designation).",
        "related_series":["aCNCBCTCAR","aCNCBNTCPA"]},
    "aCNCBCTCAR": {"slug":"cn_banking","subcategory":"Capital Adequacy","units":"Percent",
        "meaning":"Core Tier 1 Capital Adequacy Ratio — highest-quality capital (common equity) / risk-weighted assets.",
        "how_to_use":"Bank-system CET1 ratio ~10-11% — adequate but with limited buffer for major shocks. Track for capital-adequacy direction; persistent declines signal banks absorbing credit losses.",
        "related_series":["aCNCBCPARR","aCNCBNCTCA"]},
    "aCNPSLSOA": {"slug":"cn_banking","subcategory":"PBoC Operations","units":"CNY billions",
        "meaning":"Pledged Supplementary Lending (PSL) Outstanding — PBoC's targeted-lending facility to policy banks (CDB, ADBC, Eximbank) for shantytown redevelopment, infrastructure, and other policy-priority projects. Important quasi-fiscal tool.",
        "how_to_use":"PSL surges (2022-24) signaled stealth fiscal stimulus through policy banks. Watch for new PSL operations — these bypass MoF budget rules and deliver credit to specific sectors. PBoC discloses PSL stock monthly.",
        "related_series":["aCNCRR"]},

    # ============== RETAIL SALES ==============
    "aCNRSLAR": {"slug":"cn_retail_sales","subcategory":"Retail Sales","units":"Percent, YoY",
        "meaning":"Retail Sales of Consumer Goods, year-over-year change — headline retail print released monthly by NBS ~15th of each month with the broad activity bundle.",
        "how_to_use":"THE China consumer-spending gauge. Pre-2018 ~9-10% YoY; post-COVID ~3-5% (sustained sub-5% reflects consumption weakness). Sub-3% YoY is recession-territory. Pair with consumer confidence (aCNCONCF) and online retail sales (aCNRSONLNR).",
        "related_series":["aCNRSLS","aCNRSLSY","aCNRSONLNR"]},
    "aCNRSLS": {"slug":"cn_retail_sales","subcategory":"Retail Sales","units":"CNY billions",
        "meaning":"Retail Sales, Consumer Goods — level. Total retail trade (above-designated-size) value of goods sold.",
        "how_to_use":"Use YoY (aCNRSLAR) for trend. Level useful for analytical baseline. Retail sales are a narrower measure than US-style retail since they exclude services.",
        "related_series":["aCNRSLAR"]},
    "aCNRSLSY": {"slug":"cn_retail_sales","subcategory":"Retail Sales","units":"Percent, YoY",
        "meaning":"Retail Sales of Consumer Goods, YoY — alternative release.",
        "how_to_use":"Cross-check against the primary release. Use whichever has fresher data; methodology and timing differences across releases are typically minor and resolved on revision.",
        "related_series":["aCNRSLAR"]},
    "aCNRSLYAP": {"slug":"cn_retail_sales","subcategory":"Retail Sales","units":"Percent, YoY",
        "meaning":"China Retail Sales: Consumer Goods, Initial Release YoY — Reuters poll-anchored 'actual' release for surprise-vs-consensus tracking.",
        "how_to_use":"Markets compare to Reuters consensus poll. Surprise drives Hong Kong + China A-share sentiment.",
        "related_series":["aCNRSLAR"]},
    "aCNRSONLNR": {"slug":"cn_retail_sales","subcategory":"Online Retail","units":"Percent, YoY",
        "meaning":"National Online Retail Sales, YoY — pace of e-commerce sales growth. Tracks Alibaba (Taobao/Tmall), JD, Pinduoduo, Douyin commerce activity.",
        "how_to_use":"Online share of total retail ~25-28% (vs ~16% US). Growth has slowed to single-digit YoY post-2022 as the e-commerce category matured. Tracks China's digital-economy share of GDP.",
        "related_series":["aCNRSLAR","aCNRSONLNA"]},
    "aCNRSGOFDR": {"slug":"cn_retail_sales","subcategory":"Sub-Sectors","units":"Percent, YoY",
        "meaning":"Retail Sales: Grain, Oil and Food — staple-food retail-sales growth.",
        "how_to_use":"Stable category. Tracks population + per-capita food spending. Useful as baseline for non-staples (durables, etc.) interpretation.",
        "related_series":["aCNRSLAR"]},
    "aCNRSGFTLR": {"slug":"cn_retail_sales","subcategory":"Sub-Sectors","units":"Percent, YoY",
        "meaning":"Wholesale and Retail Trade: Tobacco and Liquor, growth rate — alcohol + tobacco sales. Cyclical with disposable income; baijiu (Chinese liquor) is a major category.",
        "how_to_use":"Watch for premium-baijiu sales as a luxury-consumption indicator. Sustained drops in this category signal middle-class spending pullback. Anti-corruption campaigns historically depressed this category.",
        "related_series":["aCNRSLAR"]},

    # ============== ROUND 3 ==============

    # ============== HOUSING / REAL ESTATE (KEY: 20%+ of GDP, deleveraging since 2021) ==============
    "aCNBCOMPT": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Total Buildings Completed — total floor space of completed buildings (residential + commercial + other). Released monthly in NBS Real Estate Investment release.",
        "how_to_use":"Lagging completion gauge. Pre-2021 ~10mn sq m/month; collapsed 50%+ since 2022. Tracks property-developer ability to finish pre-sold projects ('保交楼' policy priority). Sustained drops alongside rising under-construction stock signals stalled projects.",
        "related_series":["aCNBCOMPRT","aCNBCOMPCB","aCNBCOMPTY","aCNBLDUCT"]},
    "aCNBCOMPTY": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Percent, YoY",
        "meaning":"Total Buildings Completed, YoY change — pace of construction completions.",
        "how_to_use":"Sharp negative YoY (e.g. -25% in 2023-24) marks the depth of China's property completion crisis. Watch for stabilization signals (>0% YoY) as a property-cycle bottoming indicator.",
        "related_series":["aCNBCOMPT","aCNBCOMPRTY"]},
    "aCNBCOMPRT": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Buildings Completed, Residential — residential-only completions. ~75% of total completions.",
        "how_to_use":"Tracks delivery to homebuyers who pre-purchased units. The '保交楼' (deliver-on-pre-sold-homes) policy targets this metric. Watch alongside under-construction (aCNBLDUCRB) for the gap reflecting stalled projects.",
        "related_series":["aCNBCOMPT","aCNBCOMPRTY","aCNBLDUCRB"]},
    "aCNBCOMPRTY": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Percent, YoY",
        "meaning":"Buildings Completed, Residential, YoY — residential completion growth pace.",
        "how_to_use":"Most-watched of the residential housing-cycle indicators. Sustained negative YoY since 2022 reflects developer-finance crisis. Bottoming would mark property-policy success.",
        "related_series":["aCNBCOMPRT","aCNBCOMPTY"]},
    "aCNBCOMPCB": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Real Estate Investment, Buildings Completed, Floor Space (commercial) — commercial buildings completion. Subset of total completions.",
        "how_to_use":"Tracks office and retail-mall completion. China's commercial real estate cycle has been in oversupply for years; sustained low completions signal absorption period.",
        "related_series":["aCNBCOMPT","aCNBCOMPCBY"]},
    "aCNBCOMPCBY": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Percent, YoY",
        "meaning":"Buildings Completed, Commercial, YoY — commercial-construction growth pace.",
        "how_to_use":"Track for office/retail real estate cycle. Commercial completions have been more stable than residential through the property downturn.",
        "related_series":["aCNBCOMPCB"]},
    "aCNBLDUCT": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Total Buildings Under Construction — floor space of buildings currently being built. Stock measure (cumulative).",
        "how_to_use":"Stock measure tracking the property-development pipeline. Massive ~7-8 billion sq m in recent years, reflecting the pre-sale-driven Chinese property model. Falling under-construction stock signals industry-wide deleveraging.",
        "related_series":["aCNBLDUCRB","aCNBLDUCTY","aCNBCOMPT"]},
    "aCNBLDUCTY": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Percent, YoY",
        "meaning":"Buildings Under Construction, YoY — pace of under-construction stock growth.",
        "how_to_use":"Track for property-pipeline direction. Falling YoY since 2022 shows industry-wide reduction in active development.",
        "related_series":["aCNBLDUCT","aCNBLDUCCBY"]},
    "aCNBLDUCRB": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Buildings Under Construction, Residential — residential-only floor space being built.",
        "how_to_use":"Tracks residential-housing pipeline. Pair with completions (aCNBCOMPRT) — gap reflects stalled projects (developer financing crisis).",
        "related_series":["aCNBLDUCT","aCNBLDUCRBY","aCNBCOMPRT"]},
    "aCNBLDUCRBY": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Percent, YoY",
        "meaning":"Buildings Under Construction, Residential, YoY — residential pipeline growth.",
        "how_to_use":"Track for residential-cycle direction. Negative YoY confirms ongoing deleveraging.",
        "related_series":["aCNBLDUCRB"]},
    "aCNBLDUCCB": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Real Estate Investment, Floor Space Under Construction — alternative aggregation of under-construction floor space.",
        "how_to_use":"Cross-check against aCNBLDUCT. Real estate development under-construction stock is a key property-pipeline gauge.",
        "related_series":["aCNBLDUCT"]},
    "aCNBLDUCCBY": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Percent, YoY",
        "meaning":"Buildings Floor Space Under Construction, YoY — alternative release.",
        "how_to_use":"Cross-check against aCNBLDUCTY. Both track the same under-construction floor space at quarterly cadence.",
        "related_series":["aCNBLDUCTY"]},
    "aCNBSTFSH": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Floor Space of Houses Newly Started — total newly-started construction (residential + commercial). Most forward-looking property-cycle indicator.",
        "how_to_use":"THE leading housing-cycle indicator. Newly-started construction collapsed 50%+ from 2021 peak, marking the depth of the property crisis. Watch for stabilization (>0% YoY) as a forward-looking property-recovery signal.",
        "related_series":["aCNBSTFSHR","aCNBLDUCT"]},
    "aCNBSTFSHR": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Million sq m",
        "meaning":"Floor Space of Residential Buildings Newly Started — residential-only new construction. The single most-watched leading indicator for China property.",
        "how_to_use":"Track YoY growth. Sustained negative YoY signals continued property weakness; positive YoY would signal cycle bottom. Falling new starts means developers cutting the pipeline — eventual supply shortage if structural housing demand is unmet.",
        "related_series":["aCNBSTFSH","aCNBLDUCRB"]},
    "aCNCONINVR": {"slug":"cn_housing_construction","subcategory":"Construction","units":"CNY billions",
        "meaning":"Construction Investment, Residential — residential property-development investment. Subset of total fixed-asset investment.",
        "how_to_use":"Major GDP-component driver historically (~10% of GDP at peak). Has declined sharply since 2021 as property deleveraging compressed developer balance sheets. Watch alongside FAI (fixed-asset investment) total.",
        "related_series":["aCNCONINVRY","aCNCGFCD/CA"]},
    "aCNCONINVRY": {"slug":"cn_housing_construction","subcategory":"Construction","units":"Percent, YoY",
        "meaning":"Construction Investment, Residential, YoY — pace of residential investment.",
        "how_to_use":"Most market-relevant housing-cycle gauge. Sustained -10% YoY since 2022 reflects ongoing crisis. PBoC mortgage cuts, special-purpose bond support, and 'whitelist' lending facilities target a stabilization here.",
        "related_series":["aCNCONINVR","aCNBSTFSHR"]},
    "aCNHSALESCB": {"slug":"cn_housing_construction","subcategory":"Sales","units":"Million sq m",
        "meaning":"Floor Space of Commercial Buildings Sold — total property sales by floor space (residential + commercial).",
        "how_to_use":"Demand-side indicator. Sustained drops since 2021 mirror new-starts collapse. China property sales recovery requires both confidence and developer ability to deliver — both are needed for sustained upturn.",
        "related_series":["aCNBSTFSH"]},

    # ============== UNEMPLOYMENT (Urban survey rate is headline) ==============
    "aCNCNUERLM": {"slug":"cn_workforce_unemployment","subcategory":"Unemployment","units":"Percent",
        "meaning":"Urban Survey Unemployment Rate — the official monthly headline unemployment rate, based on the urban-area labor-force survey. Replaced the old urban-registered unemployment rate as the headline gauge in 2018.",
        "how_to_use":"THE China unemployment headline. Pre-COVID ~5%; spiked to 6.2% in 2020 and 2022 (lockdowns). Released monthly. Youth unemployment (16-24 yo, separately published) is much higher (~17-21%) — a major political concern; NBS suspended the youth series in mid-2023 then resumed with revised methodology.",
        "related_series":["aCNCNRLVKQ","aCNCUNPQ/A","aCNCEMFO/A"]},
    "aCNCNRLVKQ": {"slug":"cn_workforce_unemployment","subcategory":"Unemployment","units":"Percent",
        "meaning":"Urban Registered Unemployment Rate — legacy unemployment measure tracking only people who registered for unemployment benefits at local labor bureaus. Pre-2018 official headline; less meaningful now (people often don't bother registering).",
        "how_to_use":"Use the survey rate (aCNCNUERLM) instead. Urban-registered rate runs much lower (~3-4%) than the broader survey rate (5-6%) because registration is incomplete.",
        "related_series":["aCNCNUERLM"]},
    "aCNCUNPQ/A": {"slug":"cn_workforce_unemployment","subcategory":"Unemployment","units":"Percent",
        "meaning":"Unemployment Rate, Standardized — OECD-comparable framing of the China unemployment rate.",
        "how_to_use":"Cross-check series. Standardized version used in international comparisons.",
        "related_series":["aCNCNUERLM","aCNCUNPP"]},
    "aCNCUNPP": {"slug":"cn_workforce_unemployment","subcategory":"Unemployment","units":"Persons, thousands",
        "meaning":"Unemployment Level, standardized — total unemployed persons.",
        "how_to_use":"Pair with employment level for unemployment-rate calculation. Smaller in China than US/EU per capita due to large informal sector and underemployment that doesn't register as 'unemployment'.",
        "related_series":["aCNCEMFO/A","aCNCNUERLM"]},
    "aCNUEMP": {"slug":"cn_workforce_unemployment","subcategory":"Unemployment","units":"Persons, thousands",
        "meaning":"Unemployment, Urban Area (annual) — Ministry of Human Resources and Social Security headline annual unemployment level.",
        "how_to_use":"Annual frequency. Use monthly survey rate (aCNCNUERLM) for high-frequency tracking.",
        "related_series":["aCNCNUERLM","aCNCUNPP"]},
    "aCNCEMFO/A": {"slug":"cn_workforce_unemployment","subcategory":"Employment","units":"Persons, thousands",
        "meaning":"Employment, Labour Force Survey — standardized total-employment level. ~750M employed.",
        "how_to_use":"Compare to labor force for unemployment rate. China labor force has been shrinking since 2014 (peak ~810M) due to demographic transition — a major structural macro story.",
        "related_series":["aCNCNUERLM"]},
    "aCNJOBVT": {"slug":"cn_workforce_unemployment","subcategory":"Labor Demand","units":"Number, partial cities",
        "meaning":"Job Vacancies (Partial Cities) — partial measure of job-vacancy stocks across major Chinese cities. Less comprehensive than a true national vacancy series.",
        "how_to_use":"Indicative. Use alongside JV-to-applicants ratio (separately published) for labor-demand pulse. Falls during recessions.",
        "related_series":["aCNCNUERLM"]},

    # ============== EMPLOYMENT BY SECTOR ==============
    "aCNCEMPO/A": {"slug":"cn_employment_hours","subcategory":"Employment","units":"Persons, thousands",
        "meaning":"Employment, Payroll Jobs (Standardized) — total formal-sector payroll employment. Subset of total employment that excludes self-employed and informal workers.",
        "how_to_use":"Tracks formal employment trend. Compare to total employment (aCNCEMFO/A) — formal share has been growing slowly but informal sector remains large in China.",
        "related_series":["aCNCEMFO/A","aCNEMPALL"]},
    "aCNEMPALL": {"slug":"cn_employment_hours","subcategory":"Employment","units":"Persons, thousands",
        "meaning":"Employment, Urban Non-Private Units — public-sector + SOE + collective + state-controlled enterprise employment. Subset of formal-sector workforce.",
        "how_to_use":"Tracks public-sector employment (~150M). Stable category. SOE-sector employment cuts during reform periods (2015-16 'supply-side reform', 2024 fiscal-pressure-driven layoffs in some local SOEs).",
        "related_series":["aCNEMPP"]},
    "aCNEMPP": {"slug":"cn_employment_hours","subcategory":"Employment","units":"Persons, thousands",
        "meaning":"Total Employment, Annual (NBS) — annual total employment count.",
        "how_to_use":"Annual frequency. Use for long-run trend tracking. Total employment peaked in 2014 and is now slowly declining.",
        "related_series":["aCNCEMFO/A"]},

    # ============== BALANCE OF PAYMENTS ==============
    "aCNCCURB/A": {"slug":"cn_balance_of_payments","subcategory":"Current Account","units":"USD billions",
        "meaning":"Current Account Balance, level — quarterly absolute current account. Publishes ~3 months after quarter-end by SAFE.",
        "how_to_use":"China runs persistent CA surpluses (~$300-400B/year recently). Surplus driven by goods trade (~$700B annually) offset by services deficit (~$200B, mostly tourism + IP royalties) and primary income deficit (~$50-100B).",
        "related_series":["aCNCAA","aCNCCURYB/A","aCNCBOPA"]},
    "aCNCCURPB/A": {"slug":"cn_balance_of_payments","subcategory":"Current Account","units":"USD billions",
        "meaning":"Current Account Balance, QoQ absolute change — quarter-over-quarter momentum.",
        "how_to_use":"Track for sequential changes. Quarterly volatility from commodity-price swings and seasonal trade patterns.",
        "related_series":["aCNCCURB/A"]},
    "aCNCCURYB/A": {"slug":"cn_balance_of_payments","subcategory":"Current Account","units":"USD billions",
        "meaning":"Current Account Balance, YoY absolute change — year-over-year change in CA level.",
        "how_to_use":"Cleaner trend gauge than QoQ. Track for annual current-account balance changes vs same quarter year ago.",
        "related_series":["aCNCCURB/A"]},
    "aCNCCURQ/A": {"slug":"cn_balance_of_payments","subcategory":"Current Account","units":"Percent of GDP",
        "meaning":"Current Account Balance as % of GDP, standardized — the headline external-balance ratio. China's CA/GDP fell from ~10% (2007) to ~2% post-2014 reflecting growth rebalancing.",
        "how_to_use":"China CA/GDP currently ~2% — moderate surplus. Sustained moves toward deficit (as in late 2010s) would indicate weakening external position. The yuan's structural appreciation drivers depend on this.",
        "related_series":["aCNCCURB/A","aCNCCURYQ/A"]},
    "aCNCCURPQ/A": {"slug":"cn_balance_of_payments","subcategory":"Current Account","units":"Percent of GDP, QoQ",
        "meaning":"Current Account % of GDP, QoQ change — sequential momentum of CA-to-GDP ratio.",
        "how_to_use":"Track quarterly inflection points. Use the level series (aCNCCURQ/A) for cross-country comparison.",
        "related_series":["aCNCCURQ/A"]},
    "aCNCCURYQ/A": {"slug":"cn_balance_of_payments","subcategory":"Current Account","units":"Percent of GDP, YoY",
        "meaning":"Current Account % of GDP, YoY change — annual change in CA-to-GDP ratio.",
        "how_to_use":"Smooths quarterly variability. Use for CA/GDP trend; China CA/GDP swings 1-2pp through commodity cycles.",
        "related_series":["aCNCCURQ/A"]},
    "aCNCBOPA": {"slug":"cn_balance_of_payments","subcategory":"Trade Balance","units":"USD billions",
        "meaning":"Visible Trade Balance (BoP basis), standardized — quarterly goods trade balance. Largest CA component.",
        "how_to_use":"Annual surplus ~$700B (world's largest goods surplus). Cross-check against monthly customs data (aCNCEXPB/A minus aCNCIMPB/A).",
        "related_series":["aCNCEXBA","aCNCIMBA","aCNCCURB/A"]},
    "aCNCBOPPA": {"slug":"cn_balance_of_payments","subcategory":"Trade Balance","units":"USD billions",
        "meaning":"Visible Trade Balance, QoQ absolute change — quarter-over-quarter momentum.",
        "how_to_use":"Track quarterly direction. Cross-check against the YoY change (aCNCBOPYA) for cleaner trend.",
        "related_series":["aCNCBOPA"]},
    "aCNCBOPYA": {"slug":"cn_balance_of_payments","subcategory":"Trade Balance","units":"USD billions",
        "meaning":"Visible Trade Balance, YoY absolute change — year-over-year goods balance change.",
        "how_to_use":"Smooths quarterly noise. Track for goods-trade cycle direction; pair with monthly customs data.",
        "related_series":["aCNCBOPA"]},
    "aCNCEXBA": {"slug":"cn_balance_of_payments","subcategory":"Goods Exports","units":"USD billions",
        "meaning":"Goods Exports on BoP basis (standardized) — quarterly merchandise exports level.",
        "how_to_use":"Cross-check against monthly customs (aCNCEXPB/A). BoP basis differs slightly due to coverage and timing methodology.",
        "related_series":["aCNCEXPB/A","aCNCBOPA"]},
    "aCNBOPFANA": {"slug":"cn_balance_of_payments","subcategory":"Financial Account","units":"USD billions",
        "meaning":"Financial Account, Balance — net flows of FDI + portfolio investment + other investment + reserves. Mirror of current account.",
        "how_to_use":"Decompose: FDI flows (typically inflows but recent declines), portfolio (volatile, Stock Connect / Bond Connect dependent), other investment (loans, trade credits). 2024 saw weak FDI inflows — major macro concern.",
        "related_series":["aCNBOPSENA","aCNBPNRESA"]},
    "aCNBOPSENA": {"slug":"cn_balance_of_payments","subcategory":"Portfolio Investment","units":"USD billions",
        "meaning":"Financial Account: Portfolio Investment Balance — net flows of equity + bond portfolio investment. Highly volatile; Stock Connect / Bond Connect channels matter.",
        "how_to_use":"Sensitive to global risk sentiment and US-China rate spread. 2022-23 saw heavy outflows; 2024+ stabilizing. Watch alongside Bond Connect monthly statistics.",
        "related_series":["aCNBOPFANA","aCNBOPOTNA"]},
    "aCNBOPOTNA": {"slug":"cn_balance_of_payments","subcategory":"Other Investment","units":"USD billions",
        "meaning":"Financial Account: Other Investment Balance — non-FDI, non-portfolio cross-border flows (loans, trade credits, currency/deposits).",
        "how_to_use":"Often the residual that absorbs unmeasured capital flows. Persistent large net-outflow balances indicate capital flight pressure.",
        "related_series":["aCNBOPFANA"]},
    "aCNBPNRESA": {"slug":"cn_balance_of_payments","subcategory":"Financial Account","units":"USD billions",
        "meaning":"Financial Account, Non-Reserve Balance — financial account excluding reserves changes. The 'private capital flow' measure.",
        "how_to_use":"Cleaner private-capital signal than total financial account. Sustained negative non-reserve balances mean private capital is leaving — pressure for reserves to fill the gap.",
        "related_series":["aCNBOPFANA","aCNBPRESVA"]},
    "aCNBPRESVA": {"slug":"cn_balance_of_payments","subcategory":"Reserve Assets","units":"USD billions",
        "meaning":"Reserve Assets Change — quarterly change in official reserves on BoP basis.",
        "how_to_use":"Should reconcile with monthly reserves data (aCNCRESA difference). When CA + non-reserve financial account is negative and reserves draw down, BI is intervening to defend CNY.",
        "related_series":["aCNBPNRESA","aCNCRESA"]},
    "aCNBPMAPAA": {"slug":"cn_balance_of_payments","subcategory":"Capital Account","units":"USD billions",
        "meaning":"Capital Account Balance — quarterly capital-account balance (small in China; dominated by transfers).",
        "how_to_use":"Tiny relative to current and financial accounts. Mostly captures bilateral aid, debt forgiveness, intangible asset transfers. Not market-moving.",
        "related_series":["aCNCAFIN"]},
    "aCNCAFIN": {"slug":"cn_balance_of_payments","subcategory":"Capital + Financial","units":"USD billions",
        "meaning":"Capital and Financial Account Balance — combined capital + financial accounts. Mirror of current account balance.",
        "how_to_use":"Should equal -CA balance (with errors and omissions). Useful for total-financing-side cross-check.",
        "related_series":["aCNBOPFANA","aCNCCURB/A"]},
    "aCNCAPAC": {"slug":"cn_balance_of_payments","subcategory":"Capital Account","units":"USD billions",
        "meaning":"Capital Account Balance, Annual — annual aggregate of capital-account flows.",
        "how_to_use":"Annual frequency aggregate. Capital account is small relative to current and financial accounts in China.",
        "related_series":["aCNBPMAPAA"]},

}


def main() -> int:
    by_slug: dict[str, dict] = defaultdict(dict)
    for ric, fields in TIER1.items():
        slug = fields["slug"]
        by_slug[slug][ric] = fields

    updated = 0
    missing: list[str] = []
    for slug, ric_map in by_slug.items():
        path = os.path.join(CATALOG_DIR, f"{slug}.json")
        if not os.path.exists(path):
            print(f"  SKIP: catalog/cn/{slug}.json not found")
            for r in ric_map:
                missing.append(r)
            continue

        with open(path, encoding="utf-8") as f:
            cat = json.load(f)

        rics_index = {r["ric"]: r for r in cat.get("rics", [])}

        for ric, fields in ric_map.items():
            if ric not in rics_index:
                missing.append(ric)
                print(f"  MISS: {ric} not found in {slug}.json")
                continue
            entry = rics_index[ric]
            entry["subcategory"] = fields["subcategory"]
            entry["units"] = fields["units"]
            entry["meaning"] = fields["meaning"]
            entry["how_to_use"] = fields["how_to_use"]
            entry["related_series"] = fields["related_series"]
            updated += 1

        with open(path, "w", encoding="utf-8") as f:
            json.dump(cat, f, ensure_ascii=False, indent=2)

    print(f"[seed-cn-tier1] updated {updated} RICs across {len(by_slug)} catalog files")
    if missing:
        print(f"[seed-cn-tier1] {len(missing)} RICs missing: {missing}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
