"""Rebuild agent6.json with all fetched tickers and proper sub-industry labels."""
import pandas as pd
import json
from pathlib import Path

import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parent))
from _paths import DATA_ROOT, DB_PATH  # external data-store paths
ROOT = Path(__file__).resolve().parents[1]
STAGE_RAW = DATA_ROOT / "raw" / "staging"
STAGE_CAT = ROOT / "catalog" / "staging"

wk = pd.read_parquet(STAGE_RAW / "agent6_weekly.parquet")
all_tickers = sorted(wk.columns.tolist())

sub_map = {
    # Internet E-commerce
    "IDX:BELI": "Internet — E-commerce",
    "IDX:GOTO": "Internet — E-commerce",
    "IDX:BUKA": "Internet — E-commerce",
    "IDX:KIOS": "Internet — E-commerce",
    # Internet Online Services
    "IDX:DNET": "Internet — Online Services",
    "IDX:WIFI": "Internet — Online Services",
    "IDX:INET": "Internet — Online Services",
    "IDX:AWAN": "Internet — Online Services",
    "IDX:PGJO": "Internet — Online Services",
    "IDX:AREA": "Internet — Online Services",
    # IT Services & Consulting
    "IDX:MTDL": "IT Services & Consulting",
    "IDX:DGNS": "IT Services & Consulting",
    "IDX:ATIC": "IT Services & Consulting",
    "IDX:MSTI": "IT Services & Consulting",
    "IDX:CYBR": "IT Services & Consulting",
    "IDX:LUCK": "IT Services & Consulting",
    "IDX:AXIO": "IT Services & Consulting",
    "IDX:JATI": "IT Services & Consulting",
    "IDX:RUNS": "IT Services & Consulting",
    "IDX:WGSH": "IT Services & Consulting",
    # Tech Hardware & Distribution
    "IDX:WIRG": "Tech Hardware & Distribution",
    "IDX:GLVA": "Tech Hardware & Distribution",
    "IDX:ZYRX": "Tech Hardware & Distribution",
    "IDX:PTSN": "Tech Hardware & Distribution",
    "IDX:MCAS": "Tech Hardware & Distribution",
    "IDX:TFAS": "Tech Hardware & Distribution",
    "IDX:NFCX": "Tech Hardware & Distribution",
    "IDX:DIVA": "Tech Hardware & Distribution",
    "IDX:DCII": "Tech Hardware & Distribution",
    "IDX:ELIT": "Tech Hardware & Distribution",
    "IDX:TRON": "Tech Hardware & Distribution",
    "IDX:CHIP": "Tech Hardware & Distribution",
    "IDX:MENN": "Tech Hardware & Distribution",
    "IDX:NINE": "Tech Hardware & Distribution",
    "IDX:UVCR": "Tech Hardware & Distribution",
    "IDX:TOSK": "Tech Hardware & Distribution",
    "IDX:IOTF": "Tech Hardware & Distribution",
    "IDX:DMMX": "Tech Hardware & Distribution",
    "IDX:HDIT": "Tech Hardware & Distribution",
    "IDX:LMAS": "Tech Hardware & Distribution",
    "IDX:SKYB": "Tech Hardware & Distribution",
    "IDX:IRSX": "Tech Hardware & Distribution",
    "IDX:KREN": "Tech Hardware & Distribution",
    "IDX:ENVY": "Tech Hardware & Distribution",
    "IDX:TECH": "Tech Hardware & Distribution",
    # Fintech
    "IDX:EMTK": "Fintech",
    "IDX:CASH": "Fintech",
    # Logistics & Distribution
    "IDX:ASSA": "Logistics & Distribution",
    "IDX:ALII": "Logistics & Distribution",
    "IDX:BLOG": "Logistics & Distribution",
    "IDX:PPGL": "Logistics & Distribution",
    "IDX:LOPI": "Logistics & Distribution",
    "IDX:CANI": "Logistics & Distribution",
    "IDX:JAYA": "Logistics & Distribution",
    "IDX:TNCA": "Logistics & Distribution",
    "IDX:KJEN": "Logistics & Distribution",
    "IDX:LAJU": "Logistics & Distribution",
    "IDX:SAPX": "Logistics & Distribution",
    "IDX:DEAL": "Logistics & Distribution",
    "IDX:AKSI": "Logistics & Distribution",
    "IDX:INPS": "Logistics & Distribution",
    "IDX:SDMU": "Logistics & Distribution",
    "IDX:TRJA": "Logistics & Distribution",
    "IDX:PURA": "Logistics & Distribution",
    # Marine Transportation
    "IDX:SMDR": "Marine Transportation",
    "IDX:BULL": "Marine Transportation",
    "IDX:TMAS": "Marine Transportation",
    "IDX:MBSS": "Marine Transportation",
    "IDX:ELPI": "Marine Transportation",
    "IDX:BBRM": "Marine Transportation",
    "IDX:BLTA": "Marine Transportation",
    "IDX:BSML": "Marine Transportation",
    "IDX:NELY": "Marine Transportation",
    "IDX:HAIS": "Marine Transportation",
    "IDX:GTRA": "Marine Transportation",
    "IDX:PJHB": "Marine Transportation",
    "IDX:RIGS": "Marine Transportation",
    "IDX:KLAS": "Marine Transportation",
    "IDX:TPMA": "Marine Transportation",
    "IDX:TEBE": "Marine Transportation",
    "IDX:PSAT": "Marine Transportation",
    "IDX:HATM": "Marine Transportation",
    "IDX:HUMI": "Marine Transportation",
    "IDX:WINS": "Marine Transportation",
    "IDX:BESS": "Marine Transportation",
    "IDX:CBRE": "Marine Transportation",
    # Air Transportation
    "IDX:GIAA": "Air Transportation",
    "IDX:CMPP": "Air Transportation",
    "IDX:CASS": "Air Transportation",
    "IDX:IATA": "Air Transportation",
    # Road Transport
    "IDX:BIRD": "Road Transport",
    "IDX:WEHA": "Road Transport",
    "IDX:BPTR": "Road Transport",
    "IDX:TAXI": "Road Transport",
    "IDX:MIRA": "Road Transport",
    "IDX:LRNA": "Road Transport",
    "IDX:SAFE": "Road Transport",
    "IDX:TRUK": "Road Transport",
    "IDX:RCCC": "Road Transport",
    "IDX:HELI": "Road Transport",
    # Rail Transport (toll road infra operators)
    "IDX:JSMR": "Rail Transport",
    "IDX:CMNP": "Rail Transport",
    "IDX:META": "Rail Transport",
    "IDX:BIPI": "Rail Transport",
    "IDX:RMKE": "Rail Transport",
    "IDX:INDX": "Rail Transport",
    # Ports & Airports
    "IDX:IPCM": "Ports & Airports",
    "IDX:KARW": "Ports & Airports",
    "IDX:PTIS": "Ports & Airports",
}

name_map = {
    "IDX:BELI": "PT Global Digital Niaga Tbk",
    "IDX:GOTO": "PT GoTo Gojek Tokopedia Tbk",
    "IDX:BUKA": "PT Bukalapak.com Tbk",
    "IDX:KIOS": "PT Kioson Komersial Indonesia Tbk",
    "IDX:DNET": "PT Indoritel Makmur Internasional Tbk",
    "IDX:WIFI": "PT Solusi Sinergi Digital Tbk",
    "IDX:INET": "PT Indointernet Tbk",
    "IDX:AWAN": "PT Era Digital Media Tbk",
    "IDX:PGJO": "PT Tourindo Guide Indonesia Tbk",
    "IDX:AREA": "PT Dunia Virtual Online Tbk",
    "IDX:MTDL": "PT Metrodata Electronics Tbk",
    "IDX:DGNS": "PT Datacomm Diangraha Tbk",
    "IDX:ATIC": "PT Anabatic Technologies Tbk",
    "IDX:MSTI": "PT Mastersystem Infotama Tbk",
    "IDX:CYBR": "PT ITSEC Asia Tbk",
    "IDX:LUCK": "PT Sentral Mitra Informatika Tbk",
    "IDX:AXIO": "PT Tera Data Indonusa Tbk",
    "IDX:JATI": "PT Informasi Teknologi Indonesia Tbk",
    "IDX:RUNS": "PT Global Sukses Solusi Tbk",
    "IDX:WGSH": "PT Wira Global Solusi Tbk",
    "IDX:WIRG": "PT WIR Asia Tbk",
    "IDX:GLVA": "PT Galva Technologies Tbk",
    "IDX:ZYRX": "PT Zyrexindo Mandiri Buana Tbk",
    "IDX:PTSN": "PT Sat Nusapersada Tbk",
    "IDX:MCAS": "PT M Cash Integrasi Tbk",
    "IDX:TFAS": "PT Telefast Indonesia Tbk",
    "IDX:NFCX": "PT NFC Indonesia Tbk",
    "IDX:DIVA": "PT Distribusi Voucher Nusantara Tbk",
    "IDX:DCII": "PT DCI Indonesia Tbk",
    "IDX:ELIT": "PT Data Sinergitama Jaya Tbk",
    "IDX:TRON": "PT Teknologi Karya Digital Nusa Tbk",
    "IDX:CHIP": "PT Pelita Teknologi Global Tbk",
    "IDX:MENN": "PT Menn Teknologi Indonesia Tbk",
    "IDX:NINE": "PT Techno9 Indonesia Tbk",
    "IDX:UVCR": "PT Trimegah Karya Pratama Tbk",
    "IDX:TOSK": "PT Topindo Solusi Komunika Tbk",
    "IDX:IOTF": "PT Sumber Sinergi Makmur Tbk",
    "IDX:DMMX": "PT Digital Mediatama Maxima Tbk",
    "IDX:HDIT": "PT Hensel Davest Indonesia Tbk",
    "IDX:LMAS": "PT Limas Indonesia Makmur Tbk",
    "IDX:SKYB": "PT Northcliff Citranusa Indonesia Tbk",
    "IDX:IRSX": "PT Aviana Sinar Abadi Tbk",
    "IDX:KREN": "PT Quantum Clovera Investama Tbk",
    "IDX:ENVY": "PT Envy Technologies Indonesia Tbk",
    "IDX:TECH": "PT Indosterling Technomedia Tbk",
    "IDX:EMTK": "PT Elang Mahkota Teknologi Tbk",
    "IDX:CASH": "PT Cashlez Worldwide Indonesia Tbk",
    "IDX:ASSA": "PT Adi Sarana Armada Tbk",
    "IDX:ALII": "PT Ancara Logistics Indonesia Tbk",
    "IDX:BLOG": "PT Trimitra Trans Persada Tbk",
    "IDX:PPGL": "PT Prima Globalindo Logistik Tbk",
    "IDX:LOPI": "PT Logisticsplus International Tbk",
    "IDX:CANI": "PT Capitol Nusantara Indonesia Tbk",
    "IDX:JAYA": "PT Armada Berjaya Trans Tbk",
    "IDX:TNCA": "PT Trimuda Nuansa Citra Tbk",
    "IDX:KJEN": "PT Krida Jaringan Nusantara Tbk",
    "IDX:LAJU": "PT Jasa Berdikari Logistics Tbk",
    "IDX:SAPX": "PT Satria Antaran Prima Tbk",
    "IDX:DEAL": "PT Dewata Freightinternational Tbk",
    "IDX:AKSI": "PT Mineral Sumberdaya Mandiri Tbk",
    "IDX:INPS": "PT Indah Prakasa Sentosa Tbk",
    "IDX:SDMU": "PT Sidomulyo Selaras Tbk",
    "IDX:TRJA": "PT Transkon Jaya Tbk",
    "IDX:PURA": "PT Putra Rajawali Kencana Tbk",
    "IDX:SMDR": "PT Samudera Indonesia Tbk",
    "IDX:BULL": "PT Buana Lintas Lautan Tbk",
    "IDX:TMAS": "PT Temas Tbk",
    "IDX:MBSS": "PT Mitrabahtera Segara Sejati Tbk",
    "IDX:ELPI": "PT Pelayaran Nasional Ekalya Purnamasari Tbk",
    "IDX:BBRM": "PT Pelayaran Nasional Bina Buana Raya Tbk",
    "IDX:BLTA": "PT Berlian Laju Tanker Tbk",
    "IDX:BSML": "PT Bintang Samudera Mandiri Lines Tbk",
    "IDX:NELY": "PT Pelayaran Nelly Dwi Putri Tbk",
    "IDX:HAIS": "PT Hasnur Internasional Shipping Tbk",
    "IDX:GTRA": "PT Grahaprima Suksesmandiri Tbk",
    "IDX:PJHB": "PT Pelayaran Jaya Hidup Baru Tbk",
    "IDX:RIGS": "PT Rig Tenders Indonesia Tbk",
    "IDX:KLAS": "PT Pelayaran Kurnia Lautan Semesta Tbk",
    "IDX:TPMA": "PT Trans Power Marine Tbk",
    "IDX:IPCM": "PT Jasa Armada Indonesia Tbk",
    "IDX:TEBE": "PT Dana Brata Luhur Tbk",
    "IDX:PSAT": "PT Pancaran Samudera Transport Tbk",
    "IDX:HATM": "PT Habco Trans Maritima Tbk",
    "IDX:HUMI": "PT Humpuss Maritim Internasional Tbk",
    "IDX:WINS": "PT Wintermar Offshore Marine Tbk",
    "IDX:BESS": "PT Batulicin Nusantara Maritim Tbk",
    "IDX:CBRE": "PT Cakra Buana Resources Energi Tbk",
    "IDX:GIAA": "PT Garuda Indonesia (Persero) Tbk",
    "IDX:CMPP": "PT AirAsia Indonesia Tbk",
    "IDX:CASS": "PT Cahaya Aero Services Tbk",
    "IDX:IATA": "PT Indo Aviasi Perdana Tbk",
    "IDX:BIRD": "PT Blue Bird Tbk",
    "IDX:WEHA": "PT WEHA Transportasi Indonesia Tbk",
    "IDX:BPTR": "PT Batavia Prosperindo Trans Tbk",
    "IDX:TAXI": "PT Express Transindo Utama Tbk",
    "IDX:MIRA": "PT Mitra International Resources Tbk",
    "IDX:LRNA": "PT Eka Sari Lorena Transport Tbk",
    "IDX:SAFE": "PT Steady Safe Tbk",
    "IDX:TRUK": "PT Guna Timur Raya Tbk",
    "IDX:RCCC": "PT Utama Radar Cahaya Tbk",
    "IDX:HELI": "PT Jaya Trishindo Tbk",
    "IDX:JSMR": "PT Jasa Marga (Persero) Tbk",
    "IDX:CMNP": "PT Citra Marga Nusaphala Persada Tbk",
    "IDX:META": "PT Nusantara Infrastructure Tbk",
    "IDX:BIPI": "PT Astrindo Nusantara Infrastruktur Tbk",
    "IDX:RMKE": "PT RMK Energy Tbk",
    "IDX:INDX": "PT Tanah Laut Tbk",
    "IDX:KARW": "PT Meratus Jasa Prima Tbk",
    "IDX:PTIS": "PT Indo Straits Tbk",
}

entries = []
for col in all_tickers:
    tkr = col.split(":")[1]
    entries.append({
        "id": col,
        "name": name_map.get(col, f"PT {tkr} Tbk"),
        "yf": f"{tkr}.JK",
        "src": "tv",
        "cat": "indonesia_equities",
        "sub": sub_map.get(col, "Stock"),
        "ret": "log",
        "start": 2011,
    })

out = {
    "agent": 6,
    "fetched": len(entries),
    "attempted": len(all_tickers),
    "entries": entries,
}

out_path = STAGE_CAT / "agent6.json"
out_path.write_text(json.dumps(out, separators=(",", ":"), indent=2))
print(f"Written {len(entries)} entries to {out_path}")

# Print sub-industry summary
from collections import Counter
ctr = Counter(e["sub"] for e in entries)
for sub, count in sorted(ctr.items()):
    print(f"  {sub}: {count}")
